import { storage } from "./storage";
import type { InsertRecipe } from "@shared/schema";

const focacciaRecipes: InsertRecipe[] = [
  {
    title: "Gluten-Free Focaccia Pizza Crust with Garlic & Rosemary",
    slug: "gluten-free-focaccia-pizza-crust-garlic-rosemary",
    description: "Classic Italian focaccia with aromatic garlic and fresh rosemary - light, airy, and perfect for pizza.",
    longDescription: "This classic gluten-free focaccia pizza crust features aromatic roasted garlic and fresh rosemary baked into a light, airy dough. The combination of olive oil, garlic, and herbs creates an authentic Italian flavor profile with a soft, bubbly interior and golden crisp exterior. Perfect as a pizza base or enjoyed on its own, this focaccia delivers restaurant-quality results at home.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135, // includes 90 min rise time
    servings: 8,
    rating: "4.8",
    calories: 245,
    protein: "6.5",
    carbs: "32.0",
    fat: "10.5",
    fiber: "3.2",
    sugar: "1.8",
    image: "/attached_assets/generated_images/Garlic_Rosemary_Focaccia_Crust_2db6d94f.png",
    ingredients: [
      "2 cups gluten-free flour blend (rice flour, tapioca starch, potato starch)",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "6 cloves roasted garlic, mashed",
      "2 tablespoons fresh rosemary, chopped",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "In a small bowl, combine warm water, sugar, and yeast. Let sit for 5-10 minutes until foamy.",
      "In a large bowl, whisk together gluten-free flour blend, almond flour, psyllium husk, and sea salt.",
      "Add the yeast mixture and 3 tablespoons olive oil to the dry ingredients. Mix until a wet, sticky dough forms.",
      "Fold in mashed roasted garlic and half the rosemary. Cover bowl with plastic wrap and let rise in a warm place for 90 minutes.",
      "Preheat oven to 425°F. Drizzle a 9x13-inch baking sheet with 2 tablespoons olive oil.",
      "Transfer dough to prepared pan. With oiled fingers, press and stretch dough to fill the pan, creating dimples all over the surface.",
      "Drizzle remaining olive oil over the top, sprinkle with remaining rosemary and flaky sea salt.",
      "Bake for 20-25 minutes until golden brown and crisp on the edges. Internal temperature should reach 200°F.",
      "Let cool for 5 minutes before slicing. Serve warm as a pizza base or flatbread."
    ],
    tips: "For deeper flavor, roast the garlic ahead of time by wrapping whole cloves in foil with olive oil and baking at 400°F for 30 minutes. The wetter the dough, the airier the crumb - don't be tempted to add more flour!",
    variations: [
      "Add grated Parmesan cheese to the dough for extra richness",
      "Substitute dried rosemary (1 tablespoon) if fresh isn't available",
      "Top with cherry tomatoes during the last 10 minutes of baking",
      "Use roasted shallots instead of garlic for a sweeter profile"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Italian", "garlic", "rosemary", "bread", "flatbread"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Garlic & Rosemary | Unglued Food",
    seoDescription: "Light and airy gluten-free focaccia pizza crust with roasted garlic and fresh rosemary. Perfect for homemade pizza with authentic Italian flavor and golden crispy edges."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Tomato & Basil",
    slug: "gluten-free-focaccia-pizza-crust-tomato-basil",
    description: "Vibrant summer focaccia with cherry tomatoes and fresh basil - a perfect base for margherita-style pizzas.",
    longDescription: "This gluten-free focaccia pizza crust celebrates summer flavors with sweet cherry tomatoes and aromatic fresh basil baked right into the dough. The tomatoes create pockets of burst flavor while the basil infuses the bread with herbaceous notes. With a soft, airy interior and golden edges, this focaccia makes an exceptional base for margherita pizzas or can be enjoyed as a standalone Italian flatbread.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135,
    servings: 8,
    rating: "4.7",
    calories: 238,
    protein: "6.0",
    carbs: "33.5",
    fat: "9.5",
    fiber: "3.0",
    sugar: "3.2",
    image: "/attached_assets/generated_images/Tomato_Basil_Focaccia_Crust_5c072762.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "1 cup cherry tomatoes, halved",
      "1/4 cup fresh basil leaves, torn",
      "Flaky sea salt and black pepper for topping"
    ],
    instructions: [
      "Combine warm water, sugar, and yeast in a bowl. Let bloom for 10 minutes until bubbly.",
      "Mix gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Stir until a sticky dough forms.",
      "Cover and let rise in a warm spot for 90 minutes until doubled in size.",
      "Preheat oven to 425°F. Oil a 9x13-inch baking sheet with 2 tablespoons olive oil.",
      "Press dough into prepared pan with oiled hands, creating dimples across the surface.",
      "Press halved cherry tomatoes cut-side up into the dough. Scatter torn basil leaves over the top.",
      "Drizzle with remaining olive oil, season with flaky salt and black pepper.",
      "Bake 20-25 minutes until golden and tomatoes are slightly caramelized.",
      "Cool briefly before serving. Use as pizza base or enjoy as rustic Italian bread."
    ],
    tips: "Pat the cherry tomatoes dry with paper towels before adding to prevent excess moisture. For maximum flavor, use ripe, in-season tomatoes. The focaccia is best served warm on the day it's made.",
    variations: [
      "Add fresh mozzarella pearls for a caprese-style focaccia",
      "Use sun-dried tomatoes for more intense flavor",
      "Drizzle with balsamic glaze before serving",
      "Mix in minced garlic with the basil"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Italian", "tomato", "basil", "summer", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Tomato & Basil | Unglued Food",
    seoDescription: "Fresh and vibrant gluten-free focaccia with cherry tomatoes and basil. Perfect summer pizza crust with burst tomatoes and aromatic herbs baked into airy bread."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Caramelized Onions & Thyme",
    slug: "gluten-free-focaccia-pizza-crust-caramelized-onions-thyme",
    description: "Sweet caramelized onions and aromatic thyme create an elegant focaccia perfect for gourmet white pizzas.",
    longDescription: "This sophisticated gluten-free focaccia features deeply caramelized onions and fresh thyme for a rich, savory flavor profile. The sweet, golden onions add complexity while the thyme provides earthy, aromatic notes. With its soft, airy texture and crispy golden crust, this focaccia is ideal as a base for white pizzas, topped with goat cheese, or enjoyed on its own as an artisan flatbread.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 25,
    totalTime: 160,
    servings: 8,
    rating: "4.8",
    calories: 252,
    protein: "6.2",
    carbs: "34.0",
    fat: "10.8",
    fiber: "3.5",
    sugar: "4.5",
    image: "/attached_assets/generated_images/Caramelized_Onion_Thyme_Focaccia_d2f3d651.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "2 large yellow onions, thinly sliced",
      "2 tablespoons fresh thyme leaves",
      "1 tablespoon butter (or dairy-free alternative)",
      "Flaky sea salt for finishing"
    ],
    instructions: [
      "Caramelize onions: Heat 2 tablespoons olive oil and butter in a large skillet over medium heat. Add sliced onions and cook, stirring occasionally, for 30-35 minutes until deep golden brown. Set aside to cool.",
      "In a bowl, combine warm water, sugar, and yeast. Let stand 10 minutes until foamy.",
      "Whisk together gluten-free flour blend, almond flour, psyllium husk, and salt.",
      "Add yeast mixture and 3 tablespoons olive oil to dry ingredients. Mix to form a wet dough.",
      "Fold in half the caramelized onions and 1 tablespoon thyme. Cover and rise for 90 minutes.",
      "Preheat oven to 425°F. Oil a 9x13-inch pan with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Top with remaining caramelized onions, thyme leaves, and flaky salt.",
      "Bake 20-25 minutes until golden and crispy on edges.",
      "Let cool slightly before serving as pizza base or appetizer bread."
    ],
    tips: "Don't rush the caramelization process - slow cooking develops deep sweetness. Use a mix of yellow and red onions for more complex flavor. Store leftovers in an airtight container and reheat in a 375°F oven to restore crispness.",
    variations: [
      "Add crumbled goat cheese after baking",
      "Mix in balsamic vinegar during caramelization",
      "Top with crispy prosciutto before serving",
      "Add roasted garlic alongside the onions"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "caramelized onions", "thyme", "gourmet", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Caramelized Onions & Thyme | Unglued Food",
    seoDescription: "Elegant gluten-free focaccia with sweet caramelized onions and fresh thyme. Perfect for gourmet white pizzas with rich, savory flavors and golden crispy crust."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Olive Tapenade",
    slug: "gluten-free-focaccia-pizza-crust-olive-tapenade",
    description: "Mediterranean-inspired focaccia with bold olive tapenade swirled throughout - savory and intensely flavorful.",
    longDescription: "This Mediterranean gluten-free focaccia showcases the bold flavors of olive tapenade - a mixture of olives, capers, and herbs - swirled into the dough. The briny, savory notes of the tapenade permeate the bread, creating an intensely flavored focaccia with a soft, airy crumb and crispy edges. Perfect for serving with Mediterranean dishes or as a unique pizza base.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 140,
    servings: 8,
    rating: "4.6",
    calories: 258,
    protein: "6.8",
    carbs: "31.0",
    fat: "12.5",
    fiber: "4.0",
    sugar: "1.5",
    image: "/attached_assets/generated_images/Olive_Tapenade_Focaccia_Crust_e0278407.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "1/2 cup olive tapenade (mixed olives, capers, garlic, herbs)",
      "2 tablespoons chopped fresh parsley",
      "Whole olives for topping (optional)"
    ],
    instructions: [
      "Mix warm water, sugar, and yeast in a bowl. Let proof for 10 minutes until bubbly.",
      "Combine gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Stir until a sticky dough forms.",
      "Gently fold in olive tapenade and parsley, creating swirls (don't overmix).",
      "Cover and let rise in a warm place for 90 minutes.",
      "Preheat oven to 425°F. Drizzle a 9x13-inch baking sheet with remaining olive oil.",
      "Transfer dough to pan and spread with oiled fingers, creating dimples.",
      "Press additional whole olives into the surface if desired.",
      "Bake 20-25 minutes until golden brown with crispy edges.",
      "Cool briefly before slicing. Serve as pizza base or Mediterranean appetizer."
    ],
    tips: "Use a high-quality olive tapenade for best flavor - either homemade or from a specialty store. If the tapenade is very oily, drain excess before adding to dough. This focaccia pairs beautifully with hummus, labneh, or as a base for white pizza.",
    variations: [
      "Use green olive tapenade for a milder flavor",
      "Add sun-dried tomatoes to the tapenade mixture",
      "Top with crumbled feta cheese after baking",
      "Mix in chopped fresh oregano or basil"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Mediterranean", "olives", "tapenade", "savory"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Olive Tapenade | Unglued Food",
    seoDescription: "Bold Mediterranean gluten-free focaccia with olive tapenade swirled throughout. Intensely flavorful pizza crust with briny olives, capers, and fresh herbs."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Roasted Peppers & Feta",
    slug: "gluten-free-focaccia-pizza-crust-roasted-peppers-feta",
    description: "Greek-inspired focaccia with sweet roasted red peppers and tangy feta - colorful and delicious.",
    longDescription: "This Greek-inspired gluten-free focaccia combines sweet roasted red peppers with tangy feta cheese for a colorful, flavor-packed bread. The peppers add sweetness and vibrant color while the feta provides a salty, creamy contrast. With a light, airy texture and golden crispy crust, this focaccia makes an excellent base for Mediterranean pizzas or a standout appetizer.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135,
    servings: 8,
    rating: "4.7",
    calories: 265,
    protein: "8.0",
    carbs: "32.5",
    fat: "11.2",
    fiber: "3.2",
    sugar: "3.8",
    image: "/attached_assets/generated_images/Roasted_Pepper_Feta_Focaccia_fa633672.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "1 cup roasted red peppers, sliced",
      "3/4 cup crumbled feta cheese",
      "1 teaspoon dried oregano",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Combine warm water, sugar, and yeast. Let bloom for 10 minutes.",
      "In a large bowl, whisk together gluten-free flour blend, almond flour, psyllium husk, and salt.",
      "Add yeast mixture and 3 tablespoons olive oil. Mix until a wet dough forms.",
      "Cover and let rise for 90 minutes in a warm location.",
      "Preheat oven to 425°F. Oil a 9x13-inch baking pan with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Arrange roasted pepper strips across the surface, pressing lightly into dough.",
      "Scatter crumbled feta over the top and sprinkle with oregano.",
      "Bake 20-25 minutes until golden and feta is slightly melted.",
      "Garnish with fresh basil and serve warm as pizza base or flatbread."
    ],
    tips: "Use jarred roasted red peppers (drained well) or roast your own for deeper flavor. For a dairy-free version, use vegan feta. This focaccia is excellent topped with additional ingredients like olives, artichokes, or spinach for a full Greek-style pizza.",
    variations: [
      "Add sliced Kalamata olives alongside the peppers",
      "Use yellow or orange roasted peppers for color variety",
      "Drizzle with tzatziki sauce after baking",
      "Mix in chopped fresh dill or mint"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Greek", "roasted peppers", "feta", "Mediterranean"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Roasted Peppers & Feta | Unglued Food",
    seoDescription: "Greek-inspired gluten-free focaccia with sweet roasted red peppers and tangy feta cheese. Colorful, flavorful pizza crust perfect for Mediterranean toppings."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Sun-Dried Tomato & Parmesan",
    slug: "gluten-free-focaccia-pizza-crust-sun-dried-tomato-parmesan",
    description: "Robust focaccia with intense sun-dried tomatoes and aged Parmesan - rich and satisfying.",
    longDescription: "This gluten-free focaccia delivers bold Italian flavors with intensely flavored sun-dried tomatoes and nutty aged Parmesan cheese. The sun-dried tomatoes provide concentrated sweetness and umami while the Parmesan adds a salty, savory depth. With a slightly chewy texture, airy crumb, and crispy golden crust, this focaccia is perfect for those who love big, robust flavors.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135,
    servings: 8,
    rating: "4.8",
    calories: 272,
    protein: "8.5",
    carbs: "31.0",
    fat: "12.8",
    fiber: "3.5",
    sugar: "2.5",
    image: "/attached_assets/generated_images/Sun-Dried_Tomato_Parmesan_Focaccia_8f72bb86.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "2/3 cup sun-dried tomatoes, chopped (oil-packed, drained)",
      "3/4 cup grated Parmesan cheese, divided",
      "1 teaspoon Italian seasoning",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Mix warm water, sugar, and yeast in a small bowl. Let stand 10 minutes until foamy.",
      "Combine gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Stir to form a sticky dough.",
      "Fold in chopped sun-dried tomatoes and 1/2 cup Parmesan cheese.",
      "Cover and let rise in a warm place for 90 minutes.",
      "Preheat oven to 425°F. Drizzle a 9x13-inch pan with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Sprinkle remaining Parmesan and Italian seasoning over the top.",
      "Bake 20-25 minutes until golden with crispy, cheese-crusted edges.",
      "Garnish with fresh basil and serve warm as pizza base or Italian bread."
    ],
    tips: "Use oil-packed sun-dried tomatoes for best flavor and texture - pat dry before chopping. For extra richness, reserve 2 tablespoons of the tomato oil to use in the dough. This focaccia freezes well for up to 3 months.",
    variations: [
      "Add fresh mozzarella chunks for extra cheesiness",
      "Mix in roasted garlic with the sun-dried tomatoes",
      "Top with pine nuts before baking",
      "Use pecorino Romano instead of Parmesan"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Italian", "sun-dried tomato", "Parmesan", "savory"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Sun-Dried Tomato & Parmesan | Unglued Food",
    seoDescription: "Robust gluten-free focaccia with intense sun-dried tomatoes and aged Parmesan. Rich, flavorful pizza crust with bold Italian flavors and crispy cheese edges."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Za'atar & Olive Oil",
    slug: "gluten-free-focaccia-pizza-crust-zaatar-olive-oil",
    description: "Middle Eastern-inspired focaccia with aromatic za'atar spice blend - exotic and fragrant.",
    longDescription: "This Middle Eastern-inspired gluten-free focaccia features the aromatic za'atar spice blend - a mixture of dried herbs, sesame seeds, and sumac - creating a uniquely flavorful bread. Drizzled with high-quality olive oil and baked until golden, this focaccia offers an exotic twist on the Italian classic. Perfect as a base for labneh and vegetables or enjoyed simply with hummus.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135,
    servings: 8,
    rating: "4.6",
    calories: 248,
    protein: "6.8",
    carbs: "32.0",
    fat: "10.5",
    fiber: "3.8",
    sugar: "1.5",
    image: "/attached_assets/generated_images/Za'atar_Olive_Oil_Focaccia_68f77086.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "3 tablespoons za'atar spice blend",
      "2 tablespoons sesame seeds",
      "Flaky sea salt for finishing"
    ],
    instructions: [
      "Combine warm water, sugar, and yeast in a bowl. Let proof for 10 minutes.",
      "In a large bowl, whisk together gluten-free flour blend, almond flour, psyllium husk, and salt.",
      "Add yeast mixture and 3 tablespoons olive oil. Mix to create a sticky dough.",
      "Fold in 2 tablespoons za'atar. Cover and rise for 90 minutes.",
      "Preheat oven to 425°F. Oil a 9x13-inch baking sheet with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Drizzle generously with additional olive oil (about 2 tablespoons).",
      "Sprinkle remaining za'atar, sesame seeds, and flaky salt over the surface.",
      "Bake 20-25 minutes until golden with crispy, aromatic crust.",
      "Serve warm with labneh, hummus, or as a Middle Eastern-style pizza base."
    ],
    tips: "Use authentic za'atar for best flavor - look for it at Middle Eastern markets or specialty spice shops. The quality of olive oil matters here, so use a fruity, high-quality extra-virgin variety. This focaccia is excellent for wraps, sandwiches, or torn into pieces for dipping.",
    variations: [
      "Add crumbled feta or labneh after baking",
      "Mix in chopped fresh mint or parsley",
      "Top with sliced cucumbers and tomatoes for a light meal",
      "Drizzle with honey for a sweet-savory contrast"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "Middle Eastern", "za'atar", "sesame", "exotic"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Za'atar & Olive Oil | Unglued Food",
    seoDescription: "Middle Eastern-inspired gluten-free focaccia with aromatic za'atar spice blend. Exotic, fragrant pizza crust perfect with hummus, labneh, or fresh vegetables."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Roasted Garlic & Sea Salt",
    slug: "gluten-free-focaccia-pizza-crust-roasted-garlic-sea-salt",
    description: "Simple yet sophisticated focaccia with sweet roasted garlic and flaky sea salt - aromatic and versatile.",
    longDescription: "This gluten-free focaccia celebrates simplicity with sweet, caramelized roasted garlic cloves and flaky sea salt. The slow-roasted garlic becomes mellow and spreadable, infusing the bread with deep, aromatic flavor. With a light, airy crumb and crispy golden crust, this versatile focaccia works beautifully as a pizza base, sandwich bread, or appetizer.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 55,
    totalTime: 165,
    servings: 8,
    rating: "4.8",
    calories: 242,
    protein: "6.2",
    carbs: "32.5",
    fat: "10.2",
    fiber: "3.0",
    sugar: "1.8",
    image: "/attached_assets/generated_images/Roasted_Garlic_Sea_Salt_Focaccia_dcf9bbab.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "2 whole heads of garlic",
      "2 tablespoons flaky sea salt for topping",
      "Fresh herbs for garnish (optional)"
    ],
    instructions: [
      "Preheat oven to 400°F. Cut tops off garlic heads, drizzle with olive oil, wrap in foil, and roast for 30 minutes until soft and golden. Let cool, then squeeze out cloves.",
      "Combine warm water, sugar, and yeast. Let stand 10 minutes until foamy.",
      "Mix gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Stir to form a wet dough.",
      "Gently fold in half the roasted garlic cloves. Cover and rise for 90 minutes.",
      "Increase oven temperature to 425°F. Oil a 9x13-inch pan with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating deep dimples.",
      "Press remaining roasted garlic cloves into the dimples. Sprinkle generously with flaky sea salt.",
      "Bake 20-25 minutes until golden brown with crispy edges.",
      "Cool slightly before serving as pizza base or artisan bread."
    ],
    tips: "Roast extra garlic heads and keep refrigerated for up to a week - it's delicious spread on the finished focaccia. The roasted garlic adds natural sweetness and can be mashed into the dough for even distribution. Don't skip the flaky sea salt - it provides essential texture contrast.",
    variations: [
      "Add fresh rosemary or thyme for extra herbaceous notes",
      "Top with grated Parmesan before baking",
      "Brush with garlic-infused butter after baking",
      "Mix in sun-dried tomatoes with the roasted garlic"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "roasted garlic", "sea salt", "simple", "aromatic"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Roasted Garlic & Sea Salt | Unglued Food",
    seoDescription: "Simple yet sophisticated gluten-free focaccia with sweet roasted garlic and flaky sea salt. Aromatic, versatile pizza crust perfect for any topping."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Everything Bagel Seasoning",
    slug: "gluten-free-focaccia-pizza-crust-everything-bagel-seasoning",
    description: "Fun and flavorful focaccia coated in everything bagel seasoning - perfect for brunch-style pizzas.",
    longDescription: "This playful gluten-free focaccia brings the beloved flavors of an everything bagel to pizza crust form. Generously coated with sesame seeds, poppy seeds, dried onion, and garlic, this focaccia offers a fun twist on traditional Italian bread. With a soft, airy interior and seed-crusted exterior, it's perfect for brunch pizzas, breakfast sandwiches, or as a unique appetizer.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 25,
    totalTime: 135,
    servings: 8,
    rating: "4.7",
    calories: 255,
    protein: "7.0",
    carbs: "33.0",
    fat: "11.0",
    fiber: "3.5",
    sugar: "1.5",
    image: "/attached_assets/generated_images/Everything_Bagel_Focaccia_Crust_2b46b245.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "1/4 cup everything bagel seasoning (sesame seeds, poppy seeds, dried onion, dried garlic, sea salt)",
      "Extra everything bagel seasoning for topping"
    ],
    instructions: [
      "Mix warm water, sugar, and yeast in a bowl. Let bloom for 10 minutes.",
      "Combine gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Mix until a sticky dough forms.",
      "Fold in 1/4 cup everything bagel seasoning. Cover and rise for 90 minutes.",
      "Preheat oven to 425°F. Drizzle a 9x13-inch baking sheet with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Brush surface with additional olive oil (1-2 tablespoons).",
      "Generously sprinkle everything bagel seasoning over the entire surface, pressing lightly to adhere.",
      "Bake 20-25 minutes until golden brown with toasted, aromatic seed coating.",
      "Serve warm as a brunch pizza base, for breakfast sandwiches, or with cream cheese."
    ],
    tips: "Make your own everything bagel seasoning by mixing 2 tablespoons each: sesame seeds, poppy seeds, dried minced onion, dried minced garlic, and 1 tablespoon coarse sea salt. This focaccia is fantastic topped with smoked salmon, cream cheese, and capers for a bagel-inspired pizza.",
    variations: [
      "Top with scrambled eggs and cheese for breakfast pizza",
      "Add cream cheese and smoked salmon for a bagel-style appetizer",
      "Use as sandwich bread for deli meat and cheese",
      "Serve with flavored cream cheese spreads"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "everything bagel", "brunch", "breakfast", "fun"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Everything Bagel Seasoning | Unglued Food",
    seoDescription: "Fun gluten-free focaccia coated in everything bagel seasoning with sesame, poppy seeds, onion, and garlic. Perfect for brunch pizzas and breakfast sandwiches."
  },
  {
    title: "Gluten-Free Focaccia Pizza Crust with Spinach & Ricotta Swirl",
    slug: "gluten-free-focaccia-pizza-crust-spinach-ricotta-swirl",
    description: "Light and savory focaccia with fresh spinach and creamy ricotta - perfect for vegetarian pizza nights.",
    longDescription: "This elegant gluten-free focaccia features a beautiful swirl of fresh spinach and creamy ricotta cheese, creating a light yet satisfying bread. The herb-infused dough pairs perfectly with the mild, creamy ricotta while the spinach adds color, nutrition, and earthy flavor. With a soft, airy texture and golden edges, this focaccia is ideal for vegetarian pizza nights or as a standalone Italian flatbread.",
    category: "Pizza",
    subcategory: "Gluten-Free Focaccia Pizza Crust",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 140,
    servings: 8,
    rating: "4.7",
    calories: 268,
    protein: "9.5",
    carbs: "32.0",
    fat: "11.5",
    fiber: "3.5",
    sugar: "2.0",
    image: "/attached_assets/generated_images/Spinach_Ricotta_Swirl_Focaccia_ff4de387.png",
    ingredients: [
      "2 cups gluten-free flour blend",
      "1/4 cup almond flour",
      "2 teaspoons psyllium husk powder",
      "1 tablespoon active dry yeast",
      "1 tablespoon sugar",
      "1 1/4 cups warm water (110°F)",
      "1/3 cup extra-virgin olive oil, divided",
      "1 teaspoon sea salt",
      "2 cups fresh spinach, chopped",
      "1 cup ricotta cheese",
      "2 cloves garlic, minced",
      "1/4 cup grated Parmesan cheese",
      "1 teaspoon Italian herbs (basil, oregano)",
      "Pinch of nutmeg"
    ],
    instructions: [
      "Prepare spinach mixture: Sauté chopped spinach in 1 tablespoon olive oil until wilted. Let cool, then squeeze out excess moisture. Mix with ricotta, garlic, Parmesan, Italian herbs, and nutmeg. Set aside.",
      "Combine warm water, sugar, and yeast. Let stand 10 minutes until foamy.",
      "Mix gluten-free flour blend, almond flour, psyllium husk, and salt in a large bowl.",
      "Add yeast mixture and 3 tablespoons olive oil. Stir to form a wet dough.",
      "Cover and let rise in a warm place for 90 minutes.",
      "Preheat oven to 425°F. Oil a 9x13-inch pan with remaining olive oil.",
      "Transfer dough to pan and press with oiled fingers to fill, creating dimples.",
      "Dollop spinach-ricotta mixture over the surface in spoonfuls, swirling gently with a knife.",
      "Bake 20-25 minutes until golden and ricotta is set with slight browning.",
      "Cool briefly before serving as vegetarian pizza base or Italian flatbread."
    ],
    tips: "Make sure to squeeze out all excess moisture from the cooked spinach to prevent a soggy focaccia. Fresh ricotta works best - drain if very wet. For a dairy-free version, use cashew ricotta or tofu-based alternative. This focaccia reheats beautifully in a 350°F oven.",
    variations: [
      "Add sun-dried tomatoes to the ricotta mixture",
      "Mix in crumbled feta with the spinach",
      "Top with pine nuts before baking",
      "Use kale or Swiss chard instead of spinach"
    ],
    tags: ["gluten-free", "pizza", "focaccia", "spinach", "ricotta", "vegetarian", "Italian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Focaccia Pizza Crust with Spinach & Ricotta Swirl | Unglued Food",
    seoDescription: "Light and savory gluten-free focaccia with fresh spinach and creamy ricotta swirl. Perfect vegetarian pizza crust with herb-infused dough and golden edges."
  }
];

async function addFocacciaRecipes() {
  console.log("Adding 10 gluten-free focaccia pizza crust recipes...\n");
  
  for (const recipe of focacciaRecipes) {
    try {
      const created = await storage.createRecipe(recipe);
      console.log(`✓ Added: ${created.title}`);
    } catch (error) {
      console.error(`✗ Failed to add: ${recipe.title}`);
      console.error(error);
    }
  }
  
  console.log("\n✓ All focaccia recipes added successfully!");
  process.exit(0);
}

addFocacciaRecipes().catch((error) => {
  console.error("Error adding recipes:", error);
  process.exit(1);
});
