import { storage } from "./storage";
import type { InsertRecipe } from "@shared/schema";

const dessertRecipes: InsertRecipe[] = [
  {
    title: "Gluten-Free Chocolate Lava Cake",
    slug: "gluten-free-chocolate-lava-cake",
    description: "Rich molten chocolate center with almond flour base - indulgent, decadent, and perfect for special occasions.",
    longDescription: "This gluten-free chocolate lava cake delivers restaurant-quality decadence with a molten chocolate center that flows when cut. Made with almond flour for a tender crumb and rich dark chocolate for intense flavor, each individual ramekin bakes to perfection with a crispy exterior and gooey interior. The combination of quality cocoa and precise baking creates that signature molten center that makes this dessert unforgettable.",
    category: "Desserts",
    subcategory: "Cakes & Cupcakes",
    difficulty: "Hard",
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    servings: 4,
    rating: "4.9",
    calories: 385,
    protein: "8.5",
    carbs: "32.0",
    fat: "26.5",
    fiber: "4.5",
    sugar: "22.0",
    image: "/recipe-images/Chocolate_Lava_Cake_Molten_Center_d5ab98ff.png",
    ingredients: [
      "6 oz dark chocolate (70% cacao), chopped",
      "1/2 cup unsalted butter (or coconut oil)",
      "2 large eggs plus 2 egg yolks",
      "1/4 cup granulated sugar",
      "2 tablespoons honey or maple syrup",
      "1/2 cup almond flour",
      "2 tablespoons cocoa powder",
      "1/4 teaspoon sea salt",
      "1 teaspoon vanilla extract",
      "Butter and cocoa powder for ramekins",
      "Powdered sugar for dusting",
      "Fresh raspberries for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Butter four 6-oz ramekins and dust with cocoa powder, tapping out excess.",
      "In a double boiler or microwave, melt chocolate and butter together, stirring until smooth. Let cool slightly.",
      "In a medium bowl, whisk together eggs, egg yolks, sugar, and honey until pale and slightly thickened, about 2 minutes.",
      "Whisk the melted chocolate mixture into the egg mixture along with vanilla extract.",
      "Sift almond flour, cocoa powder, and salt together. Gently fold into chocolate mixture until just combined.",
      "Divide batter evenly among prepared ramekins, filling about 3/4 full.",
      "Place ramekins on a baking sheet and bake for 12-14 minutes. Edges should be set but centers will still jiggle slightly.",
      "Remove from oven and let stand for 1 minute. Run a knife around edges to loosen.",
      "Invert each ramekin onto a serving plate. Let sit for 10 seconds, then carefully lift off ramekin.",
      "Dust with powdered sugar, garnish with fresh raspberries, and serve immediately while centers are molten."
    ],
    tips: "The key to perfect lava cakes is timing - bake just until the edges are set but the center still jiggles. You can prepare the batter ahead and refrigerate filled ramekins for up to 24 hours; add 2-3 minutes to baking time if baking from cold.",
    variations: [
      "Add a teaspoon of espresso powder for mocha lava cakes",
      "Place a square of chocolate in the center before baking for extra gooeyness",
      "Use coconut sugar instead of granulated for a caramel note",
      "Add a tablespoon of orange zest for chocolate-orange flavor"
    ],
    tags: ["gluten-free", "dessert", "chocolate", "lava cake", "special occasion", "romantic", "individual serving"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Chocolate Lava Cake with Molten Center | Unglued Food",
    seoDescription: "Decadent gluten-free chocolate lava cake with molten center. Made with almond flour and dark chocolate for the perfect special occasion dessert with gooey interior."
  },
  {
    title: "Gluten-Free Lemon Pudding Cups",
    slug: "gluten-free-lemon-pudding-cups",
    description: "Light, tangy lemon custard layered with whipped cream and zest - simple, elegant, and refreshing.",
    longDescription: "These gluten-free lemon pudding cups offer a perfect balance of sweet and tart with a silky-smooth custard texture. Fresh lemon juice and zest create bright, vibrant flavor while the creamy pudding base provides richness. Layered in clear glasses with whipped cream and garnished with lemon curls, these individual desserts are as beautiful as they are delicious - ideal for spring and summer entertaining.",
    category: "Desserts",
    subcategory: "Custards & Puddings",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 10,
    totalTime: 145,
    servings: 6,
    rating: "4.7",
    calories: 245,
    protein: "4.5",
    carbs: "28.0",
    fat: "13.5",
    fiber: "0.5",
    sugar: "24.0",
    image: "/recipe-images/Lemon_Pudding_Cups_Layered_500cddc4.png",
    ingredients: [
      "3/4 cup fresh lemon juice (about 4 lemons)",
      "1 tablespoon lemon zest",
      "3/4 cup granulated sugar",
      "3 large eggs",
      "2 egg yolks",
      "1/2 cup heavy cream (or coconut cream)",
      "3 tablespoons cornstarch",
      "1/4 teaspoon sea salt",
      "3 tablespoons unsalted butter, cubed",
      "1 cup heavy whipping cream for topping",
      "2 tablespoons powdered sugar",
      "Additional lemon zest for garnish",
      "Fresh lemon slices for decoration"
    ],
    instructions: [
      "In a medium saucepan, whisk together lemon juice, lemon zest, sugar, eggs, egg yolks, cream, cornstarch, and salt.",
      "Cook over medium heat, whisking constantly, until mixture thickens and comes to a gentle boil, about 8-10 minutes.",
      "Remove from heat and whisk in butter cubes one at a time until fully melted and incorporated.",
      "Strain pudding through a fine-mesh sieve into a bowl to remove any lumps and lemon zest pieces.",
      "Press plastic wrap directly onto surface of pudding to prevent skin from forming. Refrigerate for at least 2 hours or until completely chilled.",
      "When ready to serve, whip cream with powdered sugar until stiff peaks form.",
      "Spoon chilled lemon pudding into clear glass cups or bowls, filling about 2/3 full.",
      "Top each cup with a generous dollop of whipped cream.",
      "Garnish with lemon zest curls and a thin lemon slice. Serve chilled."
    ],
    tips: "For the brightest flavor, use fresh lemon juice - bottled won't deliver the same vibrant taste. The pudding can be made up to 3 days ahead and stored covered in the refrigerator. For a lighter version, fold half the whipped cream into the pudding and top with the rest.",
    variations: [
      "Use lime juice and zest for tangy lime pudding cups",
      "Add fresh blueberries or raspberries between layers",
      "Make it dairy-free with full-fat coconut cream throughout",
      "Swirl in 2 tablespoons of lavender honey for floral notes"
    ],
    tags: ["gluten-free", "dessert", "lemon", "pudding", "custard", "individual serving", "make-ahead", "refreshing"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Lemon Pudding Cups - Light & Tangy | Unglued Food",
    seoDescription: "Refreshing gluten-free lemon pudding cups with silky custard and whipped cream. Bright, tangy dessert perfect for spring and summer entertaining."
  },
  {
    title: "Gluten-Free Strawberry Shortcake Bars",
    slug: "gluten-free-strawberry-shortcake-bars",
    description: "Almond flour shortbread base topped with whipped cream and macerated strawberries - classic flavor, handheld form.",
    longDescription: "These gluten-free strawberry shortcake bars transform the beloved classic into a portable dessert with layers of buttery almond flour shortbread, fluffy whipped cream, and sweet macerated strawberries. The shortbread base is crisp yet tender, providing the perfect foundation for fresh strawberry topping. Cut into bars for easy serving, these treats bring all the nostalgic flavors of summer in a convenient handheld format.",
    category: "Desserts",
    subcategory: "Bars & Brownies",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 105,
    servings: 12,
    rating: "4.8",
    calories: 285,
    protein: "5.0",
    carbs: "26.5",
    fat: "18.5",
    fiber: "2.8",
    sugar: "16.0",
    image: "/recipe-images/Strawberry_Shortcake_Bars_Layered_2e76b778.png",
    ingredients: [
      "2 cups almond flour",
      "1/4 cup coconut flour",
      "1/3 cup granulated sugar",
      "1/2 teaspoon sea salt",
      "1/2 cup cold unsalted butter, cubed",
      "1 teaspoon vanilla extract",
      "1 egg yolk",
      "2 lbs fresh strawberries, hulled and sliced",
      "1/4 cup sugar for macerating",
      "1 tablespoon lemon juice",
      "1 1/2 cups heavy whipping cream",
      "3 tablespoons powdered sugar",
      "1 teaspoon vanilla extract",
      "Fresh mint for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Line a 9x13-inch baking pan with parchment paper, leaving overhang on sides.",
      "In a food processor, combine almond flour, coconut flour, sugar, and salt. Pulse to mix.",
      "Add cold butter cubes and pulse until mixture resembles coarse crumbs.",
      "Add vanilla extract and egg yolk. Pulse until dough just comes together.",
      "Press dough evenly into prepared pan. Prick all over with a fork.",
      "Bake for 22-25 minutes until golden brown and firm. Cool completely in pan.",
      "Meanwhile, toss sliced strawberries with 1/4 cup sugar and lemon juice. Let macerate for 30 minutes, stirring occasionally.",
      "Whip cream with powdered sugar and vanilla until stiff peaks form.",
      "Once shortbread is completely cool, spread whipped cream evenly over the top.",
      "Drain excess juice from strawberries (reserve for drizzling). Arrange strawberry slices over whipped cream.",
      "Refrigerate for at least 30 minutes. Cut into 12 bars using the parchment overhang to lift from pan.",
      "Garnish with fresh mint and drizzle with reserved strawberry juice before serving."
    ],
    tips: "Make sure the shortbread base is completely cool before adding whipped cream, or it will melt. These bars are best served the same day but the shortbread can be baked 1-2 days ahead. For clean cuts, wipe your knife between slices.",
    variations: [
      "Use raspberries, blueberries, or mixed berries instead",
      "Add a layer of lemon curd between shortbread and cream",
      "Mix fresh basil into the macerated strawberries",
      "Use stabilized whipped cream (add cream cheese) for longer storage"
    ],
    tags: ["gluten-free", "dessert", "strawberry", "shortcake", "bars", "summer", "fresh fruit", "handheld"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Strawberry Shortcake Bars - Classic Summer Dessert | Unglued Food",
    seoDescription: "Classic gluten-free strawberry shortcake bars with almond flour shortbread, whipped cream, and fresh strawberries. Perfect handheld summer dessert."
  },
  {
    title: "Gluten-Free Tiramisu Cups",
    slug: "gluten-free-tiramisu-cups",
    description: "Espresso-soaked gluten-free sponge layers with mascarpone cream and cocoa dusting - Italian-inspired individual treats.",
    longDescription: "These gluten-free tiramisu cups bring authentic Italian flavor in individual portions with layers of espresso-soaked almond flour sponge cake and silky mascarpone cream. The coffee-soaked layers provide bold flavor while the sweet, creamy mascarpone balances with rich smoothness. Dusted with cocoa powder and garnished with coffee beans, these elegant desserts are perfect for dinner parties and special occasions.",
    category: "Desserts",
    subcategory: "Custards & Puddings",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 15,
    totalTime: 165,
    servings: 8,
    rating: "4.9",
    calories: 365,
    protein: "7.5",
    carbs: "28.0",
    fat: "26.0",
    fiber: "1.5",
    sugar: "20.0",
    image: "/recipe-images/Tiramisu_Cups_Individual_Servings_22eba0a6.png",
    ingredients: [
      "3/4 cup almond flour",
      "1/4 cup tapioca starch",
      "4 large eggs, separated",
      "1/2 cup sugar, divided",
      "1 teaspoon vanilla extract",
      "1/4 teaspoon cream of tartar",
      "1 cup strong brewed espresso, cooled",
      "2 tablespoons coffee liqueur (optional)",
      "16 oz mascarpone cheese, room temperature",
      "1/2 cup heavy cream",
      "1/3 cup powdered sugar",
      "1 teaspoon vanilla extract",
      "Unsweetened cocoa powder for dusting",
      "Chocolate-covered espresso beans for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Line an 8x8-inch pan with parchment paper.",
      "For sponge cake: Whisk together almond flour and tapioca starch. Set aside.",
      "Beat egg yolks with 1/4 cup sugar until pale and thick, about 3 minutes. Mix in vanilla.",
      "In separate bowl, beat egg whites with cream of tartar until soft peaks form. Gradually add remaining 1/4 cup sugar, beating to stiff peaks.",
      "Gently fold flour mixture into yolk mixture. Fold in 1/3 of egg whites to lighten, then fold in remaining whites.",
      "Spread batter in prepared pan. Bake 12-15 minutes until golden and springy. Cool completely.",
      "Combine cooled espresso with coffee liqueur if using. Set aside.",
      "For mascarpone cream: Beat mascarpone, heavy cream, powdered sugar, and vanilla until smooth and fluffy, about 2 minutes.",
      "Cut cooled sponge into cubes. Quickly dip half the cubes in espresso mixture.",
      "Layer espresso-soaked cake cubes in bottom of 8 clear glasses or cups.",
      "Spoon half of mascarpone cream over cake layer. Repeat with remaining soaked cake and cream.",
      "Cover and refrigerate for at least 2 hours or overnight. Before serving, dust generously with cocoa powder and top with espresso bean."
    ],
    tips: "Don't over-soak the sponge cake or it will become mushy - a quick dip is all you need. Make sure mascarpone is at room temperature for smoothest cream. Tiramisu actually tastes better the next day after flavors meld, and it keeps refrigerated for up to 3 days.",
    variations: [
      "Use decaf espresso for a caffeine-free version",
      "Layer with fresh raspberries for fruity contrast",
      "Add a tablespoon of instant espresso powder to mascarpone cream",
      "Use amaretto instead of coffee liqueur for almond flavor"
    ],
    tags: ["gluten-free", "dessert", "tiramisu", "Italian", "coffee", "mascarpone", "individual serving", "make-ahead", "elegant"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Tiramisu Cups - Individual Italian Dessert | Unglued Food",
    seoDescription: "Elegant gluten-free tiramisu cups with espresso-soaked sponge and mascarpone cream. Classic Italian dessert in individual portions perfect for entertaining."
  },
  {
    title: "Gluten-Free Almond Butter Brownies",
    slug: "gluten-free-almond-butter-brownies",
    description: "Fudgy, rich brownies swirled with creamy almond butter - no refined sugar, perfectly chewy.",
    longDescription: "These gluten-free almond butter brownies are intensely fudgy with a rich chocolate flavor enhanced by swirls of creamy almond butter throughout. Made without refined sugar using coconut sugar and maple syrup, these brownies are naturally sweetened yet deeply satisfying. The almond butter creates beautiful marbling and adds protein and healthy fats, making these treats both indulgent and nourishing.",
    category: "Desserts",
    subcategory: "Bars & Brownies",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 30,
    totalTime: 105,
    servings: 16,
    rating: "4.8",
    calories: 225,
    protein: "6.5",
    carbs: "22.0",
    fat: "14.5",
    fiber: "3.0",
    sugar: "14.0",
    image: "/recipe-images/Almond_Butter_Brownies_Fudgy_8e040aea.png",
    ingredients: [
      "1 cup almond flour",
      "1/2 cup cocoa powder",
      "1/2 teaspoon baking soda",
      "1/4 teaspoon sea salt",
      "3/4 cup coconut sugar",
      "1/3 cup coconut oil, melted",
      "1/4 cup maple syrup",
      "3 large eggs",
      "2 teaspoons vanilla extract",
      "1/2 cup dark chocolate chips",
      "1/2 cup creamy almond butter",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "Preheat oven to 350°F. Line an 8x8-inch baking pan with parchment paper, leaving overhang on sides.",
      "In a medium bowl, whisk together almond flour, cocoa powder, baking soda, and salt.",
      "In a large bowl, whisk together coconut sugar, melted coconut oil, maple syrup, eggs, and vanilla until smooth.",
      "Add dry ingredients to wet ingredients and stir until just combined. Fold in chocolate chips.",
      "Pour batter into prepared pan, spreading evenly.",
      "Warm almond butter slightly to make it pourable. Drop spoonfuls of almond butter over brownie batter.",
      "Using a knife or skewer, swirl almond butter into the batter creating marble patterns.",
      "Sprinkle top with flaky sea salt.",
      "Bake for 28-32 minutes until edges are set but center still appears slightly underdone (a toothpick should have moist crumbs).",
      "Cool completely in pan on a wire rack, about 1 hour. The brownies will firm up as they cool.",
      "Use parchment overhang to lift brownies from pan. Cut into 16 squares with a sharp knife."
    ],
    tips: "Don't overbake - the key to fudgy brownies is pulling them when they still look slightly underdone. They'll continue cooking as they cool. For extra decadence, serve warm with vanilla ice cream. These brownies are even better the next day once flavors develop.",
    variations: [
      "Use peanut butter or cashew butter instead of almond butter",
      "Add 1/2 cup chopped walnuts or pecans to batter",
      "Drizzle with melted dark chocolate after cooling",
      "Mix in 1/2 teaspoon espresso powder for mocha brownies"
    ],
    tags: ["gluten-free", "dessert", "brownies", "almond butter", "chocolate", "no refined sugar", "fudgy", "naturally sweetened"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Almond Butter Brownies - Fudgy & Naturally Sweetened | Unglued Food",
    seoDescription: "Fudgy gluten-free almond butter brownies made without refined sugar. Rich chocolate brownies swirled with creamy almond butter for perfect chewy texture."
  },
  {
    title: "Gluten-Free Coconut Cream Pie Bars",
    slug: "gluten-free-coconut-cream-pie-bars",
    description: "Toasted coconut crust with coconut pudding and whipped topping - tropical and creamy.",
    longDescription: "These gluten-free coconut cream pie bars deliver tropical paradise in every bite with three distinct coconut layers: a toasted coconut-almond crust, silky coconut pudding filling, and fluffy whipped cream topped with more toasted coconut. The combination of textures - crunchy, creamy, and light - creates a perfectly balanced dessert that's easier to serve than traditional pie. Coconut lovers will be in heaven!",
    category: "Desserts",
    subcategory: "Bars & Brownies",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 20,
    totalTime: 185,
    servings: 12,
    rating: "4.7",
    calories: 315,
    protein: "4.5",
    carbs: "28.0",
    fat: "21.5",
    fiber: "3.5",
    sugar: "18.0",
    image: "/recipe-images/Coconut_Cream_Pie_Bars_4f4961a9.png",
    ingredients: [
      "1 1/2 cups sweetened shredded coconut, divided",
      "1 cup almond flour",
      "1/4 cup coconut flour",
      "1/4 cup coconut sugar",
      "1/4 teaspoon sea salt",
      "1/3 cup coconut oil, melted",
      "1 can (13.5 oz) full-fat coconut milk",
      "1 cup whole milk (or additional coconut milk)",
      "2/3 cup granulated sugar",
      "1/4 cup cornstarch",
      "3 egg yolks",
      "2 tablespoons butter (or coconut oil)",
      "2 teaspoons vanilla extract",
      "1 teaspoon coconut extract",
      "1 cup heavy whipping cream",
      "2 tablespoons powdered sugar"
    ],
    instructions: [
      "Preheat oven to 350°F. Line a 9x13-inch pan with parchment paper.",
      "Spread 1 cup shredded coconut on a baking sheet. Toast in oven for 5-7 minutes, stirring halfway, until golden. Let cool.",
      "For crust: Mix almond flour, coconut flour, coconut sugar, salt, and 3/4 cup toasted coconut. Stir in melted coconut oil until combined.",
      "Press mixture firmly into prepared pan. Bake 12-15 minutes until golden. Cool completely.",
      "For filling: In a saucepan, whisk together coconut milk, milk, sugar, cornstarch, and egg yolks until smooth.",
      "Cook over medium heat, whisking constantly, until mixture thickens and bubbles, about 8-10 minutes.",
      "Remove from heat. Stir in butter, vanilla, and coconut extract. Let cool for 10 minutes, stirring occasionally.",
      "Pour coconut pudding over cooled crust, spreading evenly. Press plastic wrap directly on surface.",
      "Refrigerate for at least 2 hours until completely set.",
      "Before serving, whip cream with powdered sugar until stiff peaks form. Spread over chilled coconut layer.",
      "Sprinkle remaining toasted coconut over whipped cream. Cut into 12 bars and serve chilled."
    ],
    tips: "Watch the coconut closely while toasting - it goes from golden to burned quickly. For deeper coconut flavor, use all coconut milk instead of mixing with dairy milk. These bars can be made dairy-free by using coconut cream for whipping (chilled can overnight).",
    variations: [
      "Add a layer of pineapple preserves between crust and pudding",
      "Mix mini chocolate chips into the pudding for coconut-chocolate combo",
      "Use lime zest in the pudding for key lime-coconut flavor",
      "Top with fresh mango or passion fruit"
    ],
    tags: ["gluten-free", "dessert", "coconut", "pie bars", "tropical", "creamy", "layered"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Coconut Cream Pie Bars - Tropical Layered Dessert | Unglued Food",
    seoDescription: "Tropical gluten-free coconut cream pie bars with toasted coconut crust, creamy coconut pudding, and whipped topping. Perfect coconut lover's dessert."
  },
  {
    title: "Gluten-Free Salted Caramel Cheesecake Cups",
    slug: "gluten-free-salted-caramel-cheesecake-cups",
    description: "Mini cheesecakes layered with almond crust, caramel sauce, and flaky sea salt - sweet, salty, and smooth.",
    longDescription: "These gluten-free salted caramel cheesecake cups offer the perfect marriage of sweet and salty in elegant individual portions. A buttery almond-based crust provides the foundation for rich, creamy cheesecake filling topped with luscious homemade caramel and finished with flaky sea salt. Served in mini mason jars or cups, these no-bake cheesecakes are ideal for parties and make-ahead entertaining.",
    category: "Desserts",
    subcategory: "Custards & Puddings",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 0,
    totalTime: 265,
    servings: 6,
    rating: "4.9",
    calories: 425,
    protein: "7.0",
    carbs: "36.0",
    fat: "29.5",
    fiber: "2.0",
    sugar: "28.0",
    image: "/recipe-images/Salted_Caramel_Cheesecake_Cups_d2b3fea0.png",
    ingredients: [
      "1 cup almond flour",
      "3 tablespoons coconut sugar",
      "1/4 teaspoon sea salt",
      "3 tablespoons melted butter",
      "16 oz cream cheese, softened",
      "1/2 cup powdered sugar",
      "1 teaspoon vanilla extract",
      "1 cup heavy whipping cream",
      "3/4 cup granulated sugar",
      "1/4 cup water",
      "1/3 cup heavy cream, warmed",
      "2 tablespoons butter",
      "1/2 teaspoon vanilla extract",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "For crust: Mix almond flour, coconut sugar, and salt. Stir in melted butter until mixture resembles wet sand.",
      "Divide crust mixture among 6 small mason jars or dessert cups (about 1/4 cup each). Press firmly to form base. Refrigerate.",
      "For cheesecake filling: Beat softened cream cheese until smooth and fluffy, about 2 minutes.",
      "Add powdered sugar and vanilla. Beat until fully combined and creamy.",
      "In separate bowl, whip heavy cream to stiff peaks. Gently fold whipped cream into cream cheese mixture in three additions.",
      "Spoon or pipe cheesecake mixture over chilled crusts, filling cups about 3/4 full. Smooth tops. Refrigerate.",
      "For salted caramel: In a saucepan, combine sugar and water. Cook over medium-high heat without stirring until deep amber, about 8-10 minutes.",
      "Remove from heat and carefully whisk in warm cream (it will bubble vigorously). Stir in butter and vanilla.",
      "Let caramel cool to room temperature, about 30 minutes. It will thicken as it cools.",
      "Spoon cooled caramel over each cheesecake cup (about 2 tablespoons each).",
      "Top each with a generous pinch of flaky sea salt. Refrigerate for at least 2 hours before serving."
    ],
    tips: "Make sure cream cheese is fully softened for smooth, lump-free filling. The caramel can be made up to a week ahead and stored refrigerated. For easier assembly, use a piping bag for the cheesecake layer. These cups can be made 2 days ahead.",
    variations: [
      "Use graham cracker-style gluten-free cookies for crust",
      "Add a layer of chocolate ganache between cheesecake and caramel",
      "Top with chopped pecans or toasted almonds",
      "Use dulce de leche instead of homemade caramel for shortcut"
    ],
    tags: ["gluten-free", "dessert", "cheesecake", "salted caramel", "no-bake", "individual serving", "make-ahead", "elegant"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Salted Caramel Cheesecake Cups - No-Bake Dessert | Unglued Food",
    seoDescription: "Elegant gluten-free salted caramel cheesecake cups with almond crust and homemade caramel. No-bake individual desserts perfect for entertaining."
  },
  {
    title: "Gluten-Free Blueberry Crumble Bars",
    slug: "gluten-free-blueberry-crumble-bars",
    description: "Buttery oat-almond crust with blueberry filling and golden crumb topping - perfect for breakfast or dessert.",
    longDescription: "These gluten-free blueberry crumble bars combine a buttery oat-almond base, jammy blueberry filling, and golden crumb topping for the ultimate fruit bar. Fresh or frozen blueberries cook down into a sweet-tart filling while the oat crumble provides satisfying texture and nutty flavor. Cut into squares, these versatile bars work equally well for breakfast, snacks, or dessert and transport easily for picnics and potlucks.",
    category: "Desserts",
    subcategory: "Bars & Brownies",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 125,
    servings: 16,
    rating: "4.8",
    calories: 195,
    protein: "3.5",
    carbs: "26.0",
    fat: "9.5",
    fiber: "2.5",
    sugar: "14.0",
    image: "/recipe-images/Blueberry_Crumble_Bars_Golden_1f088396.png",
    ingredients: [
      "2 cups gluten-free rolled oats",
      "1 cup almond flour",
      "1/2 cup coconut sugar",
      "1/2 teaspoon baking soda",
      "1/4 teaspoon sea salt",
      "1/2 teaspoon cinnamon",
      "1/2 cup coconut oil, melted",
      "1/4 cup maple syrup",
      "1 teaspoon vanilla extract",
      "3 cups fresh or frozen blueberries",
      "1/4 cup granulated sugar",
      "2 tablespoons cornstarch",
      "2 tablespoons lemon juice",
      "1 teaspoon lemon zest",
      "Powdered sugar for dusting"
    ],
    instructions: [
      "Preheat oven to 350°F. Line a 9x9-inch baking pan with parchment paper.",
      "In a large bowl, combine oats, almond flour, coconut sugar, baking soda, salt, and cinnamon.",
      "Add melted coconut oil, maple syrup, and vanilla. Stir until mixture is crumbly and holds together when pressed.",
      "Reserve 1 cup of the oat mixture for topping. Press remaining mixture firmly into prepared pan.",
      "Bake crust for 15 minutes until lightly golden. Remove from oven.",
      "Meanwhile, make blueberry filling: In a saucepan, combine blueberries, sugar, cornstarch, lemon juice, and lemon zest.",
      "Cook over medium heat, stirring gently, until blueberries release juice and mixture thickens, about 8-10 minutes.",
      "Pour blueberry filling over par-baked crust, spreading evenly.",
      "Crumble reserved oat mixture over blueberry layer, creating uneven crumb topping.",
      "Return to oven and bake 28-32 minutes until topping is golden brown and filling is bubbling at edges.",
      "Cool completely in pan, about 1 hour. The filling will set as it cools.",
      "Dust with powdered sugar. Cut into 16 squares and serve."
    ],
    tips: "If using frozen blueberries, don't thaw them first - they'll release too much liquid. For firmer bars, refrigerate after cooling before cutting. These bars freeze beautifully for up to 3 months - thaw at room temperature before serving.",
    variations: [
      "Use raspberries, blackberries, or mixed berries",
      "Add 1/4 teaspoon almond extract to the filling",
      "Mix in 1/4 cup chopped pecans to the crumb topping",
      "Use half blueberries and half strawberries"
    ],
    tags: ["gluten-free", "dessert", "blueberry", "crumble bars", "breakfast", "fruit bars", "oats"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Blueberry Crumble Bars - Perfect Fruit Dessert | Unglued Food",
    seoDescription: "Delicious gluten-free blueberry crumble bars with oat-almond crust and jammy filling. Perfect for breakfast, dessert, or snacks. Freezer-friendly!"
  },
  {
    title: "Gluten-Free Peanut Butter Chocolate Mousse",
    slug: "gluten-free-peanut-butter-chocolate-mousse",
    description: "Silky, dairy-free mousse made with cocoa, peanut butter, and coconut cream - rich yet light.",
    longDescription: "This gluten-free peanut butter chocolate mousse is incredibly silky and rich while remaining surprisingly light thanks to whipped coconut cream. The combination of deep chocolate flavor with creamy peanut butter creates an irresistible taste while being completely dairy-free and naturally gluten-free. Served in individual glasses and topped with crushed peanuts, this elegant mousse is perfect for those with dietary restrictions who don't want to compromise on decadence.",
    category: "Desserts",
    subcategory: "Frozen & No-Bake Desserts",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 5,
    totalTime: 140,
    servings: 6,
    rating: "4.8",
    calories: 285,
    protein: "7.5",
    carbs: "22.0",
    fat: "20.5",
    fiber: "3.5",
    sugar: "14.0",
    image: "/recipe-images/Peanut_Butter_Chocolate_Mousse_c2f6dd2e.png",
    ingredients: [
      "2 cans (13.5 oz each) full-fat coconut milk, refrigerated overnight",
      "1/2 cup cocoa powder",
      "1/3 cup maple syrup or agave nectar",
      "1/3 cup creamy peanut butter",
      "2 teaspoons vanilla extract",
      "Pinch of sea salt",
      "2 tablespoons powdered sugar",
      "2 oz dark chocolate, melted and slightly cooled",
      "Crushed peanuts for garnish",
      "Cocoa powder for dusting",
      "Peanut butter drizzle for topping"
    ],
    instructions: [
      "Refrigerate coconut milk cans overnight - this is crucial for the cream to separate and whip properly.",
      "Carefully open chilled cans and scoop out the thick coconut cream into a large bowl, leaving the liquid behind (save for smoothies).",
      "Add cocoa powder, maple syrup, peanut butter, vanilla, and salt to coconut cream.",
      "Using an electric mixer, beat on medium-high speed for 3-4 minutes until smooth, fluffy, and mousse-like.",
      "Add powdered sugar and beat for another minute until fully incorporated.",
      "Gently fold in melted dark chocolate, creating slight swirls (don't overmix).",
      "Divide mousse among 6 serving glasses or bowls.",
      "Cover and refrigerate for at least 2 hours to set and chill completely.",
      "Before serving, top each mousse with crushed peanuts, a dust of cocoa powder, and a drizzle of warmed peanut butter.",
      "Serve chilled. Mousse keeps refrigerated for up to 3 days."
    ],
    tips: "Don't skip refrigerating the coconut milk overnight - this step is essential for getting thick cream that whips. Use natural peanut butter (just peanuts and salt) for best flavor and texture. For extra richness, add 2 tablespoons of melted coconut oil to the mousse.",
    variations: [
      "Use almond butter or cashew butter instead of peanut",
      "Add a tablespoon of instant espresso powder for mocha flavor",
      "Layer with sliced bananas for peanut butter-chocolate-banana mousse",
      "Top with whipped coconut cream and chocolate shavings"
    ],
    tags: ["gluten-free", "dessert", "mousse", "chocolate", "peanut butter", "dairy-free", "vegan", "no-bake"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Peanut Butter Chocolate Mousse - Dairy-Free Dessert | Unglued Food",
    seoDescription: "Silky gluten-free peanut butter chocolate mousse made with coconut cream. Rich, dairy-free, vegan dessert that's light yet decadent. No-bake recipe!"
  },
  {
    title: "Gluten-Free Apple Cinnamon Galette",
    slug: "gluten-free-apple-cinnamon-galette",
    description: "Rustic tart with spiced apples, honey, and a flaky almond flour crust - comforting and naturally sweet.",
    longDescription: "This gluten-free apple cinnamon galette showcases the beauty of rustic baking with a free-form tart featuring tender spiced apples wrapped in a flaky almond flour crust. Unlike traditional pie, the galette's casual fold-over edges and golden caramelized apples create an artisan appearance that's forgiving for home bakers. Naturally sweetened with honey and warm spices, this comforting dessert fills your kitchen with the aroma of autumn.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 40,
    totalTime: 125,
    servings: 8,
    rating: "4.8",
    calories: 245,
    protein: "4.5",
    carbs: "32.0",
    fat: "12.5",
    fiber: "3.5",
    sugar: "18.0",
    image: "/recipe-images/Apple_Cinnamon_Galette_Rustic_27b19cd8.png",
    ingredients: [
      "1 1/2 cups almond flour",
      "1/2 cup tapioca flour",
      "2 tablespoons coconut sugar",
      "1/4 teaspoon sea salt",
      "6 tablespoons cold butter, cubed",
      "1 egg yolk",
      "2-3 tablespoons ice water",
      "3 large apples (Honeycrisp or Granny Smith), thinly sliced",
      "1/4 cup honey",
      "2 tablespoons lemon juice",
      "2 teaspoons cinnamon",
      "1/4 teaspoon nutmeg",
      "2 tablespoons tapioca starch",
      "1 egg, beaten (for egg wash)",
      "Coarse sugar for sprinkling",
      "Vanilla ice cream for serving"
    ],
    instructions: [
      "For crust: Combine almond flour, tapioca flour, coconut sugar, and salt in food processor. Pulse to mix.",
      "Add cold butter cubes and pulse until mixture resembles coarse crumbs with pea-sized pieces.",
      "Add egg yolk and 2 tablespoons ice water. Pulse until dough just comes together, adding more water if needed.",
      "Form dough into a disk, wrap in plastic, and refrigerate for 30 minutes.",
      "Meanwhile, prepare filling: Toss sliced apples with honey, lemon juice, cinnamon, nutmeg, and tapioca starch.",
      "Preheat oven to 375°F. Line a large baking sheet with parchment paper.",
      "On parchment paper dusted with tapioca flour, roll chilled dough into a 12-inch circle (doesn't need to be perfect).",
      "Transfer dough on parchment to prepared baking sheet.",
      "Arrange apple slices in overlapping circles in center of dough, leaving a 2-inch border. Drizzle any remaining juices over apples.",
      "Fold edges of dough over apples, pleating as you go. The center will remain open.",
      "Brush crust edges with beaten egg and sprinkle with coarse sugar.",
      "Bake 38-42 minutes until crust is golden and apples are tender and caramelized.",
      "Cool for 15 minutes. Serve warm with vanilla ice cream."
    ],
    tips: "The dough is more delicate than wheat-based crusts, so don't worry about imperfections - that's the charm of a galette! Use a mix of sweet and tart apples for best flavor. If the crust browns too quickly, tent edges with foil.",
    variations: [
      "Use pears instead of apples for pear galette",
      "Add 1/4 cup dried cranberries to the apple filling",
      "Mix in chopped pecans or walnuts with the apples",
      "Use maple syrup instead of honey for different sweetness"
    ],
    tags: ["gluten-free", "dessert", "galette", "apple", "cinnamon", "pie", "rustic", "autumn", "fall"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Cinnamon Galette - Rustic Fall Dessert | Unglued Food",
    seoDescription: "Rustic gluten-free apple cinnamon galette with flaky almond flour crust and spiced apples. Comforting fall dessert naturally sweetened with honey."
  }
];

async function addDessertRecipes() {
  console.log("Adding 10 gluten-free dessert recipes...\n");
  
  for (const recipe of dessertRecipes) {
    try {
      const created = await storage.createRecipe(recipe);
      console.log(`✓ Added: ${created.title}`);
    } catch (error) {
      console.error(`✗ Failed to add: ${recipe.title}`);
      console.error(error);
    }
  }
  
  console.log("\n✓ All dessert recipes added successfully!");
  process.exit(0);
}

addDessertRecipes().catch((error) => {
  console.error("Error adding recipes:", error);
  process.exit(1);
});
