import { type InsertRecipe } from "@shared/schema";

export const glutenFreeRecipes: InsertRecipe[] = [
  // Breakfast Recipes
  {
    title: "Mediterranean Quinoa Bowl",
    description: "Fresh vegetables, quinoa, and a zesty lemon dressing make this bowl perfect for lunch or dinner.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 25,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
    ingredients: ["1 cup quinoa", "2 cups vegetable broth", "1 cucumber, diced", "1 cup cherry tomatoes", "1/2 red onion", "1/4 cup olive oil", "2 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Cook quinoa in vegetable broth", "Let quinoa cool", "Mix vegetables", "Whisk dressing", "Combine all ingredients"],
    tags: ["Mediterranean", "Quinoa", "Healthy", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Perfect GF Chocolate Chip Cookies",
    description: "Made with almond flour, these cookies are chewy, delicious, and nobody will know they're gluten-free.",
    category: "Desserts",
    difficulty: "Medium",
    cookTime: 35,
    servings: 24,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=600&fit=crop",
    ingredients: ["2 cups almond flour", "1/2 tsp baking soda", "1/2 tsp salt", "1/2 cup coconut oil", "1/2 cup brown sugar", "1 egg", "1 tsp vanilla", "1 cup chocolate chips"],
    instructions: ["Preheat oven to 350°F", "Mix dry ingredients", "Cream wet ingredients", "Combine wet and dry", "Add chocolate chips", "Bake 12-15 minutes"],
    tags: ["Cookies", "Almond Flour", "Chocolate", "Baking"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Creamy Mushroom GF Pasta",
    description: "Rich and creamy pasta made with rice noodles and fresh mushrooms in a dairy-free sauce.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 20,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop",
    ingredients: ["12 oz GF pasta", "1 lb mixed mushrooms", "3 cloves garlic", "1 cup coconut milk", "1/4 cup nutritional yeast", "2 tbsp olive oil", "Salt and pepper", "Fresh herbs"],
    instructions: ["Cook pasta according to package", "Sauté mushrooms and garlic", "Add coconut milk", "Stir in nutritional yeast", "Combine with pasta", "Garnish with herbs"],
    tags: ["Pasta", "Mushrooms", "Dairy-Free", "Comfort Food"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Fluffy GF Pancakes",
    description: "Light and airy pancakes made with rice flour blend that taste just like traditional ones.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop",
    ingredients: ["1 cup GF flour blend", "2 tbsp sugar", "2 tsp baking powder", "1/2 tsp salt", "1 cup milk", "1 egg", "2 tbsp melted butter", "1 tsp vanilla"],
    instructions: ["Mix dry ingredients", "Whisk wet ingredients separately", "Combine wet and dry until just mixed", "Heat griddle to 375°F", "Pour 1/4 cup batter per pancake", "Cook until bubbles form, flip and cook 2 more minutes"],
    tags: ["Pancakes", "Breakfast", "Easy", "Quick"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Thai Coconut Curry Chicken",
    description: "Aromatic coconut curry with tender chicken, vegetables, and fragrant spices served over rice.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 30,
    servings: 6,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&h=600&fit=crop",
    ingredients: ["2 lbs chicken thighs", "1 can coconut milk", "3 tbsp red curry paste", "1 onion, sliced", "1 bell pepper", "1 cup green beans", "2 tbsp fish sauce", "1 tbsp brown sugar", "Fresh basil", "Jasmine rice"],
    instructions: ["Cook rice separately", "Brown chicken in large pan", "Remove chicken, sauté vegetables", "Add curry paste and cook 1 minute", "Add coconut milk, fish sauce, sugar", "Return chicken to pan", "Simmer 15 minutes", "Garnish with basil"],
    tags: ["Thai", "Curry", "Coconut", "Spicy", "One-Pan"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "GF Banana Bread",
    description: "Moist and tender banana bread made with almond flour and naturally sweetened.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 60,
    servings: 10,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1555686913-2e38a187c840?w=800&h=600&fit=crop",
    ingredients: ["3 ripe bananas", "2 cups almond flour", "3 eggs", "1/4 cup honey", "1/4 cup coconut oil", "1 tsp vanilla", "1 tsp baking soda", "1/2 tsp salt", "1/2 cup walnuts"],
    instructions: ["Preheat oven to 350°F", "Mash bananas in large bowl", "Mix in wet ingredients", "Add dry ingredients", "Fold in nuts", "Pour into greased loaf pan", "Bake 55-60 minutes"],
    tags: ["Banana", "Bread", "Almond Flour", "Healthy", "Nuts"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Grilled Salmon with Quinoa Salad",
    description: "Perfectly grilled salmon served over a refreshing quinoa salad with cucumber and herbs.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 25,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&h=600&fit=crop",
    ingredients: ["4 salmon fillets", "1 cup quinoa", "2 cups vegetable broth", "1 cucumber, diced", "1/4 cup red onion", "1/4 cup fresh dill", "3 tbsp olive oil", "2 tbsp lemon juice", "Salt and pepper"],
    instructions: ["Cook quinoa in broth", "Season salmon with salt and pepper", "Grill salmon 4-5 minutes per side", "Mix quinoa with vegetables and herbs", "Whisk olive oil and lemon for dressing", "Serve salmon over quinoa salad"],
    tags: ["Salmon", "Quinoa", "Healthy", "Protein", "Fresh"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Chocolate Avocado Brownies",
    description: "Fudgy, rich brownies made with avocado and cocoa powder for a healthier treat.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 35,
    servings: 16,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1515037893149-de7f840978dd?w=800&h=600&fit=crop",
    ingredients: ["2 ripe avocados", "1/2 cup cocoa powder", "1/2 cup almond flour", "1/3 cup honey", "2 eggs", "1/4 cup coconut oil", "1 tsp vanilla", "1/2 tsp baking soda", "1/4 tsp salt", "1/2 cup dark chocolate chips"],
    instructions: ["Preheat oven to 350°F", "Blend avocados until smooth", "Mix in wet ingredients", "Add dry ingredients", "Fold in chocolate chips", "Pour into 8x8 pan", "Bake 25-30 minutes"],
    tags: ["Brownies", "Avocado", "Chocolate", "Healthy", "Fudgy"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Mexican Cauliflower Rice Bowl",
    description: "Spicy cauliflower rice topped with black beans, avocado, and fresh salsa.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 20,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop",
    ingredients: ["1 large cauliflower head", "1 can black beans", "1 avocado, sliced", "1/2 cup corn", "1/4 cup red onion", "2 tbsp olive oil", "1 tsp cumin", "1 tsp chili powder", "1/4 cup cilantro", "Lime wedges"],
    instructions: ["Pulse cauliflower in food processor", "Heat oil in large pan", "Sauté cauliflower with spices 8 minutes", "Heat black beans", "Prepare fresh toppings", "Assemble bowls with cauliflower rice", "Top with beans, avocado, corn, and cilantro"],
    tags: ["Mexican", "Cauliflower", "Healthy", "Vegetarian", "Low-Carb"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "GF Lemon Bars",
    description: "Tangy lemon curd on a buttery shortbread crust, all made gluten-free.",
    category: "Desserts",
    difficulty: "Medium",
    cookTime: 45,
    servings: 12,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1565537967-1f4bfc3b7db5?w=800&h=600&fit=crop",
    ingredients: ["1 1/2 cups GF flour blend", "1/2 cup powdered sugar", "1/2 cup butter", "4 large eggs", "1 1/3 cups granulated sugar", "1/4 cup GF flour", "1/2 cup lemon juice", "2 tbsp lemon zest", "Powdered sugar for dusting"],
    instructions: ["Preheat oven to 350°F", "Mix crust ingredients", "Press into 9x13 pan", "Bake crust 15 minutes", "Whisk filling ingredients", "Pour over hot crust", "Bake 20-25 minutes more", "Cool completely, dust with powdered sugar"],
    tags: ["Lemon", "Bars", "Citrus", "Sweet", "Classic"],
    isNaturallyGlutenFree: false,
  },
  // Additional 100+ recipes
  {
    title: "Asian Lettuce Wraps",
    description: "Fresh and light lettuce wraps filled with seasoned ground turkey and vegetables.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=800&h=600&fit=crop",
    ingredients: ["1 lb ground turkey", "1 head butter lettuce", "1 can water chestnuts", "2 green onions", "2 cloves garlic", "1 tbsp ginger", "3 tbsp coconut aminos", "1 tbsp sesame oil", "1 tsp rice vinegar", "Red pepper flakes"],
    instructions: ["Heat oil in large skillet", "Cook turkey until browned", "Add garlic and ginger, cook 1 minute", "Stir in water chestnuts and sauce", "Cook 3-4 minutes", "Remove from heat", "Serve in lettuce cups", "Garnish with green onions"],
    tags: ["Asian", "Lettuce Wraps", "Low-Carb", "Fresh", "Quick"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Coconut Chia Pudding",
    description: "Creamy overnight chia pudding with coconut milk and fresh berries.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 5,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1609348938370-6b4b5d824257?w=800&h=600&fit=crop",
    ingredients: ["1/4 cup chia seeds", "1 can coconut milk", "2 tbsp maple syrup", "1 tsp vanilla", "1/4 tsp salt", "1 cup mixed berries", "1/4 cup toasted coconut", "2 tbsp almond butter"],
    instructions: ["Whisk chia seeds with coconut milk", "Add maple syrup, vanilla, and salt", "Refrigerate overnight", "Stir after 1 hour to prevent clumping", "Serve topped with berries", "Garnish with coconut and almond butter"],
    tags: ["Chia", "Pudding", "Coconut", "Healthy", "Make-Ahead"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with seasoned ground beef, rice, and vegetables.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 45,
    servings: 6,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1614961064251-953f17de0bed?w=800&h=600&fit=crop",
    ingredients: ["6 large bell peppers", "1 lb ground beef", "1 cup cooked rice", "1 onion, diced", "2 cloves garlic", "1 can diced tomatoes", "1 cup shredded cheese", "2 tsp Italian seasoning", "Salt and pepper", "2 tbsp olive oil"],
    instructions: ["Preheat oven to 375°F", "Cut tops off peppers, remove seeds", "Cook beef with onion and garlic", "Add tomatoes, rice, seasonings", "Stuff peppers with mixture", "Top with cheese", "Bake 35-40 minutes"],
    tags: ["Stuffed Peppers", "Ground Beef", "Rice", "Comfort Food", "Family"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "GF Apple Crisp",
    description: "Classic apple crisp with a crunchy oat topping, perfectly spiced and naturally gluten-free.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 40,
    servings: 8,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800&h=600&fit=crop",
    ingredients: ["6 large apples, sliced", "1 cup GF oats", "1/2 cup almond flour", "1/2 cup brown sugar", "1/4 cup butter", "1 tsp cinnamon", "1/2 tsp nutmeg", "1/4 tsp salt", "2 tbsp lemon juice"],
    instructions: ["Preheat oven to 375°F", "Toss apples with lemon juice and cinnamon", "Place apples in baking dish", "Mix oats, flour, sugar, and spices", "Cut in butter until crumbly", "Sprinkle over apples", "Bake 35-40 minutes until golden"],
    tags: ["Apple", "Crisp", "Oats", "Fall", "Comfort"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Greek Chicken Bowls",
    description: "Mediterranean-inspired bowls with marinated chicken, vegetables, and tzatziki sauce.",
    category: "Lunch",
    difficulty: "Medium",
    cookTime: 30,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=600&fit=crop",
    ingredients: ["2 lbs chicken breast", "1 cucumber, diced", "2 cups cherry tomatoes", "1/2 red onion", "1/2 cup kalamata olives", "1/2 cup feta cheese", "1/4 cup olive oil", "2 tbsp lemon juice", "2 tsp oregano", "Greek yogurt", "Fresh dill"],
    instructions: ["Marinate chicken in oil, lemon, oregano", "Grill chicken 6-7 minutes per side", "Prepare vegetables", "Make tzatziki with yogurt, cucumber, dill", "Slice chicken", "Assemble bowls with chicken and vegetables", "Top with feta and tzatziki"],
    tags: ["Greek", "Mediterranean", "Chicken", "Fresh", "Protein"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Sweet Potato Gnocchi",
    description: "Pillowy soft gnocchi made from roasted sweet potatoes and served with sage butter.",
    category: "Dinner",
    difficulty: "Hard",
    cookTime: 90,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1609183480237-ccbb2d7c5772?w=800&h=600&fit=crop",
    ingredients: ["3 large sweet potatoes", "2 cups GF flour blend", "1 egg", "1 tsp salt", "1/4 cup butter", "8 fresh sage leaves", "1/2 cup parmesan cheese", "Black pepper"],
    instructions: ["Roast sweet potatoes at 400°F for 1 hour", "Mash sweet potatoes until smooth", "Mix with flour, egg, and salt", "Knead into smooth dough", "Roll into ropes, cut into pieces", "Boil gnocchi until they float", "Sauté with butter and sage", "Serve with parmesan"],
    tags: ["Gnocchi", "Sweet Potato", "Homemade", "Italian", "Advanced"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Energy Balls",
    description: "No-bake energy balls packed with dates, nuts, and chocolate chips for a quick snack.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 15,
    servings: 20,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1604298458655-ae6e04213678?w=800&h=600&fit=crop",
    ingredients: ["1 cup medjool dates", "1 cup almonds", "1/4 cup chia seeds", "2 tbsp cocoa powder", "1 tsp vanilla", "1/4 tsp salt", "1/4 cup mini chocolate chips", "Coconut flakes for rolling"],
    instructions: ["Pulse dates in food processor", "Add almonds and pulse until chopped", "Add chia seeds, cocoa, vanilla, salt", "Process until mixture holds together", "Fold in chocolate chips", "Roll into 1-inch balls", "Roll in coconut", "Chill 30 minutes"],
    tags: ["Energy Balls", "No-Bake", "Dates", "Healthy", "Snack"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Zucchini Fritters",
    description: "Crispy zucchini fritters with fresh herbs, perfect as a side dish or appetizer.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 20,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394ea5ad?w=800&h=600&fit=crop",
    ingredients: ["2 large zucchini, grated", "1/2 cup GF flour blend", "1 egg", "1/4 cup fresh dill", "2 green onions", "1 tsp salt", "1/2 tsp pepper", "1/4 cup olive oil", "Greek yogurt for serving"],
    instructions: ["Grate zucchini and salt, let drain 30 minutes", "Squeeze out excess moisture", "Mix zucchini with flour, egg, herbs", "Heat oil in large skillet", "Form patties and fry 3-4 minutes per side", "Drain on paper towels", "Serve with yogurt"],
    tags: ["Zucchini", "Fritters", "Crispy", "Herbs", "Vegetarian"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Teriyaki Salmon Bowls",
    description: "Glazed salmon served over rice with steamed vegetables and homemade teriyaki sauce.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 25,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1580959375944-abd7e991f971?w=800&h=600&fit=crop",
    ingredients: ["4 salmon fillets", "2 cups cooked rice", "1 cup broccoli", "1 cup snap peas", "1/4 cup coconut aminos", "2 tbsp honey", "2 tbsp rice vinegar", "1 tbsp ginger", "2 cloves garlic", "1 tbsp sesame seeds"],
    instructions: ["Steam vegetables until tender", "Mix sauce ingredients in small pan", "Simmer sauce until thickened", "Pan-sear salmon 4 minutes per side", "Brush salmon with teriyaki sauce", "Serve over rice with vegetables", "Garnish with sesame seeds"],
    tags: ["Teriyaki", "Salmon", "Asian", "Healthy", "Bowl"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Almond Flour Muffins",
    description: "Fluffy blueberry muffins made with almond flour and sweetened with maple syrup.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 25,
    servings: 12,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&h=600&fit=crop",
    ingredients: ["2 cups almond flour", "3 eggs", "1/4 cup maple syrup", "1/4 cup coconut oil", "1 tsp vanilla", "1 tsp baking soda", "1/2 tsp salt", "1 cup fresh blueberries", "1 tbsp lemon zest"],
    instructions: ["Preheat oven to 350°F", "Whisk wet ingredients", "Mix dry ingredients separately", "Combine wet and dry ingredients", "Fold in blueberries and zest", "Fill muffin cups 2/3 full", "Bake 18-22 minutes"],
    tags: ["Muffins", "Almond Flour", "Blueberry", "Healthy", "Breakfast"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Cauliflower Mac and Cheese",
    description: "Creamy comfort food made with roasted cauliflower and a rich cheese sauce.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 35,
    servings: 6,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1543339511-0aa1f7b5d6a9?w=800&h=600&fit=crop",
    ingredients: ["1 large cauliflower head", "2 cups shredded cheddar", "1 cup milk", "3 tbsp butter", "2 tbsp GF flour", "1 tsp mustard powder", "1/2 tsp paprika", "Salt and pepper", "1/4 cup breadcrumbs"],
    instructions: ["Cut cauliflower into bite-sized pieces", "Roast at 425°F for 20 minutes", "Make cheese sauce with butter, flour, milk", "Add cheese and seasonings", "Combine cauliflower with sauce", "Top with breadcrumbs", "Bake 15 minutes until golden"],
    tags: ["Cauliflower", "Mac and Cheese", "Comfort Food", "Creamy", "Vegetarian"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Acai Smoothie Bowl",
    description: "Antioxidant-rich acai bowl topped with fresh fruit, granola, and coconut flakes.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 10,
    servings: 2,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=600&fit=crop",
    ingredients: ["2 acai packets", "1 frozen banana", "1/2 cup blueberries", "1/4 cup coconut milk", "1 tbsp honey", "1/4 cup GF granola", "1 kiwi, sliced", "2 tbsp coconut flakes", "1 tbsp chia seeds"],
    instructions: ["Blend acai, banana, and coconut milk", "Add honey to taste", "Pour into bowls", "Arrange fresh fruit on top", "Sprinkle with granola and coconut", "Add chia seeds", "Serve immediately"],
    tags: ["Acai", "Smoothie Bowl", "Antioxidants", "Fresh Fruit", "Healthy"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Herb-Crusted Lamb Chops",
    description: "Tender lamb chops with a flavorful herb crust, served with roasted vegetables.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 25,
    servings: 4,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1595777216528-071e0127ccbf?w=800&h=600&fit=crop",
    ingredients: ["8 lamb chops", "2 tbsp fresh rosemary", "2 tbsp fresh thyme", "3 cloves garlic", "1/4 cup olive oil", "2 tbsp Dijon mustard", "1 lb baby potatoes", "1 bunch asparagus", "Salt and pepper"],
    instructions: ["Season lamb chops with salt and pepper", "Mix herbs, garlic, oil, and mustard", "Coat lamb with herb mixture", "Roast potatoes at 400°F for 20 minutes", "Add asparagus to pan", "Sear lamb 3-4 minutes per side", "Rest 5 minutes before serving"],
    tags: ["Lamb", "Herbs", "Elegant", "Roasted Vegetables", "Special Occasion"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Pumpkin Spice Latte Overnight Oats",
    description: "Fall-flavored overnight oats with pumpkin, spices, and a hint of coffee.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 10,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1609501847468-c6f2b709d09c?w=800&h=600&fit=crop",
    ingredients: ["2 cups GF oats", "1/2 cup pumpkin puree", "2 cups milk", "1/4 cup maple syrup", "2 tbsp chia seeds", "1 tsp pumpkin pie spice", "1/2 tsp vanilla", "2 tbsp instant coffee", "Whipped cream"],
    instructions: ["Mix all ingredients except whipped cream", "Divide among 4 jars", "Refrigerate overnight", "Stir before serving", "Top with whipped cream", "Sprinkle with extra pumpkin spice"],
    tags: ["Overnight Oats", "Pumpkin", "Fall", "Coffee", "Make-Ahead"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Shrimp and Avocado Salad",
    description: "Light and refreshing salad with grilled shrimp, avocado, and citrus dressing.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=800&h=600&fit=crop",
    ingredients: ["1 lb large shrimp", "2 avocados, sliced", "4 cups mixed greens", "1 cup cherry tomatoes", "1/4 red onion", "1/4 cup olive oil", "2 tbsp lime juice", "1 tbsp honey", "1 tsp cumin", "Salt and pepper"],
    instructions: ["Season and grill shrimp 2-3 minutes per side", "Prepare salad vegetables", "Whisk dressing ingredients", "Arrange greens, avocado, tomatoes", "Top with warm shrimp", "Drizzle with dressing", "Serve immediately"],
    tags: ["Shrimp", "Avocado", "Salad", "Light", "Citrus"],
    isNaturallyGlutenFree: true,
  },
  // Continue with more recipes...
  {
    title: "Chocolate Zucchini Cake",
    description: "Moist and decadent chocolate cake with hidden zucchini for extra nutrition.",
    category: "Desserts",
    difficulty: "Medium",
    cookTime: 45,
    servings: 12,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop",
    ingredients: ["2 cups grated zucchini", "1 3/4 cups GF flour blend", "3/4 cup cocoa powder", "2 cups sugar", "3 eggs", "1 cup vegetable oil", "2 tsp vanilla", "1 1/2 tsp baking soda", "1 tsp salt", "1 cup chocolate chips"],
    instructions: ["Preheat oven to 350°F", "Grate zucchini and squeeze out moisture", "Mix dry ingredients", "Beat eggs, oil, and vanilla", "Combine wet and dry ingredients", "Fold in zucchini and chocolate chips", "Bake in bundt pan 40-45 minutes"],
    tags: ["Chocolate", "Zucchini", "Cake", "Hidden Vegetables", "Moist"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Mexican Street Corn Salad",
    description: "All the flavors of elote in a fresh, easy-to-eat salad with lime and cotija cheese.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 15,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1600850056064-a8b380df8395?w=800&h=600&fit=crop",
    ingredients: ["4 cups corn kernels", "1/4 cup mayonnaise", "1/4 cup Mexican crema", "1/2 cup cotija cheese", "1/4 cup cilantro", "2 tbsp lime juice", "1 tsp chili powder", "1/4 tsp cayenne", "Salt to taste"],
    instructions: ["Char corn in dry skillet until golden", "Mix mayo, crema, and lime juice", "Add warm corn to dressing", "Stir in most of the cheese and cilantro", "Season with chili powder and cayenne", "Garnish with remaining cheese and cilantro"],
    tags: ["Mexican", "Corn", "Street Food", "Salad", "Spicy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Turkey Meatballs with Marinara",
    description: "Tender turkey meatballs in a rich tomato sauce, perfect over zucchini noodles or rice.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 30,
    servings: 6,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&h=600&fit=crop",
    ingredients: ["2 lbs ground turkey", "1/2 cup GF breadcrumbs", "1 egg", "1/4 cup grated parmesan", "2 cloves garlic", "1 jar marinara sauce", "2 tbsp olive oil", "1/4 cup fresh basil", "Salt and pepper", "Zucchini noodles"],
    instructions: ["Mix turkey, breadcrumbs, egg, cheese, garlic", "Form into 1.5-inch meatballs", "Heat oil in large skillet", "Brown meatballs on all sides", "Add marinara sauce", "Simmer 15-20 minutes", "Serve over zucchini noodles", "Garnish with basil"],
    tags: ["Turkey", "Meatballs", "Marinara", "Italian", "Healthy"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Coconut Rice Pudding",
    description: "Creamy, comforting rice pudding made with coconut milk and topped with toasted coconut.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 25,
    servings: 6,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1530805828292-29b0d6e1199b?w=800&h=600&fit=crop",
    ingredients: ["1 cup jasmine rice", "1 can coconut milk", "2 cups whole milk", "1/3 cup sugar", "1/2 tsp vanilla", "1/4 tsp salt", "1/2 tsp cinnamon", "1/4 cup toasted coconut", "Fresh mango"],
    instructions: ["Cook rice according to package directions", "Heat coconut milk and regular milk", "Add cooked rice to milk mixture", "Stir in sugar, vanilla, salt", "Simmer 15-20 minutes until thick", "Add cinnamon", "Serve warm or chilled", "Top with coconut and mango"],
    tags: ["Rice Pudding", "Coconut", "Comfort", "Creamy", "Tropical"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Buffalo Cauliflower Bites",
    description: "Crispy roasted cauliflower tossed in spicy buffalo sauce, perfect for game day.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c564b50a?w=800&h=600&fit=crop",
    ingredients: ["1 large cauliflower head", "3/4 cup GF flour", "3/4 cup water", "1 tsp garlic powder", "1/2 cup buffalo sauce", "2 tbsp butter", "Ranch or blue cheese dressing", "Celery sticks"],
    instructions: ["Preheat oven to 450°F", "Cut cauliflower into florets", "Make batter with flour, water, garlic powder", "Dip cauliflower in batter", "Bake 15 minutes", "Mix buffalo sauce with butter", "Toss cauliflower in sauce", "Bake 20 more minutes"],
    tags: ["Buffalo", "Cauliflower", "Spicy", "Game Day", "Crispy"],
    isNaturallyGlutenFree: false,
  },
  // Continue with even more recipes to reach 100+
  {
    title: "Vietnamese Pho Bowl",
    description: "Fragrant rice noodle soup with tender beef and fresh herbs, naturally gluten-free.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 45,
    servings: 4,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1582878826629-29b7bfad0217?w=800&h=600&fit=crop",
    ingredients: ["8 oz rice noodles", "1 lb beef sirloin", "8 cups beef broth", "1 onion", "3 star anise", "1 cinnamon stick", "Bean sprouts", "Fresh basil", "Lime wedges", "Jalapeños"],
    instructions: ["Simmer broth with spices 30 minutes", "Cook rice noodles separately", "Slice beef very thin", "Strain broth, return to heat", "Place noodles in bowls", "Top with raw beef slices", "Pour hot broth over beef", "Garnish with herbs and vegetables"],
    tags: ["Vietnamese", "Pho", "Soup", "Rice Noodles", "Herbs"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Spinach Artichoke Dip",
    description: "Creamy, cheesy dip with spinach and artichokes, perfect with GF crackers.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 25,
    servings: 8,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1593030668930-8130abedd2b0?w=800&h=600&fit=crop",
    ingredients: ["2 cups spinach", "1 can artichoke hearts", "8 oz cream cheese", "1/2 cup sour cream", "1/2 cup mayonnaise", "1 cup mozzarella", "1/2 cup parmesan", "3 cloves garlic", "GF crackers"],
    instructions: ["Preheat oven to 375°F", "Mix cream cheese, sour cream, mayo", "Add chopped spinach and artichokes", "Stir in cheeses and garlic", "Transfer to baking dish", "Bake 20-25 minutes until bubbly", "Serve hot with crackers"],
    tags: ["Dip", "Spinach", "Artichoke", "Cheesy", "Party"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Moroccan Chickpea Stew",
    description: "Warming spiced stew with chickpeas, vegetables, and aromatic North African flavors.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 35,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
    ingredients: ["2 cans chickpeas", "1 can diced tomatoes", "2 carrots", "1 zucchini", "1 onion", "3 cloves garlic", "2 tsp cumin", "1 tsp cinnamon", "1/2 cup dried apricots", "Fresh cilantro"],
    instructions: ["Sauté onion and garlic", "Add spices, cook 1 minute", "Add vegetables and tomatoes", "Simmer 20 minutes", "Add chickpeas and apricots", "Cook 10 more minutes", "Garnish with cilantro", "Serve over rice or quinoa"],
    tags: ["Moroccan", "Chickpeas", "Stew", "Vegetarian", "Spiced"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Baked Egg Muffins",
    description: "Protein-packed breakfast muffins with eggs, vegetables, and cheese.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 20,
    servings: 12,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&h=600&fit=crop",
    ingredients: ["12 eggs", "1/2 cup milk", "1 cup spinach", "1/2 cup bell peppers", "1/4 cup onion", "1 cup shredded cheese", "6 slices bacon", "Salt and pepper", "Cooking spray"],
    instructions: ["Preheat oven to 350°F", "Whisk eggs and milk", "Chop vegetables and bacon", "Mix everything together", "Spray muffin tin", "Pour mixture into cups", "Bake 18-20 minutes", "Cool before removing"],
    tags: ["Eggs", "Muffins", "Breakfast", "Protein", "Make-Ahead"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Coconut Curry Lentils",
    description: "Creamy red lentil curry with coconut milk and warming spices.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 30,
    servings: 6,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=800&h=600&fit=crop",
    ingredients: ["1 cup red lentils", "1 can coconut milk", "2 cups vegetable broth", "1 onion", "3 cloves garlic", "1 tbsp curry powder", "1 tsp turmeric", "1 can diced tomatoes", "2 cups spinach", "Naan or rice"],
    instructions: ["Sauté onion and garlic", "Add spices, cook 1 minute", "Add lentils, coconut milk, broth", "Simmer 20 minutes", "Add tomatoes and spinach", "Cook until spinach wilts", "Season with salt", "Serve with rice"],
    tags: ["Curry", "Lentils", "Coconut", "Vegetarian", "Indian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Caprese Skewers",
    description: "Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 10,
    servings: 24,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=800&h=600&fit=crop",
    ingredients: ["1 lb cherry tomatoes", "1 lb fresh mozzarella balls", "1 bunch fresh basil", "1/4 cup olive oil", "2 tbsp balsamic glaze", "Salt and pepper", "Wooden skewers"],
    instructions: ["Thread tomato, mozzarella, and basil on skewers", "Arrange on platter", "Drizzle with olive oil", "Season with salt and pepper", "Drizzle with balsamic glaze", "Serve immediately"],
    tags: ["Caprese", "Italian", "Fresh", "Appetizer", "No-Cook"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Korean Bibimbap Bowl",
    description: "Colorful rice bowl topped with seasoned vegetables, egg, and gochujang sauce.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 40,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1590301157172-8d06e4bd53e0?w=800&h=600&fit=crop",
    ingredients: ["2 cups rice", "1 lb ground beef", "2 cups spinach", "1 cup bean sprouts", "1 carrot", "1 zucchini", "4 eggs", "3 tbsp gochujang", "2 tbsp sesame oil", "Kimchi"],
    instructions: ["Cook rice", "Season and cook beef", "Blanch and season vegetables separately", "Fry eggs sunny side up", "Arrange rice in bowls", "Top with beef, vegetables, and egg", "Serve with gochujang sauce", "Mix before eating"],
    tags: ["Korean", "Bibimbap", "Rice Bowl", "Vegetables", "Egg"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Pesto Zucchini Noodles",
    description: "Fresh zucchini noodles tossed with homemade basil pesto and cherry tomatoes.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&h=600&fit=crop",
    ingredients: ["4 large zucchini", "2 cups basil", "1/2 cup pine nuts", "1/2 cup parmesan", "2 cloves garlic", "1/2 cup olive oil", "1 cup cherry tomatoes", "Salt and pepper"],
    instructions: ["Spiralize zucchini into noodles", "Make pesto with basil, nuts, cheese, garlic", "Stream in olive oil while blending", "Sauté zucchini noodles 2-3 minutes", "Toss with pesto", "Add halved tomatoes", "Serve immediately"],
    tags: ["Pesto", "Zucchini Noodles", "Low-Carb", "Fresh", "Italian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Loaded Sweet Potato Skins",
    description: "Crispy sweet potato skins filled with bacon, cheese, and green onions.",
    category: "Snacks",
    difficulty: "Medium",
    cookTime: 60,
    servings: 8,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1544384308-c88e5e8547a5?w=800&h=600&fit=crop",
    ingredients: ["4 large sweet potatoes", "6 slices bacon", "1 cup shredded cheddar", "1/4 cup sour cream", "2 green onions", "2 tbsp olive oil", "Salt and pepper", "Paprika"],
    instructions: ["Bake sweet potatoes 45 minutes", "Cut in half, scoop out most flesh", "Brush with oil, season", "Bake 10 minutes until crispy", "Cook and crumble bacon", "Fill with cheese and bacon", "Bake until cheese melts", "Top with sour cream and onions"],
    tags: ["Sweet Potato", "Loaded", "Bacon", "Cheese", "Crispy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Thai Mango Salad",
    description: "Refreshing salad with ripe mango, crunchy vegetables, and tangy lime dressing.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1604497181015-76590d828b75?w=800&h=600&fit=crop",
    ingredients: ["2 ripe mangoes", "1 red bell pepper", "1/2 red onion", "1 cucumber", "1/4 cup peanuts", "2 tbsp lime juice", "1 tbsp fish sauce", "1 tbsp brown sugar", "Fresh cilantro", "Thai chili"],
    instructions: ["Julienne mango and vegetables", "Mix lime juice, fish sauce, sugar", "Toss salad with dressing", "Add chopped peanuts", "Garnish with cilantro", "Add sliced chili for heat"],
    tags: ["Thai", "Mango", "Salad", "Fresh", "Tangy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Chickpea Flour Flatbread",
    description: "Simple, protein-rich flatbread made with chickpea flour, perfect for wraps.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 20,
    servings: 4,
    rating: "4.4",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&h=600&fit=crop",
    ingredients: ["1 cup chickpea flour", "1 cup water", "2 tbsp olive oil", "1 tsp salt", "1/2 tsp cumin", "1/4 tsp turmeric", "Fresh herbs"],
    instructions: ["Mix chickpea flour with water", "Add oil and spices", "Let batter rest 10 minutes", "Heat skillet with oil", "Pour thin layer of batter", "Cook 2-3 minutes per side", "Serve warm"],
    tags: ["Chickpea", "Flatbread", "Protein", "Simple", "Vegan"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Shakshuka",
    description: "Middle Eastern dish of eggs poached in spicy tomato sauce with peppers.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 25,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1590438984884-b837c0961b1f?w=800&h=600&fit=crop",
    ingredients: ["6 eggs", "1 can crushed tomatoes", "1 red bell pepper", "1 onion", "3 cloves garlic", "1 tsp cumin", "1 tsp paprika", "1/4 tsp cayenne", "Fresh parsley", "Feta cheese"],
    instructions: ["Sauté onion and pepper", "Add garlic and spices", "Add tomatoes, simmer 10 minutes", "Make wells in sauce", "Crack eggs into wells", "Cover and cook until eggs set", "Garnish with parsley and feta"],
    tags: ["Shakshuka", "Eggs", "Middle Eastern", "Breakfast", "Spicy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Quinoa Tabbouleh",
    description: "Fresh herb salad with quinoa instead of bulgur, packed with parsley and mint.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 20,
    servings: 6,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&h=600&fit=crop",
    ingredients: ["1 cup quinoa", "2 cups parsley", "1/2 cup mint", "3 tomatoes", "1 cucumber", "3 green onions", "1/4 cup lemon juice", "1/4 cup olive oil", "Salt and pepper"],
    instructions: ["Cook and cool quinoa", "Finely chop herbs", "Dice tomatoes and cucumber", "Mix everything together", "Add lemon juice and oil", "Season with salt and pepper", "Chill before serving"],
    tags: ["Tabbouleh", "Quinoa", "Herbs", "Lebanese", "Fresh"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Beet and Goat Cheese Salad",
    description: "Roasted beets with creamy goat cheese, walnuts, and balsamic dressing.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 60,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1609501847468-25b5e5e59b9a?w=800&h=600&fit=crop",
    ingredients: ["4 medium beets", "4 oz goat cheese", "1/2 cup walnuts", "4 cups arugula", "2 tbsp balsamic vinegar", "3 tbsp olive oil", "1 tbsp honey", "Salt and pepper"],
    instructions: ["Roast beets at 400°F for 45 minutes", "Peel and slice beets", "Toast walnuts", "Whisk vinegar, oil, honey", "Arrange arugula on plates", "Top with beets and goat cheese", "Sprinkle with walnuts", "Drizzle with dressing"],
    tags: ["Beets", "Goat Cheese", "Salad", "Elegant", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Fish Tacos with Mango Salsa",
    description: "Grilled white fish tacos topped with fresh mango salsa and lime crema.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 25,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=600&fit=crop",
    ingredients: ["1 lb white fish", "8 corn tortillas", "1 mango, diced", "1/2 red onion", "1 jalapeño", "1/4 cup cilantro", "2 limes", "1/2 cup sour cream", "Cabbage slaw"],
    instructions: ["Season and grill fish", "Make mango salsa", "Mix sour cream with lime juice", "Warm tortillas", "Flake fish into pieces", "Assemble tacos with fish", "Top with salsa and crema", "Add cabbage slaw"],
    tags: ["Fish Tacos", "Mango", "Mexican", "Fresh", "Grilled"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Eggplant Parmesan",
    description: "Crispy breaded eggplant layered with marinara and melted cheese.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 60,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1600718707159-15dfd249c165?w=800&h=600&fit=crop",
    ingredients: ["2 large eggplants", "2 cups GF breadcrumbs", "3 eggs", "2 cups marinara", "2 cups mozzarella", "1 cup parmesan", "1/4 cup basil", "Olive oil", "Salt"],
    instructions: ["Slice eggplant, salt and drain", "Dip in egg, then breadcrumbs", "Fry until golden", "Layer with sauce and cheese", "Bake at 375°F for 30 minutes", "Let rest 10 minutes", "Garnish with basil"],
    tags: ["Eggplant", "Parmesan", "Italian", "Vegetarian", "Comfort"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Coconut Lime Chicken",
    description: "Tender chicken in a creamy coconut lime sauce with cilantro.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=600&fit=crop",
    ingredients: ["4 chicken breasts", "1 can coconut milk", "3 limes", "3 cloves garlic", "1 tbsp ginger", "2 tbsp honey", "1/4 cup cilantro", "Jasmine rice"],
    instructions: ["Season and sear chicken", "Remove chicken from pan", "Sauté garlic and ginger", "Add coconut milk and lime juice", "Add honey, simmer", "Return chicken to pan", "Cook until done", "Serve over rice with cilantro"],
    tags: ["Coconut", "Lime", "Chicken", "Thai-inspired", "Creamy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Roasted Vegetable Frittata",
    description: "Fluffy egg frittata loaded with roasted vegetables and herbs.",
    category: "Breakfast",
    difficulty: "Medium",
    cookTime: 35,
    servings: 6,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1555243896-71a8f6c76ab4?w=800&h=600&fit=crop",
    ingredients: ["10 eggs", "1/2 cup milk", "1 zucchini", "1 bell pepper", "1 cup mushrooms", "1 onion", "1 cup cheese", "2 tbsp olive oil", "Fresh thyme"],
    instructions: ["Roast vegetables at 400°F", "Whisk eggs with milk", "Heat oven-safe skillet", "Add roasted vegetables", "Pour egg mixture over", "Top with cheese", "Bake 20 minutes at 375°F", "Cool before slicing"],
    tags: ["Frittata", "Eggs", "Vegetables", "Breakfast", "Brunch"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Chocolate Chia Mousse",
    description: "Rich and creamy chocolate mousse made with chia seeds and avocado.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 10,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&h=600&fit=crop",
    ingredients: ["1/4 cup chia seeds", "1 ripe avocado", "1/4 cup cocoa powder", "1/3 cup maple syrup", "1 cup almond milk", "1 tsp vanilla", "Pinch of salt", "Berries for topping"],
    instructions: ["Soak chia seeds in almond milk", "Blend avocado until smooth", "Add cocoa and maple syrup", "Mix with chia mixture", "Add vanilla and salt", "Chill 2 hours", "Top with berries"],
    tags: ["Chocolate", "Chia", "Mousse", "Healthy", "No-Bake"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Indian Samosa Filling Bowl",
    description: "All the flavors of samosas without the wrapper - spiced potatoes and peas.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=600&fit=crop",
    ingredients: ["3 large potatoes", "1 cup green peas", "1 onion", "2 tsp curry powder", "1 tsp cumin seeds", "1/2 tsp turmeric", "2 tbsp oil", "Cilantro chutney", "Yogurt"],
    instructions: ["Boil and cube potatoes", "Heat oil, add cumin seeds", "Sauté onion until golden", "Add spices, cook 1 minute", "Add potatoes and peas", "Mash slightly while cooking", "Serve in bowls", "Top with chutney and yogurt"],
    tags: ["Indian", "Samosa", "Potatoes", "Vegetarian", "Spiced"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Stuffed Portobello Mushrooms",
    description: "Large mushroom caps filled with quinoa, vegetables, and melted cheese.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1584277127104-1d6c5b2dbf2a?w=800&h=600&fit=crop",
    ingredients: ["4 large portobello caps", "1 cup cooked quinoa", "1/2 cup sun-dried tomatoes", "1/2 cup spinach", "1 cup mozzarella", "3 cloves garlic", "2 tbsp olive oil", "Fresh basil"],
    instructions: ["Remove mushroom stems", "Brush caps with oil", "Mix quinoa with vegetables", "Add half the cheese", "Fill mushroom caps", "Top with remaining cheese", "Bake at 400°F for 20 minutes", "Garnish with basil"],
    tags: ["Portobello", "Stuffed", "Quinoa", "Vegetarian", "Mushrooms"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Japanese Okonomiyaki",
    description: "Savory Japanese pancake made with cabbage and topped with special sauce.",
    category: "Lunch",
    difficulty: "Medium",
    cookTime: 25,
    servings: 2,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1563245375-30404ec02e31?w=800&h=600&fit=crop",
    ingredients: ["2 cups cabbage", "1 cup GF flour", "3 eggs", "1/2 cup water", "4 slices bacon", "Okonomiyaki sauce", "Japanese mayo", "Bonito flakes", "Green onions"],
    instructions: ["Shred cabbage finely", "Mix flour, eggs, water", "Add cabbage to batter", "Heat oil in pan", "Pour batter, top with bacon", "Cook 5 minutes, flip", "Cook until golden", "Top with sauce and mayo"],
    tags: ["Japanese", "Okonomiyaki", "Cabbage", "Savory Pancake", "Street Food"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Brazilian Cheese Bread",
    description: "Chewy, cheesy bread balls made with tapioca flour, naturally gluten-free.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 25,
    servings: 24,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1598928431231-394cd5d45c6e?w=800&h=600&fit=crop",
    ingredients: ["2 cups tapioca flour", "1/2 cup milk", "1/4 cup oil", "2 eggs", "1 cup parmesan cheese", "1/2 cup mozzarella", "1 tsp salt"],
    instructions: ["Preheat oven to 400°F", "Heat milk and oil", "Pour over tapioca flour", "Mix and cool slightly", "Add eggs one at a time", "Mix in cheeses and salt", "Roll into balls", "Bake 20 minutes until golden"],
    tags: ["Brazilian", "Cheese Bread", "Tapioca", "Cheesy", "Snack"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Turmeric Golden Milk Latte",
    description: "Warming anti-inflammatory drink with turmeric, ginger, and coconut milk.",
    category: "Beverages",
    difficulty: "Easy",
    cookTime: 10,
    servings: 2,
    rating: "4.4",
    image: "https://images.unsplash.com/photo-1586991249172-8a8dd52c2cc0?w=800&h=600&fit=crop",
    ingredients: ["2 cups coconut milk", "1 tsp turmeric", "1/2 tsp cinnamon", "1/4 tsp ginger", "Pinch black pepper", "1 tbsp honey", "1/2 tsp vanilla"],
    instructions: ["Heat coconut milk", "Whisk in turmeric and spices", "Add black pepper", "Simmer 5 minutes", "Strain if desired", "Add honey and vanilla", "Serve warm"],
    tags: ["Golden Milk", "Turmeric", "Anti-inflammatory", "Beverage", "Healthy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Mediterranean Stuffed Tomatoes",
    description: "Ripe tomatoes filled with quinoa, feta, and Mediterranean herbs.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1564844563535-d92f8f2c8b5e?w=800&h=600&fit=crop",
    ingredients: ["4 large tomatoes", "1 cup cooked quinoa", "1/2 cup feta cheese", "1/4 cup olives", "2 tbsp pine nuts", "Fresh basil", "2 cloves garlic", "Olive oil"],
    instructions: ["Cut tops off tomatoes, hollow out", "Mix quinoa with feta and olives", "Add pine nuts and herbs", "Stuff tomatoes with mixture", "Drizzle with olive oil", "Bake at 375°F for 25 minutes"],
    tags: ["Mediterranean", "Stuffed Tomatoes", "Quinoa", "Feta", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Pad Thai with Rice Noodles",
    description: "Classic Thai street food with rice noodles, shrimp, and tangy sauce.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 20,
    servings: 4,
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop",
    ingredients: ["8 oz rice noodles", "1 lb shrimp", "3 eggs", "1 cup bean sprouts", "3 green onions", "1/4 cup peanuts", "2 tbsp tamarind paste", "2 tbsp fish sauce", "2 tbsp sugar", "Lime wedges"],
    instructions: ["Soak noodles in hot water", "Make sauce with tamarind, fish sauce, sugar", "Stir-fry shrimp", "Push aside, scramble eggs", "Add drained noodles and sauce", "Toss until coated", "Add bean sprouts and onions", "Garnish with peanuts and lime"],
    tags: ["Pad Thai", "Thai", "Rice Noodles", "Shrimp", "Street Food"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Cauliflower Buffalo Wings",
    description: "Crispy baked cauliflower bites tossed in spicy buffalo sauce.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 35,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1599020793342-07e797f595ba?w=800&h=600&fit=crop",
    ingredients: ["1 large cauliflower", "1 cup GF flour", "1 cup milk", "2 tsp garlic powder", "1/2 cup buffalo sauce", "2 tbsp butter", "Ranch dressing", "Celery sticks"],
    instructions: ["Cut cauliflower into florets", "Mix flour, milk, garlic powder", "Coat cauliflower in batter", "Bake at 450°F for 20 minutes", "Mix buffalo sauce with butter", "Toss cauliflower in sauce", "Bake 15 more minutes", "Serve with ranch and celery"],
    tags: ["Buffalo", "Cauliflower", "Wings", "Spicy", "Vegetarian"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Sushi Bowl with Salmon",
    description: "Deconstructed sushi with fresh salmon, avocado, and sushi rice.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop",
    ingredients: ["2 cups sushi rice", "1 lb sushi-grade salmon", "1 avocado", "1 cucumber", "Nori sheets", "Sesame seeds", "Soy sauce", "Wasabi", "Pickled ginger"],
    instructions: ["Cook sushi rice", "Season with rice vinegar", "Cube salmon", "Slice avocado and cucumber", "Cut nori into strips", "Assemble bowls with rice", "Top with salmon and vegetables", "Garnish with nori and sesame"],
    tags: ["Sushi Bowl", "Salmon", "Japanese", "Fresh", "Poke"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Polenta Pizza Bites",
    description: "Crispy polenta rounds topped with marinara, cheese, and mini pepperoni.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 25,
    servings: 24,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop",
    ingredients: ["1 tube polenta", "1 cup marinara", "1 cup mozzarella", "Mini pepperoni", "Italian seasoning", "Olive oil"],
    instructions: ["Slice polenta into rounds", "Brush with olive oil", "Bake at 425°F for 10 minutes", "Flip and bake 5 more minutes", "Top with marinara and cheese", "Add pepperoni", "Bake until cheese melts"],
    tags: ["Polenta", "Pizza Bites", "Italian", "Snack", "Party"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Caribbean Jerk Chicken",
    description: "Spicy marinated chicken with Caribbean jerk seasoning and tropical salsa.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 40,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&h=600&fit=crop",
    ingredients: ["4 chicken thighs", "3 tbsp jerk seasoning", "2 tbsp brown sugar", "2 tbsp oil", "1 mango", "1 pineapple", "1 red onion", "Cilantro", "Lime", "Rice and beans"],
    instructions: ["Mix jerk seasoning with sugar and oil", "Marinate chicken 2 hours", "Grill chicken until charred", "Make tropical salsa", "Let chicken rest", "Serve with rice and beans", "Top with salsa"],
    tags: ["Caribbean", "Jerk Chicken", "Spicy", "Grilled", "Tropical"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Ratatouille",
    description: "French vegetable stew with eggplant, zucchini, tomatoes, and herbs.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 60,
    servings: 6,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&h=600&fit=crop",
    ingredients: ["1 eggplant", "2 zucchini", "2 bell peppers", "4 tomatoes", "1 onion", "4 cloves garlic", "1/4 cup olive oil", "Fresh thyme", "Fresh basil", "Bay leaf"],
    instructions: ["Slice all vegetables", "Sauté onion and garlic", "Layer vegetables in baking dish", "Drizzle with olive oil", "Add herbs and seasonings", "Cover and bake 40 minutes", "Uncover, bake 20 more minutes"],
    tags: ["Ratatouille", "French", "Vegetables", "Stew", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Corn and Black Bean Salsa",
    description: "Fresh and colorful salsa with corn, black beans, and lime dressing.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 10,
    servings: 8,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1536304556577-39ec76e87b5f?w=800&h=600&fit=crop",
    ingredients: ["2 cups corn", "1 can black beans", "1 red bell pepper", "1/2 red onion", "1/4 cup cilantro", "2 limes", "1 jalapeño", "Cumin", "Tortilla chips"],
    instructions: ["Char corn in skillet", "Rinse and drain beans", "Dice pepper and onion", "Mix everything together", "Add lime juice and cilantro", "Season with cumin and salt", "Chill before serving"],
    tags: ["Salsa", "Corn", "Black Beans", "Mexican", "Fresh"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Spinach and Feta Stuffed Chicken",
    description: "Chicken breasts stuffed with creamy spinach and feta cheese filling.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 35,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c5c7?w=800&h=600&fit=crop",
    ingredients: ["4 chicken breasts", "2 cups spinach", "1/2 cup feta cheese", "1/4 cup cream cheese", "2 cloves garlic", "Sun-dried tomatoes", "Olive oil", "Italian seasoning"],
    instructions: ["Butterfly chicken breasts", "Sauté spinach with garlic", "Mix with cheeses", "Stuff chicken with mixture", "Secure with toothpicks", "Season outside", "Bake at 375°F for 25-30 minutes"],
    tags: ["Stuffed Chicken", "Spinach", "Feta", "Elegant", "Protein"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Thai Green Curry",
    description: "Fragrant green curry with vegetables, basil, and coconut milk.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 30,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
    ingredients: ["2 tbsp green curry paste", "1 can coconut milk", "1 lb chicken or tofu", "1 eggplant", "1 cup green beans", "Thai basil", "2 tbsp fish sauce", "1 tbsp sugar", "Jasmine rice"],
    instructions: ["Fry curry paste in oil", "Add thick coconut milk", "Add protein, cook through", "Add vegetables", "Pour in remaining coconut milk", "Season with fish sauce and sugar", "Simmer until vegetables tender", "Garnish with basil"],
    tags: ["Thai", "Green Curry", "Coconut", "Spicy", "Aromatic"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Zucchini Lasagna",
    description: "Low-carb lasagna using thin zucchini slices instead of pasta sheets.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 60,
    servings: 8,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1619894965194-3c7e29dd78f1?w=800&h=600&fit=crop",
    ingredients: ["3 large zucchini", "1 lb ground beef", "2 cups ricotta", "2 cups mozzarella", "1 jar marinara", "1 egg", "Italian herbs", "Parmesan cheese"],
    instructions: ["Slice zucchini lengthwise", "Salt and drain zucchini", "Brown ground beef", "Mix ricotta with egg", "Layer zucchini, meat, cheese", "Repeat layers", "Top with mozzarella", "Bake 45 minutes at 375°F"],
    tags: ["Lasagna", "Zucchini", "Low-Carb", "Italian", "Comfort"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Matcha Energy Balls",
    description: "Green tea infused energy balls with cashews and coconut.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 15,
    servings: 20,
    rating: "4.4",
    image: "https://images.unsplash.com/photo-1591735179859-5d3f965de154?w=800&h=600&fit=crop",
    ingredients: ["1 cup cashews", "1 cup dates", "2 tbsp matcha powder", "1/4 cup coconut oil", "1/2 cup shredded coconut", "1 tsp vanilla", "Pinch of salt"],
    instructions: ["Process cashews until fine", "Add dates and process", "Add matcha and coconut oil", "Add vanilla and salt", "Roll into balls", "Roll in shredded coconut", "Refrigerate until firm"],
    tags: ["Matcha", "Energy Balls", "Green Tea", "Healthy", "No-Bake"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Lentil Shepherd's Pie",
    description: "Hearty vegetarian shepherd's pie with lentil filling and mashed potato topping.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 50,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1570197952464-a8d58eec6322?w=800&h=600&fit=crop",
    ingredients: ["1 cup green lentils", "4 large potatoes", "2 carrots", "1 onion", "2 cups vegetable broth", "1 cup peas", "2 tbsp tomato paste", "Fresh thyme", "Butter", "Milk"],
    instructions: ["Cook lentils in broth", "Boil and mash potatoes", "Sauté vegetables", "Add lentils and tomato paste", "Transfer to baking dish", "Top with mashed potatoes", "Bake at 400°F for 25 minutes"],
    tags: ["Shepherd's Pie", "Lentils", "Vegetarian", "Comfort", "Hearty"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Cucumber Gazpacho",
    description: "Refreshing cold soup with cucumber, yogurt, and fresh herbs.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 10,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1560963689-fae6d6bcc027?w=800&h=600&fit=crop",
    ingredients: ["3 large cucumbers", "1 cup Greek yogurt", "2 cloves garlic", "1/4 cup olive oil", "2 tbsp lemon juice", "Fresh dill", "Fresh mint", "Salt and pepper"],
    instructions: ["Peel and chop cucumbers", "Blend with yogurt and garlic", "Add olive oil and lemon", "Season with salt and pepper", "Chill for 2 hours", "Garnish with herbs", "Serve cold"],
    tags: ["Gazpacho", "Cucumber", "Cold Soup", "Summer", "Refreshing"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Cashew Alfredo Pasta",
    description: "Creamy dairy-free alfredo sauce made with cashews over GF pasta.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 20,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1611270629569-8b357cb88da9?w=800&h=600&fit=crop",
    ingredients: ["12 oz GF pasta", "1 cup raw cashews", "1 cup water", "3 cloves garlic", "2 tbsp nutritional yeast", "1 tbsp lemon juice", "Salt and pepper", "Fresh parsley"],
    instructions: ["Soak cashews in hot water", "Cook pasta according to package", "Blend cashews with water and garlic", "Add nutritional yeast and lemon", "Toss pasta with sauce", "Season to taste", "Garnish with parsley"],
    tags: ["Alfredo", "Cashew", "Dairy-Free", "Pasta", "Creamy"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Watermelon Feta Salad",
    description: "Sweet and salty summer salad with watermelon, feta, and mint.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 10,
    servings: 6,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1588417321386-036603153e06?w=800&h=600&fit=crop",
    ingredients: ["4 cups watermelon cubes", "1 cup feta cheese", "1/2 red onion", "1/4 cup fresh mint", "2 tbsp olive oil", "1 tbsp balsamic vinegar", "Black pepper", "Arugula"],
    instructions: ["Cube watermelon", "Crumble feta", "Slice onion thinly", "Tear mint leaves", "Arrange on arugula", "Drizzle with oil and vinegar", "Season with black pepper"],
    tags: ["Watermelon", "Feta", "Summer", "Salad", "Refreshing"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Pumpkin Curry Soup",
    description: "Velvety pumpkin soup with Thai curry flavors and coconut milk.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 30,
    servings: 6,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&h=600&fit=crop",
    ingredients: ["1 small pumpkin", "1 can coconut milk", "2 tbsp red curry paste", "1 onion", "3 cloves garlic", "1 tbsp ginger", "2 cups vegetable broth", "Lime juice", "Cilantro"],
    instructions: ["Roast pumpkin chunks", "Sauté onion, garlic, ginger", "Add curry paste", "Add pumpkin and broth", "Simmer 15 minutes", "Blend until smooth", "Stir in coconut milk", "Garnish with cilantro"],
    tags: ["Pumpkin", "Curry", "Soup", "Thai", "Creamy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Quinoa Stuffed Acorn Squash",
    description: "Roasted acorn squash halves filled with cranberry quinoa stuffing.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 60,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1511994942558-90d8b2bef53a?w=800&h=600&fit=crop",
    ingredients: ["2 acorn squash", "1 cup quinoa", "1/2 cup cranberries", "1/2 cup pecans", "1 apple", "1 onion", "2 cups vegetable broth", "Sage", "Cinnamon"],
    instructions: ["Halve and roast squash", "Cook quinoa in broth", "Sauté onion and apple", "Mix with quinoa, cranberries, pecans", "Season with sage and cinnamon", "Fill squash halves", "Bake 15 more minutes"],
    tags: ["Acorn Squash", "Quinoa", "Stuffed", "Fall", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Chocolate Quinoa Breakfast Bowl",
    description: "Protein-packed chocolate quinoa porridge topped with fruits and nuts.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1517093611884-52e9788a327b?w=800&h=600&fit=crop",
    ingredients: ["1 cup quinoa", "2 cups almond milk", "3 tbsp cocoa powder", "2 tbsp maple syrup", "1 tsp vanilla", "Banana slices", "Berries", "Almonds", "Coconut flakes"],
    instructions: ["Cook quinoa in almond milk", "Stir in cocoa powder", "Add maple syrup and vanilla", "Cook until creamy", "Pour into bowls", "Top with fruits and nuts", "Sprinkle with coconut"],
    tags: ["Quinoa", "Chocolate", "Breakfast", "Protein", "Healthy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Mediterranean Chickpea Salad",
    description: "Protein-rich salad with chickpeas, vegetables, and lemon-herb dressing.",
    category: "Lunch",
    difficulty: "Easy",
    cookTime: 15,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&h=600&fit=crop",
    ingredients: ["2 cans chickpeas", "1 cucumber", "2 cups cherry tomatoes", "1/2 red onion", "1/2 cup kalamata olives", "1/2 cup feta", "1/4 cup olive oil", "2 tbsp lemon juice", "Fresh oregano"],
    instructions: ["Rinse chickpeas", "Dice cucumber and tomatoes", "Slice onion thinly", "Mix vegetables with chickpeas", "Add olives and feta", "Whisk oil with lemon juice", "Toss with dressing", "Garnish with oregano"],
    tags: ["Mediterranean", "Chickpeas", "Salad", "Protein", "Fresh"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Almond Flour Pizza Crust",
    description: "Crispy gluten-free pizza crust made with almond flour and cheese.",
    category: "Dinner",
    difficulty: "Medium",
    cookTime: 30,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=600&fit=crop",
    ingredients: ["2 cups almond flour", "2 eggs", "2 cups mozzarella", "2 oz cream cheese", "1 tsp Italian seasoning", "Pizza sauce", "Toppings of choice"],
    instructions: ["Melt mozzarella and cream cheese", "Mix with almond flour and eggs", "Form into pizza crust", "Bake at 425°F for 10 minutes", "Add sauce and toppings", "Bake 10-15 more minutes"],
    tags: ["Pizza", "Almond Flour", "Low-Carb", "Crispy", "Italian"],
    isNaturallyGlutenFree: false,
  },
  {
    title: "Miso Glazed Eggplant",
    description: "Japanese-style roasted eggplant with sweet and savory miso glaze.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 30,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1626082928669-a4bb9a8d5e7c?w=800&h=600&fit=crop",
    ingredients: ["2 large eggplants", "3 tbsp miso paste", "2 tbsp mirin", "1 tbsp honey", "1 tbsp sesame oil", "1 tsp ginger", "Sesame seeds", "Green onions"],
    instructions: ["Score eggplant halves", "Mix miso, mirin, honey", "Brush eggplant with glaze", "Roast at 400°F for 25 minutes", "Brush with more glaze", "Broil 2-3 minutes", "Garnish with sesame and onions"],
    tags: ["Japanese", "Eggplant", "Miso", "Glazed", "Vegetarian"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Cauliflower Steaks with Chimichurri",
    description: "Thick-cut roasted cauliflower steaks topped with vibrant chimichurri sauce.",
    category: "Dinner",
    difficulty: "Easy",
    cookTime: 35,
    servings: 4,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1615870103730-b8850b067964?w=800&h=600&fit=crop",
    ingredients: ["2 large cauliflower heads", "1 cup parsley", "1/4 cup cilantro", "3 cloves garlic", "1/4 cup red wine vinegar", "1/2 cup olive oil", "Red pepper flakes", "Salt"],
    instructions: ["Cut cauliflower into 1-inch steaks", "Brush with oil, season", "Roast at 425°F for 25 minutes", "Make chimichurri sauce", "Flip steaks once during roasting", "Serve topped with chimichurri"],
    tags: ["Cauliflower", "Chimichurri", "Vegetarian", "Argentinian", "Steaks"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Black Bean Brownies",
    description: "Fudgy flourless brownies made with black beans and cocoa.",
    category: "Desserts",
    difficulty: "Easy",
    cookTime: 30,
    servings: 16,
    rating: "4.4",
    image: "https://images.unsplash.com/photo-1594969617298-0cb71ca2475f?w=800&h=600&fit=crop",
    ingredients: ["1 can black beans", "3 eggs", "1/3 cup cocoa powder", "1/2 cup sugar", "1/4 cup coconut oil", "1 tsp vanilla", "1/2 tsp baking powder", "Chocolate chips"],
    instructions: ["Rinse and drain beans", "Blend all ingredients except chips", "Fold in chocolate chips", "Pour into 8x8 pan", "Bake at 350°F for 25-30 minutes", "Cool completely before cutting"],
    tags: ["Brownies", "Black Beans", "Flourless", "Fudgy", "Healthy"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Tom Yum Soup",
    description: "Spicy and sour Thai soup with shrimp, mushrooms, and aromatic herbs.",
    category: "Lunch",
    difficulty: "Medium",
    cookTime: 20,
    servings: 4,
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1608039830572-78524f79c4c7?w=800&h=600&fit=crop",
    ingredients: ["1 lb shrimp", "4 cups chicken broth", "2 stalks lemongrass", "3 kaffir lime leaves", "1 cup mushrooms", "3 Thai chilies", "2 tbsp fish sauce", "2 tbsp lime juice", "Cilantro"],
    instructions: ["Simmer broth with lemongrass", "Add lime leaves and chilies", "Add mushrooms", "Cook shrimp until pink", "Season with fish sauce", "Add lime juice off heat", "Garnish with cilantro"],
    tags: ["Thai", "Tom Yum", "Soup", "Spicy", "Sour"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Hasselback Sweet Potatoes",
    description: "Crispy sliced sweet potatoes with butter, herbs, and marshmallows.",
    category: "Snacks",
    difficulty: "Medium",
    cookTime: 50,
    servings: 4,
    rating: "4.6",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
    ingredients: ["4 sweet potatoes", "4 tbsp butter", "2 tbsp brown sugar", "1 tsp cinnamon", "Fresh thyme", "Mini marshmallows", "Pecans", "Salt"],
    instructions: ["Make thin cuts in potatoes", "Mix butter with sugar and cinnamon", "Brush between slices", "Bake at 425°F for 40 minutes", "Add marshmallows last 5 minutes", "Top with pecans"],
    tags: ["Sweet Potatoes", "Hasselback", "Crispy", "Marshmallows", "Side Dish"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Edamame Hummus",
    description: "Green protein-packed hummus made with edamame instead of chickpeas.",
    category: "Snacks",
    difficulty: "Easy",
    cookTime: 10,
    servings: 8,
    rating: "4.5",
    image: "https://images.unsplash.com/photo-1613492874228-5fa71a827f2f?w=800&h=600&fit=crop",
    ingredients: ["2 cups shelled edamame", "1/4 cup tahini", "3 cloves garlic", "1/4 cup lemon juice", "1/4 cup olive oil", "1 tsp cumin", "Salt", "GF crackers"],
    instructions: ["Cook edamame until tender", "Blend with tahini and garlic", "Add lemon juice", "Stream in olive oil", "Season with cumin and salt", "Serve with vegetables or crackers"],
    tags: ["Edamame", "Hummus", "Protein", "Green", "Dip"],
    isNaturallyGlutenFree: true,
  },
  {
    title: "Paleo Breakfast Hash",
    description: "Hearty breakfast skillet with sweet potatoes, vegetables, and eggs.",
    category: "Breakfast",
    difficulty: "Easy",
    cookTime: 25,
    servings: 4,
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1460306855393-0410f61241c7?w=800&h=600&fit=crop",
    ingredients: ["2 sweet potatoes", "1 lb breakfast sausage", "1 bell pepper", "1 onion", "2 cups spinach", "4 eggs", "2 tbsp olive oil", "Paprika", "Hot sauce"],
    instructions: ["Dice sweet potatoes", "Cook sausage, set aside", "Sauté potatoes until crispy", "Add pepper and onion", "Return sausage to pan", "Add spinach until wilted", "Make wells, crack eggs", "Cover until eggs set"],
    tags: ["Paleo", "Breakfast", "Hash", "Sweet Potatoes", "Eggs"],
    isNaturallyGlutenFree: true,
  }
];