import { db } from "../server/db";
import { recipes } from "../shared/schema";

const thanksgivingRecipes = [
  {
    title: "Gluten-Free Herb-Roasted Turkey with Garlic Butter",
    slug: "gluten-free-herb-roasted-turkey-with-garlic-butter",
    description: "Juicy, tender turkey infused with fresh herbs, garlic, and butter — crisp golden skin and flavorful drippings perfect for gravy.",
    longDescription: "This show-stopping Gluten-Free Herb-Roasted Turkey is the centerpiece of any Thanksgiving table. The turkey is generously seasoned with fresh rosemary, thyme, and sage, then rubbed with aromatic garlic butter that penetrates deep into the meat for incredible flavor. As it roasts, the skin becomes beautifully golden and crisp while the meat stays incredibly moist and tender. The pan drippings create the foundation for the most delicious homemade gravy. This recipe includes tips for prep-ahead seasoning and proper roasting techniques to ensure your turkey is cooked to perfection every time.",
    category: "Thanksgiving",
    subcategory: "Holiday Mains",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 180,
    totalTime: 210,
    servings: 12,
    rating: "4.9",
    calories: 320,
    protein: "45.0",
    carbs: "2.0",
    fat: "14.0",
    fiber: "0.5",
    sugar: "0.5",
    image: "/recipe-images/gluten-free-herb-roasted-turkey.png",
    ingredients: [
      "1 whole turkey (12-14 lbs), giblets removed",
      "1/2 cup unsalted butter, softened",
      "6 cloves garlic, minced",
      "2 tablespoons fresh rosemary, chopped",
      "2 tablespoons fresh thyme, chopped",
      "2 tablespoons fresh sage, chopped",
      "2 teaspoons sea salt",
      "1 teaspoon black pepper",
      "1 lemon, halved",
      "1 onion, quartered",
      "4 cups gluten-free chicken broth",
      "Fresh herb sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 325°F. Pat turkey completely dry with paper towels.",
      "Mix softened butter with minced garlic, chopped rosemary, thyme, sage, salt, and pepper.",
      "Carefully loosen the skin from the turkey breast and rub herb butter underneath the skin and all over the outside.",
      "Place lemon halves and onion quarters inside the turkey cavity.",
      "Tie legs together with kitchen twine and tuck wing tips under the body.",
      "Place turkey breast-side up on a roasting rack in a large roasting pan.",
      "Pour chicken broth into the bottom of the pan.",
      "Roast for 3-3.5 hours, basting every 45 minutes, until internal temperature reaches 165°F in the thickest part of the thigh.",
      "Tent with foil if skin browns too quickly.",
      "Let rest for 30 minutes before carving. Reserve pan drippings for gravy."
    ],
    tips: "For crispier skin, start at 425°F for 30 minutes, then reduce to 325°F. Use a meat thermometer to ensure proper doneness. Let turkey rest fully to retain juices.",
    variations: [
      "Add maple syrup to the butter for a sweet glaze",
      "Use duck fat instead of butter for richer flavor",
      "Stuff with aromatics like apples and celery"
    ],
    tags: ["gluten-free", "thanksgiving", "turkey", "holiday", "main dish", "roasted", "herbs", "family-style"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Herb-Roasted Turkey with Garlic Butter - Perfect Thanksgiving Recipe",
    seoDescription: "Juicy herb-roasted turkey with crispy golden skin and garlic butter. This gluten-free Thanksgiving centerpiece serves 12 with flavorful pan drippings for gravy."
  },
  {
    title: "Gluten-Free Sweet Potato Casserole with Pecan Streusel",
    slug: "gluten-free-sweet-potato-casserole-with-pecan-streusel",
    description: "Whipped sweet potatoes topped with a crunchy pecan-oat crumble — naturally sweetened and dairy-optional for a crowd-pleasing holiday side.",
    longDescription: "This Gluten-Free Sweet Potato Casserole is a Thanksgiving classic reimagined without gluten. Creamy, naturally sweet roasted sweet potatoes are whipped until silky smooth with a touch of cinnamon and nutmeg. The showstopper is the crunchy pecan streusel topping made with gluten-free oats, chopped pecans, and a hint of maple syrup. The contrast between the smooth, sweet filling and the crunchy, caramelized topping is absolutely divine. This recipe can easily be made dairy-free by using coconut oil or vegan butter, making it perfect for guests with various dietary needs.",
    category: "Thanksgiving",
    subcategory: "Holiday Sides",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.8",
    calories: 280,
    protein: "4.0",
    carbs: "42.0",
    fat: "12.0",
    fiber: "5.0",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-sweet-potato-casserole.png",
    ingredients: [
      "4 lbs sweet potatoes, peeled and cubed",
      "1/4 cup butter or coconut oil",
      "1/4 cup maple syrup",
      "1 teaspoon cinnamon",
      "1/2 teaspoon nutmeg",
      "1/2 teaspoon salt",
      "For topping: 1 cup gluten-free oats",
      "1 cup pecans, chopped",
      "1/3 cup brown sugar",
      "1/4 cup butter or coconut oil, melted",
      "1/2 teaspoon cinnamon"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Boil sweet potatoes in salted water for 15-20 minutes until very tender. Drain well.",
      "Mash sweet potatoes with butter, maple syrup, cinnamon, nutmeg, and salt until smooth and creamy.",
      "Spread sweet potato mixture evenly in prepared baking dish.",
      "For topping: Mix oats, chopped pecans, brown sugar, melted butter, and cinnamon in a bowl.",
      "Sprinkle topping evenly over sweet potato layer.",
      "Bake for 30-35 minutes until topping is golden brown and crispy.",
      "Let cool for 10 minutes before serving."
    ],
    tips: "Can be assembled a day ahead and refrigerated. Add 10 minutes to bake time if starting from cold. For extra flavor, add a splash of vanilla extract to the sweet potatoes.",
    variations: [
      "Add mini marshmallows on top for the last 5 minutes of baking",
      "Use walnuts instead of pecans",
      "Mix in a mashed banana for extra sweetness"
    ],
    tags: ["gluten-free", "thanksgiving", "sweet potato", "casserole", "side dish", "pecans", "holiday", "make-ahead"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Casserole with Pecan Streusel - Thanksgiving Side",
    seoDescription: "Creamy whipped sweet potatoes with crunchy pecan streusel topping. This gluten-free Thanksgiving casserole is naturally sweetened and dairy-optional."
  },
  {
    title: "Gluten-Free Classic Stuffing with Sausage & Apples",
    slug: "gluten-free-classic-stuffing-with-sausage-apples",
    description: "Homemade gluten-free bread cubes, sautéed onion, celery, herbs, and crumbled sausage with sweet apple chunks — savory, satisfying, and crispy on top.",
    longDescription: "This Gluten-Free Classic Stuffing captures all the nostalgic flavors of traditional Thanksgiving dressing without any gluten. Made with toasted gluten-free bread cubes, savory Italian sausage, aromatic vegetables, and sweet apple chunks, every bite delivers the perfect balance of flavors and textures. The bread soaks up rich chicken broth infused with sage, thyme, and rosemary, while the top layer bakes to a beautiful golden crisp. The addition of apples adds a subtle sweetness that complements the savory sausage perfectly. This stuffing can be made ahead and reheated, making your Thanksgiving prep much easier.",
    category: "Thanksgiving",
    subcategory: "Holiday Sides",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 12,
    rating: "4.9",
    calories: 245,
    protein: "10.0",
    carbs: "28.0",
    fat: "11.0",
    fiber: "3.0",
    sugar: "6.0",
    image: "/recipe-images/gluten-free-classic-stuffing.png",
    ingredients: [
      "1 loaf gluten-free bread, cut into 1-inch cubes (about 10 cups)",
      "1 lb gluten-free Italian sausage, casings removed",
      "1/2 cup butter",
      "1 large onion, diced",
      "3 celery stalks, diced",
      "2 apples, peeled and diced",
      "3 cloves garlic, minced",
      "2 tablespoons fresh sage, chopped",
      "1 tablespoon fresh thyme",
      "1 tablespoon fresh rosemary, chopped",
      "3 cups gluten-free chicken broth",
      "2 eggs, beaten",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Preheat oven to 350°F. Spread bread cubes on baking sheets and toast for 15 minutes until dry and lightly golden. Transfer to large bowl.",
      "In a large skillet, cook sausage over medium heat, breaking it into crumbles. Transfer to bowl with bread.",
      "In same skillet, melt butter. Add onion, celery, and apples. Cook 8-10 minutes until softened.",
      "Add garlic, sage, thyme, and rosemary. Cook 2 minutes until fragrant.",
      "Pour vegetable mixture over bread and sausage. Toss to combine.",
      "Mix chicken broth with beaten eggs. Pour over stuffing mixture and stir until evenly moistened.",
      "Season with salt and pepper. Transfer to greased 9x13 inch baking dish.",
      "Cover with foil and bake 30 minutes. Remove foil and bake 15-20 minutes more until top is crispy and golden.",
      "Let rest 10 minutes before serving."
    ],
    tips: "Toast bread cubes the day before for easier prep. Use a mix of mild and spicy sausage for more complex flavor. Don't skip the egg - it helps bind everything together.",
    variations: [
      "Add dried cranberries for a sweet-tart pop",
      "Use pears instead of apples",
      "Make it vegetarian by omitting sausage and adding mushrooms"
    ],
    tags: ["gluten-free", "thanksgiving", "stuffing", "sausage", "apples", "holiday", "side dish", "make-ahead"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Classic Stuffing with Sausage & Apples - Thanksgiving Recipe",
    seoDescription: "Traditional stuffing made gluten-free with toasted bread cubes, savory sausage, and sweet apples. Crispy top, moist inside - perfect for Thanksgiving."
  },
  {
    title: "Gluten-Free Green Bean Almondine",
    slug: "gluten-free-green-bean-almondine",
    description: "Crisp-tender green beans tossed with toasted almonds, lemon zest, and garlic butter — a simple, elegant side that comes together in minutes.",
    longDescription: "This Gluten-Free Green Bean Almondine is a classic French-inspired side dish that brings elegance and freshness to your Thanksgiving table. Vibrant green beans are blanched to crisp-tender perfection, then tossed with golden toasted almond slices and aromatic garlic butter. A touch of fresh lemon zest brightens the dish and cuts through the richness of the holiday meal. This recipe is naturally gluten-free and can be prepared in under 20 minutes, making it perfect for busy holiday cooking. The key is not to overcook the beans - they should still have a slight snap when you bite into them.",
    category: "Thanksgiving",
    subcategory: "Holiday Sides",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 12,
    totalTime: 22,
    servings: 8,
    rating: "4.7",
    calories: 120,
    protein: "3.5",
    carbs: "8.0",
    fat: "9.0",
    fiber: "3.5",
    sugar: "3.0",
    image: "/recipe-images/gluten-free-green-bean-almondine.png",
    ingredients: [
      "2 lbs fresh green beans, trimmed",
      "1/3 cup sliced almonds",
      "3 tablespoons butter",
      "3 cloves garlic, minced",
      "Zest of 1 lemon",
      "2 tablespoons fresh lemon juice",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Bring a large pot of salted water to boil. Add green beans and cook 4-5 minutes until crisp-tender.",
      "Drain beans and immediately plunge into ice water to stop cooking. Drain again and pat dry.",
      "In a large skillet, toast almond slices over medium heat for 2-3 minutes until golden and fragrant. Remove and set aside.",
      "In same skillet, melt butter over medium heat. Add garlic and cook 1 minute until fragrant.",
      "Add green beans to skillet and toss to coat in garlic butter. Cook 3-4 minutes until heated through.",
      "Add lemon zest, lemon juice, and toasted almonds. Toss well.",
      "Season with salt and pepper. Garnish with fresh parsley and serve immediately."
    ],
    tips: "Blanch green beans up to 2 days ahead and store in refrigerator. Just reheat in garlic butter before serving. Use fresh green beans for best texture and flavor.",
    variations: [
      "Add a splash of white wine to the garlic butter",
      "Use hazelnuts instead of almonds",
      "Sprinkle with Parmesan cheese before serving"
    ],
    tags: ["gluten-free", "thanksgiving", "green beans", "almonds", "side dish", "quick", "healthy", "vegetarian"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Green Bean Almondine - Easy Thanksgiving Side Dish",
    seoDescription: "Crisp-tender green beans with toasted almonds, garlic butter, and lemon zest. This elegant gluten-free side dish takes just 20 minutes to make."
  },
  {
    title: "Gluten-Free Cranberry Orange Relish",
    slug: "gluten-free-cranberry-orange-relish",
    description: "Fresh cranberries simmered with orange juice, zest, and maple syrup — tart, sweet, and vibrant with jewel-toned color.",
    longDescription: "This Gluten-Free Cranberry Orange Relish is a refreshing departure from canned cranberry sauce. Made with fresh cranberries, bright orange juice and zest, and naturally sweetened with pure maple syrup, this relish is perfectly balanced between tart and sweet. The cranberries burst as they cook, creating a beautiful ruby-red sauce with a vibrant, jewel-like appearance. The orange adds a citrusy brightness that complements the turkey and cuts through rich, heavy dishes. This relish can be made up to 5 days ahead and actually tastes better after the flavors have time to meld together.",
    category: "Thanksgiving",
    subcategory: "Holiday Condiments",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 15,
    totalTime: 20,
    servings: 10,
    rating: "4.8",
    calories: 65,
    protein: "0.3",
    carbs: "16.0",
    fat: "0.1",
    fiber: "2.0",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-cranberry-orange-relish.png",
    ingredients: [
      "12 oz fresh cranberries",
      "1 cup orange juice",
      "Zest of 2 oranges",
      "1/2 cup maple syrup",
      "1/4 cup water",
      "1 cinnamon stick",
      "Pinch of salt"
    ],
    instructions: [
      "Rinse cranberries and remove any stems or soft berries.",
      "In a medium saucepan, combine orange juice, orange zest, maple syrup, water, cinnamon stick, and salt.",
      "Bring to a boil over medium-high heat.",
      "Add cranberries and return to a boil.",
      "Reduce heat to medium and simmer 10-12 minutes, stirring occasionally, until cranberries burst and mixture thickens.",
      "Remove from heat and discard cinnamon stick.",
      "Let cool to room temperature - relish will thicken more as it cools.",
      "Transfer to serving bowl and refrigerate until ready to serve. Can be made up to 5 days ahead."
    ],
    tips: "The relish will be quite liquid when hot but will gel as it cools. For a smoother texture, pulse a few times in a food processor after cooling. Add a splash of Grand Marnier for an adult version.",
    variations: [
      "Add diced apple for extra texture",
      "Stir in chopped candied ginger",
      "Use honey instead of maple syrup"
    ],
    tags: ["gluten-free", "thanksgiving", "cranberry", "orange", "condiment", "make-ahead", "vegan", "healthy"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cranberry Orange Relish - Fresh Thanksgiving Condiment",
    seoDescription: "Homemade cranberry relish with fresh orange and maple syrup. Better than canned, this gluten-free condiment is tart, sweet, and ready in 20 minutes."
  },
  {
    title: "Gluten-Free Gravy with Roasted Turkey Drippings",
    slug: "gluten-free-gravy-with-roasted-turkey-drippings",
    description: "Rich, velvety gravy thickened with rice flour or cornstarch — made from flavorful turkey drippings and seasoned with herbs and black pepper.",
    longDescription: "This Gluten-Free Gravy is the crowning glory of your Thanksgiving turkey. Made with the rich, flavorful pan drippings from your roasted turkey and thickened with rice flour or cornstarch instead of wheat flour, this gravy is silky smooth and deeply savory. Fresh herbs and a touch of black pepper add complexity and warmth. The secret to perfect gravy is properly deglazing the roasting pan to capture all those caramelized bits of flavor stuck to the bottom. This recipe ensures you'll never have lumpy gravy again, and it's so delicious that your guests will never know it's gluten-free.",
    category: "Thanksgiving",
    subcategory: "Holiday Sauces",
    difficulty: "Medium",
    prepTime: 5,
    cookTime: 15,
    totalTime: 20,
    servings: 12,
    rating: "4.9",
    calories: 45,
    protein: "1.5",
    carbs: "4.0",
    fat: "3.0",
    fiber: "0.1",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-turkey-gravy.png",
    ingredients: [
      "Turkey pan drippings (about 1/2 cup fat and drippings)",
      "1/4 cup rice flour or cornstarch",
      "4 cups gluten-free turkey or chicken broth, warmed",
      "1 tablespoon fresh thyme leaves",
      "1 teaspoon black pepper",
      "Salt to taste",
      "Optional: 2 tablespoons butter for richness"
    ],
    instructions: [
      "After removing turkey from roasting pan, pour drippings through a fine-mesh strainer into a measuring cup.",
      "Let fat rise to the top. Skim off 1/2 cup of fat and return it to the roasting pan (or use butter if needed).",
      "Place roasting pan over medium heat on stovetop (use two burners if needed).",
      "Whisk rice flour into the fat until smooth, scraping up all browned bits from bottom of pan.",
      "Cook roux for 2-3 minutes, whisking constantly, until golden and fragrant.",
      "Gradually whisk in warm broth, about 1 cup at a time, whisking constantly to prevent lumps.",
      "Bring to a simmer and cook 8-10 minutes until gravy thickens to desired consistency.",
      "Stir in thyme and black pepper. Taste and adjust seasoning with salt.",
      "Strain through fine-mesh sieve if desired for ultra-smooth gravy.",
      "Keep warm until ready to serve. Thin with additional broth if gravy gets too thick."
    ],
    tips: "Have everything ready before you start - gravy comes together quickly. If you don't have enough drippings, supplement with butter. For extra rich flavor, add a splash of white wine when deglazing the pan.",
    variations: [
      "Add a splash of cream for extra richness",
      "Stir in caramelized onions",
      "Add fresh sage instead of thyme"
    ],
    tags: ["gluten-free", "thanksgiving", "gravy", "turkey", "sauce", "holiday", "savory"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Turkey Gravy with Pan Drippings - Perfect Thanksgiving Sauce",
    seoDescription: "Silky smooth gravy made from turkey drippings and thickened with rice flour. This gluten-free gravy recipe is rich, savory, and lump-free every time."
  },
  {
    title: "Gluten-Free Mashed Cauliflower & Potatoes",
    slug: "gluten-free-mashed-cauliflower-potatoes",
    description: "Creamy mash combining cauliflower and Yukon Golds for a lighter, silky side — finished with olive oil or butter, garlic, and fresh chives.",
    longDescription: "This Gluten-Free Mashed Cauliflower & Potatoes is a healthier twist on classic mashed potatoes that doesn't sacrifice flavor or texture. By combining tender Yukon Gold potatoes with roasted cauliflower, you get a lighter, more nutritious side dish that's incredibly creamy and satisfying. The cauliflower adds a subtle sweetness and creates an ultra-silky texture when mashed. Finished with roasted garlic, rich butter or olive oil, and fresh chives, this dish is so delicious that even vegetable skeptics will love it. It's naturally gluten-free and can easily be made dairy-free for guests with additional restrictions.",
    category: "Thanksgiving",
    subcategory: "Holiday Sides",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 10,
    rating: "4.7",
    calories: 145,
    protein: "3.0",
    carbs: "22.0",
    fat: "6.0",
    fiber: "3.5",
    sugar: "3.0",
    image: "/recipe-images/gluten-free-mashed-cauliflower-potatoes.png",
    ingredients: [
      "2 lbs Yukon Gold potatoes, peeled and cubed",
      "1 large head cauliflower, cut into florets",
      "6 cloves garlic, peeled",
      "1/2 cup butter or olive oil",
      "1/2 cup warm milk or unsweetened almond milk",
      "Salt and pepper to taste",
      "Fresh chives, chopped for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F if roasting cauliflower (optional for extra flavor).",
      "Place potatoes in large pot of salted water. Bring to boil and cook 15-20 minutes until very tender.",
      "Meanwhile, steam cauliflower florets 10-12 minutes until very soft, or roast in oven 20-25 minutes until golden.",
      "Add garlic cloves to potatoes for last 5 minutes of cooking.",
      "Drain potatoes and garlic well. Return to pot and let steam dry for 2 minutes.",
      "Add cauliflower to pot with potatoes and garlic.",
      "Add butter and warm milk. Mash until smooth and creamy using potato masher or hand mixer.",
      "Season generously with salt and pepper.",
      "Transfer to serving bowl and garnish with chopped chives. Serve hot."
    ],
    tips: "Don't skip the steam-drying step - it ensures fluffy, not gluey, mashed potatoes. For extra flavor, roast the garlic separately until caramelized. Can be made 2 hours ahead and kept warm in slow cooker.",
    variations: [
      "Add cream cheese for extra richness",
      "Mix in roasted garlic",
      "Top with crispy fried onions"
    ],
    tags: ["gluten-free", "thanksgiving", "mashed potatoes", "cauliflower", "side dish", "healthy", "vegetarian"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Mashed Cauliflower & Potatoes - Lighter Thanksgiving Side",
    seoDescription: "Creamy mashed potatoes mixed with cauliflower for a lighter, healthier side dish. This gluten-free recipe is silky smooth and full of flavor."
  },
  {
    title: "Gluten-Free Pumpkin Pie with Almond Crust",
    slug: "gluten-free-pumpkin-pie-with-almond-crust",
    description: "Classic spiced pumpkin custard baked in a nutty almond flour crust — smooth, creamy, perfectly spiced, and the ultimate Thanksgiving dessert.",
    longDescription: "This Gluten-Free Pumpkin Pie features a silky smooth pumpkin custard filling infused with warm spices like cinnamon, ginger, and nutmeg, all nestled in a tender almond flour crust. The almond crust provides a subtle nutty flavor that perfectly complements the sweet pumpkin filling while staying tender and flaky without any wheat flour. The filling is made with pure pumpkin puree, eggs, cream, and just the right amount of sweetness. This pie is indistinguishable from traditional pumpkin pie and is sure to be the star of your Thanksgiving dessert table. Serve with fresh whipped cream for the perfect finish.",
    category: "Thanksgiving",
    subcategory: "Holiday Desserts",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 55,
    totalTime: 85,
    servings: 8,
    rating: "4.9",
    calories: 310,
    protein: "7.0",
    carbs: "32.0",
    fat: "18.0",
    fiber: "4.0",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-pumpkin-pie.png",
    ingredients: [
      "For crust: 2 cups almond flour",
      "1/4 cup coconut flour",
      "1/4 cup cold butter, cubed",
      "2 tablespoons maple syrup",
      "1/4 teaspoon salt",
      "For filling: 1 can (15 oz) pure pumpkin puree",
      "3/4 cup brown sugar",
      "3 large eggs",
      "1 cup heavy cream or coconut cream",
      "2 teaspoons cinnamon",
      "1 teaspoon ginger",
      "1/2 teaspoon nutmeg",
      "1/4 teaspoon cloves",
      "1/2 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "For crust: Mix almond flour, coconut flour, and salt in bowl. Cut in cold butter until crumbly.",
      "Add maple syrup and mix until dough comes together. Press evenly into 9-inch pie pan.",
      "Prick bottom with fork and bake 12 minutes until lightly golden. Let cool slightly.",
      "For filling: Whisk together pumpkin puree, brown sugar, eggs, cream, cinnamon, ginger, nutmeg, cloves, and salt until smooth.",
      "Pour filling into pre-baked crust.",
      "Bake 45-50 minutes until center is just set but still slightly jiggly.",
      "Cool completely on wire rack, then refrigerate at least 4 hours or overnight.",
      "Serve chilled with whipped cream."
    ],
    tips: "Don't overbake - the pie will continue to set as it cools. Cover crust edges with foil if browning too quickly. Pie tastes best when made a day ahead.",
    variations: [
      "Add a pecan streusel topping",
      "Swirl in cream cheese for pumpkin cheesecake pie",
      "Top with candied pecans"
    ],
    tags: ["gluten-free", "thanksgiving", "pumpkin pie", "dessert", "almond crust", "holiday", "make-ahead"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pumpkin Pie with Almond Crust - Classic Thanksgiving Dessert",
    seoDescription: "Silky smooth pumpkin custard in a nutty almond flour crust. This gluten-free pumpkin pie is perfectly spiced and tastes just like traditional pie."
  },
  {
    title: "Gluten-Free Rosemary Focaccia Rolls",
    slug: "gluten-free-rosemary-focaccia-rolls",
    description: "Airy rolls brushed with olive oil and sea salt — crisp outside, soft inside, perfect for sopping up gravy and holiday feasting.",
    longDescription: "These Gluten-Free Rosemary Focaccia Rolls are impossibly soft and fluffy with a crispy, golden exterior. Made with a blend of gluten-free flours and enhanced with fresh rosemary, olive oil, and flaky sea salt, these rolls taste just like traditional focaccia bread. The dough is enriched with eggs and olive oil for a tender crumb, while the rosemary and sea salt topping provides aromatic flavor and textural contrast. These rolls are perfect for soaking up gravy, making turkey sandwiches with leftovers, or simply enjoying warm from the oven with butter. They're best served fresh but can be reheated to restore their crispy crust.",
    category: "Thanksgiving",
    subcategory: "Holiday Breads",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 12,
    rating: "4.8",
    calories: 185,
    protein: "4.0",
    carbs: "28.0",
    fat: "7.0",
    fiber: "2.5",
    sugar: "3.0",
    image: "/recipe-images/gluten-free-rosemary-focaccia-rolls.png",
    ingredients: [
      "2 cups gluten-free all-purpose flour blend",
      "1 cup tapioca starch",
      "2 teaspoons xanthan gum (if not in flour blend)",
      "1 tablespoon instant yeast",
      "1 tablespoon sugar",
      "1 1/2 teaspoons salt",
      "3 large eggs, room temperature",
      "1 cup warm water",
      "1/4 cup olive oil, plus more for brushing",
      "2 tablespoons fresh rosemary, chopped",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "In large bowl, whisk together flour, tapioca starch, xanthan gum, yeast, sugar, and salt.",
      "In separate bowl, whisk eggs, warm water, and olive oil.",
      "Pour wet ingredients into dry and mix until smooth dough forms. Dough will be sticky.",
      "Cover bowl and let rise in warm place for 45 minutes until doubled.",
      "Preheat oven to 400°F. Line muffin tin with paper liners or grease well.",
      "Stir down dough and divide among 12 muffin cups, filling each about 2/3 full.",
      "Brush tops generously with olive oil. Sprinkle with chopped rosemary and flaky sea salt.",
      "Let rise 15 minutes while oven preheats.",
      "Bake 22-25 minutes until golden brown and crispy on top.",
      "Remove from pan immediately and cool on wire rack. Serve warm."
    ],
    tips: "Make sure eggs and water are at room temperature for best rise. Don't skip the second rise - it makes the rolls extra fluffy. Brush with olive oil twice during baking for crispier crust.",
    variations: [
      "Add garlic to the olive oil",
      "Sprinkle with Parmesan cheese",
      "Mix in sun-dried tomatoes"
    ],
    tags: ["gluten-free", "thanksgiving", "bread", "rolls", "rosemary", "focaccia", "holiday", "side"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Rosemary Focaccia Rolls - Soft & Crispy Thanksgiving Bread",
    seoDescription: "Fluffy gluten-free rolls with crispy rosemary and sea salt topping. These focaccia-style rolls are perfect for Thanksgiving and sopping up gravy."
  },
  {
    title: "Gluten-Free Apple Crisp with Cinnamon Oat Topping",
    slug: "gluten-free-apple-crisp-with-cinnamon-oat-topping",
    description: "Warm spiced apples baked with a buttery oat-almond crumble — a rustic, comforting dessert to end your Thanksgiving feast.",
    longDescription: "This Gluten-Free Apple Crisp is the perfect ending to your Thanksgiving meal - warm, comforting, and not too heavy after a big dinner. Tender cinnamon-spiced apples are topped with a golden, buttery crumble made from gluten-free oats and almond flour. As it bakes, the apples soften and release their juices, creating a delicious sauce that bubbles up around the crispy topping. The contrast between the soft, sweet apples and the crunchy, nutty topping is absolutely irresistible. Serve warm with a scoop of vanilla ice cream or a dollop of whipped cream for the ultimate cozy dessert. This crisp is also wonderful for breakfast the next morning!",
    category: "Thanksgiving",
    subcategory: "Holiday Desserts",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.8",
    calories: 265,
    protein: "3.5",
    carbs: "42.0",
    fat: "11.0",
    fiber: "5.0",
    sugar: "26.0",
    image: "/recipe-images/gluten-free-apple-crisp.png",
    ingredients: [
      "For filling: 6 cups apples, peeled and sliced (Granny Smith or Honeycrisp)",
      "1/3 cup granulated sugar",
      "2 tablespoons lemon juice",
      "1 tablespoon cornstarch",
      "1 1/2 teaspoons cinnamon",
      "1/4 teaspoon nutmeg",
      "For topping: 1 1/2 cups gluten-free oats",
      "3/4 cup almond flour",
      "1/2 cup brown sugar",
      "1/2 cup cold butter, cubed",
      "1 teaspoon cinnamon",
      "1/4 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "In large bowl, toss sliced apples with sugar, lemon juice, cornstarch, cinnamon, and nutmeg.",
      "Spread apple mixture evenly in prepared baking dish.",
      "For topping: In bowl, combine oats, almond flour, brown sugar, cinnamon, and salt.",
      "Cut in cold butter using pastry cutter or fingers until mixture resembles coarse crumbs.",
      "Sprinkle topping evenly over apples.",
      "Bake 40-45 minutes until apples are tender and topping is golden brown and crispy.",
      "Let cool 15 minutes before serving.",
      "Serve warm with vanilla ice cream or whipped cream."
    ],
    tips: "Use a mix of tart and sweet apples for best flavor. Don't skip the lemon juice - it prevents browning and adds brightness. Crisp can be assembled a day ahead and refrigerated, then baked before serving.",
    variations: [
      "Add cranberries to the apple mixture",
      "Mix in chopped pecans with the topping",
      "Add a handful of raisins to filling"
    ],
    tags: ["gluten-free", "thanksgiving", "apple crisp", "dessert", "oats", "holiday", "make-ahead", "comfort food"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Crisp with Cinnamon Oat Topping - Easy Thanksgiving Dessert",
    seoDescription: "Warm spiced apples topped with buttery oat-almond crumble. This gluten-free apple crisp is the perfect comforting dessert for Thanksgiving."
  }
];

async function addThanksgivingRecipes() {
  console.log("Adding 10 Thanksgiving recipes to database...");
  
  try {
    for (const recipe of thanksgivingRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Thanksgiving recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/ and update paths!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addThanksgivingRecipes();
