import { db } from "../server/db";
import { recipes } from "../shared/schema";

const delicataSquashRecipes = [
  {
    title: "Gluten-Free Roasted Delicata Squash with Apples & Sage",
    slug: "gluten-free-roasted-delicata-squash-apples-sage",
    description: "Caramelized delicata squash and apples roasted with olive oil, maple syrup, and fresh sage — a perfect fall side.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Apples & Sage is the quintessential autumn side dish. Delicata squash's naturally sweet, creamy flesh pairs beautifully with tart apples and aromatic sage. Unlike other winter squash, delicata's tender skin is completely edible, making prep incredibly easy. Roasting at high heat caramelizes the natural sugars, creating golden, crispy edges while keeping the interior tender. A drizzle of maple syrup and olive oil enhances the squash's sweetness and helps everything caramelize perfectly. Fresh sage adds an earthy, slightly peppery note that ties all the flavors together. This dish is stunning on a Thanksgiving table but simple enough for weeknight dinners.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "4.9",
    calories: 145,
    protein: "1.5",
    carbs: "28.0",
    fat: "5.0",
    fiber: "3.5",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-apples-sage.png",
    ingredients: [
      "2 delicata squash, halved lengthwise, seeded, sliced into 1/2-inch crescents",
      "2 medium apples (Honeycrisp or Granny Smith), cored and sliced",
      "3 tablespoons olive oil",
      "2 tablespoons pure maple syrup",
      "12 fresh sage leaves",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Flaky sea salt for finishing"
    ],
    instructions: [
      "Preheat oven to 425°F. Line large baking sheet with parchment paper.",
      "Slice delicata squash in half lengthwise and scoop out seeds. No need to peel - the skin is edible!",
      "Cut squash into 1/2-inch thick crescents.",
      "In large bowl, toss squash crescents and apple slices with olive oil, maple syrup, salt, and pepper.",
      "Arrange in single layer on prepared baking sheet, making sure pieces don't overlap.",
      "Scatter fresh sage leaves over top.",
      "Roast for 15 minutes, then flip squash and apples. Continue roasting 15 more minutes until golden brown and caramelized at edges.",
      "Remove from oven and transfer to serving platter.",
      "Finish with flaky sea salt and additional fresh sage leaves.",
      "Serve warm."
    ],
    tips: "Don't peel delicata squash - the skin becomes tender when roasted. Make sure squash pieces are in single layer for best caramelization. Toss halfway through cooking for even browning. Choose firm apples that hold their shape when roasted.",
    variations: [
      "Add toasted pecans for crunch",
      "Drizzle with balsamic glaze before serving",
      "Sprinkle with crumbled goat cheese"
    ],
    tags: ["gluten-free", "delicata squash", "roasted", "apples", "sage", "fall", "thanksgiving", "autumn", "side dish", "vegan"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Apples & Sage - Perfect Fall Side",
    seoDescription: "Caramelized delicata squash and apples roasted with maple syrup and fresh sage. Easy, naturally gluten-free fall side dish."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Maple Glaze & Pecans",
    slug: "gluten-free-roasted-delicata-squash-maple-glaze-pecans",
    description: "Sweet maple glaze with toasted pecans and a hint of cinnamon for cozy flavor and crunch.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Maple Glaze & Pecans is comfort food at its finest. The squash is roasted until caramelized and tender, then drizzled with a thick, glossy maple glaze infused with warm cinnamon. Toasted pecans add wonderful crunch and nutty richness. The combination of sweet maple, warming spices, and buttery pecans creates a dish that tastes like the best of autumn in every bite. This is the kind of side dish that disappears quickly at holiday gatherings. It's naturally vegan and gluten-free, making it perfect for serving a crowd with varied dietary needs.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "4.9",
    calories: 195,
    protein: "2.5",
    carbs: "30.0",
    fat: "9.0",
    fiber: "4.0",
    sugar: "15.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-maple-glaze-pecans.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into rings",
      "3 tablespoons olive oil",
      "1/3 cup pure maple syrup",
      "1 teaspoon ground cinnamon",
      "3/4 cup pecans, roughly chopped",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "1 tablespoon butter or vegan butter (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F. Toast pecans on separate baking sheet for 5-7 minutes until fragrant. Set aside.",
      "Line large baking sheet with parchment paper.",
      "Slice delicata squash into 1/2-inch rings, removing seeds.",
      "Toss squash rings with olive oil, 2 tablespoons maple syrup, cinnamon, salt, and pepper.",
      "Arrange in single layer on baking sheet.",
      "Roast 15 minutes, then flip. Roast another 15 minutes until golden and caramelized.",
      "While squash roasts, warm remaining maple syrup with butter in small saucepan until slightly thickened, about 3 minutes.",
      "Transfer roasted squash to serving platter.",
      "Drizzle with warm maple glaze and sprinkle generously with toasted pecans.",
      "Serve immediately while glaze is warm and glossy."
    ],
    tips: "Toast pecans separately so they don't burn. The maple glaze should be warm when drizzled for best coverage. Can be made ahead and reheated in 350°F oven for 10 minutes.",
    variations: [
      "Use walnuts instead of pecans",
      "Add a pinch of nutmeg",
      "Finish with orange zest"
    ],
    tags: ["gluten-free", "delicata squash", "maple", "pecans", "roasted", "fall", "sweet", "thanksgiving", "holiday", "vegan"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Maple Glaze & Pecans - Cozy Fall Side",
    seoDescription: "Sweet roasted delicata squash with maple glaze and toasted pecans. Perfect Thanksgiving side dish, naturally gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Cranberries & Thyme",
    slug: "gluten-free-roasted-delicata-squash-cranberries-thyme",
    description: "Tart cranberries and thyme bring balance to the squash's natural sweetness — colorful and festive.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Cranberries & Thyme is a feast for the eyes and the palate. The golden squash provides a beautiful canvas for jewel-toned cranberries that burst during roasting, releasing their tart juice. Fresh thyme adds herbaceous, earthy notes that complement both the sweet squash and tart berries. The color contrast is stunning - perfect for holiday tables. The combination of sweet, tart, and savory creates a perfectly balanced dish. Fresh cranberries are best, but dried cranberries soaked in warm water also work beautifully. This is Thanksgiving perfection on a plate.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "4.8",
    calories: 125,
    protein: "1.5",
    carbs: "24.0",
    fat: "4.5",
    fiber: "3.0",
    sugar: "10.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-cranberries-thyme.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into crescents",
      "1 cup fresh cranberries",
      "3 tablespoons olive oil",
      "2 tablespoons honey or maple syrup",
      "2 tablespoons fresh thyme leaves",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Orange zest for garnish (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Cut delicata squash into 1/2-inch crescents, leaving skin on.",
      "In large bowl, toss squash with olive oil, honey, half the thyme, salt, and pepper.",
      "Arrange squash in single layer on baking sheet.",
      "Roast 15 minutes, then flip squash and scatter cranberries around.",
      "Continue roasting 15 more minutes until squash is golden and cranberries have burst.",
      "Transfer to serving dish and sprinkle with remaining fresh thyme.",
      "Garnish with orange zest if desired.",
      "Serve warm or at room temperature."
    ],
    tips: "Fresh cranberries will pop and release juice during roasting - this creates a beautiful glaze. If using dried cranberries, soak in warm water for 10 minutes first. The dish is equally delicious warm or at room temperature.",
    variations: [
      "Add toasted walnuts for crunch",
      "Include fresh orange segments",
      "Drizzle with balsamic glaze"
    ],
    tags: ["gluten-free", "delicata squash", "cranberries", "thyme", "roasted", "thanksgiving", "festive", "holiday", "fall", "vegan"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Cranberries & Thyme - Festive Fall Side",
    seoDescription: "Colorful roasted delicata squash with tart cranberries and fresh thyme. Perfect Thanksgiving side, naturally gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Brown Butter & Sage",
    slug: "gluten-free-roasted-delicata-squash-brown-butter-sage",
    description: "Nutty brown butter and crisp sage leaves drizzled over golden roasted squash rings — simple and elegant.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Brown Butter & Sage is elegance defined. The squash is roasted until caramelized and tender, then finished with fragrant brown butter and crispy fried sage. Brown butter - butter cooked until the milk solids turn golden and nutty - adds incredible depth and richness. The sage leaves are quickly fried in the butter until crisp, releasing their aromatic oils. This classic Italian-inspired preparation is deceptively simple but absolutely restaurant-quality. The combination of sweet squash, nutty butter, and crispy sage is pure magic. Perfect for impressing dinner guests or treating yourself.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "5.0",
    calories: 155,
    protein: "1.5",
    carbs: "20.0",
    fat: "8.0",
    fiber: "2.5",
    sugar: "4.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-brown-butter-sage.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into rings",
      "2 tablespoons olive oil",
      "4 tablespoons butter",
      "16-20 fresh sage leaves",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Flaky sea salt for finishing",
      "Fresh lemon juice (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Slice delicata squash into 1/2-inch rings. Toss with olive oil, salt, and pepper.",
      "Arrange in single layer on baking sheet.",
      "Roast 30 minutes, flipping halfway, until golden and caramelized.",
      "While squash roasts, make brown butter: melt butter in light-colored skillet over medium heat.",
      "Cook butter, swirling occasionally, until it turns golden brown and smells nutty, about 5 minutes. Watch carefully to prevent burning.",
      "Add sage leaves to brown butter and fry for 30-60 seconds until crisp.",
      "Transfer roasted squash to serving platter.",
      "Drizzle brown butter over squash and top with crispy sage leaves.",
      "Finish with flaky sea salt and a squeeze of lemon juice if desired.",
      "Serve immediately while butter is warm."
    ],
    tips: "Watch brown butter carefully - it goes from perfect to burnt quickly. Use a light-colored pan so you can see the color change. Sage leaves will crisp up in just seconds. Make this dish right before serving for best results.",
    variations: [
      "Add toasted hazelnuts",
      "Include crispy prosciutto",
      "Finish with Parmesan shavings"
    ],
    tags: ["gluten-free", "delicata squash", "brown butter", "sage", "roasted", "elegant", "italian-inspired", "fall", "simple", "vegetarian"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Brown Butter & Sage - Simple Elegance",
    seoDescription: "Elegant roasted delicata squash with nutty brown butter and crispy sage. Restaurant-quality, naturally gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Honey Apple Cider Drizzle",
    slug: "gluten-free-roasted-delicata-squash-honey-cider-drizzle",
    description: "A tangy-sweet glaze made with apple cider, honey, and a touch of Dijon — perfectly sticky and flavorful.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Honey Apple Cider Drizzle celebrates autumn flavors in their full glory. Apple cider is reduced with honey and a touch of Dijon mustard until thick and syrupy, creating a glaze that's sweet, tangy, and slightly savory all at once. The Dijon adds subtle depth and helps balance the sweetness. This glaze is brushed on the squash during the final minutes of roasting, allowing it to caramelize and create a gorgeous, sticky coating. The result is incredibly flavorful - each bite delivers sweet squash enhanced by the complex cider glaze. This is autumn on a plate.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 35,
    totalTime: 45,
    servings: 6,
    rating: "4.9",
    calories: 140,
    protein: "1.5",
    carbs: "30.0",
    fat: "4.0",
    fiber: "2.5",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-honey-cider-drizzle.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced",
      "2 tablespoons olive oil",
      "1 cup apple cider",
      "3 tablespoons honey",
      "1 teaspoon gluten-free Dijon mustard",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Make the glaze: combine apple cider, honey, and Dijon in small saucepan. Bring to boil, then reduce heat and simmer 15-20 minutes until reduced by half and syrupy. Set aside.",
      "Slice delicata squash into crescents. Toss with olive oil, salt, and pepper.",
      "Arrange in single layer on baking sheet and roast 20 minutes.",
      "Flip squash and brush generously with half the cider glaze.",
      "Return to oven for 10 more minutes until glaze is caramelized and squash is tender.",
      "Transfer to serving platter.",
      "Drizzle with remaining warm cider glaze.",
      "Garnish with fresh thyme.",
      "Serve warm."
    ],
    tips: "Reduce cider glaze until it coats the back of a spoon. Don't add glaze too early or it will burn. Any leftover glaze is delicious on roasted pork or chicken. The glaze thickens as it cools.",
    variations: [
      "Add cinnamon to the glaze",
      "Include fresh apple slices",
      "Top with toasted pumpkin seeds"
    ],
    tags: ["gluten-free", "delicata squash", "apple cider", "honey", "roasted", "fall", "sticky", "glazed", "autumn", "vegan-adaptable"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Honey Apple Cider Drizzle - Autumn Perfection",
    seoDescription: "Roasted delicata squash with sticky honey and apple cider glaze. Sweet-tangy perfection, naturally gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Caramelized Onions & Apples",
    slug: "gluten-free-roasted-delicata-squash-caramelized-onions-apples",
    description: "Savory-sweet layers of roasted onion, squash, and apples — aromatic and hearty.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Caramelized Onions & Apples is a study in sweet and savory harmony. Sweet onions are slowly caramelized until golden and jammy, then roasted alongside squash and apples. The onions add deep, savory notes while the apples provide bright tartness and the squash offers natural sweetness. As everything roasts together, the flavors meld and intensify. This is comfort food that's elegant enough for company. The combination is incredibly satisfying and pairs beautifully with roasted meats or can stand alone as a vegetarian main course over grains.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    rating: "4.9",
    calories: 165,
    protein: "2.0",
    carbs: "30.0",
    fat: "6.0",
    fiber: "4.0",
    sugar: "14.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-caramelized-onions-apples.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced",
      "2 large onions, thinly sliced",
      "2 apples, cored and sliced",
      "3 tablespoons olive oil, divided",
      "2 tablespoons butter or vegan butter",
      "1 tablespoon balsamic vinegar",
      "2 teaspoons fresh thyme leaves",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "In large skillet, heat butter and 1 tablespoon olive oil over medium-low heat. Add onions and cook slowly, stirring occasionally, until deeply caramelized, about 25-30 minutes.",
      "Add balsamic vinegar to onions and cook 2 more minutes. Set aside.",
      "Toss squash and apple slices with remaining olive oil, thyme, salt, and pepper.",
      "Spread on large baking sheet in single layer.",
      "Roast 15 minutes, then flip and scatter caramelized onions over top.",
      "Continue roasting 15 more minutes until squash is golden and tender.",
      "Transfer to serving platter, making sure to get all the caramelized bits.",
      "Garnish with additional fresh thyme.",
      "Serve warm."
    ],
    tips: "Don't rush caramelizing onions - low and slow is key. Can caramelize onions ahead of time. Choose firm apples that hold their shape. This dish reheats beautifully.",
    variations: [
      "Add dried cranberries",
      "Include toasted walnuts",
      "Top with crumbled goat cheese"
    ],
    tags: ["gluten-free", "delicata squash", "caramelized onions", "apples", "roasted", "savory-sweet", "fall", "hearty", "vegetarian", "comforting"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Caramelized Onions & Apples - Savory-Sweet",
    seoDescription: "Hearty roasted delicata squash with caramelized onions and apples. Savory-sweet autumn comfort, gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Goat Cheese & Pomegranate",
    slug: "gluten-free-roasted-delicata-squash-goat-cheese-pomegranate",
    description: "Creamy goat cheese and jewel-like pomegranate seeds add richness and bright contrast.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Goat Cheese & Pomegranate is a showstopper. Golden roasted squash provides the perfect canvas for creamy, tangy goat cheese and bright, juicy pomegranate arils. The color contrast alone is stunning - golden squash, white cheese, and ruby-red pomegranate. But the flavor combination is even better. The goat cheese adds luxurious creaminess and tang, the pomegranate provides sweet-tart pops of juice, and the squash offers natural sweetness. This is special occasion food that's surprisingly simple to prepare. Perfect for holidays or dinner parties when you want to impress.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "5.0",
    calories: 175,
    protein: "4.0",
    carbs: "26.0",
    fat: "7.0",
    fiber: "3.5",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-goat-cheese-pomegranate.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into crescents",
      "3 tablespoons olive oil",
      "1 tablespoon honey",
      "4 oz goat cheese, crumbled",
      "1/2 cup pomegranate arils",
      "2 tablespoons fresh mint, chopped",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Balsamic glaze for drizzling (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Toss squash crescents with olive oil, honey, salt, and pepper.",
      "Arrange in single layer on baking sheet.",
      "Roast 30 minutes, flipping halfway, until golden and caramelized.",
      "Transfer roasted squash to serving platter while still warm.",
      "Immediately scatter crumbled goat cheese over warm squash so it softens slightly.",
      "Sprinkle generously with pomegranate arils.",
      "Garnish with fresh mint.",
      "Drizzle with balsamic glaze if desired.",
      "Serve immediately while squash is warm and cheese is soft."
    ],
    tips: "Add goat cheese while squash is still warm so it softens beautifully. Fresh pomegranate arils are worth the effort but you can use packaged. The dish is equally good at room temperature. Make it vegetarian or omit cheese for vegan option.",
    variations: [
      "Use feta instead of goat cheese",
      "Add toasted pistachios",
      "Include fresh basil with mint"
    ],
    tags: ["gluten-free", "delicata squash", "goat cheese", "pomegranate", "roasted", "elegant", "festive", "holiday", "colorful", "vegetarian"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Goat Cheese & Pomegranate - Elegant & Festive",
    seoDescription: "Stunning roasted delicata squash with creamy goat cheese and pomegranate. Perfect holiday side, gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Tahini Maple Sauce",
    slug: "gluten-free-roasted-delicata-squash-tahini-maple-sauce",
    description: "Middle Eastern-inspired — tahini and maple syrup whisked into a drizzle with lemon and sea salt.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Tahini Maple Sauce brings Middle Eastern flavors to autumn vegetables. Roasted squash is drizzled with a creamy sauce made from tahini (sesame seed paste), maple syrup, and fresh lemon juice. The tahini provides rich, nutty depth while the maple adds sweetness and the lemon brightens everything. The combination is unexpectedly perfect - creamy, sweet, tangy, and savory all at once. A sprinkle of sesame seeds adds texture and visual appeal. This is modern, globally-inspired cooking that's both delicious and beautiful. Perfect for those looking to try something different.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "4.8",
    calories: 180,
    protein: "3.5",
    carbs: "26.0",
    fat: "8.0",
    fiber: "3.5",
    sugar: "11.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-tahini-maple-sauce.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into rings",
      "3 tablespoons olive oil",
      "1/3 cup tahini",
      "3 tablespoons pure maple syrup",
      "2 tablespoons fresh lemon juice",
      "2-3 tablespoons water (to thin)",
      "2 tablespoons sesame seeds, toasted",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Toss squash rings with olive oil, salt, and pepper. Arrange in single layer.",
      "Roast 30 minutes, flipping halfway, until golden and tender.",
      "While squash roasts, make tahini maple sauce: whisk together tahini, maple syrup, and lemon juice.",
      "Add water 1 tablespoon at a time until sauce reaches drizzling consistency.",
      "Toast sesame seeds in dry skillet for 2-3 minutes until golden and fragrant.",
      "Transfer roasted squash to serving platter.",
      "Drizzle generously with tahini maple sauce.",
      "Sprinkle with toasted sesame seeds.",
      "Garnish with fresh parsley and serve."
    ],
    tips: "Tahini can vary in thickness - adjust water as needed. The sauce should be pourable but not too thin. Make sauce ahead and store in fridge - bring to room temperature before using. Toast sesame seeds until fragrant but not burnt.",
    variations: [
      "Add cumin to the sauce",
      "Include fresh cilantro",
      "Top with pomegranate seeds"
    ],
    tags: ["gluten-free", "delicata squash", "tahini", "maple", "middle-eastern", "roasted", "modern", "vegan", "fall", "unique"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Tahini Maple Sauce - Modern & Unique",
    seoDescription: "Creative roasted delicata squash with tahini maple drizzle. Middle Eastern-inspired fall side, vegan and gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Cinnamon & Toasted Almonds",
    slug: "gluten-free-roasted-delicata-squash-cinnamon-almonds",
    description: "Lightly spiced with cinnamon and finished with toasted almonds for texture and warmth.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Cinnamon & Toasted Almonds is cozy autumn comfort in every bite. The squash is tossed with warm cinnamon before roasting, allowing the spice to caramelize and create an aromatic coating. Toasted almonds add wonderful crunch and nutty richness. A touch of honey enhances the natural sweetness while a sprinkle of sea salt provides balance. This is the kind of dish that makes your kitchen smell amazing and draws everyone to the table. Simple, wholesome, and absolutely delicious. Perfect for family dinners or meal prep.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    rating: "4.8",
    calories: 170,
    protein: "3.0",
    carbs: "25.0",
    fat: "8.0",
    fiber: "4.0",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-cinnamon-almonds.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced",
      "3 tablespoons olive oil",
      "1.5 teaspoons ground cinnamon",
      "2 tablespoons honey or maple syrup",
      "3/4 cup sliced almonds",
      "1 teaspoon sea salt",
      "1/4 teaspoon nutmeg (optional)",
      "Flaky sea salt for finishing"
    ],
    instructions: [
      "Preheat oven to 425°F. Toast almonds on separate baking sheet for 5-7 minutes until golden. Set aside.",
      "Line baking sheet with parchment paper.",
      "Toss squash with olive oil, cinnamon, honey, salt, and nutmeg if using.",
      "Arrange in single layer on baking sheet.",
      "Roast 15 minutes, then flip and continue roasting 15 more minutes until golden and caramelized.",
      "Transfer to serving platter.",
      "Sprinkle generously with toasted almonds.",
      "Finish with flaky sea salt.",
      "Serve warm."
    ],
    tips: "Toast almonds separately so they don't burn. The cinnamon will caramelize beautifully on the squash edges. Can be made ahead and reheated. Leftovers are delicious cold over salads.",
    variations: [
      "Use pecans instead of almonds",
      "Add a pinch of cardamom",
      "Drizzle with vanilla yogurt"
    ],
    tags: ["gluten-free", "delicata squash", "cinnamon", "almonds", "roasted", "cozy", "fall", "spiced", "simple", "vegan"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Cinnamon & Almonds - Cozy Fall Comfort",
    seoDescription: "Warm spiced delicata squash with cinnamon and toasted almonds. Cozy autumn side dish, naturally gluten-free."
  },
  {
    title: "Gluten-Free Roasted Delicata Squash with Balsamic Apple Glaze",
    slug: "gluten-free-roasted-delicata-squash-balsamic-apple-glaze",
    description: "Roasted and then brushed with a balsamic-apple reduction — glossy, tangy, and rich.",
    longDescription: "This Gluten-Free Roasted Delicata Squash with Balsamic Apple Glaze is sophisticated simplicity at its finest. The squash is roasted until caramelized, then brushed with a glossy reduction made from balsamic vinegar, apple cider, and a touch of honey. The glaze is both sweet and tangy with wonderful depth from the balsamic. As it reduces, it becomes thick and syrupy, creating a gorgeous lacquered coating. The combination of sweet squash and tangy glaze is absolutely delicious. This dish looks and tastes restaurant-quality but is surprisingly easy to make. Perfect for impressing guests or treating yourself.",
    category: "Sides",
    subcategory: "Vegetables",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 40,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 145,
    protein: "1.5",
    carbs: "28.0",
    fat: "4.5",
    fiber: "2.5",
    sugar: "16.0",
    image: "/recipe-images/gluten-free-roasted-delicata-squash-balsamic-apple-glaze.png",
    ingredients: [
      "2 delicata squash, halved, seeded, sliced into rings",
      "2 tablespoons olive oil",
      "1/2 cup balsamic vinegar",
      "1/2 cup apple cider or apple juice",
      "2 tablespoons honey",
      "1 teaspoon sea salt",
      "1/2 teaspoon black pepper",
      "Fresh rosemary for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheet with parchment paper.",
      "Make the glaze: combine balsamic vinegar, apple cider, and honey in small saucepan. Bring to boil, then reduce heat and simmer 15-20 minutes until reduced by half and syrupy. Set aside.",
      "Toss squash rings with olive oil, salt, and pepper.",
      "Arrange in single layer on baking sheet.",
      "Roast 20 minutes, then flip.",
      "Brush squash with half the balsamic-apple glaze.",
      "Return to oven for 10 more minutes until glaze is caramelized and squash is tender.",
      "Transfer to serving platter.",
      "Drizzle with remaining warm glaze.",
      "Garnish with fresh rosemary.",
      "Serve warm or at room temperature."
    ],
    tips: "Use good quality aged balsamic for best flavor. The glaze should coat the back of a spoon when ready. Don't add glaze too early or it will burn. Glaze thickens as it cools. Can make glaze ahead and reheat gently.",
    variations: [
      "Add fresh thyme to glaze",
      "Include apple slices with squash",
      "Top with crumbled blue cheese"
    ],
    tags: ["gluten-free", "delicata squash", "balsamic", "apple glaze", "roasted", "elegant", "glossy", "fall", "sophisticated", "vegan"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Roasted Delicata Squash with Balsamic Apple Glaze - Sophisticated",
    seoDescription: "Elegant roasted delicata squash with glossy balsamic and apple glaze. Restaurant-quality, naturally gluten-free."
  }
];

async function addDelicataSquashRecipes() {
  console.log("Adding 10 Roasted Delicata Squash recipes to database...");
  
  try {
    for (const recipe of delicataSquashRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Roasted Delicata Squash recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addDelicataSquashRecipes();
