import { db } from "../server/db";
import { recipes } from "../shared/schema";

const hamantaschenRecipes = [
  {
    title: "Gluten-Free Classic Apricot Hamantaschen",
    slug: "gluten-free-classic-apricot-hamantaschen",
    description: "The timeless favorite — buttery gluten-free dough filled with sweet-tart apricot preserves.",
    longDescription: "These Gluten-Free Classic Apricot Hamantaschen are the traditional Purim cookies reimagined for gluten-free baking. Tender, buttery dough made with a blend of gluten-free flours creates the perfect vessel for sweet-tart apricot preserves. The iconic triangular shape symbolizes Haman's hat, and these cookies maintain that traditional form beautifully despite being gluten-free. The dough is enriched with eggs, butter, and a touch of vanilla, creating a cookie that's both tender and sturdy enough to hold its shape. The apricot filling provides a perfect balance of sweetness and acidity, complementing the buttery dough. These hamantaschen are perfect for Purim celebrations, Jewish holidays, or any time you want to enjoy a classic cookie with deep cultural roots. The gluten-free flour blend ensures that everyone can enjoy this beloved tradition.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 15,
    totalTime: 45,
    servings: 24,
    rating: "5.0",
    calories: 145,
    protein: "2.0",
    carbs: "22.0",
    fat: "5.5",
    fiber: "0.5",
    sugar: "11.0",
    image: "/recipe-images/hamantaschen-classic-apricot.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "1 tablespoon orange juice",
      "1 cup apricot preserves",
      "1 egg for egg wash",
      "Additional gluten-free flour for rolling"
    ],
    instructions: [
      "In medium bowl, whisk together gluten-free flour, xanthan gum, baking powder, and salt. Set aside.",
      "In large bowl, cream butter and sugar until light and fluffy, about 3 minutes.",
      "Beat in eggs one at a time, then add vanilla and orange juice.",
      "Gradually mix in dry ingredients until dough comes together. Dough will be soft.",
      "Divide dough in half, flatten into disks, wrap in plastic, and refrigerate for at least 2 hours or overnight.",
      "Preheat oven to 350°F. Line baking sheets with parchment paper.",
      "On lightly floured surface, roll out one disk of dough to ⅛-inch thickness.",
      "Cut circles using 3-inch round cutter. Re-roll scraps as needed.",
      "Place 1 teaspoon apricot preserves in center of each circle.",
      "To form triangular shape: fold up three sides of circle, leaving filling visible in center. Pinch corners firmly to seal.",
      "Transfer to prepared baking sheets. Brush dough edges with egg wash.",
      "Bake 12-15 minutes until edges are lightly golden.",
      "Cool on baking sheet 5 minutes, then transfer to wire rack to cool completely."
    ],
    tips: "Keep dough well chilled for easier handling and shaping. If dough becomes too soft while working, return to refrigerator for 15 minutes. Use a light touch when rolling gluten-free dough to prevent cracking. Pinch corners very firmly to prevent cookies from opening during baking.",
    variations: [
      "Add lemon zest to dough for citrus flavor",
      "Mix apricot preserves with a pinch of cinnamon",
      "Brush finished cookies with apricot glaze for extra shine"
    ],
    tags: ["gluten-free", "hamantaschen", "purim", "jewish holiday", "apricot", "traditional", "cookies", "pastries", "holiday baking", "kosher"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Classic Apricot Hamantaschen - Traditional Purim Cookies",
    seoDescription: "Traditional Purim hamantaschen made gluten-free with buttery dough and sweet-tart apricot filling. Perfect triangular holiday cookies."
  },
  {
    title: "Gluten-Free Chocolate Raspberry Hamantaschen",
    slug: "gluten-free-chocolate-raspberry-hamantaschen",
    description: "Decadent cocoa-infused dough filled with raspberry jam and drizzled with dark chocolate.",
    longDescription: "These Gluten-Free Chocolate Raspberry Hamantaschen elevate the traditional Purim cookie to a decadent chocolate dessert that rivals any bakery confection. Rich cocoa powder is incorporated into the gluten-free dough, creating deep chocolate flavor and a beautiful dark color that contrasts gorgeously with the bright red raspberry filling. The chocolate dough maintains the perfect balance of tender and sturdy, holding its triangular shape while remaining soft and cookie-like. Bright, tart raspberry jam provides a fruity counterpoint to the rich chocolate, and a final drizzle of dark chocolate ganache adds an elegant finishing touch. These sophisticated hamantaschen are perfect for chocolate lovers, special celebrations, or when you want to serve something that looks and tastes extraordinary. The combination of chocolate and raspberry is timeless and universally loved.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 15,
    totalTime: 50,
    servings: 24,
    rating: "5.0",
    calories: 165,
    protein: "2.5",
    carbs: "24.0",
    fat: "7.0",
    fiber: "1.0",
    sugar: "13.0",
    image: "/recipe-images/hamantaschen-chocolate-raspberry.png",
    ingredients: [
      "2¼ cups gluten-free all-purpose flour blend",
      "¼ cup unsweetened cocoa powder",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "1 cup raspberry preserves",
      "4 oz dark chocolate, melted (for drizzling)",
      "1 egg for egg wash"
    ],
    instructions: [
      "Whisk together gluten-free flour, cocoa powder, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar until fluffy. Beat in eggs and vanilla.",
      "Gradually mix in dry ingredients until dough forms. Dough will be dark and slightly sticky.",
      "Divide dough in half, flatten into disks, wrap, and refrigerate at least 2 hours.",
      "Preheat oven to 350°F. Line baking sheets with parchment.",
      "Roll out dough on cocoa-dusted surface to ⅛-inch thickness.",
      "Cut 3-inch circles. Place 1 teaspoon raspberry preserves in center of each.",
      "Fold up three sides to form triangle, pinching corners firmly. Leave filling visible.",
      "Brush edges with egg wash. Bake 12-15 minutes until set.",
      "Cool completely on wire rack.",
      "Drizzle melted dark chocolate over cooled cookies in decorative pattern.",
      "Let chocolate set before serving."
    ],
    tips: "Use Dutch-process cocoa for richer chocolate flavor. Make sure dough is well chilled before rolling — chocolate dough can be especially soft. If raspberry preserves are very seedy, strain them first for smoother filling. Let chocolate drizzle set fully before stacking or storing cookies.",
    variations: [
      "Use strawberry or black cherry preserves instead of raspberry",
      "Add mini chocolate chips to the dough",
      "Drizzle with white chocolate for contrast"
    ],
    tags: ["gluten-free", "hamantaschen", "chocolate", "raspberry", "purim", "elegant", "cookies", "pastries", "holiday baking", "decadent"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Chocolate Raspberry Hamantaschen - Decadent Purim Cookies",
    seoDescription: "Rich chocolate hamantaschen filled with raspberry jam and drizzled with dark chocolate. Elegant gluten-free Purim cookies."
  },
  {
    title: "Gluten-Free Lemon Poppyseed Hamantaschen",
    slug: "gluten-free-lemon-poppyseed-hamantaschen",
    description: "Bright and zesty — lemony dough with poppyseed filling for a refreshing twist.",
    longDescription: "These Gluten-Free Lemon Poppyseed Hamantaschen bring bright, sunny citrus flavors to the traditional Purim cookie, making them perfect for spring celebrations or any time you want something light and refreshing. The dough is infused with fresh lemon zest and juice, creating vibrant citrus flavor throughout. The classic poppyseed filling is made with ground poppy seeds, honey, milk, and lemon, creating a paste that's nutty, slightly sweet, and beautifully textured. Poppyseed filling has long been a traditional hamantaschen flavor in Eastern European Jewish communities, and this gluten-free version honors that heritage while adding an extra boost of lemon brightness. The combination of lemony dough and poppyseed filling creates a sophisticated cookie that's not overly sweet, making it perfect for afternoon tea or coffee. These hamantaschen are elegant, distinctive, and absolutely delicious.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 15,
    totalTime: 55,
    servings: 24,
    rating: "4.9",
    calories: 155,
    protein: "3.0",
    carbs: "23.0",
    fat: "6.0",
    fiber: "1.5",
    sugar: "10.0",
    image: "/recipe-images/hamantaschen-lemon-poppyseed.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "Zest of 2 lemons",
      "2 tablespoons fresh lemon juice",
      "1 teaspoon vanilla extract",
      "1 cup poppyseed filling (see filling instructions)",
      "1 egg for egg wash"
    ],
    instructions: [
      "For poppyseed filling: In saucepan, combine ½ cup ground poppy seeds, ½ cup milk, ¼ cup honey, 2 tablespoons sugar, and 1 tablespoon lemon juice. Simmer 10 minutes, stirring, until thick. Cool completely.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar. Beat in eggs, lemon zest, lemon juice, and vanilla.",
      "Mix in dry ingredients until dough forms. Refrigerate 2 hours.",
      "Preheat oven to 350°F. Line baking sheets.",
      "Roll dough to ⅛-inch thickness on floured surface.",
      "Cut 3-inch circles. Place 1 teaspoon poppyseed filling in center.",
      "Form triangles by folding up three sides and pinching corners.",
      "Brush with egg wash. Bake 12-15 minutes until golden.",
      "Cool on wire rack."
    ],
    tips: "Fresh lemon zest makes a huge difference — don't skip it! You can buy prepared poppyseed filling (make sure it's gluten-free) or make your own. If making filling from scratch, grind poppy seeds in spice grinder or food processor first. The filling should be thick and paste-like, not runny.",
    variations: [
      "Add almond extract to the dough for extra depth",
      "Use orange zest instead of lemon for different citrus flavor",
      "Glaze cookies with lemon icing after baking"
    ],
    tags: ["gluten-free", "hamantaschen", "lemon", "poppyseed", "purim", "citrus", "cookies", "pastries", "traditional", "spring"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Lemon Poppyseed Hamantaschen - Bright Citrus Purim Cookies",
    seoDescription: "Bright lemon hamantaschen with traditional poppyseed filling. Refreshing gluten-free Purim cookies with citrus flavor."
  },
  {
    title: "Gluten-Free Pistachio & Honey Hamantaschen",
    slug: "gluten-free-pistachio-honey-hamantaschen",
    description: "Nutty and floral — pistachio-honey paste wrapped in delicate gluten-free pastry.",
    longDescription: "These Gluten-Free Pistachio & Honey Hamantaschen are an elegant, Middle Eastern-inspired take on traditional Purim cookies, combining nutty pistachios with floral honey in a sophisticated filling. The dough itself is delicate and buttery, providing the perfect backdrop for the star attraction: a creamy pistachio-honey paste made from ground pistachios, honey, and a touch of rose water. The filling is vibrant green, beautifully textured, and full of complex flavors — nutty, sweet, and gently floral. These hamantaschen are visually stunning with their pale green filling peeking out from golden pastry triangles. They're perfect for upscale celebrations, gift-giving, or any occasion where you want to serve something truly special. The combination of pistachios and honey has ancient roots in Mediterranean and Middle Eastern cuisine, making these cookies feel both traditional and innovative.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 15,
    totalTime: 50,
    servings: 24,
    rating: "5.0",
    calories: 175,
    protein: "3.5",
    carbs: "21.0",
    fat: "9.0",
    fiber: "1.0",
    sugar: "11.0",
    image: "/recipe-images/hamantaschen-pistachio-honey.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "1 cup shelled pistachios",
      "⅓ cup honey",
      "2 tablespoons butter",
      "½ teaspoon rose water (optional)",
      "Pinch of salt",
      "1 egg for egg wash",
      "Crushed pistachios for garnish"
    ],
    instructions: [
      "For pistachio filling: Pulse pistachios in food processor until finely ground. Add honey, 2 tablespoons butter, rose water, and pinch of salt. Process until smooth paste forms. Refrigerate until needed.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar until fluffy. Beat in eggs and vanilla.",
      "Mix in dry ingredients. Refrigerate dough 2 hours.",
      "Preheat oven to 350°F. Line baking sheets.",
      "Roll dough to ⅛-inch thickness.",
      "Cut 3-inch circles. Place 1 teaspoon pistachio filling in center.",
      "Form triangles, pinching corners firmly.",
      "Brush with egg wash and sprinkle with crushed pistachios.",
      "Bake 12-15 minutes until edges are golden.",
      "Cool on wire rack."
    ],
    tips: "Use raw, unsalted pistachios for best flavor and color. If you can't find rose water, substitute with orange blossom water or omit entirely. The filling should be thick paste consistency — if too thin, add more ground pistachios. These cookies are beautiful when garnished with whole or crushed pistachios on top before baking.",
    variations: [
      "Add cardamom to the pistachio filling for spiced flavor",
      "Use almond extract in the dough",
      "Drizzle with honey glaze after baking"
    ],
    tags: ["gluten-free", "hamantaschen", "pistachio", "honey", "purim", "middle eastern", "elegant", "cookies", "pastries", "nuts"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pistachio & Honey Hamantaschen - Elegant Nutty Purim Cookies",
    seoDescription: "Elegant pistachio and honey hamantaschen with Middle Eastern-inspired flavors. Nutty, floral gluten-free Purim cookies."
  },
  {
    title: "Gluten-Free Date & Orange Blossom Hamantaschen",
    slug: "gluten-free-date-orange-blossom-hamantaschen",
    description: "Middle Eastern-inspired — smooth date filling scented with orange blossom water.",
    longDescription: "These Gluten-Free Date & Orange Blossom Hamantaschen transport traditional Purim cookies to the fragrant souks and ancient markets of the Middle East. The filling is made from sweet Medjool dates blended into a smooth, caramel-like paste and scented with delicate orange blossom water, which adds a floral, citrusy aroma that's intoxicating without being overwhelming. Dates have been a staple sweetener in Middle Eastern cuisine for thousands of years, and their natural sweetness pairs perfectly with the buttery gluten-free pastry. The orange blossom water adds sophistication and exotic appeal. These hamantaschen are deeply flavored, naturally sweet, and have a luxurious texture. They're perfect for those who appreciate dates, love Middle Eastern flavors, or want to try something beautifully different from traditional fruit preserves. The combination is ancient yet innovative, comforting yet exotic.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 15,
    totalTime: 50,
    servings: 24,
    rating: "4.9",
    calories: 160,
    protein: "2.0",
    carbs: "26.0",
    fat: "5.5",
    fiber: "1.5",
    sugar: "15.0",
    image: "/recipe-images/hamantaschen-date-orange-blossom.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "1 tablespoon orange juice",
      "12 oz Medjool dates, pitted",
      "¼ cup water",
      "1 teaspoon orange blossom water",
      "1 tablespoon lemon juice",
      "1 egg for egg wash"
    ],
    instructions: [
      "For date filling: In food processor, combine pitted dates, water, orange blossom water, and lemon juice. Process until smooth paste forms. If too thick, add water 1 tablespoon at a time. Refrigerate until needed.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar until fluffy. Beat in eggs, vanilla, and orange juice.",
      "Mix in dry ingredients until dough forms. Refrigerate 2 hours.",
      "Preheat oven to 350°F. Line baking sheets.",
      "Roll dough to ⅛-inch thickness on floured surface.",
      "Cut 3-inch circles. Place 1 teaspoon date filling in center.",
      "Form triangles by folding three sides up and pinching corners.",
      "Brush with egg wash. Bake 12-15 minutes until golden.",
      "Cool on wire rack."
    ],
    tips: "Use soft, fresh Medjool dates for easiest blending and best flavor. If dates are dry, soak in warm water for 10 minutes before processing. Orange blossom water is potent — start with less and add more to taste. The date filling can be made several days ahead and refrigerated.",
    variations: [
      "Add chopped walnuts to date filling",
      "Use rose water instead of orange blossom water",
      "Add cinnamon and cardamom to filling for spiced version"
    ],
    tags: ["gluten-free", "hamantaschen", "dates", "orange blossom", "purim", "middle eastern", "cookies", "pastries", "exotic", "floral"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Date & Orange Blossom Hamantaschen - Middle Eastern Purim Cookies",
    seoDescription: "Middle Eastern-inspired hamantaschen with smooth date filling and orange blossom water. Exotic gluten-free Purim cookies."
  },
  {
    title: "Gluten-Free Chocolate Hazelnut Hamantaschen",
    slug: "gluten-free-chocolate-hazelnut-hamantaschen",
    description: "Rich and indulgent — filled with hazelnut spread and topped with a sprinkle of sea salt.",
    longDescription: "These Gluten-Free Chocolate Hazelnut Hamantaschen are pure indulgence, featuring a buttery gluten-free dough filled with creamy chocolate-hazelnut spread and finished with a touch of flaky sea salt for sophisticated flavor contrast. The filling is rich, smooth, and intensely chocolatey with nutty hazelnut undertones. As the cookies bake, the chocolate-hazelnut spread becomes warm and slightly molten, creating an irresistible texture. A sprinkle of flaky sea salt on top before baking enhances all the flavors, adding a subtle savory note that makes the chocolate taste even more intense and complex. These hamantaschen are perfect for chocolate lovers, kids and adults alike, and anyone who appreciates the magical combination of chocolate, hazelnuts, and salt. They're decadent enough to serve as dessert but traditional enough for Purim celebrations.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Easy",
    prepTime: 30,
    cookTime: 15,
    totalTime: 45,
    servings: 24,
    rating: "5.0",
    calories: 180,
    protein: "2.5",
    carbs: "23.0",
    fat: "9.0",
    fiber: "1.0",
    sugar: "13.0",
    image: "/recipe-images/hamantaschen-chocolate-hazelnut.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "1 cup chocolate-hazelnut spread (ensure gluten-free)",
      "1 egg for egg wash",
      "Flaky sea salt for topping",
      "Chopped hazelnuts for garnish (optional)"
    ],
    instructions: [
      "Whisk together flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar until light and fluffy.",
      "Beat in eggs and vanilla until well combined.",
      "Gradually mix in dry ingredients until dough forms.",
      "Divide dough in half, flatten into disks, wrap, and refrigerate 2 hours.",
      "Preheat oven to 350°F. Line baking sheets with parchment.",
      "Roll dough to ⅛-inch thickness on lightly floured surface.",
      "Cut 3-inch circles. Place 1 teaspoon chocolate-hazelnut spread in center of each.",
      "Form triangles by folding up three sides, pinching corners firmly.",
      "Brush edges with egg wash. Sprinkle with sea salt and chopped hazelnuts if using.",
      "Bake 12-15 minutes until edges are golden.",
      "Cool on baking sheet 5 minutes (filling will be very hot), then transfer to wire rack."
    ],
    tips: "Don't overfill — chocolate-hazelnut spread melts and can leak during baking. Make sure to pinch corners very firmly. The filling will be molten hot when cookies come out of oven — let cool before eating. Use good quality chocolate-hazelnut spread for best flavor.",
    variations: [
      "Use almond butter or sunflower seed butter for nut-free version",
      "Add mini chocolate chips on top before baking",
      "Dust with powdered sugar instead of sea salt"
    ],
    tags: ["gluten-free", "hamantaschen", "chocolate", "hazelnut", "purim", "indulgent", "cookies", "pastries", "sea salt", "decadent"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Chocolate Hazelnut Hamantaschen - Indulgent Purim Cookies",
    seoDescription: "Rich chocolate-hazelnut hamantaschen with sea salt. Indulgent gluten-free Purim cookies perfect for chocolate lovers."
  },
  {
    title: "Gluten-Free Blueberry Cheesecake Hamantaschen",
    slug: "gluten-free-blueberry-cheesecake-hamantaschen",
    description: "Creamy cheesecake-style filling with blueberry swirl — dessert meets tradition.",
    longDescription: "These Gluten-Free Blueberry Cheesecake Hamantaschen transform the traditional Purim cookie into an elegant dessert that rivals any bakery cheesecake. The filling is a creamy blend of cream cheese, sugar, and vanilla that's enriched with egg for structure, creating a true cheesecake texture that sets as it bakes. Swirled through the cream cheese filling is bright blueberry preserves, adding fruity sweetness and beautiful purple-blue color. As these hamantaschen bake, the cheesecake filling firms up while remaining incredibly creamy, and the blueberry swirl intensifies in flavor. The result is a cookie that tastes like individual mini cheesecakes in portable form. These are perfect for special occasions, dessert tables, or anytime you want to elevate the hamantaschen experience. They're sophisticated, delicious, and absolutely stunning to look at with their marbled filling.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 18,
    totalTime: 58,
    servings: 24,
    rating: "5.0",
    calories: 170,
    protein: "3.0",
    carbs: "22.0",
    fat: "8.0",
    fiber: "0.5",
    sugar: "12.0",
    image: "/recipe-images/hamantaschen-blueberry-cheesecake.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "8 oz cream cheese, softened",
      "¼ cup granulated sugar",
      "1 large egg yolk",
      "1 teaspoon vanilla extract",
      "½ cup blueberry preserves",
      "1 egg for egg wash"
    ],
    instructions: [
      "For cheesecake filling: Beat cream cheese, ¼ cup sugar, egg yolk, and 1 teaspoon vanilla until smooth. Refrigerate until needed.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and ¾ cup sugar. Beat in 2 eggs and 2 teaspoons vanilla.",
      "Mix in dry ingredients. Refrigerate dough 2 hours.",
      "Preheat oven to 325°F (lower temp for cheesecake filling). Line baking sheets.",
      "Roll dough to ⅛-inch thickness.",
      "Cut 3-inch circles. Place 1 teaspoon cheesecake filling in center of each.",
      "Add small dollop of blueberry preserves on top and gently swirl with toothpick.",
      "Form triangles, pinching corners firmly.",
      "Brush edges with egg wash. Bake 15-18 minutes until edges are golden and filling is set.",
      "Cool completely on wire rack. Refrigerate until serving."
    ],
    tips: "Bake at lower temperature (325°F) to prevent cheesecake filling from cracking or browning too much. Don't overfill — the filling will expand slightly during baking. These are best stored in the refrigerator due to the cream cheese filling. Serve chilled or at room temperature.",
    variations: [
      "Use raspberry, strawberry, or cherry preserves instead of blueberry",
      "Add lemon zest to cheesecake filling",
      "Top with fresh blueberries before serving"
    ],
    tags: ["gluten-free", "hamantaschen", "cheesecake", "blueberry", "purim", "elegant", "cookies", "pastries", "dessert", "cream cheese"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Blueberry Cheesecake Hamantaschen - Elegant Purim Dessert Cookies",
    seoDescription: "Elegant cheesecake-filled hamantaschen with blueberry swirl. Creamy, decadent gluten-free Purim cookies."
  },
  {
    title: "Gluten-Free Cinnamon Apple Hamantaschen",
    slug: "gluten-free-cinnamon-apple-hamantaschen",
    description: "Warm, cozy flavors — apple-cinnamon compote tucked into tender pastry.",
    longDescription: "These Gluten-Free Cinnamon Apple Hamantaschen bring all the warmth and comfort of apple pie to the traditional Purim cookie format. The filling is a homemade apple-cinnamon compote made by cooking fresh apples with cinnamon, sugar, and a touch of lemon juice until they're tender and jammy. The apples break down into a chunky, spiced filling that's reminiscent of the best apple pie filling but concentrated and intensified. The buttery gluten-free dough provides the perfect complement to the warm spice and fruit flavors. These hamantaschen smell incredible while baking — your kitchen will be filled with the cozy aroma of cinnamon and baked apples. They're perfect for fall and winter celebrations, Rosh Hashanah (apples and honey are traditional), or anytime you want something that tastes like a warm hug. The combination of tender apples, warming cinnamon, and buttery pastry is timeless and universally loved.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 15,
    totalTime: 55,
    servings: 24,
    rating: "4.9",
    calories: 150,
    protein: "2.0",
    carbs: "24.0",
    fat: "5.5",
    fiber: "1.0",
    sugar: "12.0",
    image: "/recipe-images/hamantaschen-cinnamon-apple.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "3 medium apples, peeled and diced small",
      "¼ cup brown sugar",
      "1 tablespoon lemon juice",
      "1½ teaspoons cinnamon",
      "2 tablespoons butter",
      "1 egg for egg wash",
      "Cinnamon sugar for sprinkling"
    ],
    instructions: [
      "For apple filling: In saucepan, melt 2 tablespoons butter. Add diced apples, brown sugar, lemon juice, and cinnamon. Cook over medium heat 10-12 minutes, stirring occasionally, until apples are tender and mixture is thick. Cool completely.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream ½ cup butter and granulated sugar. Beat in eggs and vanilla.",
      "Mix in dry ingredients. Refrigerate dough 2 hours.",
      "Preheat oven to 350°F. Line baking sheets.",
      "Roll dough to ⅛-inch thickness.",
      "Cut 3-inch circles. Place 1 teaspoon apple filling in center of each.",
      "Form triangles, pinching corners firmly.",
      "Brush with egg wash and sprinkle with cinnamon sugar.",
      "Bake 12-15 minutes until golden.",
      "Cool on wire rack."
    ],
    tips: "Dice apples small so they cook down into a jam-like consistency. If apple filling is too liquidy, continue cooking until most moisture evaporates. The filling should be thick enough to stay in place. Use firm, tart apples like Granny Smith for best flavor and texture. The cinnamon sugar topping adds extra flavor and pretty sparkle.",
    variations: [
      "Add chopped walnuts or pecans to filling",
      "Use apple pie spice instead of just cinnamon",
      "Drizzle with caramel sauce after baking"
    ],
    tags: ["gluten-free", "hamantaschen", "apple", "cinnamon", "purim", "fall", "cookies", "pastries", "cozy", "spiced"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cinnamon Apple Hamantaschen - Cozy Spiced Purim Cookies",
    seoDescription: "Warm cinnamon apple hamantaschen with homemade apple compote filling. Cozy, spiced gluten-free Purim cookies."
  },
  {
    title: "Gluten-Free Savory Feta & Spinach Hamantaschen",
    slug: "gluten-free-savory-feta-spinach-hamantaschen",
    description: "A Mediterranean-inspired savory take — spinach, feta, and herbs in crisp gluten-free dough.",
    longDescription: "These Gluten-Free Savory Feta & Spinach Hamantaschen break from sweet tradition to create a sophisticated savory appetizer that's perfect for parties, brunches, or anytime you want something elegant and different. The dough is adapted to be less sweet, with reduced sugar and the addition of herbs, creating a pastry that's perfect for savory fillings. The filling combines sautéed spinach with crumbled feta cheese, garlic, and fresh herbs for a Mediterranean-inspired flavor profile that's tangy, herbaceous, and absolutely delicious. As the hamantaschen bake, the feta becomes creamy and the spinach intensifies in flavor. These savory hamantaschen challenge expectations while honoring the traditional triangular form, making them conversation starters as well as crowd pleasers. They're perfect served warm as appetizers, alongside soups and salads, or as part of a brunch spread.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 18,
    totalTime: 53,
    servings: 24,
    rating: "4.8",
    calories: 125,
    protein: "4.0",
    carbs: "15.0",
    fat: "6.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/hamantaschen-savory-feta-spinach.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "1 teaspoon salt",
      "½ cup unsalted butter, softened",
      "¼ cup granulated sugar",
      "2 large eggs",
      "2 tablespoons fresh dill, chopped",
      "10 oz frozen spinach, thawed and squeezed dry",
      "6 oz feta cheese, crumbled",
      "2 cloves garlic, minced",
      "2 tablespoons olive oil",
      "¼ teaspoon black pepper",
      "¼ teaspoon nutmeg",
      "1 egg for egg wash",
      "Sesame seeds for topping"
    ],
    instructions: [
      "For filling: Heat olive oil in skillet. Sauté garlic 30 seconds. Add squeezed spinach, pepper, and nutmeg. Cook 3-4 minutes. Remove from heat and let cool. Mix in crumbled feta.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar (less sweet than dessert version). Beat in eggs and dill.",
      "Mix in dry ingredients. Refrigerate dough 2 hours.",
      "Preheat oven to 375°F. Line baking sheets.",
      "Roll dough to ⅛-inch thickness.",
      "Cut 3-inch circles. Place 1 heaping teaspoon spinach-feta filling in center.",
      "Form triangles, pinching corners very firmly (savory filling can be more prone to leaking).",
      "Brush with egg wash and sprinkle with sesame seeds.",
      "Bake 15-18 minutes until golden brown.",
      "Serve warm or at room temperature."
    ],
    tips: "Squeeze spinach very dry — excess moisture will make filling leak and soggy. The spinach-feta filling can be made a day ahead and refrigerated. These are best served warm or at room temperature, not cold. Reheat gently in oven before serving if made ahead.",
    variations: [
      "Add sun-dried tomatoes to filling",
      "Use ricotta instead of or in addition to feta",
      "Add pine nuts to filling for crunch"
    ],
    tags: ["gluten-free", "hamantaschen", "savory", "feta", "spinach", "mediterranean", "appetizer", "pastries", "party food", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Savory Feta & Spinach Hamantaschen - Mediterranean Appetizer",
    seoDescription: "Savory feta and spinach hamantaschen with Mediterranean flavors. Unique gluten-free savory appetizers."
  },
  {
    title: "Gluten-Free Caramel & Sea Salt Hamantaschen",
    slug: "gluten-free-caramel-sea-salt-hamantaschen",
    description: "Sweet and modern — soft caramel center sprinkled with flaky sea salt.",
    longDescription: "These Gluten-Free Caramel & Sea Salt Hamantaschen are a modern, sophisticated take on traditional Purim cookies, featuring the wildly popular combination of sweet caramel and flaky sea salt. The filling is soft, chewy caramel — either homemade or high-quality store-bought caramel candies that melt during baking. As the cookies bake, the caramel becomes gooey and molten, creating an irresistible texture contrast with the crisp, buttery cookie edges. A sprinkle of flaky sea salt on top before baking adds the perfect savory counterpoint, making the caramel taste even sweeter and more complex. The salt also adds a pleasant textural crunch. These hamantaschen are perfect for those who love salted caramels, modern flavor combinations, or want to serve something that feels current and trend-forward while still honoring tradition. They're indulgent, beautiful, and absolutely addictive.",
    category: "Desserts",
    subcategory: "Cookies & Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 15,
    totalTime: 50,
    servings: 24,
    rating: "5.0",
    calories: 170,
    protein: "2.0",
    carbs: "25.0",
    fat: "7.0",
    fiber: "0.5",
    sugar: "15.0",
    image: "/recipe-images/hamantaschen-caramel-sea-salt.png",
    ingredients: [
      "2½ cups gluten-free all-purpose flour blend",
      "1 teaspoon xanthan gum (if not in flour blend)",
      "½ teaspoon baking powder",
      "¼ teaspoon salt",
      "½ cup unsalted butter, softened",
      "¾ cup granulated sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "24 soft caramel candies (or ¾ cup homemade caramel)",
      "1 egg for egg wash",
      "Flaky sea salt for topping",
      "Additional caramel for drizzling (optional)"
    ],
    instructions: [
      "If using caramel candies, unwrap them. If making homemade caramel, prepare and let cool to thick but still soft consistency.",
      "For dough: Whisk flour, xanthan gum, baking powder, and salt.",
      "Cream butter and sugar until fluffy. Beat in eggs and vanilla.",
      "Mix in dry ingredients until dough forms. Refrigerate 2 hours.",
      "Preheat oven to 350°F. Line baking sheets with parchment.",
      "Roll dough to ⅛-inch thickness.",
      "Cut 3-inch circles. Place one caramel candy (or 1 teaspoon caramel) in center of each.",
      "Form triangles, pinching corners very firmly to prevent caramel leakage.",
      "Brush edges with egg wash. Sprinkle generously with flaky sea salt.",
      "Bake 12-15 minutes until edges are golden.",
      "Cool on baking sheet 10 minutes (caramel will be molten hot), then carefully transfer to wire rack.",
      "Optional: Drizzle with additional caramel once cooled."
    ],
    tips: "Pinch corners extremely firmly — caramel can leak during baking. Let cookies cool on baking sheet before moving as caramel will be dangerously hot. Use soft caramels, not hard caramel candies. If caramel does leak, it will form delicious crispy edges. The flaky sea salt is key — don't use regular table salt.",
    variations: [
      "Add chocolate chips on top of caramel before folding",
      "Use dulce de leche instead of caramel",
      "Drizzle with dark chocolate after baking"
    ],
    tags: ["gluten-free", "hamantaschen", "caramel", "sea salt", "purim", "modern", "cookies", "pastries", "sweet salty", "indulgent"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramel & Sea Salt Hamantaschen - Modern Sweet Salty Purim Cookies",
    seoDescription: "Modern caramel and sea salt hamantaschen with gooey filling. Sweet and salty gluten-free Purim cookies."
  }
];

async function seed() {
  try {
    await db
      .insert(recipes)
      .values(hamantaschenRecipes)
      .onConflictDoNothing({ target: [recipes.slug] });
    
    console.log(`Successfully added ${hamantaschenRecipes.length} gluten-free hamantaschen recipes to the database!`);
    console.log("All recipes have been inserted under Desserts → Cookies & Pastries category.");
  } catch (error) {
    console.error("Error adding recipes:", error);
    throw error;
  }
}

seed()
  .then(() => {
    console.log("Seed completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
