import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const saagPaneerRecipes = [
  {
    title: "Gluten-Free Saag Paneer with Garlic & Ginger",
    slug: "gluten-free-saag-paneer-garlic-ginger",
    seoTitle: "Gluten-Free Saag Paneer with Garlic & Ginger - Classic Indian Comfort",
    description: "Classic version with aromatic garlic, fresh ginger, and cream — smooth, rich, and comforting traditional saag paneer.",
    longDescription: "This gluten-free saag paneer is the classic North Indian dish that has comforted generations with its creamy spinach curry and golden paneer cubes. Fresh spinach is blanched and blended into a smooth, vibrant green purée, then simmered with aromatic garlic and ginger. The combination creates layers of flavor — earthy spinach, pungent garlic, and warming ginger all come together in perfect harmony. Paneer cubes are lightly fried until golden before being added to the curry, creating textural contrast. Cream and butter add richness, while traditional spices like garam masala and cumin provide authentic flavor. This is comfort food at its finest — warming, nourishing, and deeply satisfying. Serve with basmati rice or gluten-free naan for a complete meal.",
    seoDescription: "Gluten-free saag paneer with garlic and ginger. Classic Indian spinach curry with golden paneer, aromatic spices, and rich cream.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-saag-paneer-garlic-ginger.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach (or 10 oz frozen)",
      "1 tablespoon fresh ginger, grated",
      "6 cloves garlic, minced",
      "1 onion, finely chopped",
      "2 green chilies, chopped (optional)",
      "3 tablespoons ghee or butter",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "1/4 cup heavy cream",
      "Salt to taste",
      "Fresh coriander for garnish",
      "Lemon wedges for serving"
    ],
    instructions: [
      "If using fresh spinach, blanch in boiling water for 2 minutes. Drain and immediately transfer to ice water. Or microwave for 2-3 minutes. Squeeze out excess water and chop.",
      "Blend spinach with 1/4 cup water until smooth. Set aside.",
      "Heat 2 tablespoons ghee in a pan over medium-high heat. Lightly fry paneer cubes until golden on all sides, about 3-4 minutes. Remove and set aside.",
      "In the same pan, add remaining ghee. Add cumin seeds and let sizzle for 30 seconds.",
      "Add onion and sauté for 5 minutes until soft. Add ginger, garlic, and green chilies. Cook for 2 minutes.",
      "Add turmeric and garam masala. Stir for 30 seconds.",
      "Pour in the spinach purée. Simmer for 8-10 minutes, stirring occasionally.",
      "Stir in cream and season with salt. Cook for 2 more minutes.",
      "Add fried paneer cubes and gently mix. Cook for 2 minutes to heat through.",
      "Garnish with fresh coriander and serve with rice or gluten-free naan."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "spinach", "paneer", "garlic", "ginger", "comfort food", "Punjabi"],
    nutrition: {
      calories: 380,
      protein: "18g",
      carbs: "12g",
      fat: "30g",
      fiber: "4g",
      sodium: "520mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Coconut Saag Paneer",
    slug: "gluten-free-coconut-saag-paneer",
    seoTitle: "Gluten-Free Coconut Saag Paneer - South Indian Fusion",
    description: "South Indian-inspired variation made with coconut milk for subtle sweetness and silky texture — creamy and aromatic.",
    longDescription: "This gluten-free coconut saag paneer is a South Indian-inspired twist on the classic, using coconut milk to create an incredibly silky, slightly sweet curry. The coconut milk adds richness without heaviness and brings a tropical note that complements the earthy spinach beautifully. Curry leaves and a touch of ginger add authentic South Indian flavor, while the paneer provides protein and textural contrast. This version is slightly lighter than the traditional cream-based saag, making it perfect for warm weather or when you want something that's rich but not overwhelming. The coconut flavor is subtle — it enhances rather than overpowers the spinach. This is a beautiful fusion that respects both North and South Indian culinary traditions.",
    seoDescription: "Gluten-free coconut saag paneer with silky coconut milk. South Indian fusion spinach curry with golden paneer and curry leaves.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-coconut-saag-paneer.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach",
      "1 can (13.5 oz) coconut milk",
      "1 tablespoon fresh ginger, grated",
      "4 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies, chopped",
      "10-12 curry leaves",
      "2 tablespoons coconut oil",
      "1 teaspoon cumin seeds",
      "1 teaspoon coriander powder",
      "1/2 teaspoon turmeric",
      "Salt to taste",
      "Fresh cilantro and coconut flakes for garnish"
    ],
    instructions: [
      "Blanch or microwave spinach. Squeeze out water and blend until smooth with 2 tablespoons water.",
      "Heat coconut oil in a pan. Fry paneer cubes until golden. Remove and set aside.",
      "In the same pan, add cumin seeds and curry leaves. Let sizzle for 30 seconds.",
      "Add onion and sauté for 5 minutes. Add ginger, garlic, and chilies. Cook for 2 minutes.",
      "Add turmeric and coriander powder. Stir for 30 seconds.",
      "Add spinach purée and simmer for 8 minutes.",
      "Pour in coconut milk and stir well. Simmer for 5 more minutes.",
      "Season with salt.",
      "Add paneer cubes and cook for 2 minutes.",
      "Garnish with cilantro and coconut flakes. Serve hot."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "coconut", "South Indian", "fusion", "curry leaves", "spinach", "dairy-light"],
    nutrition: {
      calories: 420,
      protein: "17g",
      carbs: "14g",
      fat: "35g",
      fiber: "4g",
      sodium: "480mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Kale & Mustard Greens",
    slug: "gluten-free-saag-paneer-kale-mustard-greens",
    seoTitle: "Gluten-Free Saag Paneer with Kale & Mustard Greens - Nutrient-Rich",
    description: "Mix of spinach, kale, and mustard greens for earthy, robust flavor — nutrient-rich and vibrant Indian curry.",
    longDescription: "This gluten-free saag paneer takes the traditional recipe and amplifies the nutrition and flavor by incorporating kale and mustard greens alongside spinach. The combination creates a more complex, slightly bitter, deeply earthy curry that's incredibly nutritious. Mustard greens add a subtle peppery note, while kale contributes heartiness and texture. The mix of greens is blanched together, then blended into a chunky purée that maintains some texture rather than being completely smooth. This version is for those who love robust, verdant flavors and want maximum nutritional value. The slightly bitter greens are balanced by cream and spices, creating a sophisticated dish that's both healthy and indulgent.",
    seoDescription: "Gluten-free saag paneer with kale and mustard greens. Nutrient-rich Indian curry with mixed greens, golden paneer, and aromatic spices.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-saag-paneer-kale-mustard-greens.png",
    ingredients: [
      "14 oz paneer, cubed",
      "8 oz fresh spinach",
      "8 oz kale, stems removed",
      "4 oz mustard greens",
      "1 tablespoon ginger, grated",
      "5 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons ghee",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "1/4 cup cream or yogurt",
      "Salt to taste",
      "Lemon juice for finishing"
    ],
    instructions: [
      "Blanch all greens (spinach, kale, mustard) together in boiling water for 3-4 minutes. Drain and transfer to ice water.",
      "Squeeze out excess water and roughly blend, keeping some texture.",
      "Heat 2 tablespoons ghee. Fry paneer until golden. Remove and set aside.",
      "Add remaining ghee and cumin seeds. Let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add turmeric and garam masala. Stir.",
      "Add greens purée and simmer for 10 minutes.",
      "Stir in cream or yogurt. Season with salt.",
      "Add paneer and cook for 2 minutes.",
      "Finish with a squeeze of lemon juice. Serve hot."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "kale", "mustard greens", "nutrient-rich", "healthy", "mixed greens", "robust"],
    nutrition: {
      calories: 370,
      protein: "19g",
      carbs: "15g",
      fat: "28g",
      fiber: "6g",
      sodium: "540mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Spiced Cashew Cream",
    slug: "gluten-free-saag-paneer-spiced-cashew-cream",
    seoTitle: "Gluten-Free Saag Paneer with Cashew Cream - Dairy-Light Luxury",
    description: "Dairy-light version with creamy cashew base — rich, nutty, and can be made vegan-friendly with tofu.",
    longDescription: "This gluten-free saag paneer features a luxurious cashew cream that creates richness without heavy dairy. Raw cashews are soaked and blended until silky smooth, then stirred into the spinach curry to create a velvety texture and subtle nutty flavor. The cashew cream is lighter than traditional cream but just as satisfying, making this version perfect for those who are dairy-sensitive or simply want something a bit lighter. Whole spices are toasted before grinding to intensify their flavors, and the cashews add protein along with creaminess. For a fully vegan version, replace the paneer with firm tofu. This is sophisticated Indian comfort food that proves you don't need heavy cream to create luxurious texture.",
    seoDescription: "Gluten-free saag paneer with spiced cashew cream. Dairy-light Indian spinach curry with golden paneer and silky cashew base.",
    category: "Entrees",
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-saag-paneer-spiced-cashew-cream.png",
    ingredients: [
      "14 oz paneer, cubed (or firm tofu for vegan)",
      "1 lb fresh spinach",
      "1/2 cup raw cashews, soaked 2 hours",
      "1 tablespoon ginger, grated",
      "5 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons oil",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon coriander powder",
      "1/2 teaspoon turmeric",
      "Salt to taste",
      "Crushed cashews and cilantro for garnish"
    ],
    instructions: [
      "Drain soaked cashews and blend with 1/2 cup water until completely smooth. Set aside.",
      "Blanch or microwave spinach. Squeeze out water and blend until smooth.",
      "Heat 2 tablespoons oil. Fry paneer (or tofu) until golden. Remove and set aside.",
      "Heat remaining oil. Add cumin seeds and let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add turmeric, coriander, and garam masala. Stir for 30 seconds.",
      "Add spinach purée and simmer for 8 minutes.",
      "Stir in cashew cream and cook for 5 more minutes.",
      "Season with salt.",
      "Add paneer and heat through for 2 minutes.",
      "Garnish with crushed cashews and cilantro."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "cashew cream", "dairy-light", "vegan option", "nutty", "luxury", "healthy"],
    nutrition: {
      calories: 400,
      protein: "18g",
      carbs: "16g",
      fat: "32g",
      fiber: "5g",
      sodium: "500mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Tomatoes & Cumin",
    slug: "gluten-free-saag-paneer-tomatoes-cumin",
    seoTitle: "Gluten-Free Saag Paneer with Tomatoes & Cumin - Bright & Tangy",
    description: "Bright and tangy — fresh tomatoes and toasted cumin bring a lighter, more acidic balance to classic saag.",
    longDescription: "This gluten-free saag paneer gets a bright, tangy twist from fresh tomatoes and aromatic toasted cumin. The tomatoes are added in two stages — some cooked down into the base for depth, and fresh ones added at the end for brightness and acidity. Cumin seeds are toasted until fragrant before being ground, releasing their essential oils and creating incredible aromatic depth. The result is a lighter, more acidic version of saag that's refreshing and vibrant. The tomatoes balance the richness of the paneer and add beautiful color to the green curry. This version is perfect for warm weather or when you want the comfort of saag with a brighter, fresher profile. It's familiar yet excitingly different.",
    seoDescription: "Gluten-free saag paneer with tomatoes and toasted cumin. Bright, tangy Indian spinach curry with fresh tomatoes and aromatic spices.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-saag-paneer-tomatoes-cumin.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach",
      "3 medium tomatoes, chopped (divided)",
      "1 tablespoon fresh ginger, grated",
      "4 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons ghee or oil",
      "2 teaspoons cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "1/4 cup yogurt or cream",
      "Salt to taste",
      "Fresh cilantro for garnish"
    ],
    instructions: [
      "Toast 1 teaspoon cumin seeds in a dry pan until fragrant. Grind and set aside.",
      "Blanch spinach, squeeze out water, and blend until smooth.",
      "Heat 2 tablespoons ghee. Fry paneer until golden. Remove and set aside.",
      "Add remaining ghee and remaining cumin seeds. Let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add 2/3 of the chopped tomatoes. Cook for 5-6 minutes until soft and breaking down.",
      "Add turmeric, garam masala, and ground toasted cumin. Stir.",
      "Add spinach purée and simmer for 8 minutes.",
      "Stir in yogurt or cream. Season with salt.",
      "Add paneer and remaining fresh tomatoes. Cook for 2-3 minutes.",
      "Garnish with cilantro and serve."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "tomatoes", "cumin", "tangy", "bright", "fresh", "lighter"],
    nutrition: {
      calories: 360,
      protein: "18g",
      carbs: "16g",
      fat: "27g",
      fiber: "5g",
      sodium: "510mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Fenugreek Leaves (Methi Saag)",
    slug: "gluten-free-saag-paneer-fenugreek-methi",
    seoTitle: "Gluten-Free Methi Saag Paneer with Fenugreek - Authentic Punjabi",
    description: "Traditional Punjabi-style with fenugreek leaves for distinct, aromatic depth of flavor — authentic and herbaceous.",
    longDescription: "This gluten-free methi saag paneer is the most traditional Punjabi version, featuring fresh or dried fenugreek leaves (methi) that add a distinctive bitter-sweet, highly aromatic flavor. Fenugreek is a classic ingredient in saag, and once you taste it, you'll understand why it's so beloved in North Indian cuisine. The leaves have a unique fragrance that's both sweet and slightly bitter, creating incredible depth. Fresh fenugreek is added along with the spinach, while dried kasuri methi is crushed and stirred in at the end for an extra layer of flavor. This is the saag that Indian grandmothers make — deeply flavorful, aromatic, and utterly authentic. It's comfort food with centuries of tradition behind it.",
    seoDescription: "Gluten-free methi saag paneer with fenugreek leaves. Traditional Punjabi spinach curry with aromatic fenugreek and golden paneer.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-saag-paneer-fenugreek-methi.png",
    ingredients: [
      "14 oz paneer, cubed",
      "12 oz fresh spinach",
      "1 cup fresh fenugreek leaves (methi) or 2 tablespoons dried kasuri methi",
      "1 tablespoon ginger, grated",
      "6 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons ghee",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "1/4 cup heavy cream",
      "1 tablespoon dried kasuri methi (in addition to fresh)",
      "Salt to taste"
    ],
    instructions: [
      "If using fresh fenugreek, remove stems and chop leaves. Blanch together with spinach for 2-3 minutes.",
      "Drain, squeeze out water, and blend into a slightly chunky purée.",
      "Heat 2 tablespoons ghee. Fry paneer until golden. Remove and set aside.",
      "Add remaining ghee and cumin seeds. Let sizzle.",
      "Add onion and cook for 5-6 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add turmeric and garam masala. Stir.",
      "Add spinach-fenugreek purée and simmer for 10 minutes.",
      "Crush dried kasuri methi between your palms and add to the curry. Stir well.",
      "Add cream and season with salt.",
      "Add paneer and cook for 2-3 minutes.",
      "Serve hot with butter on top."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "fenugreek", "methi", "Punjabi", "traditional", "authentic", "aromatic"],
    nutrition: {
      calories: 390,
      protein: "19g",
      carbs: "14g",
      fat: "30g",
      fiber: "5g",
      sodium: "530mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Yogurt & Lemon",
    slug: "gluten-free-saag-paneer-yogurt-lemon",
    seoTitle: "Gluten-Free Saag Paneer with Yogurt & Lemon - Light & Refreshing",
    description: "Lightened up with tangy yogurt and squeeze of lemon — refreshing, bright, and lighter than traditional versions.",
    longDescription: "This gluten-free saag paneer is a lighter, brighter take on the classic, using tangy yogurt instead of cream and finishing with fresh lemon juice. The yogurt adds protein and probiotics along with a pleasant tanginess that cuts through the richness of the paneer. Lemon juice brightened everything up, adding a citrus note that makes this version feel fresh and springlike. Greek yogurt works particularly well because it's thick and creamy, creating richness without heaviness. This is perfect for warm weather or when you want the comfort of saag without feeling weighed down. It's still indulgent and satisfying, but with a lighter, fresher profile that makes you want to come back for seconds.",
    seoDescription: "Gluten-free saag paneer with yogurt and lemon. Light, refreshing Indian spinach curry with tangy yogurt and bright citrus.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-saag-paneer-yogurt-lemon.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach",
      "1/2 cup Greek yogurt",
      "Juice of 1 lemon",
      "1 tablespoon ginger, grated",
      "4 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons oil or ghee",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "Salt to taste",
      "Fresh cilantro and lemon wedges for garnish"
    ],
    instructions: [
      "Blanch or microwave spinach. Squeeze out water and blend until smooth.",
      "Heat 2 tablespoons oil. Fry paneer until golden. Remove and set aside.",
      "Add remaining oil and cumin seeds. Let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add turmeric and garam masala. Stir.",
      "Add spinach purée and simmer for 8 minutes.",
      "Remove from heat. Whisk in yogurt gradually to prevent curdling.",
      "Return to low heat and cook for 3 minutes.",
      "Season with salt and stir in lemon juice.",
      "Add paneer and heat through for 2 minutes.",
      "Garnish with cilantro and serve with lemon wedges."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "yogurt", "lemon", "light", "fresh", "tangy", "healthy"],
    nutrition: {
      calories: 340,
      protein: "20g",
      carbs: "14g",
      fat: "24g",
      fiber: "4g",
      sodium: "490mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Saag Paneer with Roasted Garlic & Onions",
    slug: "gluten-free-saag-paneer-roasted-garlic-onions",
    seoTitle: "Gluten-Free Saag Paneer with Roasted Garlic - Smoky & Sweet",
    description: "Smoky roasted garlic and caramelized onions add sweetness and complexity to the creamy spinach base.",
    longDescription: "This gluten-free saag paneer takes the dish to gourmet levels with roasted garlic and deeply caramelized onions. Whole garlic cloves are roasted until soft, sweet, and caramelized, then mashed into a paste that adds incredible depth. Onions are cooked slowly until deeply browned and sweet, creating a rich, complex base for the spinach curry. The combination of roasted garlic and caramelized onions adds layers of sweetness and smokiness that make this version particularly special. It takes a bit more time than the standard recipe, but the depth of flavor is worth every minute. This is the saag to make when you want to impress or treat yourself to something truly exceptional.",
    seoDescription: "Gluten-free saag paneer with roasted garlic and caramelized onions. Smoky, sweet Indian spinach curry with deep complex flavors.",
    category: "Entrees",
    prepTime: 30,
    cookTime: 35,
    totalTime: 65,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-saag-paneer-roasted-garlic-onions.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach",
      "1 head garlic, cloves separated",
      "2 large onions, sliced",
      "1 tablespoon ginger, grated",
      "2 green chilies",
      "4 tablespoons ghee or butter, divided",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "1/4 cup heavy cream",
      "Salt to taste",
      "Fresh herbs for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F. Toss garlic cloves (unpeeled) with 1 tablespoon oil, wrap in foil, and roast for 20 minutes until soft. Squeeze out cloves and mash.",
      "Blanch spinach, squeeze water, and blend until smooth.",
      "Heat 2 tablespoons ghee. Fry paneer until golden. Remove and set aside.",
      "In the same pan, add 1 tablespoon ghee. Cook sliced onions over medium-low heat for 15-20 minutes, stirring often, until deeply caramelized.",
      "Add ginger and chilies. Cook 2 minutes.",
      "Add mashed roasted garlic, cumin seeds, turmeric, and garam masala. Stir well.",
      "Add spinach purée and simmer for 8-10 minutes.",
      "Stir in cream and season with salt.",
      "Add paneer and cook for 2 minutes.",
      "Serve garnished with fresh herbs."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "roasted garlic", "caramelized onions", "gourmet", "complex", "smoky", "sweet"],
    nutrition: {
      calories: 410,
      protein: "18g",
      carbs: "18g",
      fat: "32g",
      fiber: "5g",
      sodium: "520mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Spicy Saag Paneer with Green Chilies",
    slug: "gluten-free-spicy-saag-paneer-green-chilies",
    seoTitle: "Gluten-Free Spicy Saag Paneer - Fiery & Bold",
    description: "A fiery variation with green chilies, coriander, and garam masala — for spice lovers who want heat.",
    longDescription: "This gluten-free spicy saag paneer is for those who like their food with serious heat. Fresh green chilies are used generously — some cooked into the base for depth, others added fresh at the end for sharp, bright heat. Extra garam masala and a generous amount of black pepper add layers of warmth, while fresh coriander provides cooling brightness. The heat doesn't mask the other flavors; it enhances them, making you more aware of the earthy spinach, aromatic ginger, and rich paneer. This is bold, assertive comfort food for spice lovers. Serve with cooling raita and plenty of rice or naan to balance the heat. It's addictively spicy — you'll keep going back for more despite the fire.",
    seoDescription: "Gluten-free spicy saag paneer with green chilies and garam masala. Fiery Indian spinach curry for spice lovers with bold flavors.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-spicy-saag-paneer-green-chilies.png",
    ingredients: [
      "14 oz paneer, cubed",
      "1 lb fresh spinach",
      "4-6 green chilies, chopped (divided)",
      "1 tablespoon ginger, grated",
      "5 cloves garlic, minced",
      "1 onion, chopped",
      "3 tablespoons ghee or oil",
      "1 teaspoon cumin seeds",
      "1.5 teaspoons garam masala",
      "1/2 teaspoon turmeric",
      "1/2 teaspoon black pepper",
      "1/4 teaspoon red chili flakes",
      "1/4 cup cream or yogurt",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    instructions: [
      "Blanch spinach with half the green chilies. Squeeze water and blend until smooth.",
      "Heat 2 tablespoons ghee. Fry paneer until golden. Remove and set aside.",
      "Add remaining ghee and cumin seeds. Let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and remaining fresh chilies. Cook 2 minutes.",
      "Add turmeric, garam masala, black pepper, and chili flakes. Stir for 30 seconds.",
      "Add spinach purée and simmer for 8-10 minutes.",
      "Stir in cream or yogurt. Season with salt.",
      "Add paneer and cook for 2 minutes.",
      "Garnish with fresh coriander and extra chili flakes if desired.",
      "Serve with cooling raita."
    ],
    tags: ["gluten-free", "saag paneer", "Indian", "vegetarian", "spicy", "green chilies", "fiery", "bold", "garam masala", "heat"],
    nutrition: {
      calories: 370,
      protein: "18g",
      carbs: "13g",
      fat: "29g",
      fiber: "4g",
      sodium: "510mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Vegan Saag Tofu with Coconut & Spinach",
    slug: "gluten-free-vegan-saag-tofu-coconut",
    seoTitle: "Gluten-Free Vegan Saag Tofu - Dairy-Free Indian Comfort",
    description: "Dairy-free twist — tofu instead of paneer, coconut cream instead of butter or yogurt, and mild spices for balance.",
    longDescription: "This gluten-free vegan saag tofu proves that you don't need dairy to create rich, satisfying Indian comfort food. Firm tofu is pressed, cubed, and fried until golden and crispy, creating a texture remarkably similar to paneer. Coconut cream replaces dairy cream, adding richness and a subtle tropical sweetness. The spinach is blended smooth with aromatic spices, creating a vibrant green curry that's every bit as comforting as the traditional version. Nutritional yeast adds a subtle cheesy note (optional but recommended), while plenty of garlic and ginger provide authentic flavor. This is perfect for vegans, those with dairy sensitivities, or anyone who wants to try a plant-based version of this classic dish. It's proof that comfort food can be entirely plant-based and still utterly satisfying.",
    seoDescription: "Gluten-free vegan saag tofu with coconut cream. Dairy-free Indian spinach curry with crispy tofu and plant-based richness.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-vegan-saag-tofu-coconut.png",
    ingredients: [
      "14 oz extra-firm tofu, pressed and cubed",
      "1 lb fresh spinach",
      "1 can (13.5 oz) coconut cream",
      "1 tablespoon ginger, grated",
      "5 cloves garlic, minced",
      "1 onion, chopped",
      "2 green chilies",
      "3 tablespoons coconut oil",
      "1 teaspoon cumin seeds",
      "1 teaspoon garam masala",
      "1/2 teaspoon turmeric",
      "2 tablespoons nutritional yeast (optional)",
      "Salt to taste",
      "Fresh cilantro and sesame seeds for garnish"
    ],
    instructions: [
      "Press tofu between paper towels to remove excess moisture. Cut into cubes.",
      "Blanch or microwave spinach. Squeeze out water and blend until smooth.",
      "Heat 2 tablespoons coconut oil in a pan. Fry tofu cubes until golden and crispy on all sides, about 5-6 minutes. Remove and set aside.",
      "Add remaining oil and cumin seeds. Let sizzle.",
      "Add onion and cook for 5 minutes. Add ginger, garlic, and chilies. Cook 2 minutes.",
      "Add turmeric and garam masala. Stir.",
      "Add spinach purée and simmer for 8 minutes.",
      "Stir in coconut cream and nutritional yeast (if using). Cook for 3 minutes.",
      "Season with salt.",
      "Add crispy tofu and gently mix. Cook for 2 minutes.",
      "Garnish with cilantro and sesame seeds. Serve hot."
    ],
    tags: ["gluten-free", "vegan", "saag tofu", "Indian", "dairy-free", "plant-based", "coconut", "tofu", "spinach", "healthy"],
    nutrition: {
      calories: 380,
      protein: "16g",
      carbs: "14g",
      fat: "30g",
      fiber: "5g",
      sodium: "480mg"
    },
    isNaturallyGlutenFree: true
  }
];

async function addRecipes() {
  console.log("Adding 10 Gluten-Free Saag Paneer recipes...");
  
  for (const recipe of saagPaneerRecipes) {
    try {
      await db.insert(recipes).values({
        id: nanoid(),
        ...recipe,
        rating: "4.8",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`✓ Added: ${recipe.title}`);
    } catch (error) {
      console.error(`✗ Error adding ${recipe.title}:`, error);
    }
  }
  
  console.log("\n✅ All recipes added successfully!");
  process.exit(0);
}

addRecipes();
