import { db } from "../server/db";
import { recipes } from "../shared/schema";

const potRoastRecipes = [
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Apples & Onions",
    slug: "gluten-free-cider-braised-pot-roast-apples-onions",
    description: "Sweet-tart apple cider base with caramelized onions and tender chuck roast — finished with fresh thyme and pan jus for ultimate comfort.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Apples & Onions is the epitome of fall comfort food. A well-marbled chuck roast is first seared to golden perfection, then slowly braised in apple cider with caramelized onions and sweet apple wedges. As it cooks low and slow, the meat becomes fork-tender while the cider reduces into a rich, glossy sauce infused with the sweetness of apples and the savory depth of onions. Fresh thyme adds an earthy, aromatic note that ties everything together. This dish is perfect for Sunday suppers, holiday gatherings, or any time you want a warming, one-pot meal that fills your home with incredible aromas. The combination of sweet and savory flavors makes it a crowd-pleaser that even picky eaters will love.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 180,
    totalTime: 205,
    servings: 6,
    rating: "4.9",
    calories: 420,
    protein: "38.0",
    carbs: "18.0",
    fat: "22.0",
    fiber: "2.5",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-apples-onions.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "2 large onions, sliced",
      "2 Granny Smith apples, cut into wedges",
      "4 cloves garlic, minced",
      "2 cups apple cider",
      "1 cup gluten-free beef broth",
      "3 sprigs fresh thyme",
      "2 bay leaves",
      "1 tablespoon gluten-free Dijon mustard",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "2 tablespoons butter (optional, for finishing)"
    ],
    instructions: [
      "Preheat oven to 325°F. Pat roast dry and season generously with salt and pepper.",
      "Heat olive oil in large Dutch oven over medium-high heat. Sear roast on all sides until deeply browned, about 3-4 minutes per side. Remove and set aside.",
      "In same pot, add sliced onions and cook 8-10 minutes until caramelized, stirring occasionally.",
      "Add garlic and cook 1 minute until fragrant.",
      "Pour in apple cider and beef broth, scraping up browned bits from bottom of pot.",
      "Stir in Dijon mustard. Add thyme sprigs and bay leaves.",
      "Return roast to pot. Arrange apple wedges around the meat.",
      "Bring to simmer, then cover and transfer to oven.",
      "Braise for 2.5-3 hours until meat is fork-tender.",
      "Remove roast and let rest 15 minutes. Discard thyme sprigs and bay leaves.",
      "Optional: Strain sauce, return to pot, and reduce over medium heat until thickened. Whisk in butter for extra richness.",
      "Slice roast and serve with sauce, onions, and apples."
    ],
    tips: "Let roast come to room temperature before searing for best crust. Use a mix of sweet and tart apples for complexity. Sauce can be thickened with cornstarch slurry if desired.",
    variations: [
      "Add parsnips or carrots for extra vegetables",
      "Use hard cider for more complex flavor",
      "Substitute pork shoulder for beef"
    ],
    tags: ["gluten-free", "pot roast", "cider-braised", "apples", "onions", "fall", "comfort food", "one-pot", "dinner"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider-Braised Pot Roast with Apples & Onions - Fall Comfort Food",
    seoDescription: "Tender chuck roast braised in apple cider with caramelized onions and sweet apples. This gluten-free pot roast is the ultimate fall comfort meal."
  },
  {
    title: "Gluten-Free Maple Cider-Braised Pot Roast",
    slug: "gluten-free-maple-cider-braised-pot-roast",
    description: "Infused with maple syrup, garlic, and cider vinegar — slightly sweet, deeply savory, and aromatic with a beautiful caramelized glaze.",
    longDescription: "This Gluten-Free Maple Cider-Braised Pot Roast takes the classic comfort dish to new heights with the addition of pure maple syrup. The maple adds a subtle sweetness that perfectly balances the acidity of apple cider and cider vinegar, creating a complex, multi-layered sauce. Whole garlic cloves soften and sweeten as they braise, adding mellow garlic flavor throughout. As the roast cooks low and slow, the maple caramelizes, creating a gorgeous glaze that coats the meat. The result is fall-apart tender beef with a rich, glossy sauce that's neither too sweet nor too savory. This elegant dish is perfect for special occasions yet simple enough for a weeknight meal.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 195,
    totalTime: 215,
    servings: 6,
    rating: "4.8",
    calories: 445,
    protein: "39.0",
    carbs: "22.0",
    fat: "23.0",
    fiber: "0.5",
    sugar: "16.0",
    image: "/recipe-images/gluten-free-maple-cider-pot-roast.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "8 cloves garlic, peeled and left whole",
      "2 cups apple cider",
      "1/2 cup pure maple syrup",
      "1/4 cup apple cider vinegar",
      "1 cup gluten-free beef broth",
      "2 sprigs fresh rosemary",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon smoked paprika"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast with salt, pepper, and smoked paprika.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until golden brown, about 12-15 minutes total. Remove and set aside.",
      "Add garlic cloves to pot and cook 2 minutes until lightly golden.",
      "Pour in apple cider, maple syrup, cider vinegar, and beef broth. Stir to combine.",
      "Add rosemary sprigs and return roast to pot.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3-3.5 hours until meat is fork-tender, basting every hour with pan juices.",
      "Remove roast and let rest 15 minutes.",
      "Strain sauce and skim fat. Simmer sauce over medium heat 10-15 minutes until reduced and slightly syrupy.",
      "Slice roast and drizzle with maple-cider glaze. Serve with softened garlic cloves."
    ],
    tips: "Use Grade A Dark maple syrup for deeper flavor. The sauce will thicken as it cools. Basting during cooking creates a beautiful caramelized exterior.",
    variations: [
      "Add fresh thyme instead of rosemary",
      "Include root vegetables like turnips or carrots",
      "Finish with a splash of bourbon for extra depth"
    ],
    tags: ["gluten-free", "pot roast", "maple", "cider-braised", "fall", "comfort food", "sweet-savory", "dinner", "holiday"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Maple Cider-Braised Pot Roast - Sweet & Savory Fall Dinner",
    seoDescription: "Tender pot roast braised in maple syrup and apple cider with whole garlic. Sweet, savory, and perfect for fall gatherings. Gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Carrots & Thyme",
    slug: "gluten-free-cider-braised-pot-roast-carrots-thyme",
    description: "A classic slow-braise featuring root vegetables, garlic, and herbs simmered in spiced apple cider — traditional and deeply satisfying.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Carrots & Thyme is a classic preparation that showcases how simple ingredients can create extraordinary flavor. Large carrot chunks cook alongside the roast, absorbing the rich cider-based braising liquid and becoming meltingly tender. Fresh thyme and bay leaves infuse the sauce with herbal aromatics, while garlic adds savory depth. The apple cider provides a subtle fruity sweetness that enhances rather than overpowers the beef. This is the kind of Sunday dinner that brings families together around the table, with fork-tender meat, perfectly cooked vegetables, and plenty of sauce for mashed potatoes or crusty gluten-free bread.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 180,
    totalTime: 200,
    servings: 6,
    rating: "4.9",
    calories: 395,
    protein: "37.0",
    carbs: "15.0",
    fat: "21.0",
    fiber: "3.0",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-carrots-thyme.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "1 lb carrots, cut into 2-inch pieces",
      "1 large onion, roughly chopped",
      "4 cloves garlic, smashed",
      "2 cups apple cider",
      "1 cup gluten-free beef broth",
      "4 sprigs fresh thyme",
      "2 bay leaves",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon dried oregano"
    ],
    instructions: [
      "Preheat oven to 325°F. Pat roast dry and season with salt and pepper.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until well-browned, about 12 minutes. Remove and set aside.",
      "Add onion to pot and cook 5 minutes until softened. Add garlic and cook 1 minute.",
      "Pour in apple cider and beef broth, scraping bottom to release browned bits.",
      "Add thyme, bay leaves, and oregano.",
      "Return roast to pot. Arrange carrot pieces around the meat.",
      "Bring to simmer, cover tightly, and transfer to oven.",
      "Braise 3 hours until meat is very tender and carrots are soft.",
      "Remove roast and vegetables. Let meat rest 15 minutes.",
      "Strain sauce, skim fat, and reduce over medium heat if desired.",
      "Slice roast and serve with carrots and pan sauce."
    ],
    tips: "Cut carrots into large chunks so they don't overcook. Save the braising liquid for making gravy or soup. Meat is done when it shreds easily with a fork.",
    variations: [
      "Add potatoes for a complete one-pot meal",
      "Use rainbow carrots for visual appeal",
      "Add celery for more vegetable variety"
    ],
    tags: ["gluten-free", "pot roast", "cider-braised", "carrots", "thyme", "comfort food", "sunday dinner", "family meal", "classic"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider-Braised Pot Roast with Carrots & Thyme - Classic Recipe",
    seoDescription: "Traditional pot roast braised in apple cider with carrots and fresh thyme. Fork-tender, comforting, and perfect for Sunday dinner. Gluten-free."
  },
  {
    title: "Gluten-Free Hard Cider Pot Roast with Shallots & Mustard",
    slug: "gluten-free-hard-cider-pot-roast-shallots-mustard",
    description: "Braised in crisp hard cider and Dijon — balanced acidity, depth, and golden-brown finish with sophisticated flavor.",
    longDescription: "This Gluten-Free Hard Cider Pot Roast with Shallots & Mustard is an elevated take on the classic that's perfect for entertaining. The hard cider adds complexity and a gentle fermented note, while Dijon mustard provides tang and helps emulsify the sauce. Shallots, sweeter and more delicate than onions, caramelize beautifully and add sophisticated flavor. The combination creates a refined, restaurant-quality dish that's surprisingly easy to make. The hard cider's acidity tenderizes the meat while adding depth, and the mustard ties all the flavors together. This is comfort food with a gourmet edge.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 185,
    totalTime: 210,
    servings: 6,
    rating: "4.8",
    calories: 410,
    protein: "38.0",
    carbs: "12.0",
    fat: "23.0",
    fiber: "1.5",
    sugar: "4.0",
    image: "/recipe-images/gluten-free-hard-cider-pot-roast-shallots.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "6 large shallots, peeled and halved",
      "4 cloves garlic, minced",
      "2 cups gluten-free hard cider",
      "1 cup gluten-free beef broth",
      "3 tablespoons gluten-free Dijon mustard",
      "2 tablespoons whole grain mustard",
      "3 sprigs fresh thyme",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon cornstarch (for thickening, optional)"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast generously with salt and pepper.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast until deeply browned on all sides, about 15 minutes total. Remove.",
      "Add shallots cut-side down and cook 4-5 minutes until caramelized. Remove and set aside.",
      "Add garlic to pot and cook 30 seconds. Pour in hard cider and broth, scraping up browned bits.",
      "Whisk in both mustards until well combined.",
      "Add thyme sprigs and return roast to pot. Arrange shallots around meat.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3 hours until meat is fork-tender.",
      "Remove roast and shallots. Let meat rest 15 minutes.",
      "Strain sauce and skim fat. If thicker sauce desired, whisk cornstarch with 2 tablespoons water and add to sauce. Simmer until thickened.",
      "Slice roast and serve with shallots and mustard-cider sauce."
    ],
    tips: "Choose a dry or semi-dry hard cider for best results. The mustard prevents the sauce from being too sweet. Shallots can be served whole as an elegant accompaniment.",
    variations: [
      "Add pearl onions along with shallots",
      "Use a mix of Dijon and coarse-ground mustard",
      "Finish sauce with cream for extra richness"
    ],
    tags: ["gluten-free", "pot roast", "hard cider", "shallots", "mustard", "sophisticated", "dinner party", "fall", "braised"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Hard Cider Pot Roast with Shallots & Mustard - Elegant Dinner",
    seoDescription: "Sophisticated pot roast braised in hard cider with caramelized shallots and Dijon mustard. Restaurant-quality and gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Rosemary & Garlic",
    slug: "gluten-free-cider-braised-pot-roast-rosemary-garlic",
    description: "Rustic version with whole garlic cloves, rosemary sprigs, and cider reduction sauce — aromatic and deeply flavored.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Rosemary & Garlic celebrates rustic, bold flavors. Whole garlic cloves soften and sweeten during the long braise, becoming spreadable and mild. Fresh rosemary infuses the meat and braising liquid with its distinctive pine-like aroma. As the cider reduces, it concentrates into a rich sauce that coats the tender beef. This is a no-fuss, traditional preparation that lets simple, quality ingredients shine. The aroma alone will have everyone gathering in the kitchen, and the flavor delivers on that promise.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 180,
    totalTime: 195,
    servings: 6,
    rating: "4.9",
    calories: 405,
    protein: "38.0",
    carbs: "10.0",
    fat: "22.0",
    fiber: "1.0",
    sugar: "6.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-rosemary-garlic.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "12 cloves garlic, peeled and left whole",
      "2 cups apple cider",
      "1 cup gluten-free beef broth",
      "4 large sprigs fresh rosemary",
      "2 bay leaves",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon red pepper flakes (optional)"
    ],
    instructions: [
      "Preheat oven to 325°F. Pat roast dry and season with salt and pepper.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until deeply browned, about 12-15 minutes. Remove.",
      "Add whole garlic cloves and cook 2 minutes, stirring occasionally.",
      "Pour in apple cider and beef broth, scraping bottom of pot.",
      "Add rosemary sprigs, bay leaves, and red pepper flakes if using.",
      "Return roast to pot. Nestle garlic cloves around the meat.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3 hours until meat is very tender.",
      "Remove roast and let rest 15 minutes. Discard rosemary sprigs and bay leaves.",
      "Skim fat from sauce. Mash some of the softened garlic cloves into the sauce for extra flavor and body.",
      "Slice roast and serve with sauce and whole garlic cloves."
    ],
    tips: "The garlic becomes very mild and sweet - encourage guests to eat the whole cloves. Fresh rosemary is essential; dried won't provide the same aromatic quality.",
    variations: [
      "Add potatoes and carrots for complete meal",
      "Use beef bone broth for richer flavor",
      "Finish with butter for glossy sauce"
    ],
    tags: ["gluten-free", "pot roast", "rosemary", "garlic", "cider-braised", "rustic", "comfort food", "simple", "aromatic"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider-Braised Pot Roast with Rosemary & Garlic - Rustic Dinner",
    seoDescription: "Aromatic pot roast braised with whole garlic and fresh rosemary in apple cider. Simple, rustic, and deeply flavorful. Gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Cranberries & Red Wine",
    slug: "gluten-free-cider-braised-pot-roast-cranberries-red-wine",
    description: "Sweet and tart blend of cider and red wine for a holiday-worthy roast — festive, rich, and beautifully ruby-colored.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Cranberries & Red Wine is a showstopping dish perfect for holiday celebrations. The combination of apple cider and red wine creates a complex braising liquid with fruity notes and depth. Fresh cranberries add pops of tart sweetness and a gorgeous ruby color to the sauce. As everything cooks together, the flavors meld into something truly special - neither too sweet nor too acidic, but perfectly balanced. This elegant roast looks as beautiful as it tastes, making it ideal for Thanksgiving, Christmas, or any special occasion when you want to impress.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 195,
    totalTime: 220,
    servings: 8,
    rating: "4.9",
    calories: 430,
    protein: "39.0",
    carbs: "16.0",
    fat: "23.0",
    fiber: "2.0",
    sugar: "10.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-cranberries-wine.png",
    ingredients: [
      "4 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "1 large onion, diced",
      "4 cloves garlic, minced",
      "1 1/2 cups apple cider",
      "1 cup dry red wine",
      "1 cup gluten-free beef broth",
      "2 cups fresh cranberries",
      "2 tablespoons honey",
      "3 sprigs fresh thyme",
      "2 bay leaves",
      "2 teaspoons salt",
      "1 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast with salt and pepper.",
      "Heat oil in large Dutch oven over medium-high heat. Sear roast on all sides until browned, about 15 minutes. Remove.",
      "Add onion to pot and cook 5 minutes until softened. Add garlic and cook 1 minute.",
      "Pour in cider, red wine, and beef broth. Scrape up browned bits.",
      "Add cranberries, honey, thyme, and bay leaves. Stir to combine.",
      "Return roast to pot. The liquid should come about halfway up the sides of the meat.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3-3.5 hours until meat is fork-tender.",
      "Remove roast and let rest 15 minutes. Discard thyme and bay leaves.",
      "Skim fat from sauce. Use immersion blender to partially blend cranberries for a rustic sauce, or strain for smooth sauce.",
      "Slice roast and serve with cranberry-wine sauce."
    ],
    tips: "Use a full-bodied red wine like Cabernet or Merlot. Fresh cranberries can be replaced with frozen. The sauce is beautiful drizzled over mashed potatoes.",
    variations: [
      "Add orange zest for brightness",
      "Include pearl onions for elegant presentation",
      "Use dried cranberries if fresh unavailable"
    ],
    tags: ["gluten-free", "pot roast", "cranberries", "red wine", "cider", "holiday", "festive", "special occasion", "thanksgiving"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider Pot Roast with Cranberries & Red Wine - Holiday Recipe",
    seoDescription: "Festive pot roast braised in cider and red wine with fresh cranberries. Perfect for Thanksgiving or Christmas. Elegant and gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Parsnips & Leeks",
    slug: "gluten-free-cider-braised-pot-roast-parsnips-leeks",
    description: "Earthy vegetables complement tender roast simmered in apple cider and bone broth — refined and rustic at once.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Parsnips & Leeks showcases underappreciated root vegetables that shine in this elegant braise. Parsnips bring a subtle sweetness and earthy flavor that pairs beautifully with apple cider, while leeks add a mild, sophisticated onion note. The combination creates a refined dish that's still comforting and hearty. Bone broth adds extra body and richness to the sauce. This is the kind of meal that feels both rustic and refined - perfect for a dinner party where you want to serve something special but approachable.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 180,
    totalTime: 210,
    servings: 6,
    rating: "4.7",
    calories: 415,
    protein: "37.0",
    carbs: "20.0",
    fat: "22.0",
    fiber: "4.0",
    sugar: "9.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-parsnips-leeks.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "3 leeks, white and light green parts only, halved lengthwise and cut into 2-inch pieces",
      "1 lb parsnips, peeled and cut into 2-inch pieces",
      "4 cloves garlic, smashed",
      "2 cups apple cider",
      "1 cup gluten-free bone broth",
      "3 sprigs fresh thyme",
      "2 sprigs fresh parsley",
      "2 teaspoons salt",
      "1 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 325°F. Pat roast dry and season with salt and pepper.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until deeply browned, about 12 minutes. Remove.",
      "Clean leeks thoroughly by rinsing between layers. Add to pot and cook 3-4 minutes until slightly softened.",
      "Add garlic and cook 1 minute.",
      "Pour in cider and bone broth, scraping bottom of pot.",
      "Add thyme and parsley sprigs.",
      "Return roast to pot. Arrange parsnips and leeks around the meat.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3 hours until meat is tender and vegetables are soft.",
      "Remove roast and vegetables. Let meat rest 15 minutes.",
      "Strain sauce, skim fat, and reduce if desired for more concentrated flavor.",
      "Slice roast and serve with parsnips, leeks, and pan sauce."
    ],
    tips: "Clean leeks very well as dirt hides between layers. Parsnips can be woody - peel thick ones thoroughly. Both vegetables become sweet and tender when braised.",
    variations: [
      "Add celery root for more earthy flavor",
      "Include turnips for variety",
      "Finish with cream for richer sauce"
    ],
    tags: ["gluten-free", "pot roast", "parsnips", "leeks", "cider-braised", "root vegetables", "refined", "dinner party", "fall"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider Pot Roast with Parsnips & Leeks - Refined Comfort Food",
    seoDescription: "Elegant pot roast with sweet parsnips and mild leeks braised in apple cider. Refined yet rustic. Perfect gluten-free dinner party dish."
  },
  {
    title: "Gluten-Free Smoky Cider-Braised Pot Roast",
    slug: "gluten-free-smoky-cider-braised-pot-roast",
    description: "Incorporates smoked paprika, bacon, and cider for a hearty, smoky-sweet depth of flavor — bold and satisfying.",
    longDescription: "This Gluten-Free Smoky Cider-Braised Pot Roast is for those who love bold, robust flavors. Crispy bacon adds smoky, salty depth, while smoked paprika enhances the smokiness throughout. The apple cider's sweetness balances these savory, smoky elements perfectly. As the bacon fat renders into the braising liquid, it adds incredible richness. This is hearty, stick-to-your-ribs comfort food with layers of complex flavor. It's perfect for cold weather meals when you want something that warms you from the inside out.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 185,
    totalTime: 210,
    servings: 6,
    rating: "4.8",
    calories: 465,
    protein: "40.0",
    carbs: "14.0",
    fat: "28.0",
    fiber: "1.5",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-smoky-cider-pot-roast.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "6 strips thick-cut bacon, chopped",
      "1 large onion, diced",
      "4 cloves garlic, minced",
      "2 cups apple cider",
      "1 cup gluten-free beef broth",
      "2 tablespoons smoked paprika",
      "1 tablespoon tomato paste",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon cayenne pepper (optional)",
      "2 bay leaves",
      "2 sprigs fresh thyme"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast with salt, pepper, and 1 tablespoon smoked paprika.",
      "In Dutch oven over medium heat, cook bacon until crispy. Remove with slotted spoon and set aside.",
      "In bacon fat, sear roast on all sides until deeply browned, about 15 minutes. Remove.",
      "Add onion to pot and cook 5 minutes. Add garlic and cook 1 minute.",
      "Stir in remaining smoked paprika and tomato paste. Cook 1 minute.",
      "Pour in cider and broth, scraping bottom of pot.",
      "Add bay leaves, thyme, and cayenne if using.",
      "Return roast to pot. Sprinkle half the bacon over top.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3 hours until meat is fork-tender.",
      "Remove roast and let rest 15 minutes. Discard bay leaves and thyme.",
      "Skim excess fat from sauce. Stir in remaining bacon.",
      "Slice roast and serve with smoky bacon sauce."
    ],
    tips: "Use thick-cut bacon for best texture. Smoked paprika is key - regular paprika won't give the same depth. Save bacon fat for cooking vegetables another day.",
    variations: [
      "Add chipotle peppers for heat",
      "Include diced tomatoes for acidity",
      "Use pancetta instead of bacon"
    ],
    tags: ["gluten-free", "pot roast", "smoky", "bacon", "cider-braised", "bold flavors", "comfort food", "winter", "hearty"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Smoky Cider-Braised Pot Roast - Bold Comfort Food",
    seoDescription: "Hearty pot roast with bacon, smoked paprika, and apple cider. Bold, smoky, and deeply satisfying. Perfect gluten-free winter meal."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Fennel & Orange Zest",
    slug: "gluten-free-cider-braised-pot-roast-fennel-orange",
    description: "Mediterranean-inspired twist with citrus, fennel bulb, and a hint of anise — light yet comforting with bright, aromatic notes.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Fennel & Orange Zest takes a Mediterranean approach to the classic braise. Fresh fennel bulb adds a delicate anise flavor that becomes sweet and tender during cooking. Orange zest and juice brighten the sauce with citrus notes that cut through the richness of the beef. The combination of apple cider and citrus creates a unique, aromatic braising liquid that's both familiar and exotic. This lighter, brighter version is perfect when you want comfort food that doesn't feel heavy.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 180,
    totalTime: 205,
    servings: 6,
    rating: "4.7",
    calories: 400,
    protein: "37.0",
    carbs: "16.0",
    fat: "21.0",
    fiber: "3.5",
    sugar: "10.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-fennel-orange.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "2 fennel bulbs, cut into wedges (reserve fronds for garnish)",
      "4 cloves garlic, minced",
      "2 cups apple cider",
      "1 cup gluten-free beef broth",
      "Zest of 2 oranges",
      "Juice of 1 orange",
      "3 sprigs fresh thyme",
      "1 teaspoon fennel seeds",
      "2 teaspoons salt",
      "1 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast with salt, pepper, and fennel seeds.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until golden, about 12 minutes. Remove.",
      "Add fennel wedges cut-side down and cook 3-4 minutes until caramelized. Remove and set aside.",
      "Add garlic to pot and cook 30 seconds.",
      "Pour in cider, broth, orange juice, and add orange zest. Scrape bottom of pot.",
      "Add thyme sprigs.",
      "Return roast to pot. Arrange fennel wedges around meat.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3 hours until meat and fennel are very tender.",
      "Remove roast and fennel. Let meat rest 15 minutes.",
      "Strain sauce and skim fat. Reduce if desired for more concentrated flavor.",
      "Slice roast and serve with fennel, sauce, and fresh fennel fronds."
    ],
    tips: "Save fennel fronds for a beautiful garnish. The fennel becomes very sweet when braised. Orange zest adds brightness without making sauce too acidic.",
    variations: [
      "Add olives for Mediterranean flair",
      "Include white wine instead of some cider",
      "Top with gremolata for extra freshness"
    ],
    tags: ["gluten-free", "pot roast", "fennel", "orange", "cider-braised", "mediterranean", "light", "aromatic", "unique"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider Pot Roast with Fennel & Orange - Mediterranean Twist",
    seoDescription: "Bright pot roast with fennel and orange zest braised in apple cider. Mediterranean-inspired, aromatic, and lighter. Gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Pot Roast with Balsamic & Honey Glaze",
    slug: "gluten-free-cider-braised-pot-roast-balsamic-honey",
    description: "Braised in cider and balsamic vinegar with a honey finish — glossy, tangy, and perfectly tender with sweet-tart complexity.",
    longDescription: "This Gluten-Free Cider-Braised Pot Roast with Balsamic & Honey Glaze is an impressive dish that looks and tastes like it came from a fine dining restaurant. The combination of apple cider and aged balsamic vinegar creates a complex braising liquid with fruity, tangy notes. Honey adds subtle sweetness and helps create a beautiful glaze. As the sauce reduces, it becomes thick and glossy, coating the meat in a stunning lacquer. The balance of sweet honey, tart balsamic, and fruity cider is absolutely sublime. This is the pot roast to serve when you want to wow your guests.",
    category: "Entrees",
    subcategory: "Braised Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 195,
    totalTime: 220,
    servings: 6,
    rating: "4.9",
    calories: 445,
    protein: "38.0",
    carbs: "24.0",
    fat: "23.0",
    fiber: "0.5",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-cider-pot-roast-balsamic-honey.png",
    ingredients: [
      "3 lbs beef chuck roast",
      "2 tablespoons olive oil",
      "1 large onion, sliced",
      "4 cloves garlic, minced",
      "1 1/2 cups apple cider",
      "1/2 cup balsamic vinegar",
      "1 cup gluten-free beef broth",
      "1/4 cup honey",
      "3 sprigs fresh rosemary",
      "2 bay leaves",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon butter (for finishing)"
    ],
    instructions: [
      "Preheat oven to 325°F. Season roast generously with salt and pepper.",
      "Heat oil in Dutch oven over medium-high heat. Sear roast on all sides until deeply caramelized, about 15 minutes. Remove.",
      "Add onion and cook 6-8 minutes until golden. Add garlic and cook 1 minute.",
      "Pour in cider, balsamic vinegar, and broth. Scrape bottom of pot.",
      "Stir in honey until dissolved. Add rosemary and bay leaves.",
      "Return roast to pot. Liquid should come halfway up sides.",
      "Bring to simmer, cover, and transfer to oven.",
      "Braise 3-3.5 hours until meat is very tender.",
      "Remove roast and let rest 15 minutes. Discard herbs.",
      "Strain sauce and skim fat. Simmer over medium heat 10-15 minutes until reduced by half and syrupy.",
      "Whisk in butter for glossy finish.",
      "Slice roast and drizzle generously with balsamic-honey glaze."
    ],
    tips: "Use good quality aged balsamic for best flavor. The sauce should coat the back of a spoon when properly reduced. Glaze can be made ahead and reheated.",
    variations: [
      "Add figs for extra sweetness",
      "Include fresh thyme instead of rosemary",
      "Top with toasted pine nuts"
    ],
    tags: ["gluten-free", "pot roast", "balsamic", "honey", "glazed", "elegant", "special occasion", "gourmet", "impressive"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider Pot Roast with Balsamic & Honey Glaze - Gourmet Recipe",
    seoDescription: "Restaurant-quality pot roast with glossy balsamic-honey glaze. Tender, tangy, sweet, and impressive. Perfect gluten-free special occasion meal."
  }
];

async function addPotRoastRecipes() {
  console.log("Adding 10 Cider-Braised Pot Roast recipes to database...");
  
  try {
    for (const recipe of potRoastRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Pot Roast recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addPotRoastRecipes();
