import { db } from "../server/db";
import { recipes } from "../shared/schema";

const porkLoinRecipes = [
  {
    title: "Gluten-Free Pork Loin with Classic Cider Glaze",
    slug: "gluten-free-pork-loin-classic-cider-glaze",
    description: "Simple yet elegant — apple cider reduced with garlic, shallots, and butter for a sweet-savory finish that's perfect for any occasion.",
    longDescription: "This Gluten-Free Pork Loin with Classic Cider Glaze showcases how simple ingredients can create extraordinary flavor. A perfectly seared pork loin is roasted until tender and juicy, then finished with a glossy cider glaze that's both sweet and savory. The glaze is made by reducing apple cider with aromatic shallots and garlic, then whisking in butter for a silky, restaurant-quality sauce. The natural sugars in the cider caramelize beautifully, creating a gorgeous golden coating. This is elegant enough for holiday entertaining yet simple enough for a weeknight dinner. The combination of tender pork and fruity, buttery glaze is simply irresistible.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 320,
    protein: "36.0",
    carbs: "14.0",
    fat: "13.0",
    fiber: "0.0",
    sugar: "11.0",
    image: "/recipe-images/gluten-free-pork-loin-classic-cider-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "2 shallots, minced",
      "3 cloves garlic, minced",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon dried thyme",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Pat pork loin dry and season with salt, pepper, and dried thyme.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork on all sides until golden brown, about 8 minutes total.",
      "Transfer skillet to oven and roast 25-30 minutes until internal temperature reaches 145°F.",
      "Remove pork and let rest on cutting board, tented with foil.",
      "Place skillet over medium heat. Add 1 tablespoon butter, then shallots and garlic. Cook 2 minutes.",
      "Add apple cider and bring to boil. Reduce heat and simmer 8-10 minutes until reduced by half and slightly syrupy.",
      "Remove from heat and whisk in remaining butter until smooth and glossy.",
      "Slice pork into medallions and arrange on serving platter.",
      "Drizzle glaze over sliced pork and garnish with fresh thyme."
    ],
    tips: "Don't overcook pork - 145°F is perfect for juicy, slightly pink center. Let rest 5-10 minutes before slicing. Glaze should coat back of spoon when ready.",
    variations: [
      "Add splash of white wine to glaze",
      "Include fresh apple slices in glaze",
      "Use hard cider for more complex flavor"
    ],
    tags: ["gluten-free", "pork loin", "cider glaze", "autumn", "dinner", "elegant", "simple", "fall", "roasted"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Classic Cider Glaze - Simple Elegance",
    seoDescription: "Perfectly roasted pork loin with sweet-savory apple cider glaze. Simple, elegant, and naturally gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Honey Cider Glaze",
    slug: "gluten-free-pork-loin-honey-cider-glaze",
    description: "Apple cider simmered with honey and Dijon for a glossy, golden coating and subtle sweetness that caramelizes beautifully.",
    longDescription: "This Gluten-Free Pork Loin with Honey Cider Glaze is a crowd-pleaser that combines the best of sweet and savory. Local honey adds floral sweetness while Dijon mustard provides a subtle tang that balances the cider's natural sugars. As the glaze reduces, it becomes thick and glossy, coating the pork in a beautiful amber lacquer. The honey caramelizes during cooking, creating a gorgeous crust. Each bite delivers tender, juicy pork enhanced by the complex, golden glaze. This is comfort food that looks and tastes special.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 340,
    protein: "36.0",
    carbs: "20.0",
    fat: "12.0",
    fiber: "0.0",
    sugar: "17.0",
    image: "/recipe-images/gluten-free-pork-loin-honey-cider-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "1/4 cup honey",
      "2 tablespoons gluten-free Dijon mustard",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon garlic powder",
      "Fresh rosemary for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt, pepper, and garlic powder.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 20 minutes.",
      "While pork roasts, combine cider, honey, and Dijon in saucepan. Bring to boil, then reduce heat and simmer 10 minutes until reduced by half.",
      "After pork has roasted 20 minutes, brush with half the glaze. Return to oven for 10 more minutes, brushing once more, until internal temp reaches 145°F.",
      "Remove pork and let rest 10 minutes.",
      "Simmer remaining glaze until thick and syrupy.",
      "Slice pork and drizzle with remaining honey cider glaze.",
      "Garnish with fresh rosemary."
    ],
    tips: "Brush glaze on during last 10 minutes to prevent burning. Quality honey makes a difference in flavor. Reserve some glaze for serving.",
    variations: [
      "Add whole grain mustard for texture",
      "Include fresh thyme with rosemary",
      "Use orange blossom honey for floral notes"
    ],
    tags: ["gluten-free", "pork loin", "honey", "cider glaze", "sweet-savory", "fall", "dinner", "family-friendly", "roasted"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Honey Cider Glaze - Sweet & Savory",
    seoDescription: "Tender pork loin glazed with honey, apple cider, and Dijon mustard. Golden, sweet-savory perfection. Gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Maple Apple Cider Glaze",
    slug: "gluten-free-pork-loin-maple-cider-glaze",
    description: "Deeply flavored maple-cider reduction infused with rosemary and cracked pepper — perfect for fall with rich autumn flavors.",
    longDescription: "This Gluten-Free Pork Loin with Maple Apple Cider Glaze celebrates the essence of autumn. Pure maple syrup adds rich, complex sweetness while fresh rosemary provides an aromatic, slightly piney note. Cracked black pepper adds a gentle heat that balances the sweetness beautifully. As the glaze reduces, it becomes thick and syrupy, coating the pork in a gorgeous amber sauce. The maple caramelizes on the meat, creating a delicious crust. This is special occasion food that's surprisingly simple to prepare.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    servings: 6,
    rating: "4.8",
    calories: 355,
    protein: "36.0",
    carbs: "22.0",
    fat: "13.0",
    fiber: "0.0",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-pork-loin-maple-cider-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "1/3 cup pure maple syrup",
      "2 sprigs fresh rosemary",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon cracked black pepper",
      "1/2 teaspoon smoked paprika"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt, cracked pepper, and smoked paprika.",
      "Heat olive oil in oven-safe skillet. Sear pork on all sides until golden brown, about 8-10 minutes.",
      "Transfer to oven and roast 25 minutes.",
      "Meanwhile, combine cider, maple syrup, and rosemary in saucepan. Simmer 12-15 minutes until reduced and syrupy.",
      "After 25 minutes, brush pork generously with maple glaze. Return to oven for 10 more minutes until 145°F internal temp.",
      "Remove pork and tent with foil to rest 10 minutes.",
      "Remove rosemary from remaining glaze and continue simmering until very thick.",
      "Slice pork and serve drizzled with maple-cider glaze.",
      "Garnish with fresh rosemary sprigs."
    ],
    tips: "Use Grade A Dark maple syrup for richer flavor. The glaze will thicken as it cools. Don't overcook pork or it will dry out.",
    variations: [
      "Add a splash of bourbon for depth",
      "Include fresh thyme with rosemary",
      "Use pear cider for variation"
    ],
    tags: ["gluten-free", "pork loin", "maple", "cider glaze", "autumn", "fall", "holiday", "special occasion", "roasted"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Maple Apple Cider Glaze - Autumn Perfection",
    seoDescription: "Rich pork loin with maple syrup and apple cider glaze. Perfect fall dinner with deep, complex flavors. Gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Dijon Cider Reduction",
    slug: "gluten-free-pork-loin-dijon-cider-reduction",
    description: "Tangy and rich — cider and mustard whisked into a smooth glaze for balance and acidity that cuts through the richness.",
    longDescription: "This Gluten-Free Pork Loin with Dijon Cider Reduction is for those who love bold, tangy flavors. The Dijon mustard adds sophisticated acidity that perfectly balances the sweetness of the cider. As the sauce reduces, the mustard emulsifies with the cider, creating a smooth, velvety glaze. This French-inspired preparation is elegant yet approachable. The tangy sauce cuts through the richness of the pork, making each bite incredibly satisfying. Perfect for dinner parties or special family meals.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    rating: "4.8",
    calories: 310,
    protein: "37.0",
    carbs: "12.0",
    fat: "12.0",
    fiber: "0.5",
    sugar: "9.0",
    image: "/recipe-images/gluten-free-pork-loin-dijon-cider-reduction.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "3 tablespoons gluten-free Dijon mustard",
      "2 tablespoons whole grain mustard",
      "2 shallots, minced",
      "2 tablespoons butter",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork loin with salt and pepper.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork until golden on all sides, about 8 minutes.",
      "Transfer to oven and roast 25-30 minutes until 145°F internal temperature.",
      "Remove pork and let rest.",
      "In same skillet over medium heat, add shallots and cook 2 minutes.",
      "Add cider and bring to boil. Reduce heat and simmer 8-10 minutes until reduced by half.",
      "Whisk in both mustards until smooth. Simmer 2 more minutes.",
      "Remove from heat and whisk in butter until glossy.",
      "Slice pork and serve with Dijon-cider sauce.",
      "Garnish with fresh parsley."
    ],
    tips: "Whisk mustard thoroughly to prevent clumping. The sauce should be tangy but not overpowering. Adjust mustard amount to taste.",
    variations: [
      "Add cream for richer sauce",
      "Include fresh tarragon",
      "Use champagne mustard for elegance"
    ],
    tags: ["gluten-free", "pork loin", "dijon", "cider reduction", "french-inspired", "tangy", "elegant", "dinner party", "sophisticated"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Dijon Cider Reduction - French-Inspired",
    seoDescription: "Elegant pork loin with tangy Dijon mustard and apple cider reduction. Sophisticated and gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Cider & Thyme Pan Jus",
    slug: "gluten-free-pork-loin-cider-thyme-pan-jus",
    description: "Roasted pork finished with pan drippings, thyme, and apple cider reduction — simple, aromatic, and full of natural flavor.",
    longDescription: "This Gluten-Free Pork Loin with Cider & Thyme Pan Jus is rustic elegance at its finest. The sauce is made from the flavorful pan drippings, deglazed with apple cider and infused with fresh thyme. This simple technique creates a sauce with incredible depth - the caramelized bits from searing add savory richness while the cider provides sweetness and the thyme adds aromatic notes. The result is a light yet flavorful pan jus that enhances rather than masks the pork. This is traditional cooking at its best.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 35,
    totalTime: 45,
    servings: 6,
    rating: "4.9",
    calories: 305,
    protein: "37.0",
    carbs: "10.0",
    fat: "12.0",
    fiber: "0.0",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-pork-loin-cider-thyme-pan-jus.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "4 sprigs fresh thyme",
      "2 tablespoons olive oil",
      "2 tablespoons butter",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 cup gluten-free chicken broth"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork on all sides until deeply browned, about 10 minutes.",
      "Add 2 thyme sprigs to skillet. Transfer to oven and roast 25-30 minutes until 145°F.",
      "Remove pork and let rest on cutting board.",
      "Place skillet over medium heat. Add cider and remaining thyme, scraping up browned bits.",
      "Add chicken broth and simmer 8-10 minutes until reduced by half.",
      "Strain sauce and return to pan. Whisk in butter.",
      "Slice pork and serve with thyme pan jus.",
      "Garnish with fresh thyme."
    ],
    tips: "Scrape pan well to get all the flavorful browned bits. Fresh thyme is essential - dried won't provide same flavor. Pan jus should be light and flavorful, not thick.",
    variations: [
      "Add shallots for extra depth",
      "Include white wine with cider",
      "Use rosemary instead of thyme"
    ],
    tags: ["gluten-free", "pork loin", "cider", "thyme", "pan jus", "rustic", "simple", "aromatic", "traditional"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Cider & Thyme Pan Jus - Rustic Elegance",
    seoDescription: "Classic pork loin with aromatic thyme and apple cider pan jus. Simple, rustic, and naturally gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Spiced Cider Glaze",
    slug: "gluten-free-pork-loin-spiced-cider-glaze",
    description: "Warm spices like cinnamon, clove, and allspice add seasonal depth to the sweet cider glaze — perfect for holiday gatherings.",
    longDescription: "This Gluten-Free Pork Loin with Spiced Cider Glaze brings the warm, comforting flavors of fall to your table. Cinnamon, cloves, and allspice transform apple cider into a deeply aromatic glaze that smells like the holidays. The spices add complexity without overwhelming the natural sweetness of the cider or the savory pork. As it reduces, the glaze becomes thick and syrupy, coating the meat in a beautiful, fragrant sauce. This is the kind of dish that fills your home with incredible aromas and brings everyone to the table.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    servings: 6,
    rating: "4.8",
    calories: 330,
    protein: "36.0",
    carbs: "18.0",
    fat: "12.0",
    fiber: "0.5",
    sugar: "14.0",
    image: "/recipe-images/gluten-free-pork-loin-spiced-cider-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "2 cinnamon sticks",
      "4 whole cloves",
      "1/2 teaspoon ground allspice",
      "1/4 teaspoon nutmeg",
      "3 tablespoons brown sugar",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt, pepper, and allspice.",
      "Heat olive oil in oven-safe skillet. Sear pork on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 25 minutes.",
      "Meanwhile, combine cider, cinnamon sticks, cloves, brown sugar, and nutmeg in saucepan. Simmer 15 minutes until reduced and syrupy.",
      "Strain glaze to remove whole spices.",
      "After 25 minutes, brush pork generously with spiced glaze. Return to oven for 10 more minutes until 145°F.",
      "Remove pork and rest 10 minutes.",
      "Continue simmering remaining glaze until very thick.",
      "Slice pork and drizzle with spiced cider glaze."
    ],
    tips: "Whole spices provide better flavor than ground. Strain glaze before using to avoid grainy texture. Glaze should smell fragrant and spicy.",
    variations: [
      "Add star anise for extra depth",
      "Include orange zest for brightness",
      "Use maple syrup instead of brown sugar"
    ],
    tags: ["gluten-free", "pork loin", "spiced", "cider glaze", "holiday", "autumn", "warm spices", "festive", "seasonal"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Spiced Cider Glaze - Holiday Perfection",
    seoDescription: "Aromatic pork loin with warm spiced apple cider glaze. Perfect for fall and holiday dinners. Gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Caramelized Onion Cider Sauce",
    slug: "gluten-free-pork-loin-caramelized-onion-cider-sauce",
    description: "Slow-cooked onions deglazed with cider for a savory-sweet glaze that pairs beautifully with roasted pork — rich and satisfying.",
    longDescription: "This Gluten-Free Pork Loin with Caramelized Onion Cider Sauce is a study in patience and flavor development. Sweet onions are slowly caramelized until deeply golden and concentrated. When deglazed with apple cider, they create a sauce that's both sweet and savory with incredible depth. The onions add body and richness while the cider provides brightness. This is bistro-style cooking that's surprisingly easy - just give the onions time to caramelize properly and you'll be rewarded with an unforgettable sauce.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 55,
    totalTime: 75,
    servings: 6,
    rating: "4.9",
    calories: 340,
    protein: "36.0",
    carbs: "16.0",
    fat: "14.0",
    fiber: "1.5",
    sugar: "10.0",
    image: "/recipe-images/gluten-free-pork-loin-caramelized-onion-cider.png",
    ingredients: [
      "2 lbs pork loin",
      "3 large onions, thinly sliced",
      "1.5 cups apple cider",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "1 tablespoon balsamic vinegar",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 teaspoon dried thyme"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt, pepper, and thyme.",
      "Heat olive oil in oven-safe skillet. Sear pork on all sides until golden, about 8 minutes. Transfer to oven and roast 30 minutes until 145°F. Remove and rest.",
      "While pork roasts, melt 2 tablespoons butter in large skillet over medium-low heat. Add onions and cook 35-40 minutes, stirring occasionally, until deeply caramelized.",
      "Add balsamic vinegar to onions and cook 2 minutes.",
      "Add cider and bring to boil. Reduce heat and simmer 10 minutes until sauce thickens.",
      "Remove from heat and stir in remaining butter.",
      "Slice pork and top with caramelized onion cider sauce."
    ],
    tips: "Don't rush caramelizing onions - low and slow is key. Stir occasionally but not constantly. Sauce should be thick enough to coat pork.",
    variations: [
      "Add fresh thyme to onions",
      "Include crispy bacon",
      "Use red onions for color"
    ],
    tags: ["gluten-free", "pork loin", "caramelized onion", "cider sauce", "savory-sweet", "bistro-style", "elegant", "rich", "dinner"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Caramelized Onion Cider Sauce - Bistro Style",
    seoDescription: "Rich pork loin with deeply caramelized onions and apple cider sauce. Bistro elegance made easy. Gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Apple Cider & Balsamic Glaze",
    slug: "gluten-free-pork-loin-cider-balsamic-glaze",
    description: "Sweet cider balanced by balsamic vinegar and brown sugar for a bold, tangy, caramelized sauce with sophisticated flavor.",
    longDescription: "This Gluten-Free Pork Loin with Apple Cider & Balsamic Glaze is a study in contrasts. Sweet apple cider meets tangy balsamic vinegar, creating a complex sauce that's neither too sweet nor too acidic. Brown sugar adds caramel notes while the vinegar provides depth and acidity. As the glaze reduces, it becomes thick and glossy, coating the pork in a beautiful dark lacquer. This sophisticated combination elevates simple pork loin to restaurant quality. Perfect for impressing guests or treating yourself to something special.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    servings: 6,
    rating: "4.8",
    calories: 335,
    protein: "36.0",
    carbs: "20.0",
    fat: "12.0",
    fiber: "0.0",
    sugar: "16.0",
    image: "/recipe-images/gluten-free-pork-loin-cider-balsamic-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "1/3 cup balsamic vinegar",
      "3 tablespoons brown sugar",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon butter",
      "Fresh rosemary for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt and pepper.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork until golden on all sides, about 8 minutes.",
      "Transfer to oven and roast 25 minutes.",
      "Meanwhile, combine cider, balsamic vinegar, brown sugar, and garlic in saucepan. Bring to boil, then reduce heat and simmer 15 minutes until syrupy.",
      "After 25 minutes, brush pork generously with glaze. Return to oven for 10 more minutes until 145°F.",
      "Remove pork and rest 10 minutes.",
      "Whisk butter into remaining glaze until glossy.",
      "Slice pork and drizzle with balsamic-cider glaze.",
      "Garnish with fresh rosemary."
    ],
    tips: "Use good quality aged balsamic for best flavor. Glaze should be thick enough to coat back of spoon. Don't skip the butter - it makes glaze silky.",
    variations: [
      "Add figs to the glaze",
      "Include fresh thyme",
      "Use honey instead of brown sugar"
    ],
    tags: ["gluten-free", "pork loin", "balsamic", "cider glaze", "sophisticated", "tangy", "sweet-savory", "elegant", "impressive"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Cider & Balsamic Glaze - Sophisticated",
    seoDescription: "Elegant pork loin with tangy-sweet balsamic and apple cider glaze. Restaurant-quality and gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Garlic Herb Cider Glaze",
    slug: "gluten-free-pork-loin-garlic-herb-cider-glaze",
    description: "Rustic blend of cider, garlic, parsley, and butter — classic, comforting, and perfect for family dinners with simple elegance.",
    longDescription: "This Gluten-Free Pork Loin with Garlic Herb Cider Glaze celebrates the beauty of simple, classic flavors. Plenty of fresh garlic softens and mellows in the cider reduction, while fresh parsley adds bright, herbal notes. Butter whisked in at the end creates a silky, luxurious sauce. This is rustic French-inspired cooking at its finest - unpretentious but absolutely delicious. The combination of sweet cider, savory garlic, and fresh herbs is timeless and always satisfying.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 325,
    protein: "37.0",
    carbs: "12.0",
    fat: "14.0",
    fiber: "0.5",
    sugar: "9.0",
    image: "/recipe-images/gluten-free-pork-loin-garlic-herb-cider.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "6 cloves garlic, minced",
      "3 tablespoons fresh parsley, chopped",
      "1 tablespoon fresh thyme",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 25-30 minutes until 145°F internal temperature.",
      "Remove pork and let rest.",
      "In same skillet over medium heat, add 1 tablespoon butter and garlic. Cook 1 minute until fragrant.",
      "Add cider and thyme. Bring to boil, scraping up browned bits. Reduce heat and simmer 8-10 minutes until reduced by half.",
      "Remove from heat. Whisk in remaining butter and fresh parsley.",
      "Slice pork and serve with garlic herb cider glaze.",
      "Garnish with additional fresh herbs."
    ],
    tips: "Don't burn garlic - cook just until fragrant. Fresh herbs are essential for bright flavor. Glaze should be light and buttery, not thick.",
    variations: [
      "Add fresh basil or tarragon",
      "Include lemon zest for brightness",
      "Use shallots along with garlic"
    ],
    tags: ["gluten-free", "pork loin", "garlic", "herb", "cider glaze", "rustic", "classic", "family-friendly", "simple"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Garlic Herb Cider Glaze - Classic Comfort",
    seoDescription: "Rustic pork loin with garlic, fresh herbs, and apple cider glaze. Simple, classic, and naturally gluten-free."
  },
  {
    title: "Gluten-Free Pork Loin with Cranberry Cider Glaze",
    slug: "gluten-free-pork-loin-cranberry-cider-glaze",
    description: "Apple cider blended with cranberries and rosemary for a jewel-toned, holiday-ready glaze — festive, tangy, and beautiful.",
    longDescription: "This Gluten-Free Pork Loin with Cranberry Cider Glaze is a showstopper for holiday entertaining. Fresh cranberries are simmered with apple cider until they burst and release their tart juice, creating a gorgeous ruby-red sauce. Rosemary adds an aromatic, festive note. The combination of sweet cider and tart cranberries is perfectly balanced - neither too sweet nor too sour. As the sauce reduces, it becomes jewel-toned and glossy. This stunning glaze not only tastes amazing but looks beautiful drizzled over sliced pork on a holiday platter.",
    category: "Entrees",
    subcategory: "Pork Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 40,
    totalTime: 55,
    servings: 6,
    rating: "4.9",
    calories: 330,
    protein: "36.0",
    carbs: "20.0",
    fat: "11.0",
    fiber: "2.0",
    sugar: "15.0",
    image: "/recipe-images/gluten-free-pork-loin-cranberry-cider-glaze.png",
    ingredients: [
      "2 lbs pork loin",
      "1.5 cups apple cider",
      "1.5 cups fresh cranberries",
      "1/4 cup honey",
      "2 sprigs fresh rosemary",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon butter"
    ],
    instructions: [
      "Preheat oven to 375°F. Season pork with salt and pepper.",
      "Heat olive oil in oven-safe skillet over medium-high heat. Sear pork on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 25 minutes.",
      "Meanwhile, combine cider, cranberries, honey, and rosemary in saucepan. Bring to boil, then reduce heat and simmer 12-15 minutes until cranberries burst and sauce thickens.",
      "Strain sauce to remove cranberry skins and rosemary if desired, or leave rustic.",
      "After 25 minutes, brush pork with cranberry glaze. Return to oven for 10 more minutes until 145°F.",
      "Remove pork and rest 10 minutes.",
      "Whisk butter into remaining cranberry glaze.",
      "Slice pork and serve with jewel-toned cranberry cider glaze.",
      "Garnish with fresh cranberries and rosemary."
    ],
    tips: "Fresh cranberries are best but frozen work too. For smoother sauce, strain out skins. The glaze is tart-sweet and festive.",
    variations: [
      "Add orange zest for brightness",
      "Include cinnamon stick while simmering",
      "Use dried cranberries if fresh unavailable"
    ],
    tags: ["gluten-free", "pork loin", "cranberry", "cider glaze", "holiday", "festive", "thanksgiving", "christmas", "jewel-toned"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Pork Loin with Cranberry Cider Glaze - Holiday Showstopper",
    seoDescription: "Festive pork loin with ruby cranberry and apple cider glaze. Perfect for Thanksgiving and Christmas. Gluten-free."
  }
];

async function addPorkLoinRecipes() {
  console.log("Adding 10 Pork Loin with Cider Glaze recipes to database...");
  
  try {
    for (const recipe of porkLoinRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Pork Loin recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addPorkLoinRecipes();
