import { db } from "../server/db";
import { recipes } from "../shared/schema";

const beefTenderloinRecipes = [
  {
    title: "Gluten-Free Beef Tenderloin with Red Wine Reduction",
    slug: "gluten-free-beef-tenderloin-red-wine-reduction",
    description: "Classic French-style tenderloin with a silky red wine demi-glace, garlic, and shallots — elegant and rich.",
    longDescription: "This Gluten-Free Beef Tenderloin with Red Wine Reduction is the epitome of fine dining elegance. A perfectly seared beef tenderloin is roasted to medium-rare perfection, then finished with a luxurious red wine reduction. The sauce is made by reducing full-bodied red wine with aromatic shallots, garlic, and fresh thyme until it becomes thick, glossy, and intensely flavored. This classic French preparation showcases the tender, buttery texture of beef tenderloin while the wine reduction adds depth and sophistication. Perfect for special occasions, holiday dinners, or impressing dinner guests. Pair with roasted vegetables and a glass of the same wine used in the sauce.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 6,
    rating: "5.0",
    calories: 380,
    protein: "42.0",
    carbs: "6.0",
    fat: "18.0",
    fiber: "0.5",
    sugar: "3.0",
    image: "/recipe-images/gluten-free-beef-tenderloin-red-wine-reduction.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "2 cups full-bodied red wine (Cabernet Sauvignon)",
      "2 shallots, minced",
      "4 cloves garlic, minced",
      "2 cups gluten-free beef broth",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "3 sprigs fresh thyme",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 bay leaf"
    ],
    instructions: [
      "Preheat oven to 400°F. Pat beef tenderloin dry and season generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until deeply browned, about 8-10 minutes total.",
      "Transfer skillet to oven and roast 15-20 minutes for medium-rare (135°F internal temperature).",
      "Remove beef from skillet and tent with foil to rest at least 10 minutes.",
      "In same skillet over medium heat, add 1 tablespoon butter, shallots, and garlic. Cook 2-3 minutes until softened.",
      "Add red wine, thyme, and bay leaf. Bring to boil and reduce by half, about 10 minutes.",
      "Add beef broth and continue simmering until reduced by half again and sauce coats back of spoon, about 8-10 minutes.",
      "Strain sauce through fine mesh sieve. Return to pan and whisk in remaining butter until glossy.",
      "Slice beef tenderloin into thick medallions and serve with red wine reduction drizzled over top.",
      "Garnish with fresh thyme and serve immediately."
    ],
    tips: "Use a meat thermometer for perfect doneness - 135°F for medium-rare. Let beef rest before slicing to retain juices. Use the same wine for sauce that you'll serve with dinner. Sauce can be made ahead and reheated gently.",
    variations: [
      "Add cognac for extra depth",
      "Include mushrooms in the reduction",
      "Use Port wine for sweeter sauce"
    ],
    tags: ["gluten-free", "beef tenderloin", "red wine", "french", "elegant", "holiday", "special occasion", "dinner party", "wine pairing"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Beef Tenderloin with Red Wine Reduction - French Elegance",
    seoDescription: "Classic French beef tenderloin with silky red wine reduction. Perfect for holidays and special occasions. Naturally gluten-free."
  },
  {
    title: "Gluten-Free Herb-Crusted Beef Tenderloin",
    slug: "gluten-free-herb-crusted-beef-tenderloin",
    description: "Rosemary, thyme, and garlic crust seared to perfection, finished with a drizzle of olive oil and sea salt.",
    longDescription: "This Gluten-Free Herb-Crusted Beef Tenderloin showcases the pure, luxurious flavor of premium beef enhanced with aromatic herbs. A generous coating of fresh rosemary, thyme, and garlic creates a fragrant crust that caramelizes beautifully during roasting. The herbs add earthy, aromatic notes that complement rather than mask the beef's natural flavor. A final drizzle of high-quality olive oil and flaky sea salt adds richness and texture. This preparation is both rustic and elegant - simple enough for a family dinner yet impressive enough for guests. The key is using fresh herbs and quality beef, then letting the ingredients shine.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    rating: "4.9",
    calories: 360,
    protein: "43.0",
    carbs: "2.0",
    fat: "19.0",
    fiber: "0.5",
    sugar: "0.0",
    image: "/recipe-images/gluten-free-herb-crusted-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "3 tablespoons fresh rosemary, finely chopped",
      "2 tablespoons fresh thyme leaves",
      "6 cloves garlic, minced",
      "3 tablespoons olive oil, plus more for drizzling",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Flaky sea salt for finishing"
    ],
    instructions: [
      "Preheat oven to 425°F. Pat beef tenderloin completely dry with paper towels.",
      "In small bowl, combine rosemary, thyme, garlic, olive oil, salt, and pepper to form paste.",
      "Rub herb mixture all over beef tenderloin, pressing firmly to adhere.",
      "Let beef sit at room temperature for 20 minutes to allow flavors to penetrate.",
      "Heat oven-safe skillet over high heat. Sear beef on all sides until herbs are golden and fragrant, about 2-3 minutes per side.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F internal temperature).",
      "Remove from oven and tent with foil. Let rest 10-15 minutes.",
      "Slice into thick medallions and arrange on platter.",
      "Drizzle with high-quality olive oil and sprinkle with flaky sea salt.",
      "Garnish with fresh herb sprigs and serve."
    ],
    tips: "Fresh herbs are essential - dried won't provide same flavor or crust. Don't skip resting time or juices will run out when sliced. Use best quality olive oil for finishing drizzle.",
    variations: [
      "Add Dijon mustard to herb paste",
      "Include parsley and oregano",
      "Finish with lemon zest"
    ],
    tags: ["gluten-free", "beef tenderloin", "herb-crusted", "rosemary", "simple", "elegant", "roasted", "dinner", "special occasion"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Herb-Crusted Beef Tenderloin - Simple Elegance",
    seoDescription: "Perfectly roasted beef tenderloin with rosemary, thyme, and garlic crust. Simple, elegant, naturally gluten-free."
  },
  {
    title: "Gluten-Free Peppercorn Beef Tenderloin with Cream Sauce",
    slug: "gluten-free-peppercorn-beef-tenderloin-cream-sauce",
    description: "Cracked black pepper crusted tenderloin served with a creamy cognac pan sauce — bold yet refined.",
    longDescription: "This Gluten-Free Peppercorn Beef Tenderloin with Cream Sauce is a steakhouse classic that's bold, sophisticated, and incredibly satisfying. The beef is generously coated with cracked black peppercorns that create a spicy crust with wonderful texture. After roasting, the pan is deglazed with cognac (which can be flamed for drama), then finished with cream to create a luxurious sauce. The combination of peppery heat, rich cream, and tender beef is absolutely unforgettable. This is special occasion cooking at its finest - impressive yet achievable at home.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 420,
    protein: "42.0",
    carbs: "4.0",
    fat: "24.0",
    fiber: "1.0",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-peppercorn-beef-tenderloin-cream-sauce.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "3 tablespoons black peppercorns, coarsely cracked",
      "1 cup heavy cream",
      "1/4 cup cognac or brandy",
      "2 shallots, minced",
      "1 cup gluten-free beef broth",
      "2 tablespoons butter",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F. Pat beef dry and season with salt.",
      "Press cracked peppercorns firmly into all sides of beef tenderloin.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until peppercorns are toasted, about 8 minutes.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F).",
      "Remove beef and let rest on cutting board tented with foil.",
      "Place skillet over medium heat. Add shallots and cook 2 minutes.",
      "Remove pan from heat, add cognac, and carefully ignite with long match if desired. Let flames subside.",
      "Add beef broth and simmer until reduced by half, about 5 minutes.",
      "Add cream and simmer until sauce coats back of spoon, about 5-7 minutes.",
      "Remove from heat and whisk in butter. Season with salt to taste.",
      "Slice beef and serve with creamy peppercorn sauce.",
      "Garnish with fresh parsley and pink peppercorns if desired."
    ],
    tips: "Crack peppercorns in mortar and pestle or in sealed bag with rolling pin - don't use pre-ground. Be careful when flaming cognac. Sauce should be thick enough to coat beef.",
    variations: [
      "Add Dijon mustard to sauce",
      "Include green peppercorns",
      "Use whiskey instead of cognac"
    ],
    tags: ["gluten-free", "beef tenderloin", "peppercorn", "cream sauce", "steakhouse", "bold", "cognac", "elegant", "special occasion"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Peppercorn Beef Tenderloin with Cream Sauce - Steakhouse Classic",
    seoDescription: "Bold peppercorn-crusted beef tenderloin with luxurious cognac cream sauce. Restaurant-quality, gluten-free."
  },
  {
    title: "Gluten-Free Garlic Butter Beef Tenderloin",
    slug: "gluten-free-garlic-butter-beef-tenderloin",
    description: "Simple, timeless preparation — basted with garlic butter and herbs, finished with pan juices.",
    longDescription: "This Gluten-Free Garlic Butter Beef Tenderloin celebrates the beauty of simplicity. Quality beef tenderloin is seared to perfection, then basted with garlic-infused butter and fresh herbs while roasting. The butter melts into the meat, adding richness while keeping it incredibly moist. This classic preparation lets the beef shine while the garlic and herbs provide aromatic support. The pan juices become a simple, flavorful sauce. This is timeless cooking - no complicated techniques, just quality ingredients treated with respect. Perfect for when you want something special without fuss.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    rating: "5.0",
    calories: 395,
    protein: "42.0",
    carbs: "1.0",
    fat: "23.0",
    fiber: "0.0",
    sugar: "0.0",
    image: "/recipe-images/gluten-free-garlic-butter-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "6 tablespoons butter, softened",
      "8 cloves garlic, minced",
      "2 tablespoons fresh parsley, chopped",
      "1 tablespoon fresh thyme leaves",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Fresh herbs for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Pat beef tenderloin dry and season generously with salt and pepper.",
      "In small bowl, mix softened butter with garlic, parsley, and thyme.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until golden brown, about 8 minutes.",
      "Spread half the garlic butter over top of beef.",
      "Transfer skillet to oven and roast 15 minutes.",
      "Remove from oven, baste with pan juices, and spread remaining garlic butter over beef.",
      "Return to oven for 5-10 more minutes until internal temperature reaches 135°F for medium-rare.",
      "Remove from oven and transfer beef to cutting board. Tent with foil and rest 10 minutes.",
      "Pour pan juices into small bowl, season with salt and pepper.",
      "Slice beef into thick medallions and serve drizzled with garlic butter pan juices.",
      "Garnish with fresh herbs and serve immediately."
    ],
    tips: "Let butter soften to room temperature for easy mixing. Baste frequently for maximum flavor. Save all pan juices - they're liquid gold. Use fresh garlic, not jarred.",
    variations: [
      "Add rosemary to butter",
      "Include lemon zest",
      "Use compound butter with blue cheese"
    ],
    tags: ["gluten-free", "beef tenderloin", "garlic butter", "simple", "classic", "elegant", "herbs", "easy", "special occasion"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Garlic Butter Beef Tenderloin - Classic Simplicity",
    seoDescription: "Simple, elegant beef tenderloin basted with garlic butter and herbs. Timeless and naturally gluten-free."
  },
  {
    title: "Gluten-Free Coffee-Rubbed Beef Tenderloin",
    slug: "gluten-free-coffee-rubbed-beef-tenderloin",
    description: "Espresso and brown sugar rub with smoky paprika and cayenne — deep flavor and caramelized crust.",
    longDescription: "This Gluten-Free Coffee-Rubbed Beef Tenderloin is for adventurous eaters who love bold, complex flavors. Finely ground espresso is combined with brown sugar, smoked paprika, and a hint of cayenne to create an intensely flavorful rub. During roasting, the coffee and sugar caramelize, forming a dark, beautifully crusted exterior. The coffee adds earthy, slightly bitter notes that complement the beef's richness, while the sugar balances with sweetness and the spices add warmth. The result is a deeply flavored, restaurant-quality dish with a stunning presentation. This is special occasion cooking with a modern twist.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    rating: "4.8",
    calories: 375,
    protein: "43.0",
    carbs: "8.0",
    fat: "18.0",
    fiber: "0.5",
    sugar: "6.0",
    image: "/recipe-images/gluten-free-coffee-rubbed-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "3 tablespoons finely ground espresso or coffee",
      "3 tablespoons brown sugar",
      "1 tablespoon smoked paprika",
      "1 teaspoon cayenne pepper",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 teaspoon garlic powder",
      "2 tablespoons olive oil"
    ],
    instructions: [
      "Preheat oven to 425°F. Pat beef tenderloin completely dry.",
      "In small bowl, combine espresso, brown sugar, paprika, cayenne, salt, pepper, and garlic powder.",
      "Rub olive oil all over beef tenderloin.",
      "Press coffee rub firmly into all sides of beef, coating completely.",
      "Let beef sit at room temperature for 20 minutes to allow rub to adhere.",
      "Heat oven-safe skillet over high heat. Sear beef on all sides until crust is dark and caramelized, about 2-3 minutes per side.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F internal temperature).",
      "Remove from oven and tent with foil. Let rest 10-15 minutes.",
      "Slice into thick medallions, revealing the beautiful crust and pink interior.",
      "Serve immediately, garnished with coffee beans or fresh herbs if desired."
    ],
    tips: "Use finely ground espresso for best results. The crust will look very dark - that's perfect! Don't skimp on resting time. Adjust cayenne to taste for heat level.",
    variations: [
      "Add cinnamon to rub for warmth",
      "Include cocoa powder for depth",
      "Use chipotle powder for smoky heat"
    ],
    tags: ["gluten-free", "beef tenderloin", "coffee-rubbed", "bold", "modern", "caramelized", "spiced", "special occasion", "unique"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Coffee-Rubbed Beef Tenderloin - Bold & Modern",
    seoDescription: "Unique beef tenderloin with espresso, brown sugar, and spice rub. Deep caramelized flavor. Gluten-free."
  },
  {
    title: "Gluten-Free Mushroom Shallot Beef Tenderloin",
    slug: "gluten-free-mushroom-shallot-beef-tenderloin",
    description: "Sautéed mushrooms, shallots, and thyme in a gluten-free pan reduction — rustic and flavorful.",
    longDescription: "This Gluten-Free Mushroom Shallot Beef Tenderloin is rustic elegance at its finest. Meaty mushrooms and sweet shallots are sautéed until golden and caramelized, then deglazed with wine or broth to create a rich, earthy sauce. Fresh thyme adds aromatic notes that tie everything together. The mushrooms add umami depth that enhances the beef's natural savoriness. This is bistro-style cooking - unpretentious but absolutely delicious. The combination of tender beef and savory mushroom sauce is deeply satisfying and perfect for cooler weather dining.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 6,
    rating: "4.9",
    calories: 400,
    protein: "43.0",
    carbs: "8.0",
    fat: "21.0",
    fiber: "1.5",
    sugar: "3.0",
    image: "/recipe-images/gluten-free-mushroom-shallot-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "1 lb mixed mushrooms (cremini, shiitake, oyster), sliced",
      "4 shallots, thinly sliced",
      "3 cloves garlic, minced",
      "1 cup gluten-free beef broth",
      "1/2 cup dry white wine",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "3 sprigs fresh thyme",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F. Season beef generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F). Remove and rest.",
      "While beef roasts, heat 2 tablespoons butter in large skillet over medium-high heat.",
      "Add mushrooms and cook without stirring for 3-4 minutes until golden on bottom.",
      "Stir and continue cooking until mushrooms are deeply browned, about 5 more minutes.",
      "Add shallots, garlic, and thyme. Cook 3-4 minutes until shallots are softened.",
      "Add white wine and simmer until mostly evaporated, about 3 minutes.",
      "Add beef broth and simmer until reduced by half and sauce is thick, about 8 minutes.",
      "Remove from heat and stir in remaining butter. Season with salt and pepper.",
      "Slice beef and serve topped with mushroom-shallot sauce.",
      "Garnish with fresh parsley and serve immediately."
    ],
    tips: "Don't crowd mushrooms when cooking or they'll steam instead of brown. Use variety of mushrooms for complex flavor. Save any beef resting juices to add to sauce.",
    variations: [
      "Add cream for richer sauce",
      "Include porcini mushrooms for depth",
      "Use Marsala wine instead of white"
    ],
    tags: ["gluten-free", "beef tenderloin", "mushroom", "shallot", "rustic", "bistro-style", "earthy", "savory", "elegant"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Mushroom Shallot Beef Tenderloin - Bistro Elegance",
    seoDescription: "Rustic beef tenderloin with sautéed mushrooms, shallots, and thyme. Bistro-style elegance, gluten-free."
  },
  {
    title: "Gluten-Free Balsamic Glazed Beef Tenderloin",
    slug: "gluten-free-balsamic-glazed-beef-tenderloin",
    description: "Sweet-tangy balsamic and honey glaze brushed over roasted tenderloin — glossy and aromatic.",
    longDescription: "This Gluten-Free Balsamic Glazed Beef Tenderloin is a study in sweet-savory balance. Aged balsamic vinegar is reduced with honey until thick and syrupy, creating a glossy glaze with incredible depth. The balsamic provides tangy acidity while the honey adds floral sweetness - together they create a complex sauce that enhances the beef without overwhelming it. As the glaze caramelizes on the meat, it forms a beautiful, shiny coating. This preparation is both sophisticated and approachable, perfect for impressing guests or treating yourself to something special. The contrasting flavors and gorgeous presentation make this a true showstopper.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 385,
    protein: "42.0",
    carbs: "12.0",
    fat: "18.0",
    fiber: "0.0",
    sugar: "10.0",
    image: "/recipe-images/gluten-free-balsamic-glazed-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "1 cup aged balsamic vinegar",
      "1/4 cup honey",
      "3 cloves garlic, minced",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon butter",
      "Fresh rosemary for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F. Pat beef dry and season with salt and pepper.",
      "In small saucepan, combine balsamic vinegar, honey, and garlic. Bring to boil, then reduce heat and simmer 15-20 minutes until reduced by half and syrupy.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until golden brown, about 8 minutes.",
      "Brush half the balsamic glaze over beef.",
      "Transfer to oven and roast 15 minutes.",
      "Remove from oven, brush with more glaze, and return to oven for 5-8 more minutes until 135°F for medium-rare.",
      "Remove beef and tent with foil to rest 10 minutes.",
      "Whisk butter into remaining balsamic glaze until smooth and glossy.",
      "Slice beef into thick medallions and arrange on platter.",
      "Drizzle with remaining balsamic glaze and garnish with fresh rosemary.",
      "Serve immediately."
    ],
    tips: "Use quality aged balsamic for best flavor. Glaze should coat back of spoon when ready. Don't apply glaze too early or it will burn. Let beef rest before slicing.",
    variations: [
      "Add fresh thyme to glaze",
      "Include figs or cherries",
      "Use maple syrup instead of honey"
    ],
    tags: ["gluten-free", "beef tenderloin", "balsamic", "glazed", "sweet-savory", "elegant", "glossy", "special occasion", "impressive"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Balsamic Glazed Beef Tenderloin - Sweet-Savory Perfection",
    seoDescription: "Elegant beef tenderloin with glossy balsamic and honey glaze. Sweet-savory perfection, gluten-free."
  },
  {
    title: "Gluten-Free Horseradish Crusted Beef Tenderloin",
    slug: "gluten-free-horseradish-crusted-beef-tenderloin",
    description: "Creamy horseradish and gluten-free breadcrumbs baked into a golden crust — ideal for holidays.",
    longDescription: "This Gluten-Free Horseradish Crusted Beef Tenderloin is a holiday showstopper that delivers on both flavor and presentation. Fresh horseradish is mixed with gluten-free breadcrumbs, Dijon mustard, and herbs to create a flavorful crust that bakes into a beautiful golden coating. The horseradish provides a pleasant heat that cuts through the richness of the beef, while the breadcrumb crust adds wonderful texture. This classic preparation is elegant enough for Christmas dinner or New Year's Eve, yet the simple technique makes it achievable for home cooks. The combination of tender beef and zesty crust is absolutely delicious.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 6,
    rating: "4.8",
    calories: 410,
    protein: "44.0",
    carbs: "12.0",
    fat: "20.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/gluten-free-horseradish-crusted-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "1 cup gluten-free breadcrumbs",
      "1/2 cup prepared horseradish, drained",
      "3 tablespoons gluten-free Dijon mustard",
      "2 tablespoons fresh parsley, chopped",
      "1 tablespoon fresh thyme",
      "3 tablespoons olive oil, divided",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "2 egg whites, lightly beaten"
    ],
    instructions: [
      "Preheat oven to 425°F. Season beef tenderloin with salt and pepper.",
      "Heat 1 tablespoon olive oil in oven-safe skillet over high heat. Sear beef on all sides until golden, about 6-8 minutes. Remove from skillet.",
      "In bowl, combine breadcrumbs, horseradish, mustard, parsley, thyme, and remaining olive oil.",
      "Brush beef with egg whites on all sides.",
      "Press breadcrumb mixture firmly onto beef, coating completely.",
      "Return to skillet and transfer to oven.",
      "Roast 20-25 minutes until crust is golden brown and internal temperature reaches 135°F for medium-rare.",
      "Remove from oven and tent with foil. Let rest 10 minutes.",
      "Slice carefully to preserve crust and serve on platter.",
      "Garnish with fresh herbs and serve with extra horseradish sauce if desired."
    ],
    tips: "Drain horseradish well or crust will be soggy. Press breadcrumb mixture firmly to help it adhere. Use fresh breadcrumbs for best texture. Let rest before slicing to keep crust intact.",
    variations: [
      "Add grated Parmesan to crust",
      "Include panko for extra crunch",
      "Mix in fresh dill"
    ],
    tags: ["gluten-free", "beef tenderloin", "horseradish", "crusted", "holiday", "christmas", "special occasion", "impressive", "golden"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Horseradish Crusted Beef Tenderloin - Holiday Showstopper",
    seoDescription: "Elegant beef tenderloin with golden horseradish crust. Perfect for holidays and special dinners. Gluten-free."
  },
  {
    title: "Gluten-Free Blue Cheese & Herb Butter Beef Tenderloin",
    slug: "gluten-free-blue-cheese-herb-butter-beef-tenderloin",
    description: "Topped with a melted compound butter of blue cheese, chives, and garlic — rich and luxurious.",
    longDescription: "This Gluten-Free Blue Cheese & Herb Butter Beef Tenderloin is pure decadence. A perfectly cooked beef tenderloin is topped with a luxurious compound butter made from creamy blue cheese, fresh chives, and roasted garlic. As the butter melts over the hot beef, it creates a rich, creamy sauce that's both tangy and savory. The blue cheese adds bold, complex flavor while the herbs provide freshness. This is steakhouse-quality indulgence at home - perfect for when you want to treat yourself or impress someone special. The combination of tender beef and melted blue cheese butter is simply unforgettable.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 6,
    rating: "4.9",
    calories: 445,
    protein: "43.0",
    carbs: "2.0",
    fat: "28.0",
    fiber: "0.0",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-blue-cheese-herb-butter-beef-tenderloin.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "6 tablespoons butter, softened",
      "1/2 cup crumbled blue cheese",
      "3 tablespoons fresh chives, chopped",
      "2 cloves garlic, roasted and mashed",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Fresh chives for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Make compound butter: mix softened butter, blue cheese, chives, and roasted garlic until well combined. Form into log and refrigerate.",
      "Pat beef tenderloin dry and season generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until deeply browned, about 8-10 minutes.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F internal temperature).",
      "Remove from oven and transfer beef to cutting board. Tent with foil and rest 10 minutes.",
      "Slice beef into thick medallions and arrange on warm platter.",
      "Top each slice with a generous pat of blue cheese herb butter while beef is still hot.",
      "Let butter melt slightly, creating a creamy sauce.",
      "Garnish with fresh chives and crumbled blue cheese if desired.",
      "Serve immediately while butter is melting."
    ],
    tips: "Make compound butter ahead and refrigerate until needed. Quality blue cheese makes a difference - try Roquefort or Gorgonzola. Let butter soften to room temperature before mixing. Serve immediately so butter is melting.",
    variations: [
      "Add fresh tarragon to butter",
      "Use Stilton cheese",
      "Include caramelized shallots"
    ],
    tags: ["gluten-free", "beef tenderloin", "blue cheese", "compound butter", "luxurious", "steakhouse", "rich", "special occasion", "indulgent"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Blue Cheese Herb Butter Beef Tenderloin - Luxurious",
    seoDescription: "Indulgent beef tenderloin topped with melted blue cheese and herb butter. Steakhouse luxury, gluten-free."
  },
  {
    title: "Gluten-Free Cider-Braised Beef Tenderloin with Onions",
    slug: "gluten-free-cider-braised-beef-tenderloin-onions",
    description: "A fall twist — tenderloin roasted with apple cider, caramelized onions, and herbs for sweet depth.",
    longDescription: "This Gluten-Free Cider-Braised Beef Tenderloin with Onions is a celebration of autumn flavors. Sweet onions are slowly caramelized until golden and jammy, then combined with apple cider, fresh thyme, and a perfectly roasted beef tenderloin. The cider reduces into a glossy sauce that's both sweet and savory, while the onions add rich, caramelized depth. This preparation brings together the best of fall - tender beef, sweet cider, and golden onions. It's comfort food that's elegant enough for special occasions. Perfect for Thanksgiving or any autumn celebration when you want something special and seasonal.",
    category: "Dinner",
    subcategory: "Beef Dishes",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    rating: "4.9",
    calories: 405,
    protein: "42.0",
    carbs: "18.0",
    fat: "19.0",
    fiber: "2.0",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-cider-braised-beef-tenderloin-onions.png",
    ingredients: [
      "2 lbs beef tenderloin",
      "3 large onions, thinly sliced",
      "1.5 cups apple cider",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "3 sprigs fresh thyme",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1 tablespoon balsamic vinegar",
      "1/2 cup gluten-free beef broth"
    ],
    instructions: [
      "Preheat oven to 400°F. Season beef generously with salt and pepper.",
      "Heat olive oil in oven-safe skillet over high heat. Sear beef on all sides until golden, about 8 minutes. Remove from skillet.",
      "In same skillet over medium-low heat, melt 2 tablespoons butter. Add onions and cook slowly, stirring occasionally, until deeply caramelized, about 30-35 minutes.",
      "Add balsamic vinegar to onions and cook 2 minutes.",
      "Add apple cider, beef broth, and thyme. Bring to simmer.",
      "Return beef to skillet, nestling it into the onions and cider.",
      "Transfer to oven and roast 18-22 minutes for medium-rare (135°F).",
      "Remove beef and tent with foil to rest 10 minutes.",
      "Place skillet over medium-high heat and simmer onion-cider mixture until thickened and syrupy, about 5 minutes.",
      "Remove from heat and stir in remaining butter.",
      "Slice beef and serve topped with caramelized onions and cider sauce.",
      "Garnish with fresh thyme and serve."
    ],
    tips: "Don't rush caramelizing onions - low and slow is key for sweet, jammy texture. Use quality apple cider, not juice. The cider should reduce to a glaze. Rest beef before slicing.",
    variations: [
      "Add dried cranberries to onions",
      "Include rosemary with thyme",
      "Use pear cider for variation"
    ],
    tags: ["gluten-free", "beef tenderloin", "cider", "caramelized onion", "autumn", "fall", "thanksgiving", "seasonal", "sweet-savory"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Cider-Braised Beef Tenderloin with Onions - Autumn Celebration",
    seoDescription: "Fall-inspired beef tenderloin with caramelized onions and apple cider glaze. Perfect for Thanksgiving. Gluten-free."
  }
];

async function addBeefTenderloinRecipes() {
  console.log("Adding 10 Beef Tenderloin recipes to database...");
  
  try {
    for (const recipe of beefTenderloinRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Beef Tenderloin recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addBeefTenderloinRecipes();
