import { db } from "../server/db";
import { recipes } from "../shared/schema";

const turkeyRouladeRecipes = [
  {
    title: "Gluten-Free Turkey Roulade with Spinach & Feta",
    slug: "gluten-free-turkey-roulade-spinach-feta",
    description: "Rolled turkey breast filled with sautéed spinach, garlic, and crumbled feta — finished with lemon herb sauce for an elegant holiday main.",
    longDescription: "This Gluten-Free Turkey Roulade with Spinach & Feta is a showstopping centerpiece that's surprisingly easy to prepare. A butterflied turkey breast is filled with garlicky sautéed spinach and tangy feta cheese, then rolled and tied into a beautiful spiral. As it roasts, the turkey becomes golden and juicy while the filling stays moist and flavorful. The finished roulade is sliced into stunning medallions that reveal the vibrant green and white spiral inside. A bright lemon herb sauce adds the perfect finishing touch. This dish is elegant enough for holiday entertaining but simple enough for a special weeknight dinner.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 6,
    rating: "4.9",
    calories: 285,
    protein: "42.0",
    carbs: "4.0",
    fat: "11.0",
    fiber: "1.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-turkey-roulade-spinach-feta.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "3 cups fresh spinach",
      "4 cloves garlic, minced",
      "1 cup crumbled feta cheese",
      "2 tablespoons olive oil, divided",
      "1 teaspoon dried oregano",
      "2 teaspoons salt, divided",
      "1 teaspoon black pepper, divided",
      "Kitchen twine for tying",
      "1/4 cup lemon juice",
      "2 tablespoons fresh parsley, chopped",
      "1 tablespoon butter"
    ],
    instructions: [
      "Preheat oven to 375°F. If turkey breast isn't already butterflied, use a sharp knife to cut horizontally through the thickest part, opening it like a book. Pound to even 1/2-inch thickness.",
      "Heat 1 tablespoon olive oil in skillet over medium heat. Add garlic and cook 30 seconds until fragrant.",
      "Add spinach and cook 2-3 minutes until wilted. Season with salt and pepper. Let cool slightly, then squeeze out excess moisture.",
      "Lay turkey breast flat and season with 1 teaspoon salt, 1/2 teaspoon pepper, and oregano.",
      "Spread spinach mixture evenly over turkey, leaving 1-inch border. Sprinkle feta over spinach.",
      "Starting from short end, roll turkey tightly. Tie with kitchen twine at 2-inch intervals.",
      "Heat remaining olive oil in oven-safe skillet over medium-high heat. Sear roulade on all sides until golden, about 8 minutes total.",
      "Transfer skillet to oven and roast 40-45 minutes until internal temperature reaches 165°F.",
      "Remove from oven and let rest 10 minutes before slicing.",
      "For sauce: In small pan, melt butter with lemon juice and parsley. Drizzle over sliced roulade.",
      "Remove twine, slice into 1-inch medallions, and serve with lemon herb sauce."
    ],
    tips: "Use a meat mallet to ensure even thickness for uniform cooking. Don't overfill or it will be difficult to roll. Let rest before slicing to keep juices inside.",
    variations: [
      "Add sun-dried tomatoes to the filling",
      "Use goat cheese instead of feta",
      "Substitute kale for spinach"
    ],
    tags: ["gluten-free", "turkey roulade", "spinach", "feta", "holiday", "thanksgiving", "christmas", "elegant", "main dish"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Turkey Roulade with Spinach & Feta - Elegant Holiday Main",
    seoDescription: "Impressive turkey roulade filled with spinach and feta, finished with lemon herb sauce. Perfect gluten-free holiday centerpiece."
  },
  {
    title: "Gluten-Free Cranberry Pecan Turkey Roulade",
    slug: "gluten-free-cranberry-pecan-turkey-roulade",
    description: "Sweet-savory filling of dried cranberries, toasted pecans, and gluten-free breadcrumbs — perfect for Thanksgiving with festive autumn flavors.",
    longDescription: "This Gluten-Free Cranberry Pecan Turkey Roulade is the essence of Thanksgiving in every bite. The filling combines tart dried cranberries with buttery toasted pecans and aromatic herbs, creating a stuffing-inspired center that's both familiar and elegant. Gluten-free breadcrumbs bind everything together while adding texture. As the roulade roasts, the cranberries soften and the pecans add delightful crunch. Each slice reveals a beautiful spiral of ruby red and golden brown filling. This is comfort food elevated to special occasion status.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 55,
    totalTime: 90,
    servings: 8,
    rating: "4.9",
    calories: 320,
    protein: "38.0",
    carbs: "18.0",
    fat: "12.0",
    fiber: "2.5",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-cranberry-pecan-turkey-roulade.png",
    ingredients: [
      "2.5 lbs boneless turkey breast, butterflied",
      "1 cup dried cranberries",
      "1 cup pecans, toasted and chopped",
      "1 cup gluten-free breadcrumbs",
      "1 small onion, finely diced",
      "2 celery stalks, finely diced",
      "3 tablespoons butter",
      "1/2 cup gluten-free chicken broth",
      "2 teaspoons fresh sage, chopped",
      "1 teaspoon fresh thyme",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly turkey breast and pound to even thickness.",
      "In skillet, melt butter over medium heat. Sauté onion and celery 5-6 minutes until soft.",
      "Add sage and thyme, cook 1 minute.",
      "Remove from heat. Stir in breadcrumbs, cranberries, pecans, and broth. Mix until combined.",
      "Season turkey with salt and pepper.",
      "Spread filling evenly over turkey, leaving 1-inch border on all sides.",
      "Roll tightly from short end and tie with twine every 2 inches.",
      "Place seam-side down in roasting pan. Brush with melted butter.",
      "Roast 50-60 minutes until internal temperature reaches 165°F.",
      "Let rest 15 minutes before removing twine and slicing.",
      "Serve with cranberry sauce or pan drippings."
    ],
    tips: "Toast pecans in dry skillet for 3-4 minutes for enhanced flavor. If filling is too dry, add more broth. Make filling day ahead for convenience.",
    variations: [
      "Add orange zest for brightness",
      "Use walnuts instead of pecans",
      "Include dried cherries with cranberries"
    ],
    tags: ["gluten-free", "turkey roulade", "cranberry", "pecan", "thanksgiving", "holiday", "festive", "autumn", "stuffing"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cranberry Pecan Turkey Roulade - Thanksgiving Centerpiece",
    seoDescription: "Festive turkey roulade filled with cranberries, pecans, and herbs. The perfect gluten-free Thanksgiving main dish."
  },
  {
    title: "Gluten-Free Mushroom & Herb Turkey Roulade",
    slug: "gluten-free-mushroom-herb-turkey-roulade",
    description: "Earthy mushroom duxelles rolled into tender turkey — served with white wine pan sauce for sophisticated, restaurant-quality flavor.",
    longDescription: "This Gluten-Free Mushroom & Herb Turkey Roulade showcases the elegance of French cooking with its classic mushroom duxelles filling. Finely chopped mushrooms are sautéed with shallots, garlic, and fresh herbs until deeply concentrated and almost paste-like. This umami-rich filling is spread over butterflied turkey breast and rolled into a beautiful log. The result is incredibly sophisticated, with earthy mushroom flavor in every bite. A white wine pan sauce made from the drippings elevates this to restaurant-quality. Perfect for impressing dinner guests.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 50,
    totalTime: 90,
    servings: 6,
    rating: "4.8",
    calories: 295,
    protein: "41.0",
    carbs: "6.0",
    fat: "11.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/gluten-free-mushroom-herb-turkey-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "1 lb mixed mushrooms (cremini, shiitake), finely chopped",
      "2 shallots, minced",
      "4 cloves garlic, minced",
      "3 tablespoons butter, divided",
      "2 tablespoons fresh thyme",
      "1 tablespoon fresh parsley",
      "1/4 cup dry white wine",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 cup gluten-free chicken broth",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly and pound turkey breast to even thickness.",
      "For duxelles: Melt 2 tablespoons butter in large skillet over medium-high heat. Add shallots and cook 3 minutes.",
      "Add garlic and mushrooms. Cook 12-15 minutes, stirring occasionally, until liquid evaporates and mushrooms are deeply browned.",
      "Stir in thyme and parsley. Season with salt and pepper. Let cool.",
      "Season turkey with salt and pepper. Spread mushroom mixture evenly over surface, leaving borders.",
      "Roll tightly and tie with twine at 2-inch intervals.",
      "Heat remaining butter in oven-safe skillet. Sear roulade on all sides until golden, about 8 minutes.",
      "Transfer to oven and roast 40-45 minutes until 165°F internal temperature.",
      "Remove roulade and let rest. Add wine to skillet, scraping browned bits. Add broth and simmer 5 minutes until slightly reduced.",
      "Slice roulade and serve with white wine sauce."
    ],
    tips: "Chop mushrooms very finely for best texture. Cook until all moisture evaporates for concentrated flavor. Duxelles can be made 2 days ahead.",
    variations: [
      "Add truffle oil for luxury version",
      "Include cream in sauce for richness",
      "Mix in fontina cheese"
    ],
    tags: ["gluten-free", "turkey roulade", "mushroom", "herb", "elegant", "french-inspired", "dinner party", "sophisticated", "holiday"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Mushroom & Herb Turkey Roulade - Elegant French-Inspired",
    seoDescription: "Sophisticated turkey roulade with mushroom duxelles and white wine sauce. Restaurant-quality and gluten-free."
  },
  {
    title: "Gluten-Free Apple Sage Turkey Roulade",
    slug: "gluten-free-apple-sage-turkey-roulade",
    description: "Apple, celery, and sage stuffing with onion and thyme — classic autumn flavor in every bite, perfect for fall celebrations.",
    longDescription: "This Gluten-Free Apple Sage Turkey Roulade captures all the beloved flavors of traditional Thanksgiving stuffing in an elegant presentation. Sweet-tart apples combine with aromatic sage, celery, and onions to create a filling that tastes like home. Each slice reveals a beautiful spiral of autumnal flavors. The apples add moisture and subtle sweetness while sage provides that quintessential holiday aroma. This is comfort food at its finest, reimagined as an impressive centerpiece that's actually quite simple to prepare.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Easy",
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 6,
    rating: "4.9",
    calories: 305,
    protein: "39.0",
    carbs: "16.0",
    fat: "10.0",
    fiber: "2.0",
    sugar: "7.0",
    image: "/recipe-images/gluten-free-apple-sage-turkey-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "2 Granny Smith apples, diced small",
      "1 onion, finely diced",
      "2 celery stalks, finely diced",
      "3 tablespoons butter",
      "2 tablespoons fresh sage, chopped",
      "1 teaspoon fresh thyme",
      "1 cup gluten-free breadcrumbs",
      "1/4 cup gluten-free chicken broth",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly turkey and pound to even thickness.",
      "Melt butter in large skillet over medium heat. Add onion and celery, cook 5-6 minutes until soft.",
      "Add apples and cook 3-4 minutes until slightly softened.",
      "Stir in sage and thyme. Cook 1 minute.",
      "Remove from heat. Mix in breadcrumbs and broth until combined. Season with salt and pepper.",
      "Season turkey with salt and pepper. Spread apple-sage filling evenly, leaving borders.",
      "Roll tightly from short end. Tie with twine every 2 inches.",
      "Place seam-side down in roasting pan.",
      "Roast 45-50 minutes until internal temperature reaches 165°F.",
      "Let rest 10 minutes, remove twine, and slice into medallions."
    ],
    tips: "Use tart apples to balance sweetness. Don't overcook apples in filling or they'll become mushy. Fresh sage is essential for best flavor.",
    variations: [
      "Add dried cranberries for color",
      "Include chestnuts for texture",
      "Use pears instead of apples"
    ],
    tags: ["gluten-free", "turkey roulade", "apple", "sage", "autumn", "thanksgiving", "stuffing", "comfort food", "classic"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Sage Turkey Roulade - Classic Autumn Flavors",
    seoDescription: "Traditional turkey roulade filled with apples, sage, and stuffing flavors. Perfect gluten-free Thanksgiving dish."
  },
  {
    title: "Gluten-Free Prosciutto & Ricotta Turkey Roulade",
    slug: "gluten-free-prosciutto-ricotta-turkey-roulade",
    description: "Layers of prosciutto, herbed ricotta, and spinach rolled tightly and baked to golden perfection — Italian-inspired and indulgent.",
    longDescription: "This Gluten-Free Prosciutto & Ricotta Turkey Roulade brings Italian elegance to the holiday table. Layers of salty prosciutto alternate with creamy herbed ricotta and vibrant spinach, creating a sophisticated filling. The prosciutto adds umami depth while preventing the ricotta from making the turkey soggy. When sliced, the medallions reveal gorgeous layers that look as impressive as they taste. This is a special occasion dish that feels luxurious but comes together easily.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 50,
    totalTime: 85,
    servings: 6,
    rating: "4.8",
    calories: 340,
    protein: "44.0",
    carbs: "3.0",
    fat: "16.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-prosciutto-ricotta-turkey-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "8 slices prosciutto",
      "1 cup whole milk ricotta cheese",
      "1/2 cup grated Parmesan cheese",
      "2 cups fresh spinach, chopped",
      "2 cloves garlic, minced",
      "1 tablespoon fresh basil, chopped",
      "1 tablespoon olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/4 teaspoon nutmeg",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly turkey breast and pound to even thickness.",
      "Heat olive oil in skillet. Add garlic and spinach, cook until wilted. Let cool and squeeze dry.",
      "In bowl, mix ricotta, Parmesan, basil, nutmeg, salt, and pepper. Fold in spinach.",
      "Season turkey with salt and pepper. Lay prosciutto slices over turkey in even layer.",
      "Spread ricotta mixture over prosciutto, leaving 1-inch borders.",
      "Roll tightly from short end. Tie securely with twine every 2 inches.",
      "Place seam-side down in roasting pan. Brush with olive oil.",
      "Roast 45-50 minutes until internal temperature reaches 165°F.",
      "Let rest 15 minutes before removing twine and slicing.",
      "Serve with marinara or white wine sauce if desired."
    ],
    tips: "Pat spinach very dry to prevent soggy filling. Prosciutto layer acts as barrier to keep filling contained. Use good quality ricotta for best texture.",
    variations: [
      "Add sun-dried tomatoes to filling",
      "Use mozzarella instead of ricotta",
      "Include roasted red peppers"
    ],
    tags: ["gluten-free", "turkey roulade", "prosciutto", "ricotta", "italian", "elegant", "holiday", "sophisticated", "spinach"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Prosciutto & Ricotta Turkey Roulade - Italian Elegance",
    seoDescription: "Luxurious turkey roulade with prosciutto, herbed ricotta, and spinach. Italian-inspired and gluten-free."
  },
  {
    title: "Gluten-Free Butternut Squash & Goat Cheese Turkey Roulade",
    slug: "gluten-free-butternut-squash-goat-cheese-turkey-roulade",
    description: "Roasted squash and tangy goat cheese inside juicy turkey breast — creamy, colorful, and elegant with autumn sophistication.",
    longDescription: "This Gluten-Free Butternut Squash & Goat Cheese Turkey Roulade is a celebration of autumn's best flavors. Sweet roasted butternut squash is mashed and combined with tangy goat cheese, creating a filling that's both creamy and complex. The vibrant orange squash makes stunning spirals when sliced, and the goat cheese adds sophistication. Fresh herbs tie everything together. This is an elegant, modern take on holiday turkey that's sure to impress.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 60,
    totalTime: 105,
    servings: 6,
    rating: "4.7",
    calories: 315,
    protein: "40.0",
    carbs: "14.0",
    fat: "12.0",
    fiber: "2.0",
    sugar: "4.0",
    image: "/recipe-images/gluten-free-butternut-squash-goat-cheese-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "2 cups butternut squash, diced small",
      "4 oz goat cheese, softened",
      "2 tablespoons olive oil, divided",
      "2 tablespoons fresh sage, chopped",
      "1 tablespoon fresh rosemary, minced",
      "2 cloves garlic, minced",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/4 teaspoon cinnamon",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 400°F. Toss squash with 1 tablespoon olive oil, salt, and pepper. Roast 25-30 minutes until tender. Let cool slightly.",
      "Mash squash with fork. Mix in goat cheese, sage, rosemary, garlic, and cinnamon. Season to taste.",
      "Reduce oven to 375°F. Butterfly turkey and pound to even thickness.",
      "Season turkey with salt and pepper. Spread squash mixture evenly, leaving borders.",
      "Roll tightly and tie with twine every 2 inches.",
      "Heat remaining oil in oven-safe skillet. Sear roulade on all sides until golden.",
      "Transfer to oven and roast 45-50 minutes until 165°F internal temperature.",
      "Let rest 10 minutes before slicing.",
      "Garnish with fresh herbs and serve."
    ],
    tips: "Make sure squash is well-roasted for sweetness. Don't overfill or it will squeeze out. Goat cheese can be replaced with cream cheese.",
    variations: [
      "Add toasted pecans to filling",
      "Use sweet potato instead of squash",
      "Include dried cranberries"
    ],
    tags: ["gluten-free", "turkey roulade", "butternut squash", "goat cheese", "autumn", "elegant", "holiday", "colorful", "sophisticated"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Butternut Squash & Goat Cheese Turkey Roulade - Autumn Elegance",
    seoDescription: "Stunning turkey roulade with roasted butternut squash and tangy goat cheese. Colorful and gluten-free."
  },
  {
    title: "Gluten-Free Fig & Walnut Turkey Roulade",
    slug: "gluten-free-fig-walnut-turkey-roulade",
    description: "Sweet figs, walnuts, and rosemary folded into the roulade — rich and slightly sweet, ideal for festive dinners with gourmet appeal.",
    longDescription: "This Gluten-Free Fig & Walnut Turkey Roulade is a gourmet delight that combines sweet dried figs with crunchy toasted walnuts. The figs add natural sweetness and a jammy texture, while walnuts provide earthy crunch. Fresh rosemary brings an aromatic, slightly piney note that complements both. This sophisticated combination creates a filling that's both elegant and comforting. Each slice reveals a beautiful mosaic of ingredients. Perfect for impressing guests at special celebrations.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 50,
    totalTime: 85,
    servings: 6,
    rating: "4.8",
    calories: 335,
    protein: "39.0",
    carbs: "20.0",
    fat: "13.0",
    fiber: "3.0",
    sugar: "14.0",
    image: "/recipe-images/gluten-free-fig-walnut-turkey-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "1 cup dried figs, chopped",
      "1 cup walnuts, toasted and chopped",
      "1/2 cup gluten-free breadcrumbs",
      "1 small onion, finely diced",
      "2 tablespoons fresh rosemary, minced",
      "3 tablespoons butter",
      "1/4 cup gluten-free chicken broth",
      "2 tablespoons honey",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly and pound turkey to even thickness.",
      "Melt butter in skillet over medium heat. Sauté onion 5 minutes until soft.",
      "Add rosemary and cook 1 minute.",
      "Remove from heat. Stir in figs, walnuts, breadcrumbs, honey, and broth. Season with salt and pepper.",
      "Season turkey with salt and pepper. Spread fig-walnut mixture evenly, leaving borders.",
      "Roll tightly and tie with twine every 2 inches.",
      "Place seam-side down in roasting pan.",
      "Roast 45-50 minutes until internal temperature reaches 165°F.",
      "Let rest 15 minutes before removing twine and slicing.",
      "Serve with pan drippings or balsamic glaze."
    ],
    tips: "Toast walnuts in dry skillet for enhanced flavor. If filling is dry, add more broth. Honey adds moisture and helps bind ingredients.",
    variations: [
      "Use pecans instead of walnuts",
      "Add orange zest for brightness",
      "Include dried apricots with figs"
    ],
    tags: ["gluten-free", "turkey roulade", "fig", "walnut", "sweet-savory", "gourmet", "holiday", "festive", "elegant"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Fig & Walnut Turkey Roulade - Gourmet Holiday Recipe",
    seoDescription: "Sophisticated turkey roulade with sweet figs, toasted walnuts, and rosemary. Perfect gluten-free special occasion dish."
  },
  {
    title: "Gluten-Free Caramelized Onion & Gruyère Turkey Roulade",
    slug: "gluten-free-caramelized-onion-gruyere-turkey-roulade",
    description: "Sweet caramelized onions and melted Gruyère cheese create a savory, French-inspired centerpiece — sophisticated and richly flavored.",
    longDescription: "This Gluten-Free Caramelized Onion & Gruyère Turkey Roulade is French bistro elegance on a plate. Slowly caramelized onions develop deep, sweet complexity that pairs beautifully with nutty Gruyère cheese. As the roulade roasts, the cheese melts into the onions, creating pockets of gooey deliciousness. Fresh thyme adds an herbal note that ties everything together. This is comfort food with a sophisticated edge, perfect for when you want to serve something special but approachable.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 50,
    cookTime: 50,
    totalTime: 100,
    servings: 6,
    rating: "4.9",
    calories: 330,
    protein: "42.0",
    carbs: "8.0",
    fat: "14.0",
    fiber: "1.0",
    sugar: "4.0",
    image: "/recipe-images/gluten-free-caramelized-onion-gruyere-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "3 large onions, thinly sliced",
      "1.5 cups Gruyère cheese, grated",
      "3 tablespoons butter",
      "2 tablespoons fresh thyme",
      "1 tablespoon balsamic vinegar",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/4 teaspoon nutmeg",
      "Kitchen twine"
    ],
    instructions: [
      "Melt butter in large skillet over medium-low heat. Add onions and cook 30-35 minutes, stirring occasionally, until deeply caramelized and golden brown.",
      "Add thyme and balsamic vinegar. Cook 2 minutes more. Season with salt and pepper. Let cool.",
      "Preheat oven to 375°F. Butterfly turkey and pound to even thickness.",
      "Season turkey with salt, pepper, and nutmeg.",
      "Spread caramelized onions evenly over turkey. Sprinkle Gruyère over onions.",
      "Roll tightly from short end. Tie with twine every 2 inches.",
      "Place seam-side down in roasting pan.",
      "Roast 45-50 minutes until internal temperature reaches 165°F.",
      "Let rest 10 minutes before removing twine and slicing.",
      "Serve with pan juices or French onion sauce."
    ],
    tips: "Don't rush caramelizing onions - slow cooking develops sweetness. Use good quality Gruyère for best flavor. Balsamic adds depth to onions.",
    variations: [
      "Add crispy bacon to filling",
      "Use Swiss cheese if Gruyère unavailable",
      "Include sautéed mushrooms"
    ],
    tags: ["gluten-free", "turkey roulade", "caramelized onion", "gruyere", "french-inspired", "sophisticated", "holiday", "elegant", "cheese"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Gruyère Turkey Roulade - French Bistro",
    seoDescription: "Elegant French-inspired turkey roulade with sweet caramelized onions and Gruyère cheese. Sophisticated and gluten-free."
  },
  {
    title: "Gluten-Free Spinach, Artichoke & Parmesan Turkey Roulade",
    slug: "gluten-free-spinach-artichoke-parmesan-roulade",
    description: "Creamy spinach-artichoke filling wrapped inside tender turkey — indulgent yet wholesome, inspired by the classic dip everyone loves.",
    longDescription: "This Gluten-Free Spinach, Artichoke & Parmesan Turkey Roulade transforms the beloved spinach-artichoke dip into an elegant main course. Tender artichoke hearts combine with wilted spinach, cream cheese, and Parmesan to create a rich, creamy filling. Garlic and herbs add aromatic depth. When rolled inside turkey breast and roasted, the filling stays moist and indulgent while the turkey becomes golden and juicy. This is comfort food that feels special enough for holidays.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 50,
    totalTime: 85,
    servings: 6,
    rating: "4.8",
    calories: 315,
    protein: "43.0",
    carbs: "7.0",
    fat: "13.0",
    fiber: "2.5",
    sugar: "2.0",
    image: "/recipe-images/gluten-free-spinach-artichoke-parmesan-roulade.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "2 cups fresh spinach, chopped",
      "1 cup artichoke hearts, chopped",
      "4 oz cream cheese, softened",
      "1/2 cup grated Parmesan cheese",
      "3 cloves garlic, minced",
      "1 tablespoon olive oil",
      "1 teaspoon Italian seasoning",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/4 teaspoon red pepper flakes (optional)",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly turkey and pound to even thickness.",
      "Heat olive oil in skillet. Add garlic and cook 30 seconds. Add spinach and cook until wilted. Let cool and squeeze dry.",
      "In bowl, mix cream cheese, Parmesan, Italian seasoning, salt, pepper, and red pepper flakes if using.",
      "Fold in spinach and artichoke hearts.",
      "Season turkey with salt and pepper. Spread filling evenly, leaving borders.",
      "Roll tightly and tie with twine every 2 inches.",
      "Place seam-side down in roasting pan. Brush with olive oil.",
      "Roast 45-50 minutes until internal temperature reaches 165°F.",
      "Let rest 10 minutes before removing twine and slicing.",
      "Serve with garlic butter or lemon sauce."
    ],
    tips: "Pat spinach and artichokes very dry to prevent watery filling. Room temperature cream cheese mixes easier. Don't overfill or it will squeeze out.",
    variations: [
      "Add mozzarella for extra cheese",
      "Include sun-dried tomatoes",
      "Use frozen artichokes if fresh unavailable"
    ],
    tags: ["gluten-free", "turkey roulade", "spinach", "artichoke", "parmesan", "creamy", "indulgent", "holiday", "comfort food"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Spinach Artichoke Parmesan Turkey Roulade - Indulgent Main",
    seoDescription: "Creamy turkey roulade filled with spinach, artichokes, and Parmesan. Inspired by the classic dip. Gluten-free."
  },
  {
    title: "Gluten-Free Lemon Herb Turkey Roulade with Cider Glaze",
    slug: "gluten-free-lemon-herb-turkey-roulade-cider-glaze",
    description: "Light and refreshing, featuring a citrus-herb filling brushed with apple cider glaze for shine and flavor — bright and elegant.",
    longDescription: "This Gluten-Free Lemon Herb Turkey Roulade with Cider Glaze is a lighter, brighter take on holiday turkey. Fresh lemon zest and juice combine with a medley of herbs to create a vibrant, aromatic filling. The turkey is brushed with a glossy apple cider glaze during roasting, which caramelizes beautifully and adds subtle sweetness. Each bite is fresh and flavorful without being heavy. This is perfect for those who want an elegant centerpiece that won't weigh them down.",
    category: "Holiday",
    subcategory: "Main Dishes",
    difficulty: "Easy",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    rating: "4.7",
    calories: 275,
    protein: "41.0",
    carbs: "10.0",
    fat: "8.0",
    fiber: "0.5",
    sugar: "6.0",
    image: "/recipe-images/gluten-free-lemon-herb-roulade-cider-glaze.png",
    ingredients: [
      "2 lbs boneless turkey breast, butterflied",
      "Zest of 2 lemons",
      "Juice of 1 lemon",
      "2 tablespoons fresh parsley, chopped",
      "2 tablespoons fresh basil, chopped",
      "1 tablespoon fresh thyme",
      "1 tablespoon fresh rosemary, minced",
      "3 cloves garlic, minced",
      "2 tablespoons olive oil",
      "2 teaspoons salt",
      "1 teaspoon black pepper",
      "1/2 cup apple cider",
      "2 tablespoons honey",
      "Kitchen twine"
    ],
    instructions: [
      "Preheat oven to 375°F. Butterfly turkey and pound to even thickness.",
      "In bowl, mix lemon zest, lemon juice, parsley, basil, thyme, rosemary, garlic, 1 tablespoon olive oil, salt, and pepper.",
      "Season turkey with salt and pepper. Spread herb mixture evenly over surface.",
      "Roll tightly and tie with twine every 2 inches.",
      "Heat remaining olive oil in oven-safe skillet. Sear roulade on all sides until golden.",
      "In small bowl, whisk together apple cider and honey for glaze.",
      "Brush roulade generously with cider glaze. Transfer to oven.",
      "Roast 45-50 minutes, brushing with glaze every 15 minutes, until 165°F internal temperature.",
      "Let rest 10 minutes before removing twine and slicing.",
      "Drizzle with remaining glaze and serve."
    ],
    tips: "Use fresh herbs for best flavor. Don't skip basting with glaze - it creates beautiful caramelized exterior. Reserve some glaze for serving.",
    variations: [
      "Add orange zest with lemon",
      "Use maple syrup instead of honey in glaze",
      "Include fresh dill"
    ],
    tags: ["gluten-free", "turkey roulade", "lemon", "herb", "cider glaze", "light", "refreshing", "holiday", "bright"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Lemon Herb Turkey Roulade with Cider Glaze - Light & Bright",
    seoDescription: "Refreshing turkey roulade with lemon herbs and glossy apple cider glaze. Light, bright, and perfect for holidays. Gluten-free."
  }
];

async function addTurkeyRouladeRecipes() {
  console.log("Adding 10 Turkey Roulade recipes to database...");
  
  try {
    for (const recipe of turkeyRouladeRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Turkey Roulade recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addTurkeyRouladeRecipes();
