import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const risottoRecipes = [
  {
    title: "Gluten-Free Lobster Risotto with Lemon Butter & Chives",
    slug: "gluten-free-lobster-risotto-lemon-butter",
    seoTitle: "Gluten-Free Lobster Risotto with Lemon Butter - Elegant & Luxurious",
    description: "Creamy, luxurious risotto made with lobster tail, lemon butter, and fresh chives — elegant and indulgent fine dining at home.",
    longDescription: "This gluten-free lobster risotto is pure luxury on a plate, featuring tender lobster meat folded into creamy arborio rice finished with lemon butter and fresh chives. The risotto is cooked slowly in seafood stock, with each ladle of liquid added gradually to create that signature creamy texture. Lobster tails are poached separately, then chopped and stirred in at the end to preserve their delicate texture. A generous amount of lemon butter adds richness and brightness, while fresh chives provide a subtle onion flavor and beautiful green color. This is the perfect dish for special occasions, romantic dinners, or when you want to treat yourself to restaurant-quality cuisine at home. The combination of sweet lobster, creamy rice, and bright lemon is simply unforgettable.",
    seoDescription: "Gluten-free lobster risotto with lemon butter and chives. Luxurious, creamy Italian rice dish with tender lobster meat. Perfect for special occasions.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-lobster-risotto-lemon-butter.png",
    ingredients: [
      "2 lobster tails (about 6-8 oz each)",
      "1.5 cups arborio rice",
      "5 cups gluten-free seafood or fish stock, kept warm",
      "1/2 cup dry white wine (ensure gluten-free)",
      "1 shallot, finely minced",
      "3 cloves garlic, minced",
      "4 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "Zest of 1 lemon",
      "Juice of 1 lemon",
      "1/2 cup grated Parmesan cheese",
      "1/4 cup fresh chives, chopped",
      "Salt and white pepper to taste",
      "Extra chives and lemon wedges for garnish"
    ],
    instructions: [
      "Poach lobster tails in simmering water for 8-10 minutes until cooked through. Remove meat from shells, chop into chunks, and set aside.",
      "Heat olive oil and 2 tablespoons butter in a large pan over medium heat. Add shallot and cook for 2-3 minutes until soft.",
      "Add garlic and cook for 1 minute. Add arborio rice and toast for 2 minutes, stirring constantly until edges are translucent.",
      "Pour in white wine and stir until mostly absorbed.",
      "Begin adding warm stock one ladle at a time, stirring frequently. Wait until liquid is mostly absorbed before adding the next ladle.",
      "Continue for 18-20 minutes until rice is creamy and al dente. You may not need all the stock.",
      "Remove from heat. Stir in remaining 2 tablespoons butter, Parmesan, lemon zest, and lemon juice.",
      "Gently fold in lobster meat and chopped chives.",
      "Season with salt and white pepper to taste.",
      "Serve immediately, garnished with extra chives and lemon wedges."
    ],
    tags: ["gluten-free", "risotto", "lobster", "seafood", "Italian", "luxury", "special occasion", "lemon butter", "elegant", "fine dining"],
    nutrition: {
      calories: 520,
      protein: "28g",
      carbs: "58g",
      fat: "18g",
      fiber: "2g",
      sodium: "880mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free BBQ Eel Risotto with Scallions & Sesame Oil",
    slug: "gluten-free-bbq-eel-risotto-scallions-sesame",
    seoTitle: "Gluten-Free BBQ Eel Risotto - Asian Fusion Elegance",
    description: "Asian-fusion risotto featuring grilled eel glazed in gluten-free BBQ sauce, finished with scallions and sesame oil.",
    longDescription: "This gluten-free BBQ eel risotto is a stunning fusion dish that marries Italian technique with Japanese flavors. Creamy arborio rice is cooked in a blend of seafood stock and a touch of sake, creating a base that's familiar yet exotic. Grilled unagi (eel) is glazed with gluten-free BBQ sauce and placed atop the risotto, its sweet-savory flavor complementing the creamy rice perfectly. Toasted sesame oil adds nutty depth, while fresh scallions provide brightness and crunch. Sesame seeds scattered on top add texture and visual appeal. This dish is for adventurous eaters who appreciate the delicate, rich flavor of eel and enjoy creative fusion cuisine. It's impressive enough for dinner parties yet approachable enough for weeknight experimentation.",
    seoDescription: "Gluten-free BBQ eel risotto with scallions and sesame oil. Asian fusion creamy rice dish with grilled unagi and sweet BBQ glaze.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-bbq-eel-risotto-scallions-sesame.png",
    ingredients: [
      "8 oz prepared BBQ eel (unagi), sliced",
      "1.5 cups arborio rice",
      "5 cups gluten-free seafood stock, kept warm",
      "1/4 cup sake (ensure gluten-free) or water",
      "1 shallot, minced",
      "3 cloves garlic, minced",
      "2 tablespoons butter",
      "2 tablespoons vegetable oil",
      "2 tablespoons gluten-free soy sauce or tamari",
      "1 tablespoon toasted sesame oil",
      "3 scallions, sliced (white and green parts separated)",
      "2 tablespoons sesame seeds, toasted",
      "1 tablespoon gluten-free BBQ or eel sauce",
      "Salt and white pepper to taste"
    ],
    instructions: [
      "Heat BBQ eel according to package directions (usually broiled or microwaved). Keep warm and set aside.",
      "Heat vegetable oil and butter in a large pan over medium heat. Add white parts of scallions and garlic, cook for 2 minutes.",
      "Add arborio rice and toast for 2 minutes, stirring constantly.",
      "Pour in sake and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently. Wait until mostly absorbed before adding more.",
      "Continue for 18-20 minutes until rice is creamy and al dente.",
      "Remove from heat. Stir in soy sauce and sesame oil.",
      "Season with salt and white pepper.",
      "Divide risotto among bowls. Top with sliced BBQ eel.",
      "Drizzle with BBQ sauce, sprinkle with sesame seeds and green scallions."
    ],
    tags: ["gluten-free", "risotto", "eel", "unagi", "Asian fusion", "Japanese", "BBQ", "sesame", "seafood", "unique"],
    nutrition: {
      calories: 480,
      protein: "22g",
      carbs: "62g",
      fat: "15g",
      fiber: "2g",
      sodium: "920mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Alligator Risotto with Cajun Cream Sauce",
    slug: "gluten-free-alligator-risotto-cajun-cream",
    seoTitle: "Gluten-Free Alligator Risotto with Cajun Cream - Southern Exotic",
    description: "Southern-inspired dish with tender alligator bites, smoky Cajun seasoning, and creamy risotto base — bold and adventurous.",
    longDescription: "This gluten-free alligator risotto brings Southern Louisiana flavors to Italian technique in an unforgettable fusion. Alligator meat, which tastes like a cross between chicken and fish with a firm texture, is seasoned with Cajun spices and seared until golden. The risotto is cooked in chicken stock and finished with a Cajun cream sauce that adds richness and a touch of heat. Smoky paprika, cayenne, and thyme create authentic Creole flavor, while the creamy rice provides a comforting base. This is a conversation-starter dish that's perfect for adventurous eaters and those who love bold, spicy flavors. If you can't find alligator, chicken thighs make an excellent substitute while maintaining the Southern comfort feel.",
    seoDescription: "Gluten-free alligator risotto with Cajun cream sauce. Bold Southern fusion with tender alligator meat, smoky spices, and creamy Italian rice.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-alligator-risotto-cajun-cream.png",
    ingredients: [
      "12 oz alligator meat, cut into bite-sized pieces",
      "1.5 cups arborio rice",
      "5 cups gluten-free chicken stock, kept warm",
      "1/2 cup heavy cream",
      "1 onion, finely diced",
      "1 bell pepper, diced",
      "2 celery stalks, diced",
      "4 cloves garlic, minced",
      "3 tablespoons butter",
      "2 tablespoons olive oil",
      "2 teaspoons Cajun seasoning (ensure gluten-free)",
      "1 teaspoon smoked paprika",
      "1/2 teaspoon cayenne pepper",
      "1/2 cup grated Parmesan",
      "Fresh parsley and green onions for garnish",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Season alligator pieces with 1 teaspoon Cajun seasoning, salt, and pepper. Set aside.",
      "Heat olive oil in a large pan over medium-high heat. Sear alligator until golden, about 3-4 minutes per side. Remove and set aside.",
      "In the same pan, add butter. Sauté onion, bell pepper, and celery for 5 minutes until soft.",
      "Add garlic, remaining Cajun seasoning, paprika, and cayenne. Cook for 1 minute.",
      "Add arborio rice and toast for 2 minutes.",
      "Begin adding warm stock one ladle at a time, stirring frequently until absorbed.",
      "Continue for 18-20 minutes until rice is creamy.",
      "Stir in heavy cream and Parmesan.",
      "Fold in cooked alligator pieces.",
      "Serve hot, garnished with parsley and green onions."
    ],
    tags: ["gluten-free", "risotto", "alligator", "Cajun", "Southern", "exotic meat", "spicy", "Louisiana", "fusion", "adventurous"],
    nutrition: {
      calories: 550,
      protein: "30g",
      carbs: "60g",
      fat: "20g",
      fiber: "3g",
      sodium: "850mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Salmon Risotto with Dill & Lemon Zest",
    slug: "gluten-free-salmon-risotto-dill-lemon",
    seoTitle: "Gluten-Free Salmon Risotto with Dill & Lemon - Fresh & Bright",
    description: "Flaky salmon stirred through a light lemon-dill risotto — balanced, bright, and satisfying seafood comfort.",
    longDescription: "This gluten-free salmon risotto is a lighter, brighter take on the classic Italian dish, featuring flaky salmon, fresh dill, and lemon zest. The risotto is cooked in fish or vegetable stock, creating a delicate base that doesn't overpower the salmon. Fresh or roasted salmon is flaked and gently folded in at the end to maintain its texture. Lemon zest and juice add brightness, while fresh dill provides an herbaceous note that pairs beautifully with seafood. A touch of cream and Parmesan creates richness without heaviness. This is perfect for spring and summer dinners, or anytime you want something elegant yet light. It's sophisticated enough for guests but simple enough for a weeknight meal.",
    seoDescription: "Gluten-free salmon risotto with fresh dill and lemon zest. Light, bright Italian rice dish with flaky salmon and herbaceous flavors.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-salmon-risotto-dill-lemon.png",
    ingredients: [
      "12 oz salmon fillet, skin removed",
      "1.5 cups arborio rice",
      "5 cups gluten-free fish or vegetable stock, kept warm",
      "1/2 cup dry white wine",
      "1 shallot, minced",
      "2 cloves garlic, minced",
      "3 tablespoons butter",
      "2 tablespoons olive oil",
      "Zest of 2 lemons",
      "Juice of 1 lemon",
      "1/4 cup fresh dill, chopped",
      "1/2 cup grated Parmesan",
      "1/4 cup heavy cream (optional)",
      "Salt and white pepper to taste",
      "Lemon wedges and dill sprigs for garnish"
    ],
    instructions: [
      "Season salmon with salt and pepper. Roast at 400°F for 12-15 minutes or pan-sear until cooked through. Flake into chunks and set aside.",
      "Heat olive oil and 2 tablespoons butter in a large pan over medium heat. Add shallot and cook for 2 minutes.",
      "Add garlic and cook for 1 minute. Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently until absorbed.",
      "Continue for 18-20 minutes until rice is creamy and al dente.",
      "Remove from heat. Stir in remaining butter, Parmesan, cream (if using), lemon zest, lemon juice, and half the dill.",
      "Gently fold in flaked salmon.",
      "Season with salt and white pepper.",
      "Serve garnished with remaining dill, lemon wedges, and extra Parmesan."
    ],
    tags: ["gluten-free", "risotto", "salmon", "seafood", "lemon", "dill", "Italian", "light", "fresh", "healthy"],
    nutrition: {
      calories: 490,
      protein: "26g",
      carbs: "58g",
      fat: "16g",
      fiber: "2g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Chicken & Mushroom Risotto with Parmesan Cream",
    slug: "gluten-free-chicken-mushroom-risotto-parmesan",
    seoTitle: "Gluten-Free Chicken & Mushroom Risotto - Classic Comfort",
    description: "A comfort classic — sautéed mushrooms, tender chicken, and parmesan-infused cream sauce create the ultimate cozy meal.",
    longDescription: "This gluten-free chicken and mushroom risotto is the epitome of comfort food, bringing together tender chicken, earthy mushrooms, and creamy Parmesan rice in perfect harmony. Chicken thighs are seasoned and seared until golden, then set aside while the risotto cooks. A variety of mushrooms — shiitake, cremini, and oyster — are sautéed separately to develop their deep, umami flavors. The arborio rice is cooked slowly in chicken stock, with Parmesan and cream stirred in at the end for extra richness. The chicken and mushrooms are folded back in, creating a dish that's hearty, satisfying, and deeply flavorful. This is the risotto you make when you want pure comfort — it's warm, rich, and feels like a hug in a bowl.",
    seoDescription: "Gluten-free chicken and mushroom risotto with Parmesan cream. Classic comfort food with tender chicken, sautéed mushrooms, and creamy rice.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-chicken-mushroom-risotto-parmesan.png",
    ingredients: [
      "1 lb boneless, skinless chicken thighs, diced",
      "8 oz mixed mushrooms (shiitake, cremini, oyster), sliced",
      "1.5 cups arborio rice",
      "5 cups gluten-free chicken stock, kept warm",
      "1/2 cup dry white wine",
      "1 onion, finely diced",
      "3 cloves garlic, minced",
      "4 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "1/2 cup heavy cream",
      "3/4 cup grated Parmesan, plus extra for serving",
      "2 teaspoons fresh thyme leaves",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Season chicken with salt and pepper. Heat 1 tablespoon olive oil in a large pan over medium-high heat. Cook chicken until golden and cooked through, about 6-7 minutes. Remove and set aside.",
      "In the same pan, add 2 tablespoons butter. Sauté mushrooms until browned, about 5-6 minutes. Remove and set aside.",
      "Add remaining oil and 1 tablespoon butter. Sauté onion for 3 minutes until soft. Add garlic and thyme, cook 1 minute.",
      "Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently.",
      "Continue for 18-20 minutes until rice is creamy and al dente.",
      "Stir in remaining butter, cream, and Parmesan.",
      "Fold in cooked chicken and mushrooms. Season with salt and pepper.",
      "Serve hot with extra Parmesan and fresh parsley."
    ],
    tags: ["gluten-free", "risotto", "chicken", "mushroom", "Italian", "comfort food", "Parmesan", "creamy", "hearty", "classic"],
    nutrition: {
      calories: 580,
      protein: "32g",
      carbs: "60g",
      fat: "22g",
      fiber: "3g",
      sodium: "890mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Beef Risotto with Red Wine Reduction & Thyme",
    slug: "gluten-free-beef-risotto-red-wine-thyme",
    seoTitle: "Gluten-Free Beef Risotto with Red Wine & Thyme - Rich & Hearty",
    description: "Deep, rich risotto cooked with red wine, beef broth, and fresh thyme — bold, hearty, and sophisticated.",
    longDescription: "This gluten-free beef risotto is a bold, sophisticated dish that showcases the depth of flavor that comes from red wine and beef. Tender beef pieces are seared until caramelized, creating a flavorful base. The arborio rice is cooked in a combination of rich beef stock and red wine, which gives the risotto a beautiful burgundy tint and deep, complex flavor. Fresh thyme adds an earthy, aromatic note that complements the beef beautifully. A red wine reduction drizzled on top adds intensity and elegance. This is a hearty, warming dish perfect for cold evenings or when you want something truly substantial. It's rich without being heavy, and the wine adds a sophisticated touch that elevates it beyond everyday comfort food.",
    seoDescription: "Gluten-free beef risotto with red wine reduction and fresh thyme. Rich, hearty Italian rice with tender beef and bold wine flavors.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 40,
    totalTime: 60,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-beef-risotto-red-wine-thyme.png",
    ingredients: [
      "12 oz beef sirloin or tenderloin, cut into small pieces",
      "1.5 cups arborio rice",
      "4 cups gluten-free beef stock, kept warm",
      "1 cup dry red wine (ensure gluten-free), divided",
      "1 onion, finely diced",
      "3 cloves garlic, minced",
      "4 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "3 sprigs fresh thyme, plus extra for garnish",
      "1/2 cup grated Parmesan",
      "2 tablespoons tomato paste",
      "Salt and pepper to taste",
      "Balsamic glaze for drizzling (optional)"
    ],
    instructions: [
      "Season beef with salt and pepper. Heat olive oil in a large pan over high heat. Sear beef until browned but still medium-rare, about 2-3 minutes. Remove and set aside.",
      "Reduce heat to medium. Add 2 tablespoons butter and onion. Cook for 3 minutes. Add garlic and cook 1 minute.",
      "Stir in tomato paste and cook for 1 minute.",
      "Add rice and toast for 2 minutes.",
      "Pour in 3/4 cup red wine and stir until absorbed.",
      "Begin adding warm beef stock one ladle at a time, stirring frequently.",
      "Add thyme sprigs to the pan. Continue cooking for 18-20 minutes until rice is creamy.",
      "Meanwhile, make wine reduction: simmer remaining 1/4 cup wine in a small pot until reduced by half.",
      "Remove thyme sprigs. Stir in remaining butter and Parmesan.",
      "Fold in beef pieces. Serve drizzled with wine reduction and garnished with fresh thyme."
    ],
    tags: ["gluten-free", "risotto", "beef", "red wine", "Italian", "hearty", "sophisticated", "thyme", "rich", "comfort food"],
    nutrition: {
      calories: 560,
      protein: "28g",
      carbs: "62g",
      fat: "20g",
      fiber: "2g",
      sodium: "840mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Venison Risotto with Blackberry Compote",
    slug: "gluten-free-venison-risotto-blackberry-compote",
    seoTitle: "Gluten-Free Venison Risotto with Blackberry Compote - Gourmet Game",
    description: "Game-inspired risotto with seared venison medallions and sweet-tart blackberry finish — gourmet, seasonal, and elegant.",
    longDescription: "This gluten-free venison risotto is a show-stopping gourmet dish that pairs the rich, earthy flavor of venison with a sweet-tart blackberry compote. Venison medallions are seasoned and seared to medium-rare perfection, then sliced and served atop creamy risotto. The arborio rice is cooked in a blend of beef and vegetable stock with fresh herbs. The blackberry compote — made with fresh blackberries, red wine, and a touch of honey — adds a beautiful contrast of flavors and colors. The sweetness of the berries balances the gamey richness of the venison, while the wine ties everything together. This is perfect for fall dinners, special occasions, or when you want to impress with restaurant-quality cuisine at home.",
    seoDescription: "Gluten-free venison risotto with blackberry compote. Gourmet game meat with sweet-tart berry sauce and creamy Italian rice. Perfect for special occasions.",
    category: "Entrees",
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    servings: 4,
    difficulty: "Hard",
    image: "/recipe-images/gluten-free-venison-risotto-blackberry-compote.png",
    ingredients: [
      "12 oz venison tenderloin",
      "1.5 cups arborio rice",
      "4 cups gluten-free beef or vegetable stock, kept warm",
      "1/2 cup dry red wine",
      "1 shallot, minced",
      "3 cloves garlic, minced",
      "4 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "1/2 cup grated Parmesan",
      "Fresh rosemary and thyme",
      "For blackberry compote: 1 cup fresh blackberries, 1/4 cup red wine, 2 tablespoons honey, 1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
      "Fresh herbs for garnish"
    ],
    instructions: [
      "Make blackberry compote: Combine blackberries, red wine, honey, and balsamic in a saucepan. Simmer for 10-12 minutes until thickened. Set aside.",
      "Season venison with salt, pepper, and rosemary. Heat 1 tablespoon olive oil in a pan over high heat. Sear venison 3-4 minutes per side for medium-rare. Rest 5 minutes, then slice.",
      "In a large pan, heat remaining oil and 2 tablespoons butter. Cook shallot for 2 minutes. Add garlic and cook 1 minute.",
      "Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently.",
      "Continue for 18-20 minutes until creamy.",
      "Stir in remaining butter, Parmesan, and thyme.",
      "Divide risotto among plates. Top with sliced venison and drizzle with blackberry compote.",
      "Garnish with fresh herbs."
    ],
    tags: ["gluten-free", "risotto", "venison", "game meat", "blackberry", "gourmet", "elegant", "special occasion", "fall", "sophisticated"],
    nutrition: {
      calories: 540,
      protein: "30g",
      carbs: "65g",
      fat: "18g",
      fiber: "4g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Vegetable Risotto with Asparagus & Peas",
    slug: "gluten-free-vegetable-risotto-asparagus-peas",
    seoTitle: "Gluten-Free Vegetable Risotto with Asparagus & Peas - Spring Fresh",
    description: "A spring-forward vegetarian option with asparagus, peas, lemon zest, and Parmesan — light yet rich and satisfying.",
    longDescription: "This gluten-free vegetable risotto celebrates the bright, fresh flavors of spring with tender asparagus, sweet peas, and aromatic lemon zest. The risotto is cooked in vegetable stock, creating a lighter base that lets the vegetables shine. Fresh asparagus is blanched until crisp-tender, then cut into pieces and added at the end. Sweet peas — fresh or frozen — add pops of sweetness and beautiful green color. Lemon zest brightens everything up, while Parmesan adds richness and umami depth. This is the perfect vegetarian main course or elegant side dish. It's light enough for warm weather yet rich enough to satisfy, and the vibrant green colors make it as beautiful as it is delicious.",
    seoDescription: "Gluten-free vegetable risotto with asparagus and peas. Light, fresh spring vegetarian dish with lemon, Parmesan, and vibrant green vegetables.",
    category: "Entrees",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 4,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-vegetable-risotto-asparagus-peas.png",
    ingredients: [
      "1 bunch asparagus (about 12 oz), trimmed and cut into 1-inch pieces",
      "1 cup fresh or frozen peas",
      "1.5 cups arborio rice",
      "5 cups gluten-free vegetable stock, kept warm",
      "1/2 cup dry white wine",
      "1 shallot, minced",
      "2 cloves garlic, minced",
      "4 tablespoons butter",
      "2 tablespoons olive oil",
      "Zest of 1 lemon",
      "Juice of 1/2 lemon",
      "3/4 cup grated Parmesan, plus extra for serving",
      "Fresh mint or basil, chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Blanch asparagus in boiling salted water for 2-3 minutes until crisp-tender. Drain and set aside.",
      "Heat olive oil and 2 tablespoons butter in a large pan over medium heat. Add shallot and cook for 2 minutes.",
      "Add garlic and cook for 1 minute. Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently.",
      "After 15 minutes, add peas to the pan.",
      "Continue cooking for 3-5 more minutes until rice is creamy and al dente.",
      "Remove from heat. Stir in remaining butter, Parmesan, lemon zest, and lemon juice.",
      "Fold in blanched asparagus and fresh herbs.",
      "Season with salt and pepper.",
      "Serve immediately with extra Parmesan and herbs."
    ],
    tags: ["gluten-free", "risotto", "vegetarian", "asparagus", "peas", "spring", "Italian", "light", "fresh", "healthy"],
    nutrition: {
      calories: 450,
      protein: "14g",
      carbs: "64g",
      fat: "16g",
      fiber: "5g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Shrimp & Chorizo Risotto with Smoked Paprika",
    slug: "gluten-free-shrimp-chorizo-risotto-paprika",
    seoTitle: "Gluten-Free Shrimp & Chorizo Risotto - Spanish-Inspired Bold",
    description: "Spicy Spanish-inspired risotto featuring shrimp, chorizo, and smoked paprika — vibrant, full-flavored, and satisfying.",
    longDescription: "This gluten-free shrimp and chorizo risotto brings bold Spanish flavors to Italian technique in a fusion that's absolutely irresistible. Spanish chorizo provides smoky, spicy depth, while plump shrimp add sweetness and elegance. Smoked paprika infuses the risotto with gorgeous color and smoky flavor reminiscent of paella. The combination of seafood stock and the oils from the chorizo create an incredibly flavorful base. Fresh parsley and a squeeze of lemon at the end add brightness that balances the richness. This dish has the comfort of risotto with the excitement of Spanish cuisine — it's bold, colorful, and packed with flavor. Perfect for when you want something that feels special but comes together relatively quickly.",
    seoDescription: "Gluten-free shrimp and chorizo risotto with smoked paprika. Spanish-inspired creamy rice with spicy chorizo and tender shrimp. Bold and flavorful.",
    category: "Entrees",
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-shrimp-chorizo-risotto-paprika.png",
    ingredients: [
      "12 oz large shrimp, peeled and deveined",
      "6 oz Spanish chorizo, sliced",
      "1.5 cups arborio rice",
      "5 cups gluten-free seafood or chicken stock, kept warm",
      "1/2 cup dry white wine",
      "1 onion, finely diced",
      "3 cloves garlic, minced",
      "3 tablespoons butter",
      "2 tablespoons olive oil",
      "2 teaspoons smoked paprika",
      "1/2 teaspoon red pepper flakes (optional)",
      "1/2 cup grated Manchego or Parmesan",
      "Fresh parsley, chopped",
      "Lemon wedges for serving",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Heat 1 tablespoon olive oil in a large pan. Cook chorizo slices until crispy, about 3-4 minutes. Remove and set aside.",
      "Season shrimp with salt and pepper. In the same pan, cook shrimp until pink, about 2 minutes per side. Remove and set aside.",
      "Add remaining oil and butter to pan. Sauté onion for 3 minutes. Add garlic, smoked paprika, and red pepper flakes. Cook 1 minute.",
      "Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently.",
      "Continue for 18-20 minutes until rice is creamy.",
      "Stir in cheese.",
      "Fold in cooked chorizo and shrimp. Season with salt and pepper.",
      "Serve hot, garnished with fresh parsley and lemon wedges."
    ],
    tags: ["gluten-free", "risotto", "shrimp", "chorizo", "Spanish", "seafood", "spicy", "paprika", "bold", "fusion"],
    nutrition: {
      calories: 560,
      protein: "30g",
      carbs: "60g",
      fat: "20g",
      fiber: "2g",
      sodium: "980mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Truffle & Wild Mushroom Risotto",
    slug: "gluten-free-truffle-wild-mushroom-risotto",
    seoTitle: "Gluten-Free Truffle & Wild Mushroom Risotto - Pure Luxury",
    description: "Earthy, aromatic, and elegant — wild mushrooms, truffle oil, and creamy rice for pure luxury and indulgence.",
    longDescription: "This gluten-free truffle and wild mushroom risotto is the ultimate in luxury comfort food, featuring an assortment of wild mushrooms and the intoxicating aroma of truffle. A mix of shiitake, porcini, oyster, and cremini mushrooms are sautéed separately to develop their deep, earthy flavors, then stirred into creamy arborio rice. The risotto is cooked in a mushroom-infused stock made from dried porcini, creating layers of umami depth. Truffle oil is drizzled at the end, filling the kitchen with its distinctive aroma. Fresh truffle shavings on top (if available) take it to restaurant-level elegance. This is the risotto for special occasions, romantic dinners, or when you want to treat yourself to something truly extraordinary. It's earthy, aromatic, and absolutely unforgettable.",
    seoDescription: "Gluten-free truffle and wild mushroom risotto. Luxurious Italian rice with assorted wild mushrooms, truffle oil, and Parmesan. Pure indulgence.",
    category: "Entrees",
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    servings: 4,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-truffle-wild-mushroom-risotto.png",
    ingredients: [
      "12 oz mixed wild mushrooms (shiitake, oyster, porcini, cremini), sliced",
      "1 oz dried porcini mushrooms",
      "1.5 cups arborio rice",
      "4 cups gluten-free vegetable stock",
      "1/2 cup dry white wine",
      "1 shallot, minced",
      "4 cloves garlic, minced",
      "5 tablespoons butter, divided",
      "3 tablespoons olive oil",
      "3/4 cup grated Parmesan",
      "2-3 tablespoons truffle oil",
      "Fresh thyme",
      "Fresh truffle shavings (optional)",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Soak dried porcini in 1 cup hot water for 15 minutes. Drain, reserving liquid. Chop porcini and add liquid to stock. Keep stock warm.",
      "Heat 2 tablespoons olive oil and 2 tablespoons butter in a large pan. Sauté all mushrooms (fresh and soaked porcini) until browned, 8-10 minutes. Season with salt and pepper. Remove and set aside.",
      "In the same pan, add remaining oil and 2 tablespoons butter. Cook shallot for 2 minutes. Add garlic and thyme, cook 1 minute.",
      "Add rice and toast for 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring frequently.",
      "Continue for 18-20 minutes until creamy.",
      "Stir in remaining butter, Parmesan, and half the mushrooms.",
      "Remove from heat and drizzle with truffle oil.",
      "Serve topped with remaining mushrooms, truffle shavings (if using), and fresh parsley."
    ],
    tags: ["gluten-free", "risotto", "truffle", "wild mushrooms", "luxury", "Italian", "gourmet", "earthy", "elegant", "special occasion"],
    nutrition: {
      calories: 520,
      protein: "16g",
      carbs: "62g",
      fat: "24g",
      fiber: "4g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  }
];

async function addRecipes() {
  console.log("Adding 10 Gluten-Free Risotto recipes...");
  
  for (const recipe of risottoRecipes) {
    try {
      await db.insert(recipes).values({
        id: nanoid(),
        ...recipe,
        rating: "4.8",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`✓ Added: ${recipe.title}`);
    } catch (error) {
      console.error(`✗ Error adding ${recipe.title}:`, error);
    }
  }
  
  console.log("\n✅ All recipes added successfully!");
  process.exit(0);
}

addRecipes();
