import { db } from "../server/db";
import { recipes } from "../shared/schema";

const brieMushroomRecipes = [
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Garlic & Herbs",
    slug: "gluten-free-brie-stuffed-mushrooms-garlic-herbs",
    description: "Classic roasted mushrooms filled with creamy brie, minced garlic, and fresh thyme — a warm, aromatic bite perfect for entertaining.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Garlic & Herbs are the quintessential elegant appetizer. Baby bella mushrooms are cleaned and stems removed, creating perfect little cups for the filling. Each cap is filled with creamy brie cheese, then topped with aromatic minced garlic and fresh thyme before roasting until golden and bubbling. The combination is simple but absolutely divine - earthy mushrooms, rich creamy cheese, pungent garlic, and fragrant herbs. As they bake, the brie melts into the mushroom caps while the garlic becomes sweet and mellow. These are sophisticated enough for holiday parties yet easy enough for weeknight entertaining. Serve them hot from the oven on a rustic wooden board and watch them disappear.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 24,
    rating: "5.0",
    calories: 45,
    protein: "2.5",
    carbs: "2.0",
    fat: "3.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-garlic-herbs.png",
    ingredients: [
      "24 cremini or baby bella mushrooms",
      "8 oz brie cheese, cut into small pieces",
      "4 cloves garlic, minced",
      "3 tablespoons fresh thyme leaves",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Clean mushrooms with damp paper towel. Remove stems and gently scrape out gills if desired to create more room for filling.",
      "Arrange mushroom caps gill-side up on prepared baking sheet.",
      "Brush mushroom caps lightly with olive oil inside and out.",
      "Season with salt and pepper.",
      "Fill each mushroom cap with a piece of brie cheese.",
      "Top brie with minced garlic and fresh thyme leaves.",
      "Drizzle remaining olive oil over stuffed mushrooms.",
      "Bake 18-20 minutes until mushrooms are tender and cheese is melted and bubbling.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with fresh thyme sprigs and serve hot."
    ],
    tips: "Choose uniform-sized mushrooms for even cooking. Don't wash mushrooms under water - use damp paper towel to prevent sogginess. Can be assembled 4 hours ahead and refrigerated, then baked when ready to serve.",
    variations: [
      "Add crispy breadcrumbs on top (use gluten-free)",
      "Include chopped fresh parsley with thyme",
      "Drizzle with balsamic glaze before serving"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "appetizer", "garlic", "herbs", "party", "entertaining", "vegetarian", "easy"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Garlic & Herbs - Classic Elegant Appetizer",
    seoDescription: "Easy gluten-free brie-stuffed mushrooms with garlic and fresh thyme. Perfect elegant appetizer for parties and entertaining."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Bacon & Thyme",
    slug: "gluten-free-brie-stuffed-mushrooms-bacon-thyme",
    description: "Crispy bacon crumbles, thyme, and melted brie — smoky, savory, and indulgent. The ultimate crowd-pleasing appetizer.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Bacon & Thyme take the classic stuffed mushroom to indulgent new heights. The combination of earthy mushrooms, creamy brie, crispy bacon, and aromatic thyme is absolutely irresistible. Mushroom caps are filled with rich brie cheese, then topped with crispy bacon crumbles and fresh thyme before baking until golden and bubbly. The bacon adds a smoky, salty element that perfectly complements the mild, creamy cheese while the thyme provides herbaceous notes. These are guaranteed crowd-pleasers at any gathering - the kind of appetizer that disappears within minutes. Perfect for game day, holiday parties, or any time you want to impress guests with minimal effort.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 20,
    totalTime: 40,
    servings: 24,
    rating: "5.0",
    calories: 58,
    protein: "3.5",
    carbs: "2.0",
    fat: "4.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-bacon-thyme.png",
    ingredients: [
      "24 cremini mushrooms",
      "8 oz brie cheese, cubed",
      "6 strips bacon, cooked crispy and crumbled",
      "2 tablespoons fresh thyme leaves",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Cook bacon until crispy, drain on paper towels, and crumble. Set aside.",
      "Clean mushrooms with damp towel. Remove stems and hollow out caps slightly.",
      "Arrange mushroom caps on baking sheet.",
      "Brush with olive oil and season with salt and pepper.",
      "Fill each cap with brie cheese.",
      "Top with crumbled bacon and fresh thyme leaves.",
      "Bake 18-20 minutes until cheese is melted and mushrooms are tender.",
      "Let cool 2-3 minutes before serving.",
      "Garnish with additional thyme sprigs and serve warm."
    ],
    tips: "Cook bacon until very crispy so it stays crunchy on the mushrooms. Can substitute turkey bacon for lighter option. Make bacon ahead to save time on party day.",
    variations: [
      "Add caramelized onions with bacon",
      "Use pancetta instead of bacon",
      "Include minced garlic for extra flavor"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "bacon", "thyme", "appetizer", "party", "indulgent", "savory", "crowd-pleaser"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Bacon & Thyme - Indulgent Party Appetizer",
    seoDescription: "Irresistible gluten-free mushrooms stuffed with brie, crispy bacon, and thyme. Perfect savory appetizer for entertaining."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Cranberries & Walnuts",
    slug: "gluten-free-brie-stuffed-mushrooms-cranberries-walnuts",
    description: "Sweet-tart cranberries and toasted walnuts over creamy brie — festive and elegant, perfect for holiday entertaining.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Cranberries & Walnuts are the epitome of holiday elegance. The combination of creamy brie, sweet-tart dried cranberries, and toasted walnuts creates a sophisticated flavor profile that's perfect for festive gatherings. Each mushroom cap is filled with rich brie cheese, then topped with jewel-like cranberries and crunchy walnuts before baking until golden. The cranberries provide pops of sweetness while the walnuts add earthy richness and satisfying crunch. These are beautiful to look at and absolutely delicious - the kind of appetizer that makes your holiday spread look professionally catered. Serve on a white platter garnished with fresh rosemary for stunning presentation.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 20,
    totalTime: 40,
    servings: 24,
    rating: "4.9",
    calories: 52,
    protein: "2.5",
    carbs: "3.5",
    fat: "4.0",
    fiber: "0.5",
    sugar: "2.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-cranberries-walnuts.png",
    ingredients: [
      "24 baby bella mushrooms",
      "8 oz brie cheese, cubed",
      "1/2 cup dried cranberries, chopped",
      "1/2 cup walnuts, toasted and chopped",
      "2 tablespoons olive oil",
      "1 tablespoon fresh rosemary, minced",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Toast walnuts in dry skillet over medium heat 3-4 minutes until fragrant. Chop and set aside.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms with olive oil and season with salt and pepper.",
      "Fill each cap with brie cheese.",
      "Top with chopped cranberries, toasted walnuts, and minced rosemary.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with fresh rosemary sprigs.",
      "Serve warm on elegant platter."
    ],
    tips: "Toast walnuts for deeper flavor - watch carefully as they burn quickly. Fresh or frozen cranberries can be used if you cook them down with a little sugar first. These look beautiful on white serving platters.",
    variations: [
      "Use pecans instead of walnuts",
      "Add a drizzle of honey before baking",
      "Include orange zest for brightness"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "cranberries", "walnuts", "holiday", "festive", "elegant", "appetizer", "thanksgiving", "christmas"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Cranberries & Walnuts - Festive Holiday Appetizer",
    seoDescription: "Elegant gluten-free mushrooms stuffed with brie, cranberries, and walnuts. Perfect festive appetizer for holiday parties."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Spinach & Shallots",
    slug: "gluten-free-brie-stuffed-mushrooms-spinach-shallots",
    description: "Sautéed spinach and caramelized shallots tucked under melted brie — earthy, rich, and wonderfully flavorful.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Spinach & Shallots are a sophisticated appetizer that showcases layers of complementary flavors. Fresh spinach is sautéed until wilted, shallots are caramelized until sweet and golden, and both are nestled into mushroom caps with creamy brie before baking. The result is an elegant bite that's earthy from the mushrooms, rich from the cheese, slightly sweet from the shallots, and fresh from the spinach. These are the kind of appetizers you serve at dinner parties when you want to impress without spending hours in the kitchen. The flavor combination is refined and memorable, and they look absolutely beautiful on the plate.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 20,
    totalTime: 45,
    servings: 24,
    rating: "4.9",
    calories: 48,
    protein: "2.5",
    carbs: "2.5",
    fat: "3.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-spinach-shallots.png",
    ingredients: [
      "24 cremini mushrooms",
      "8 oz brie cheese, cubed",
      "2 cups fresh spinach, chopped",
      "3 shallots, thinly sliced",
      "3 tablespoons olive oil, divided",
      "2 cloves garlic, minced",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 teaspoon nutmeg",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Heat 1 tablespoon olive oil in skillet over medium heat. Add shallots and cook 8-10 minutes until caramelized. Remove and set aside.",
      "In same skillet, add another tablespoon oil. Cook garlic 30 seconds, then add spinach. Cook until wilted, 2-3 minutes. Season with nutmeg, salt, and pepper. Set aside.",
      "Clean mushrooms and remove stems. Arrange on baking sheet.",
      "Brush mushrooms with remaining oil and season lightly.",
      "Place spinach mixture in bottom of each mushroom cap.",
      "Top with brie cheese, then caramelized shallots.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Let rest 2-3 minutes.",
      "Garnish with fresh thyme and serve warm."
    ],
    tips: "Squeeze excess moisture from spinach after cooking to prevent soggy mushrooms. Caramelize shallots slowly for best flavor - they should be golden and sweet. Can prep spinach and shallots a day ahead.",
    variations: [
      "Use Swiss chard instead of spinach",
      "Add pine nuts for crunch",
      "Include sun-dried tomatoes"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "spinach", "shallots", "vegetarian", "elegant", "appetizer", "sophisticated", "party"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Spinach & Shallots - Sophisticated Appetizer",
    seoDescription: "Elegant gluten-free mushrooms with sautéed spinach, caramelized shallots, and brie. Rich, flavorful party appetizer."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Honey & Rosemary",
    slug: "gluten-free-brie-stuffed-mushrooms-honey-rosemary",
    description: "Drizzled with honey and topped with rosemary — a sweet and savory crowd-pleaser with beautiful balance.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Honey & Rosemary are a masterclass in sweet and savory balance. Mushroom caps are filled with creamy brie, topped with fragrant fresh rosemary, then drizzled with golden honey before baking. As they roast, the honey caramelizes slightly, creating a glossy glaze that mingles with the melted brie. The rosemary adds aromatic, piney notes that complement both the sweetness of the honey and the earthiness of the mushrooms. This combination is absolutely magical - sophisticated yet approachable, elegant yet comforting. These are perfect for wine tastings, cocktail parties, or any occasion when you want to serve something memorable. The honey-brie combination is unexpectedly delicious and will have guests asking for the recipe.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 24,
    rating: "5.0",
    calories: 50,
    protein: "2.5",
    carbs: "3.5",
    fat: "3.5",
    fiber: "0.5",
    sugar: "2.5",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-honey-rosemary.png",
    ingredients: [
      "24 baby bella mushrooms",
      "8 oz brie cheese, cubed",
      "3 tablespoons honey",
      "2 tablespoons fresh rosemary leaves, chopped",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms with olive oil inside and out.",
      "Season with salt and pepper.",
      "Fill each mushroom cap with brie cheese.",
      "Sprinkle chopped rosemary over brie.",
      "Drizzle honey generously over each mushroom.",
      "Bake 18-20 minutes until cheese is melted and honey is bubbling.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with fresh rosemary sprigs.",
      "Serve warm with cocktail picks."
    ],
    tips: "Use good quality honey for best flavor. The honey will caramelize and get slightly sticky - this is perfect. These are best served warm while the cheese is still gooey. Pair with white wine or champagne.",
    variations: [
      "Add crumbled goat cheese with brie",
      "Include toasted walnuts",
      "Use thyme instead of rosemary"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "honey", "rosemary", "sweet-savory", "appetizer", "elegant", "party", "wine pairing"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Honey & Rosemary - Sweet & Savory Perfection",
    seoDescription: "Beautiful gluten-free mushrooms with brie, honey, and rosemary. Perfect sweet-savory appetizer for entertaining."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Pesto & Pine Nuts",
    slug: "gluten-free-brie-stuffed-mushrooms-pesto-pine-nuts",
    description: "Bright basil pesto under gooey brie, finished with toasted pine nuts — Italian-inspired and aromatic.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Pesto & Pine Nuts bring vibrant Italian flavors to the classic appetizer. A layer of bright, garlicky basil pesto is spooned into each mushroom cap, topped with creamy brie, then finished with toasted pine nuts before baking. The pesto adds incredible aromatic freshness - basil, garlic, Parmesan, and olive oil - while the brie provides rich creaminess and the pine nuts add buttery crunch. As they bake, the pesto mingles with the melted cheese, creating a flavor combination that's absolutely irresistible. These are perfect for summer entertaining, Italian-themed parties, or any time you want an appetizer with bright, bold flavors. Serve with a crisp white wine for the ultimate pairing.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 20,
    totalTime: 40,
    servings: 24,
    rating: "4.9",
    calories: 55,
    protein: "3.0",
    carbs: "2.0",
    fat: "4.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-pesto-pine-nuts.png",
    ingredients: [
      "24 cremini mushrooms",
      "8 oz brie cheese, cubed",
      "1/2 cup basil pesto (store-bought or homemade)",
      "1/3 cup pine nuts, toasted",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh basil leaves for garnish",
      "Grated Parmesan for serving"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Toast pine nuts in dry skillet over medium heat 2-3 minutes until golden. Set aside.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms with olive oil and season with salt and pepper.",
      "Spoon about 1 teaspoon pesto into each mushroom cap.",
      "Top pesto with brie cheese.",
      "Sprinkle toasted pine nuts over brie.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with fresh basil leaves and grated Parmesan.",
      "Serve warm."
    ],
    tips: "Use gluten-free pesto - check labels carefully as some contain wheat. Toast pine nuts for deeper flavor but watch carefully as they burn easily. Can make own pesto for best quality control.",
    variations: [
      "Use sun-dried tomato pesto",
      "Substitute walnuts for pine nuts",
      "Add fresh mozzarella with brie"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "pesto", "pine nuts", "italian", "basil", "appetizer", "party", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Pesto & Pine Nuts - Italian-Inspired Appetizer",
    seoDescription: "Aromatic gluten-free mushrooms with basil pesto, brie, and toasted pine nuts. Vibrant Italian-inspired appetizer."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Caramelized Onions & Balsamic Glaze",
    slug: "gluten-free-brie-stuffed-mushrooms-caramelized-onions-balsamic",
    description: "Deeply sweet caramelized onions balanced by tangy balsamic reduction — sophisticated and comforting.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Caramelized Onions & Balsamic Glaze are the definition of sophisticated comfort food. Sweet onions are slowly caramelized until deep golden and jammy, then nestled into mushroom caps with creamy brie. After baking, each mushroom is finished with a drizzle of thick, tangy balsamic glaze. The combination is extraordinary - earthy mushrooms, sweet onions, rich cheese, and bright acidic glaze. The caramelized onions take time but are absolutely worth it, providing deep, complex sweetness. The balsamic glaze cuts through the richness with welcome acidity. These are elegant enough for the fanciest dinner parties yet comforting enough to make you feel at home. Serve on a beautiful platter and prepare for compliments.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 20,
    totalTime: 55,
    servings: 24,
    rating: "5.0",
    calories: 52,
    protein: "2.5",
    carbs: "4.0",
    fat: "3.5",
    fiber: "0.5",
    sugar: "2.5",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-caramelized-onions-balsamic.png",
    ingredients: [
      "24 baby bella mushrooms",
      "8 oz brie cheese, cubed",
      "2 large yellow onions, thinly sliced",
      "3 tablespoons olive oil, divided",
      "1/2 cup balsamic vinegar",
      "1 tablespoon brown sugar",
      "1 teaspoon fresh thyme",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Make caramelized onions: Heat 2 tablespoons olive oil in large skillet over medium heat. Add onions and cook 25-30 minutes, stirring occasionally, until deep golden and caramelized. Season with salt and pepper. Set aside.",
      "Make balsamic glaze: Simmer balsamic vinegar with brown sugar in small saucepan 10-12 minutes until reduced by half and syrupy. Set aside.",
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Clean mushrooms and remove stems. Arrange on baking sheet.",
      "Brush with remaining olive oil and season lightly.",
      "Fill each mushroom with caramelized onions.",
      "Top with brie cheese and sprinkle with thyme.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Remove from oven and let rest 2-3 minutes.",
      "Drizzle with balsamic glaze.",
      "Garnish with fresh thyme and serve warm."
    ],
    tips: "Patience is key for caramelized onions - cook low and slow for best flavor. Can make onions and balsamic glaze days ahead. Use good quality balsamic vinegar for best glaze.",
    variations: [
      "Add crispy prosciutto",
      "Include blue cheese with brie",
      "Use red wine reduction instead"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "caramelized onions", "balsamic", "sophisticated", "elegant", "appetizer", "party", "gourmet"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Caramelized Onions & Balsamic - Sophisticated Appetizer",
    seoDescription: "Elegant gluten-free mushrooms with sweet caramelized onions, brie, and balsamic glaze. Gourmet appetizer for special occasions."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Sun-Dried Tomatoes & Basil",
    slug: "gluten-free-brie-stuffed-mushrooms-sun-dried-tomatoes-basil",
    description: "Bursting with Mediterranean flavor — brie, sun-dried tomatoes, and basil in perfect harmony.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Sun-Dried Tomatoes & Basil are a celebration of Mediterranean flavors. Each mushroom cap is filled with creamy brie, then topped with chopped sun-dried tomatoes and fresh basil before baking. The sun-dried tomatoes provide intense, concentrated tomato flavor with a slight sweetness, while fresh basil adds aromatic freshness. As they bake, the brie melts around the tomatoes, creating pockets of flavor in every bite. These are colorful, vibrant, and absolutely delicious - the kind of appetizer that transports you to the Italian coast with every taste. Perfect for summer entertaining, Mediterranean-themed dinners, or any time you want bright, bold flavors. Serve with white wine and crusty gluten-free bread.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 24,
    rating: "4.9",
    calories: 48,
    protein: "2.5",
    carbs: "2.5",
    fat: "3.5",
    fiber: "0.5",
    sugar: "1.5",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-sun-dried-tomatoes-basil.png",
    ingredients: [
      "24 cremini mushrooms",
      "8 oz brie cheese, cubed",
      "1/2 cup sun-dried tomatoes in oil, drained and chopped",
      "1/4 cup fresh basil leaves, chopped",
      "3 cloves garlic, minced",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh basil leaves for garnish",
      "Grated Parmesan for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms with olive oil and season with salt and pepper.",
      "Mix chopped sun-dried tomatoes with minced garlic and half the basil.",
      "Fill each mushroom cap with brie cheese.",
      "Top brie with sun-dried tomato mixture.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Remove from oven and let rest 2-3 minutes.",
      "Top with remaining fresh basil.",
      "Garnish with Parmesan if desired and serve warm."
    ],
    tips: "Use sun-dried tomatoes packed in oil for best flavor - drain well before using. Fresh basil is essential - dried won't have the same impact. These are also delicious at room temperature for buffets.",
    variations: [
      "Add pine nuts or walnuts",
      "Include fresh mozzarella",
      "Use roasted red peppers instead"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "sun-dried tomatoes", "basil", "mediterranean", "italian", "appetizer", "party", "vegetarian"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Sun-Dried Tomatoes & Basil - Mediterranean Appetizer",
    seoDescription: "Vibrant gluten-free mushrooms with brie, sun-dried tomatoes, and fresh basil. Mediterranean-inspired party appetizer."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Prosciutto & Sage",
    slug: "gluten-free-brie-stuffed-mushrooms-prosciutto-sage",
    description: "Wrapped or topped with prosciutto for a salty edge — balanced by fragrant sage and creamy cheese.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Prosciutto & Sage are an Italian-inspired delicacy. Mushroom caps are filled with creamy brie and topped with fresh sage, then wrapped or draped with paper-thin prosciutto before baking. As they roast, the prosciutto becomes crispy while the brie melts into the mushrooms. The sage adds aromatic, earthy notes that complement both the salty prosciutto and mild cheese. This combination is classic Italian - simple ingredients prepared beautifully. The prosciutto adds a sophisticated salty element while remaining delicate. These are elegant enough for the fanciest occasions yet approachable enough for casual gatherings. Serve them hot with a glass of Prosecco for the ultimate Italian experience.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 20,
    totalTime: 40,
    servings: 24,
    rating: "5.0",
    calories: 56,
    protein: "4.0",
    carbs: "2.0",
    fat: "4.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-prosciutto-sage.png",
    ingredients: [
      "24 baby bella mushrooms",
      "8 oz brie cheese, cubed",
      "12 thin slices prosciutto, cut in half",
      "24 fresh sage leaves",
      "2 tablespoons olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Fresh sage for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms lightly with olive oil and season with salt and pepper.",
      "Place one sage leaf in each mushroom cap.",
      "Top with brie cheese.",
      "Drape or wrap each mushroom with half slice of prosciutto.",
      "Bake 18-20 minutes until prosciutto is crispy and cheese is melted.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with additional fresh sage leaves.",
      "Serve warm with cocktail picks."
    ],
    tips: "Use very thin prosciutto - it should be almost translucent. The prosciutto will crisp up beautifully in the oven. Fresh sage is essential for this recipe - dried won't provide the same aromatic quality.",
    variations: [
      "Add a drizzle of honey before serving",
      "Include minced garlic with sage",
      "Use pancetta instead of prosciutto"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "prosciutto", "sage", "italian", "elegant", "appetizer", "party", "sophisticated"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Prosciutto & Sage - Italian Elegance",
    seoDescription: "Sophisticated gluten-free mushrooms with brie, crispy prosciutto, and sage. Elegant Italian-inspired appetizer."
  },
  {
    title: "Gluten-Free Brie-Stuffed Mushrooms with Apple & Thyme",
    slug: "gluten-free-brie-stuffed-mushrooms-apple-thyme",
    description: "Sweet diced apple and thyme paired with melted brie — a fall-inspired twist with beautiful flavor balance.",
    longDescription: "These Gluten-Free Brie-Stuffed Mushrooms with Apple & Thyme are the essence of autumn in appetizer form. Fresh apple is diced and lightly caramelized, then combined with fresh thyme and creamy brie in mushroom caps before baking. The apple provides sweet, fruity notes that complement the earthy mushrooms perfectly, while thyme adds aromatic freshness. As they bake, the apple softens and mingles with the melted brie, creating a sophisticated sweet-savory combination. These are perfect for fall entertaining, Thanksgiving gatherings, or any time you want an appetizer that celebrates seasonal flavors. The apple-brie pairing is classic for a reason - it's absolutely delicious. Serve on a wooden board garnished with fresh thyme for rustic elegance.",
    category: "Appetizers",
    subcategory: "Stuffed Vegetables",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 20,
    totalTime: 40,
    servings: 24,
    rating: "4.9",
    calories: 50,
    protein: "2.5",
    carbs: "3.5",
    fat: "3.5",
    fiber: "0.5",
    sugar: "2.0",
    image: "/recipe-images/gluten-free-brie-stuffed-mushrooms-apple-thyme.png",
    ingredients: [
      "24 cremini mushrooms",
      "8 oz brie cheese, cubed",
      "1 large apple (Honeycrisp or Granny Smith), diced small",
      "3 tablespoons fresh thyme leaves",
      "3 tablespoons olive oil, divided",
      "1 tablespoon brown sugar",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 teaspoon cinnamon",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment.",
      "Heat 1 tablespoon olive oil in skillet over medium heat. Add diced apple and brown sugar. Cook 4-5 minutes until slightly softened and caramelized. Stir in 1 tablespoon thyme and cinnamon. Set aside.",
      "Clean mushrooms and remove stems. Arrange caps on baking sheet.",
      "Brush mushrooms with remaining olive oil and season with salt and pepper.",
      "Fill each mushroom cap with brie cheese.",
      "Top brie with apple-thyme mixture.",
      "Sprinkle remaining fresh thyme over mushrooms.",
      "Bake 18-20 minutes until cheese melts and mushrooms are tender.",
      "Remove from oven and let rest 2-3 minutes.",
      "Garnish with fresh thyme sprigs.",
      "Serve warm."
    ],
    tips: "Choose firm, tart apples like Granny Smith for best texture - they hold up better when cooked. Honeycrisp also works beautifully. Can prep apple mixture ahead and refrigerate. The cinnamon is subtle but adds warmth.",
    variations: [
      "Add toasted walnuts or pecans",
      "Include dried cranberries with apple",
      "Drizzle with honey before serving"
    ],
    tags: ["gluten-free", "brie", "stuffed mushrooms", "apple", "thyme", "fall", "autumn", "thanksgiving", "seasonal", "appetizer", "sweet-savory"],
    isNaturallyGlutenFree: true,
    status: "published",
    seoTitle: "Gluten-Free Brie-Stuffed Mushrooms with Apple & Thyme - Fall-Inspired Appetizer",
    seoDescription: "Seasonal gluten-free mushrooms with brie, caramelized apple, and thyme. Perfect autumn appetizer for Thanksgiving."
  }
];

async function addBrieMushroomRecipes() {
  console.log("Adding 10 Brie-Stuffed Mushroom recipes to database...");
  
  try {
    for (const recipe of brieMushroomRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Brie-Stuffed Mushroom recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addBrieMushroomRecipes();
