import { db } from "../server/db";
import { recipes } from "../shared/schema";

const appleButterPies = [
  {
    title: "Gluten-Free Classic Apple Butter Pie",
    slug: "gluten-free-classic-apple-butter-pie",
    description: "Smooth apple butter custard in a flaky gluten-free crust — lightly spiced with cinnamon, clove, and nutmeg.",
    longDescription: "This Gluten-Free Classic Apple Butter Pie is a timeless fall dessert that celebrates the rich, concentrated flavors of spiced apple butter. The filling is a silky smooth custard made with premium apple butter, eggs, and cream, delicately spiced with cinnamon, clove, and nutmeg. Baked in a tender, flaky gluten-free pie crust, this pie has a texture that falls somewhere between pumpkin pie and chess pie — creamy, smooth, and perfectly set. The deep amber color and warm spices make it a stunning centerpiece for Thanksgiving or any autumn gathering. Each slice reveals the gorgeous caramel-like filling that's sweet but not cloying, with complex apple flavor enhanced by traditional warm spices. Serve with fresh whipped cream or vanilla ice cream for the ultimate comfort dessert.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 55,
    totalTime: 80,
    servings: 8,
    rating: "4.9",
    calories: 285,
    protein: "4.5",
    carbs: "42.0",
    fat: "11.0",
    fiber: "2.5",
    sugar: "28.0",
    image: "/recipe-images/apple-butter-pie-classic.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "1½ cups thick apple butter",
      "3 large eggs",
      "½ cup heavy cream",
      "½ cup granulated sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon ground cinnamon",
      "¼ teaspoon ground nutmeg",
      "⅛ teaspoon ground cloves",
      "¼ teaspoon salt",
      "1 tablespoon cornstarch"
    ],
    instructions: [
      "Preheat oven to 350°F. Place unbaked gluten-free pie crust in 9-inch pie pan and crimp edges decoratively.",
      "In a large bowl, whisk together apple butter, eggs, heavy cream, sugar, and vanilla extract until smooth.",
      "Add cinnamon, nutmeg, cloves, salt, and cornstarch. Whisk until completely combined and no lumps remain.",
      "Pour filling into prepared pie crust, smoothing the top with a spatula.",
      "Place pie on a baking sheet to catch any drips. Bake for 50-55 minutes until filling is set but still slightly jiggly in the center.",
      "The edges should be puffed and the center should register 175°F on an instant-read thermometer.",
      "Remove from oven and cool on wire rack for at least 2 hours to allow filling to set completely.",
      "Refrigerate for at least 1 hour before serving for cleanest slices.",
      "Serve chilled or at room temperature with whipped cream or vanilla ice cream."
    ],
    tips: "Use thick, spiced apple butter with minimal added sugar for best texture and flavor. If your apple butter is thin, reduce the cream to ⅓ cup. For extra protection against a soggy bottom, brush the unbaked crust with beaten egg white and bake for 5 minutes before adding filling.",
    variations: [
      "Top with bourbon whipped cream for an adult twist",
      "Add ½ cup chopped toasted pecans to the filling",
      "Drizzle with salted caramel sauce before serving"
    ],
    tags: ["gluten-free", "apple butter", "pie", "dessert", "fall", "thanksgiving", "custard pie", "autumn", "holiday", "classic"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Classic Apple Butter Pie - Fall Dessert Recipe",
    seoDescription: "Silky smooth gluten-free apple butter custard pie with warm spices. Perfect fall and Thanksgiving dessert with rich caramel-like apple flavor."
  },
  {
    title: "Gluten-Free Apple Butter Pie with Maple Pecan Crust",
    slug: "gluten-free-apple-butter-pie-maple-pecan-crust",
    description: "Toasted pecan and maple crust complements a creamy apple butter filling — perfect for Thanksgiving.",
    longDescription: "This Gluten-Free Apple Butter Pie with Maple Pecan Crust takes the classic apple butter pie to new heights with a stunning homemade crust. The gluten-free crust is studded with toasted pecans and sweetened with pure maple syrup, creating a nutty, slightly sweet foundation that perfectly complements the spiced apple butter filling. As the pie bakes, the pecans toast further, releasing their oils and creating an irresistible aroma. The maple flavor in the crust provides a subtle sweetness that enhances but doesn't overpower the apple butter custard. This pie is a showstopper for Thanksgiving dinner, combining two beloved fall flavors — apple butter and maple pecan — in one elegant dessert. The textural contrast between the crunchy pecan crust and silky filling makes every bite interesting and delicious.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 55,
    totalTime: 90,
    servings: 8,
    rating: "5.0",
    calories: 345,
    protein: "5.5",
    carbs: "48.0",
    fat: "15.5",
    fiber: "3.0",
    sugar: "32.0",
    image: "/recipe-images/apple-butter-pie-maple-pecan.png",
    ingredients: [
      "For the maple pecan crust:",
      "1½ cups gluten-free all-purpose flour blend",
      "½ cup finely chopped toasted pecans",
      "2 tablespoons granulated sugar",
      "½ teaspoon salt",
      "½ cup cold butter, cubed",
      "3 tablespoons pure maple syrup",
      "2-3 tablespoons ice water",
      "For the filling:",
      "1½ cups apple butter",
      "3 large eggs",
      "½ cup heavy cream",
      "⅓ cup brown sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt"
    ],
    instructions: [
      "Toast pecans in a dry skillet over medium heat for 4-5 minutes until fragrant. Let cool, then chop finely.",
      "In food processor, pulse gluten-free flour, chopped pecans, sugar, and salt. Add cold butter cubes and pulse until mixture resembles coarse crumbs.",
      "Drizzle in maple syrup and 2 tablespoons ice water. Pulse until dough begins to come together. Add more water if needed.",
      "Turn dough onto plastic wrap, form into a disk, and refrigerate for 30 minutes.",
      "Preheat oven to 350°F. Roll out chilled dough between two sheets of parchment to 12-inch circle.",
      "Transfer to 9-inch pie pan, trim edges, and crimp decoratively. Refrigerate while making filling.",
      "In a large bowl, whisk together apple butter, eggs, cream, brown sugar, vanilla, cinnamon, nutmeg, and salt until smooth.",
      "Pour filling into chilled crust. Bake 50-55 minutes until filling is set but slightly jiggly in center.",
      "Cool completely on wire rack, then refrigerate at least 2 hours before serving."
    ],
    tips: "Toast the pecans for the crust to intensify their flavor. The maple syrup in the crust adds moisture and flavor — don't skip it. This pie is even better the next day after flavors have melded.",
    variations: [
      "Use walnuts instead of pecans",
      "Add a tablespoon of bourbon to the filling",
      "Top with candied pecans before serving"
    ],
    tags: ["gluten-free", "apple butter", "pie", "maple", "pecan", "thanksgiving", "fall", "holiday", "dessert", "autumn"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Pie with Maple Pecan Crust - Thanksgiving Dessert",
    seoDescription: "Stunning gluten-free apple butter pie with homemade maple pecan crust. Perfect Thanksgiving dessert with nutty, sweet flavors."
  },
  {
    title: "Gluten-Free Apple Butter Cheesecake Pie",
    slug: "gluten-free-apple-butter-cheesecake-pie",
    description: "A luscious fusion of cheesecake and pie — apple butter blended into a creamy cheesecake layer on a graham crust.",
    longDescription: "This Gluten-Free Apple Butter Cheesecake Pie is a decadent fusion dessert that combines the best of two beloved treats. A gluten-free graham cracker crust provides a sweet, crispy foundation for layers of pure indulgence. The filling starts with a rich, tangy cheesecake base made with cream cheese, sour cream, and eggs. Spiced apple butter is swirled throughout, creating beautiful marbled patterns and pockets of concentrated apple flavor. As the pie bakes in a water bath, it develops a creamy, almost velvety texture that's denser than regular pie but lighter than traditional cheesecake. The apple butter adds natural sweetness and warm spice notes that complement the tanginess of the cream cheese beautifully. This showstopping dessert is perfect for special occasions when you want to impress guests with something unique and utterly delicious.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 65,
    totalTime: 95,
    servings: 10,
    rating: "4.9",
    calories: 380,
    protein: "7.0",
    carbs: "38.0",
    fat: "22.0",
    fiber: "1.5",
    sugar: "26.0",
    image: "/recipe-images/apple-butter-pie-cheesecake.png",
    ingredients: [
      "For the crust:",
      "2 cups gluten-free graham cracker crumbs",
      "¼ cup granulated sugar",
      "6 tablespoons butter, melted",
      "For the filling:",
      "24 oz cream cheese, softened",
      "¾ cup granulated sugar",
      "3 large eggs",
      "½ cup sour cream",
      "1 teaspoon vanilla extract",
      "1 cup apple butter",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "Pinch of salt"
    ],
    instructions: [
      "Preheat oven to 325°F. Mix graham cracker crumbs, sugar, and melted butter. Press firmly into bottom and up sides of 9-inch springform pan.",
      "Bake crust for 10 minutes. Remove and let cool while preparing filling.",
      "In large bowl, beat softened cream cheese and sugar until smooth and fluffy, about 3 minutes.",
      "Add eggs one at a time, beating well after each addition. Mix in sour cream and vanilla.",
      "In separate bowl, whisk together apple butter, cinnamon, nutmeg, and salt.",
      "Pour half of cheesecake batter into cooled crust. Dollop half of apple butter mixture over batter. Pour remaining cheesecake batter on top.",
      "Dollop remaining apple butter mixture over top and swirl gently with a knife to create marble effect.",
      "Wrap bottom of springform pan in aluminum foil. Place in roasting pan and add 1 inch of hot water to roasting pan.",
      "Bake 60-65 minutes until edges are set but center still jiggles slightly. Turn off oven and let pie cool in oven with door cracked for 1 hour.",
      "Remove from water bath, cool completely, then refrigerate at least 4 hours or overnight before serving."
    ],
    tips: "Make sure cream cheese is fully softened to avoid lumps in the filling. The water bath prevents cracking and ensures even baking. Don't over-swirl the apple butter — you want distinct ribbons of flavor.",
    variations: [
      "Use a pecan crust instead of graham cracker",
      "Top with caramel drizzle and chopped pecans",
      "Add a layer of apple butter on top before serving"
    ],
    tags: ["gluten-free", "apple butter", "cheesecake", "pie", "fusion", "dessert", "elegant", "holiday", "special occasion", "fall"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Cheesecake Pie - Fusion Dessert Recipe",
    seoDescription: "Decadent gluten-free apple butter cheesecake pie with marbled layers. Perfect special occasion dessert combining cheesecake and pie."
  },
  {
    title: "Gluten-Free Apple Butter Custard Pie with Cinnamon Whipped Cream",
    slug: "gluten-free-apple-butter-custard-pie-cinnamon-whipped-cream",
    description: "Custard-based filling baked until silky, topped with spiced whipped cream and caramel drizzle.",
    longDescription: "This Gluten-Free Apple Butter Custard Pie with Cinnamon Whipped Cream is pure comfort in dessert form. The filling is a luxurious custard made with apple butter, heavy cream, and eggs, creating a silky texture that melts on your tongue. As it bakes, the custard sets to a perfect consistency — not too firm, not too soft — with a subtle jiggle that indicates optimal doneness. The real star, however, is the homemade cinnamon whipped cream that crowns each slice. Made with real cinnamon and a touch of vanilla, it adds a cloud-like contrast to the dense custard below. A drizzle of golden caramel sauce adds the finishing touch, creating layers of flavor and texture in every forkful. This pie is elegant enough for dinner parties yet comforting enough for family gatherings.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 8,
    rating: "5.0",
    calories: 395,
    protein: "5.5",
    carbs: "44.0",
    fat: "22.0",
    fiber: "2.0",
    sugar: "30.0",
    image: "/recipe-images/apple-butter-pie-custard.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "For the custard:",
      "1½ cups apple butter",
      "1 cup heavy cream",
      "3 large eggs plus 1 egg yolk",
      "½ cup granulated sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "For the cinnamon whipped cream:",
      "1 cup heavy cream, cold",
      "2 tablespoons powdered sugar",
      "1 teaspoon cinnamon",
      "½ teaspoon vanilla extract",
      "Caramel sauce for drizzling"
    ],
    instructions: [
      "Preheat oven to 350°F. Place unbaked pie crust in pie pan and crimp edges.",
      "In large bowl, whisk together apple butter, heavy cream, eggs, egg yolk, sugar, vanilla, cinnamon, nutmeg, and salt until completely smooth.",
      "Pour custard mixture through fine-mesh strainer into prepared crust to remove any lumps.",
      "Place pie on baking sheet and bake 45-50 minutes until custard is set around edges but still slightly jiggly in center.",
      "Remove from oven and cool on wire rack for 2 hours, then refrigerate until completely chilled, at least 3 hours.",
      "Before serving, make cinnamon whipped cream: In chilled bowl, beat heavy cream, powdered sugar, cinnamon, and vanilla until stiff peaks form.",
      "Dollop generous amounts of cinnamon whipped cream on each slice.",
      "Drizzle with caramel sauce and serve immediately."
    ],
    tips: "Straining the custard ensures a perfectly smooth filling with no lumps. The custard will continue to set as it cools, so don't overbake. Make the whipped cream fresh just before serving for best texture.",
    variations: [
      "Add a tablespoon of bourbon to the custard",
      "Use maple syrup instead of caramel drizzle",
      "Sprinkle with toasted pecans"
    ],
    tags: ["gluten-free", "apple butter", "custard pie", "whipped cream", "caramel", "dessert", "elegant", "fall", "holiday", "comfort food"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Custard Pie with Cinnamon Whipped Cream - Elegant Dessert",
    seoDescription: "Silky gluten-free apple butter custard pie topped with homemade cinnamon whipped cream and caramel. Perfect elegant fall dessert."
  },
  {
    title: "Gluten-Free Apple Butter Pie with Brown Sugar Streusel",
    slug: "gluten-free-apple-butter-pie-brown-sugar-streusel",
    description: "Crumbly streusel topping over rich apple filling — buttery, textured, and irresistibly cozy.",
    longDescription: "This Gluten-Free Apple Butter Pie with Brown Sugar Streusel is the ultimate comfort dessert, combining creamy filling with a crunchy, buttery topping. The apple butter filling is enriched with cream and eggs to create a custard-like base, while brown sugar adds deep molasses notes. But the star of this pie is the generous layer of streusel topping made with gluten-free flour, brown sugar, butter, and warming spices. As the pie bakes, the streusel becomes golden and crispy, forming delightful crumbly clusters that contrast beautifully with the smooth filling below. The brown sugar in both the filling and topping creates cohesive caramel-like flavor throughout. This pie is rustic, homey, and absolutely irresistible — perfect for cozy family dinners or potluck gatherings where you want to bring something that feels like a warm hug.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Easy",
    prepTime: 30,
    cookTime: 55,
    totalTime: 85,
    servings: 8,
    rating: "4.9",
    calories: 415,
    protein: "5.0",
    carbs: "56.0",
    fat: "19.0",
    fiber: "3.0",
    sugar: "38.0",
    image: "/recipe-images/apple-butter-pie-streusel.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "For the filling:",
      "1½ cups apple butter",
      "½ cup heavy cream",
      "3 large eggs",
      "½ cup packed brown sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "¼ teaspoon salt",
      "For the streusel:",
      "¾ cup gluten-free all-purpose flour",
      "½ cup packed brown sugar",
      "½ cup old-fashioned oats (certified gluten-free)",
      "1 teaspoon cinnamon",
      "¼ teaspoon salt",
      "6 tablespoons cold butter, cubed"
    ],
    instructions: [
      "Preheat oven to 350°F. Place unbaked pie crust in pie pan and crimp edges.",
      "In large bowl, whisk together apple butter, cream, eggs, brown sugar, vanilla, cinnamon, and salt until smooth.",
      "Pour filling into prepared crust.",
      "Make streusel: In medium bowl, combine gluten-free flour, brown sugar, oats, cinnamon, and salt.",
      "Add cold butter cubes and use pastry cutter or fingers to work butter into dry ingredients until mixture resembles coarse crumbs with some pea-sized pieces.",
      "Sprinkle streusel evenly over filling, covering completely.",
      "Place pie on baking sheet and bake 50-55 minutes until streusel is golden brown and filling is set.",
      "If streusel browns too quickly, tent loosely with aluminum foil.",
      "Cool on wire rack for at least 2 hours before slicing. Serve warm or at room temperature."
    ],
    tips: "Keep butter cold for the streusel to ensure a crumbly texture. Don't overwork the streusel — you want distinct buttery pieces. This pie is delicious served warm with vanilla ice cream.",
    variations: [
      "Add chopped pecans or walnuts to the streusel",
      "Use maple sugar instead of brown sugar",
      "Add a pinch of ground ginger to the filling"
    ],
    tags: ["gluten-free", "apple butter", "pie", "streusel", "brown sugar", "dessert", "comfort food", "fall", "rustic", "homestyle"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Pie with Brown Sugar Streusel - Comfort Dessert",
    seoDescription: "Cozy gluten-free apple butter pie with buttery brown sugar streusel topping. Perfect rustic fall dessert for family gatherings."
  },
  {
    title: "Gluten-Free Apple Butter Chiffon Pie",
    slug: "gluten-free-apple-butter-chiffon-pie",
    description: "Light and airy — whipped cream folded into spiced apple butter mousse in a gluten-free cookie crust.",
    longDescription: "This Gluten-Free Apple Butter Chiffon Pie is a revelation for those who love light, airy desserts. Unlike dense custard pies, this version features a mousse-like filling created by folding whipped cream into a gelatin-stabilized apple butter base. The result is ethereal and cloud-like, with the intense flavor of apple butter distributed throughout an impossibly light texture. The gluten-free vanilla cookie crust provides a sweet, crunchy contrast to the fluffy filling. This pie requires no baking after the crust is prepared, making it perfect for warm weather or when you want an elegant dessert without heating up the kitchen. The chiffon texture melts on your tongue, releasing waves of spiced apple flavor. It's sophisticated, refreshing, and a delightful departure from heavier traditional pies.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 10,
    totalTime: 45,
    servings: 8,
    rating: "4.8",
    calories: 295,
    protein: "4.0",
    carbs: "35.0",
    fat: "15.5",
    fiber: "1.5",
    sugar: "24.0",
    image: "/recipe-images/apple-butter-pie-chiffon.png",
    ingredients: [
      "For the crust:",
      "2 cups gluten-free vanilla cookie crumbs",
      "5 tablespoons butter, melted",
      "2 tablespoons sugar",
      "For the filling:",
      "1 cup apple butter",
      "1 envelope (2¼ teaspoons) unflavored gelatin",
      "¼ cup cold water",
      "3 large eggs, separated",
      "½ cup granulated sugar, divided",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "1½ cups heavy cream, cold",
      "1 teaspoon vanilla extract"
    ],
    instructions: [
      "Preheat oven to 350°F. Mix cookie crumbs, melted butter, and sugar. Press into 9-inch pie pan. Bake 8-10 minutes. Cool completely.",
      "Sprinkle gelatin over cold water in small bowl. Let stand 5 minutes to soften.",
      "In medium saucepan, whisk together apple butter, egg yolks, ¼ cup sugar, cinnamon, nutmeg, and salt. Cook over medium heat, stirring constantly, until mixture thickens slightly, about 5 minutes.",
      "Remove from heat and stir in softened gelatin until completely dissolved. Transfer to large bowl and refrigerate until mixture begins to thicken, about 20 minutes, stirring occasionally.",
      "In clean bowl, beat egg whites until soft peaks form. Gradually add remaining ¼ cup sugar and beat until stiff, glossy peaks form.",
      "In another bowl, beat heavy cream and vanilla until stiff peaks form.",
      "Gently fold whipped cream into thickened apple butter mixture. Then fold in beaten egg whites until no white streaks remain.",
      "Pour filling into cooled crust and smooth top. Refrigerate at least 4 hours or overnight until set.",
      "Garnish with additional whipped cream and a sprinkle of cinnamon before serving."
    ],
    tips: "Make sure the apple butter mixture has cooled and begun to thicken before folding in the whipped cream and egg whites, or the filling will be too runny. Fold gently to maintain the airy texture.",
    variations: [
      "Add a tablespoon of bourbon to the apple butter mixture",
      "Top with toasted chopped pecans",
      "Use a gingersnap crust for extra spice"
    ],
    tags: ["gluten-free", "apple butter", "chiffon pie", "light", "airy", "mousse", "no-bake filling", "dessert", "elegant", "fall"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Chiffon Pie - Light Airy Dessert",
    seoDescription: "Light and airy gluten-free apple butter chiffon pie with mousse-like texture. Elegant no-bake filling perfect for any occasion."
  },
  {
    title: "Gluten-Free Apple Butter Bourbon Pie",
    slug: "gluten-free-apple-butter-bourbon-pie",
    description: "Deep caramel and bourbon undertones elevate this bold, grown-up variation — warm and complex.",
    longDescription: "This Gluten-Free Apple Butter Bourbon Pie is a sophisticated dessert for adult palates, featuring the rich complexity of bourbon whiskey paired with spiced apple butter. The bourbon is cooked into the filling, mellowing its alcohol while retaining its distinctive caramel, vanilla, and oak notes. These flavors intertwine beautifully with the concentrated apple flavor and warm spices in the apple butter, creating a multi-layered taste experience. Dark brown sugar adds molasses depth, while a hint of maple syrup reinforces the bourbon's natural sweetness. The result is a pie that's warm, complex, and utterly compelling — perfect for holiday dinners, special occasions, or any time you want to serve something a cut above the ordinary. Each bite reveals new nuances of flavor, making this a dessert that demands attention and appreciation.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 55,
    totalTime: 80,
    servings: 8,
    rating: "5.0",
    calories: 340,
    protein: "4.5",
    carbs: "46.0",
    fat: "13.0",
    fiber: "2.5",
    sugar: "32.0",
    image: "/recipe-images/apple-butter-pie-bourbon.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "1½ cups apple butter",
      "3 large eggs",
      "½ cup heavy cream",
      "½ cup packed dark brown sugar",
      "¼ cup bourbon whiskey",
      "2 tablespoons maple syrup",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "½ teaspoon ground ginger",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "1 tablespoon cornstarch"
    ],
    instructions: [
      "Preheat oven to 350°F. Place unbaked pie crust in pie pan and crimp edges.",
      "In medium saucepan, combine bourbon and brown sugar. Heat over medium heat until sugar dissolves and mixture is slightly reduced, about 3-4 minutes. Remove from heat and let cool 5 minutes.",
      "In large bowl, whisk together apple butter, eggs, cream, maple syrup, and vanilla.",
      "Add cooled bourbon-sugar mixture and whisk until combined.",
      "Whisk in cinnamon, ginger, nutmeg, salt, and cornstarch until completely smooth.",
      "Pour filling into prepared crust, smoothing top.",
      "Place pie on baking sheet and bake 50-55 minutes until filling is set but center still has slight jiggle.",
      "Cool on wire rack for 2 hours, then refrigerate at least 2 hours before serving.",
      "Serve with bourbon whipped cream if desired."
    ],
    tips: "Use a good quality bourbon — the flavor really comes through in this pie. Cooking the bourbon with the brown sugar mellows the alcohol while concentrating the flavor. This pie is even better the next day after flavors have had time to develop.",
    variations: [
      "Use rum instead of bourbon for a different flavor profile",
      "Add ½ cup chopped toasted pecans to the filling",
      "Top with bourbon-caramel sauce"
    ],
    tags: ["gluten-free", "apple butter", "bourbon", "pie", "adult dessert", "sophisticated", "fall", "holiday", "special occasion", "whiskey"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Bourbon Pie - Sophisticated Adult Dessert",
    seoDescription: "Bold gluten-free apple butter bourbon pie with complex caramel flavors. Perfect sophisticated dessert for holiday entertaining."
  },
  {
    title: "Gluten-Free Apple Butter Pie with Oat Crumble Topping",
    slug: "gluten-free-apple-butter-pie-oat-crumble-topping",
    description: "Rustic and homey — a hearty oat topping adds crunch to creamy apple filling.",
    longDescription: "This Gluten-Free Apple Butter Pie with Oat Crumble Topping celebrates rustic, homestyle baking at its finest. The smooth, spiced apple butter filling provides a creamy base, while the generous layer of oat crumble adds delightful texture and visual appeal. The topping is made with certified gluten-free oats, butter, brown sugar, and cinnamon, creating clusters of golden, crunchy goodness that contrast beautifully with the silky filling. Unlike traditional streusel, the oat crumble has more heft and substance, making each bite satisfying and filling. This pie has a wholesome, farmhouse quality that feels both comforting and nourishing. It's the kind of dessert that brings people together around the table, perfect for Sunday dinners, potlucks, or any gathering where you want to serve something that feels like home.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Easy",
    prepTime: 30,
    cookTime: 55,
    totalTime: 85,
    servings: 8,
    rating: "4.9",
    calories: 385,
    protein: "6.0",
    carbs: "52.0",
    fat: "17.0",
    fiber: "4.5",
    sugar: "34.0",
    image: "/recipe-images/apple-butter-pie-oat-crumble.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "For the filling:",
      "1½ cups apple butter",
      "½ cup heavy cream",
      "3 large eggs",
      "½ cup granulated sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "For the oat crumble:",
      "1 cup certified gluten-free old-fashioned oats",
      "½ cup gluten-free all-purpose flour",
      "½ cup packed brown sugar",
      "1 teaspoon cinnamon",
      "¼ teaspoon salt",
      "6 tablespoons cold butter, cubed",
      "½ cup chopped pecans (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F. Place unbaked pie crust in pie pan and crimp edges.",
      "In large bowl, whisk together apple butter, cream, eggs, sugar, vanilla, cinnamon, nutmeg, and salt until smooth. Pour into crust.",
      "Make oat crumble: In medium bowl, combine oats, gluten-free flour, brown sugar, cinnamon, and salt. Mix well.",
      "Add cold butter cubes and use pastry cutter or fingers to work into oat mixture until crumbly with some larger pieces remaining.",
      "If using pecans, stir them into the crumble mixture.",
      "Sprinkle oat crumble evenly over filling, covering completely and creating a generous layer.",
      "Place pie on baking sheet and bake 50-55 minutes until crumble is golden brown and filling is set.",
      "If topping browns too quickly, tent with foil for the last 15 minutes of baking.",
      "Cool on wire rack for at least 2 hours. Serve warm or at room temperature, optionally with vanilla ice cream."
    ],
    tips: "Use certified gluten-free oats to ensure the pie is safe for those with celiac disease. The oat crumble can be made ahead and stored in the refrigerator. Press the crumble gently onto the filling to help it adhere.",
    variations: [
      "Add ½ teaspoon ground ginger to the crumble",
      "Use maple sugar instead of brown sugar",
      "Drizzle with maple glaze after baking"
    ],
    tags: ["gluten-free", "apple butter", "pie", "oat crumble", "rustic", "homestyle", "dessert", "fall", "comfort food", "wholesome"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter Pie with Oat Crumble Topping - Rustic Dessert",
    seoDescription: "Rustic gluten-free apple butter pie with hearty oat crumble topping. Wholesome homestyle dessert perfect for family gatherings."
  },
  {
    title: "Gluten-Free Apple Butter & Salted Caramel Pie",
    slug: "gluten-free-apple-butter-salted-caramel-pie",
    description: "Sweet meets salty — caramel swirled into apple butter custard with sea salt finish.",
    longDescription: "This Gluten-Free Apple Butter & Salted Caramel Pie is a sophisticated play on the beloved sweet-and-salty flavor combination. The base is a silky apple butter custard enriched with cream and eggs, providing the perfect canvas for ribbons of homemade salted caramel. As the pie bakes, the caramel swirls maintain their distinct identity, creating pockets of rich, buttery sweetness throughout the spiced apple filling. A sprinkle of flaky sea salt on top before baking adds the final touch, creating tiny bursts of saltiness that enhance all the other flavors. The interplay between the tart apple butter, sweet caramel, and salty finish creates a complex, crave-worthy dessert that keeps you coming back for another bite. This pie is elegant enough for special occasions yet comforting enough for everyday indulgence.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 55,
    totalTime: 90,
    servings: 8,
    rating: "5.0",
    calories: 420,
    protein: "5.0",
    carbs: "54.0",
    fat: "20.0",
    fiber: "2.5",
    sugar: "40.0",
    image: "/recipe-images/apple-butter-pie-salted-caramel.png",
    ingredients: [
      "1 gluten-free pie crust (9-inch), unbaked",
      "For the salted caramel:",
      "¾ cup granulated sugar",
      "3 tablespoons butter",
      "¼ cup heavy cream",
      "½ teaspoon sea salt",
      "For the filling:",
      "1½ cups apple butter",
      "½ cup heavy cream",
      "3 large eggs",
      "⅓ cup granulated sugar",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "Make salted caramel: In heavy saucepan, heat sugar over medium heat, stirring constantly until melted and amber colored, about 8 minutes.",
      "Remove from heat and carefully whisk in butter (mixture will bubble vigorously). Slowly add cream while whisking until smooth.",
      "Stir in sea salt. Let cool to room temperature.",
      "Preheat oven to 350°F. Place unbaked pie crust in pie pan and crimp edges.",
      "In large bowl, whisk together apple butter, cream, eggs, sugar, vanilla, cinnamon, nutmeg, and salt until smooth.",
      "Pour half of apple butter mixture into crust. Drizzle half of cooled salted caramel over filling. Swirl gently with knife.",
      "Pour remaining apple butter mixture on top. Drizzle with remaining caramel and swirl again.",
      "Sprinkle top with flaky sea salt.",
      "Bake 50-55 minutes until filling is set but center still has slight jiggle.",
      "Cool on wire rack for 2 hours, then refrigerate at least 2 hours before serving."
    ],
    tips: "Watch the caramel carefully — it can burn quickly. Make sure caramel is cooled to room temperature before swirling into the filling, or it will be too runny. Use good quality flaky sea salt for the best flavor and texture contrast.",
    variations: [
      "Add a tablespoon of bourbon to the caramel",
      "Top with additional caramel drizzle before serving",
      "Sprinkle with chopped toasted pecans"
    ],
    tags: ["gluten-free", "apple butter", "salted caramel", "pie", "sweet and salty", "dessert", "gourmet", "fall", "holiday", "elegant"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Butter & Salted Caramel Pie - Gourmet Dessert",
    seoDescription: "Gourmet gluten-free apple butter pie with salted caramel swirls and sea salt finish. Perfect sweet and salty fall dessert."
  },
  {
    title: "Gluten-Free Apple Butter Vegan Pie with Coconut Cream",
    slug: "gluten-free-apple-butter-vegan-pie-coconut-cream",
    description: "Dairy-free version using coconut milk, gluten-free crust, and vegan whipped cream topping.",
    longDescription: "This Gluten-Free Apple Butter Vegan Pie with Coconut Cream proves that plant-based desserts can be every bit as indulgent and delicious as their traditional counterparts. The filling is made with apple butter, full-fat coconut milk, and a flax egg binder, creating a rich, creamy custard that's completely dairy-free and egg-free. Coconut sugar adds depth and a subtle caramel note, while arrowroot powder helps thicken the filling to the perfect consistency. The pie is crowned with luscious coconut whipped cream made from chilled coconut cream, adding a tropical note that complements the spiced apple filling beautifully. This pie is ideal for serving guests with dietary restrictions, holiday gatherings where you need inclusive options, or anyone who simply wants to enjoy a lighter, plant-based version of this classic dessert.",
    category: "Desserts",
    subcategory: "Pies & Tarts",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 55,
    totalTime: 85,
    servings: 8,
    rating: "4.8",
    calories: 315,
    protein: "3.0",
    carbs: "44.0",
    fat: "14.5",
    fiber: "3.5",
    sugar: "28.0",
    image: "/recipe-images/apple-butter-pie-vegan.png",
    ingredients: [
      "1 gluten-free vegan pie crust (9-inch), unbaked",
      "For the filling:",
      "1½ cups apple butter",
      "1 can (14 oz) full-fat coconut milk",
      "2 tablespoons ground flaxseed mixed with 6 tablespoons water (flax eggs)",
      "½ cup coconut sugar",
      "2 tablespoons arrowroot powder",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "½ teaspoon ground ginger",
      "¼ teaspoon nutmeg",
      "¼ teaspoon salt",
      "For the coconut whipped cream:",
      "1 can (14 oz) coconut cream, chilled overnight",
      "2 tablespoons powdered sugar",
      "1 teaspoon vanilla extract"
    ],
    instructions: [
      "Prepare flax eggs by mixing ground flaxseed with water. Let sit 10 minutes to thicken.",
      "Preheat oven to 350°F. Place unbaked vegan pie crust in pie pan and crimp edges.",
      "In large bowl, whisk together apple butter, coconut milk, flax eggs, coconut sugar, arrowroot powder, vanilla, cinnamon, ginger, nutmeg, and salt until completely smooth.",
      "Pour filling into prepared crust, smoothing top.",
      "Place pie on baking sheet and bake 50-55 minutes until filling is set and edges are slightly puffed.",
      "Remove from oven and cool on wire rack for 2 hours, then refrigerate at least 4 hours or overnight.",
      "Before serving, make coconut whipped cream: Scoop solidified coconut cream from chilled can into chilled bowl (discard liquid).",
      "Beat coconut cream with powdered sugar and vanilla until light and fluffy, about 2-3 minutes.",
      "Top each slice with generous dollop of coconut whipped cream. Garnish with cinnamon if desired."
    ],
    tips: "Use full-fat coconut milk and coconut cream for best results — lite versions won't work. Chill the coconut cream can overnight to ensure proper separation. The filling will seem loose when you first remove it from the oven, but it will set as it cools.",
    variations: [
      "Add ½ cup chopped toasted walnuts to the filling",
      "Use date syrup instead of coconut sugar",
      "Sprinkle with toasted coconut flakes before serving"
    ],
    tags: ["gluten-free", "vegan", "dairy-free", "apple butter", "pie", "coconut cream", "plant-based", "dessert", "fall", "holiday"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Vegan Apple Butter Pie with Coconut Cream - Dairy-Free Dessert",
    seoDescription: "Delicious gluten-free vegan apple butter pie with coconut cream topping. Perfect dairy-free plant-based fall dessert."
  }
];

async function seed() {
  console.log("Adding 10 gluten-free apple butter pie recipes...");
  
  try {
    const result = await db
      .insert(recipes)
      .values(appleButterPies)
      .onConflictDoNothing({ target: [recipes.slug] });
    
    console.log(`Successfully added ${appleButterPies.length} apple butter pie recipes to the database!`);
    console.log("All recipes have been inserted under Desserts → Pies & Tarts category.");
  } catch (error) {
    console.error("Error adding recipes:", error);
    throw error;
  }
}

seed()
  .then(() => {
    console.log("Seed completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
