import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const chickenSoupRecipes = [
  {
    title: "Gluten-Free Classic Chicken Noodle Soup",
    slug: "gluten-free-classic-chicken-noodle-soup",
    seoTitle: "Gluten-Free Classic Chicken Noodle Soup - Homestyle Comfort",
    description: "Tender shredded chicken, carrots, celery, and gluten-free egg noodles simmered in rich homemade broth — timeless comfort in a bowl.",
    longDescription: "This gluten-free classic chicken noodle soup is pure comfort in a bowl, featuring all the traditional elements that make this soup a timeless favorite. Tender chicken is poached in rich broth until perfectly cooked, then shredded and returned to the pot along with aromatic vegetables, celery, and carrots. Gluten-free egg noodles cook directly in the flavorful broth, absorbing all the savory goodness. Fresh herbs like parsley and thyme add brightness and depth. This is the soup that soothes sore throats, warms cold nights, and brings comfort when you need it most. It's traditional, nourishing, and tastes just like the classic version everyone loves.",
    seoDescription: "Gluten-free classic chicken noodle soup with tender chicken, vegetables, and egg noodles. Traditional homestyle comfort food that soothes and nourishes.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-classic-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken breasts or thighs",
      "8 cups gluten-free chicken broth",
      "3 medium carrots, peeled and sliced",
      "3 celery stalks, sliced",
      "1 medium onion, diced",
      "3 cloves garlic, minced",
      "2 bay leaves",
      "1 teaspoon dried thyme",
      "8 oz gluten-free egg noodles",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
      "Lemon wedges for serving (optional)"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5-6 minutes until softened.",
      "Add garlic and cook for 1 minute until fragrant.",
      "Pour in chicken broth and add bay leaves and thyme. Bring to a boil.",
      "Add chicken breasts to the pot. Reduce heat and simmer for 20-25 minutes until chicken is cooked through (internal temp 165°F).",
      "Remove chicken from pot and shred with two forks. Set aside.",
      "Add gluten-free noodles to the simmering broth and cook according to package directions (usually 8-10 minutes).",
      "Return shredded chicken to the pot. Season with salt and pepper to taste.",
      "Remove bay leaves and discard.",
      "Serve hot, garnished with fresh parsley and lemon wedges if desired."
    ],
    tags: ["gluten-free", "chicken noodle soup", "comfort food", "classic", "soups & stews", "one-pot meal", "immune-boosting", "traditional", "healing", "homestyle"],
    nutrition: {
      calories: 280,
      protein: "26g",
      carbs: "28g",
      fat: "6g",
      fiber: "3g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Creamy Chicken Noodle Soup",
    slug: "gluten-free-creamy-chicken-noodle-soup",
    seoTitle: "Gluten-Free Creamy Chicken Noodle Soup - Rich & Velvety",
    description: "Velvety broth made with coconut milk or cream, gluten-free noodles, and hearty vegetables — cozy, rich, and satisfying.",
    longDescription: "This gluten-free creamy chicken noodle soup takes comfort to the next level with a rich, velvety broth that's both indulgent and nourishing. The creaminess comes from coconut milk or heavy cream, which creates a luxurious texture without overpowering the classic chicken soup flavors. Tender chicken, soft vegetables, and gluten-free noodles swim in the luscious broth. The cream adds body and richness while keeping the soup feeling light enough for any time of day. This is perfect for when you want something extra comforting — it's like a warm hug in bowl form. The dairy-free option using coconut milk is just as rich and satisfying as the cream version.",
    seoDescription: "Gluten-free creamy chicken noodle soup with velvety coconut milk or cream broth. Rich, comforting, and perfect for cold weather.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-creamy-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken thighs, diced",
      "6 cups gluten-free chicken broth",
      "1 cup coconut milk or heavy cream",
      "2 medium carrots, peeled and diced",
      "2 celery stalks, diced",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "8 oz gluten-free noodles",
      "2 tablespoons butter or olive oil",
      "2 tablespoons gluten-free flour (for thickening, optional)",
      "1 teaspoon dried thyme",
      "Salt and pepper to taste",
      "Fresh parsley and chives for garnish"
    ],
    instructions: [
      "Heat butter or oil in a large pot over medium-high heat. Add diced chicken and cook until browned, about 5-6 minutes. Remove and set aside.",
      "In the same pot, add onion, carrots, and celery. Sauté for 5 minutes until softened.",
      "Add garlic and cook for 1 minute.",
      "If using flour for extra thickness, sprinkle it over the vegetables and stir for 1 minute.",
      "Pour in chicken broth and add thyme. Bring to a boil.",
      "Add noodles and cook according to package directions.",
      "Return chicken to the pot. Reduce heat to low.",
      "Stir in coconut milk or cream. Simmer for 5 minutes until heated through and slightly thickened.",
      "Season with salt and pepper to taste.",
      "Serve hot, garnished with fresh parsley and chives."
    ],
    tags: ["gluten-free", "chicken noodle soup", "creamy", "comfort food", "soups & stews", "rich", "coconut milk", "dairy-free option", "cozy", "velvety"],
    nutrition: {
      calories: 340,
      protein: "24g",
      carbs: "30g",
      fat: "14g",
      fiber: "3g",
      sodium: "720mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Lemon & Dill Chicken Noodle Soup",
    slug: "gluten-free-lemon-dill-chicken-noodle-soup",
    seoTitle: "Gluten-Free Lemon & Dill Chicken Noodle Soup - Bright & Fresh",
    description: "Bright, citrusy twist with fresh dill and lemon juice — light yet deeply flavorful and refreshing.",
    longDescription: "This gluten-free lemon and dill chicken noodle soup is a bright, refreshing take on the classic that's perfect when you want something light yet satisfying. Fresh lemon juice and zest add vibrant citrus notes that wake up your palate, while fresh dill brings herbaceous freshness. The combination is reminiscent of Greek avgolemono soup but with the comforting addition of noodles and vegetables. Tender chicken and gluten-free noodles provide heartiness, while the lemon-dill combination keeps it feeling light and fresh. This soup is particularly wonderful in spring or when you're feeling under the weather — the bright flavors are uplifting and the warmth is soothing.",
    seoDescription: "Gluten-free lemon dill chicken noodle soup with fresh herbs and citrus. Bright, light, and refreshing twist on classic comfort soup.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-lemon-dill-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken breasts",
      "8 cups gluten-free chicken broth",
      "Juice and zest of 2 lemons",
      "1/2 cup fresh dill, chopped",
      "2 carrots, peeled and sliced",
      "2 celery stalks, sliced",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "8 oz gluten-free noodles",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "Lemon slices for serving",
      "Extra fresh dill for garnish"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes.",
      "Add garlic and cook for 1 minute.",
      "Pour in chicken broth and bring to a boil.",
      "Add chicken breasts, reduce heat, and simmer for 20 minutes until cooked through.",
      "Remove chicken, shred with two forks, and set aside.",
      "Add noodles to the pot and cook according to package directions.",
      "Return shredded chicken to the pot.",
      "Stir in lemon juice, lemon zest, and fresh dill.",
      "Season with salt and pepper to taste.",
      "Serve hot with lemon slices and extra dill for garnish."
    ],
    tags: ["gluten-free", "chicken noodle soup", "lemon", "dill", "fresh", "bright", "soups & stews", "light", "citrus", "herbs"],
    nutrition: {
      calories: 270,
      protein: "25g",
      carbs: "28g",
      fat: "5g",
      fiber: "3g",
      sodium: "760mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Thai Coconut Chicken Noodle Soup",
    slug: "gluten-free-thai-coconut-chicken-noodle-soup",
    seoTitle: "Gluten-Free Thai Coconut Chicken Noodle Soup - Aromatic & Creamy",
    description: "Coconut milk base with lime, ginger, and chili for a creamy, aromatic, Southeast Asian-inspired bowl.",
    longDescription: "This gluten-free Thai coconut chicken noodle soup transforms the classic into an exotic, aromatic experience inspired by Thai tom kha gai. Creamy coconut milk forms the base, infused with lemongrass, ginger, and lime for authentic Southeast Asian flavors. Rice noodles replace traditional egg noodles, while tender chicken, mushrooms, and fresh herbs create layers of flavor and texture. The combination of creamy, spicy, sour, and aromatic elements creates a complex, satisfying soup that's both comforting and exciting. Red chili adds heat, while lime juice provides brightness. This is comfort food with a global twist — perfect when you want something familiar but adventurous.",
    seoDescription: "Gluten-free Thai coconut chicken noodle soup with lemongrass, lime, and ginger. Creamy Southeast Asian-inspired comfort soup with rice noodles.",
    category: "Soups & Stews",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-thai-coconut-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken thighs, sliced",
      "4 cups gluten-free chicken broth",
      "2 cans (13.5 oz each) coconut milk",
      "8 oz rice noodles",
      "1 stalk lemongrass, bruised and cut into 2-inch pieces",
      "3 tablespoons fresh ginger, sliced",
      "3 cloves garlic, minced",
      "1 cup mushrooms, sliced",
      "2 Thai red chilies, sliced (or 1 teaspoon chili paste)",
      "3 tablespoons gluten-free fish sauce",
      "Juice of 2 limes",
      "1 tablespoon coconut oil",
      "Fresh cilantro, Thai basil, and lime wedges for serving"
    ],
    instructions: [
      "Cook rice noodles according to package directions. Drain and set aside.",
      "Heat coconut oil in a large pot over medium heat. Add chicken and cook until browned, about 5 minutes. Remove and set aside.",
      "In the same pot, add ginger, garlic, and lemongrass. Cook for 2 minutes until fragrant.",
      "Pour in chicken broth and coconut milk. Bring to a gentle boil.",
      "Add mushrooms and chilies. Simmer for 10 minutes.",
      "Return chicken to the pot. Add fish sauce and simmer for 5 more minutes.",
      "Remove lemongrass pieces.",
      "Stir in lime juice.",
      "Divide cooked noodles among bowls, ladle soup over the top.",
      "Garnish with fresh cilantro, Thai basil, and lime wedges."
    ],
    tags: ["gluten-free", "chicken noodle soup", "Thai", "coconut milk", "Southeast Asian", "soups & stews", "aromatic", "rice noodles", "lemongrass", "exotic"],
    nutrition: {
      calories: 420,
      protein: "26g",
      carbs: "32g",
      fat: "22g",
      fiber: "2g",
      sodium: "840mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Turmeric Chicken Noodle Soup",
    slug: "gluten-free-turmeric-chicken-noodle-soup",
    seoTitle: "Gluten-Free Turmeric Chicken Noodle Soup - Golden & Healing",
    description: "Immune-boosting and golden-hued — featuring turmeric, garlic, and black pepper for anti-inflammatory benefits.",
    longDescription: "This gluten-free turmeric chicken noodle soup is not only comforting but also packed with immune-boosting properties. Turmeric gives the broth a beautiful golden color while providing powerful anti-inflammatory benefits, especially when paired with black pepper which enhances turmeric absorption. Fresh ginger adds warmth and additional immune support, while garlic provides its well-known health benefits. Beyond the wellness aspects, this soup is deeply flavorful — earthy, slightly peppery, and warming. Tender chicken and gluten-free noodles make it a complete meal. This is the perfect soup when you're feeling under the weather or want something that's both nourishing and healing.",
    seoDescription: "Gluten-free turmeric chicken noodle soup with immune-boosting spices. Golden, healing soup with anti-inflammatory benefits and comforting flavors.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-turmeric-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken thighs, diced",
      "8 cups gluten-free chicken broth",
      "2 tablespoons fresh turmeric, grated (or 2 teaspoons ground turmeric)",
      "2 tablespoons fresh ginger, grated",
      "4 cloves garlic, minced",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "1 onion, diced",
      "8 oz gluten-free noodles",
      "2 tablespoons coconut oil",
      "1 teaspoon black pepper",
      "1/2 teaspoon cayenne pepper (optional)",
      "Salt to taste",
      "Fresh parsley or cilantro for garnish",
      "Lemon wedges for serving"
    ],
    instructions: [
      "Heat coconut oil in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes.",
      "Add garlic, ginger, and turmeric. Cook for 2 minutes, stirring constantly to prevent burning.",
      "Add diced chicken and cook until browned on the outside, about 5 minutes.",
      "Pour in chicken broth and add black pepper. Bring to a boil.",
      "Reduce heat and simmer for 15 minutes.",
      "Add gluten-free noodles and cook according to package directions.",
      "Season with salt and cayenne pepper if using.",
      "Serve hot, garnished with fresh herbs and lemon wedges."
    ],
    tags: ["gluten-free", "chicken noodle soup", "turmeric", "immune-boosting", "anti-inflammatory", "soups & stews", "healing", "golden", "ginger", "healthy"],
    nutrition: {
      calories: 290,
      protein: "25g",
      carbs: "30g",
      fat: "8g",
      fiber: "3g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Ginger Miso Chicken Noodle Soup",
    slug: "gluten-free-ginger-miso-chicken-noodle-soup",
    seoTitle: "Gluten-Free Ginger Miso Chicken Noodle Soup - Asian Fusion",
    description: "Asian fusion with gluten-free rice noodles, white miso, ginger, and scallions for soothing umami flavor.",
    longDescription: "This gluten-free ginger miso chicken noodle soup is an Asian fusion take on the classic, bringing together the comforting elements of chicken soup with the umami richness of miso and the warming properties of ginger. White miso paste adds depth and complexity without overwhelming the other flavors, while fresh ginger provides spicy warmth. Rice noodles replace traditional egg noodles for an authentic Asian touch. Shiitake mushrooms add earthiness, and scallions provide fresh, oniony bite. The result is a soup that's both familiar and exotic, comforting yet exciting. It's perfect for when you want the soul-soothing properties of chicken soup with a sophisticated twist.",
    seoDescription: "Gluten-free ginger miso chicken noodle soup with rice noodles and shiitake mushrooms. Asian fusion comfort soup with umami-rich flavors.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-ginger-miso-chicken-noodle-soup.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken breast, sliced thin",
      "8 cups gluten-free chicken broth",
      "3 tablespoons white miso paste (ensure gluten-free)",
      "3 tablespoons fresh ginger, grated",
      "4 cloves garlic, minced",
      "1 cup shiitake mushrooms, sliced",
      "8 oz rice noodles",
      "4 scallions, sliced (white and green parts separated)",
      "2 tablespoons sesame oil",
      "1 tablespoon gluten-free soy sauce or tamari",
      "2 cups baby spinach",
      "Soft-boiled eggs for serving (optional)",
      "Sesame seeds for garnish"
    ],
    instructions: [
      "Cook rice noodles according to package directions. Drain and set aside.",
      "Heat sesame oil in a large pot over medium heat. Add white parts of scallions, garlic, and ginger. Cook for 2 minutes.",
      "Add chicken and cook until no longer pink, about 5 minutes.",
      "Pour in chicken broth and bring to a boil.",
      "Add shiitake mushrooms and simmer for 10 minutes.",
      "In a small bowl, whisk miso paste with 1/2 cup of hot broth until smooth. Stir back into the pot.",
      "Add soy sauce and baby spinach. Cook until spinach wilts, about 2 minutes.",
      "Divide cooked noodles among bowls, ladle soup over the top.",
      "Garnish with green parts of scallions, sesame seeds, and soft-boiled eggs if desired."
    ],
    tags: ["gluten-free", "chicken noodle soup", "miso", "ginger", "Asian fusion", "soups & stews", "umami", "rice noodles", "Japanese-inspired", "mushrooms"],
    nutrition: {
      calories: 310,
      protein: "27g",
      carbs: "32g",
      fat: "8g",
      fiber: "2g",
      sodium: "920mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Chicken Noodle Soup with Wild Mushrooms",
    slug: "gluten-free-chicken-noodle-soup-wild-mushrooms",
    seoTitle: "Gluten-Free Chicken Noodle Soup with Wild Mushrooms - Earthy & Savory",
    description: "Earthy wild mushrooms and fresh herbs create a deep, savory variation of the classic comfort soup.",
    longDescription: "This gluten-free chicken noodle soup with wild mushrooms elevates the classic with the earthy, umami-rich flavors of mixed wild mushrooms. A combination of shiitake, oyster, and cremini mushrooms adds depth and complexity, creating a sophisticated soup that's still wonderfully comforting. The mushrooms are sautéed first to develop their flavors, then simmered in the broth where they infuse every spoonful with earthy goodness. Fresh thyme complements the mushrooms perfectly, while tender chicken and gluten-free noodles make it a complete meal. This is for mushroom lovers who want their chicken soup to be both elegant and deeply satisfying.",
    seoDescription: "Gluten-free chicken noodle soup with wild mushrooms and fresh thyme. Earthy, savory variation with shiitake, oyster, and cremini mushrooms.",
    category: "Soups & Stews",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-chicken-noodle-soup-wild-mushrooms.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken thighs",
      "8 cups gluten-free chicken broth",
      "8 oz mixed wild mushrooms (shiitake, oyster, cremini), sliced",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "1 onion, diced",
      "4 cloves garlic, minced",
      "8 oz gluten-free noodles",
      "3 tablespoons butter",
      "2 tablespoons olive oil",
      "2 teaspoons fresh thyme leaves",
      "1 bay leaf",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
      "Grated Parmesan for serving (optional)"
    ],
    instructions: [
      "Heat butter and 1 tablespoon olive oil in a large pot over medium-high heat. Add mushrooms and cook until browned, about 6-7 minutes. Remove and set aside.",
      "In the same pot, heat remaining olive oil. Add onion, carrots, and celery. Sauté for 5 minutes.",
      "Add garlic and cook for 1 minute.",
      "Pour in chicken broth, add thyme and bay leaf. Bring to a boil.",
      "Add chicken and simmer for 20 minutes until cooked through.",
      "Remove chicken, shred, and set aside.",
      "Return mushrooms to the pot. Add noodles and cook according to package directions.",
      "Return shredded chicken to the pot. Season with salt and pepper.",
      "Remove bay leaf. Serve hot, garnished with fresh parsley and Parmesan if desired."
    ],
    tags: ["gluten-free", "chicken noodle soup", "wild mushrooms", "earthy", "savory", "soups & stews", "shiitake", "umami", "herbs", "gourmet"],
    nutrition: {
      calories: 310,
      protein: "26g",
      carbs: "30g",
      fat: "10g",
      fiber: "3g",
      sodium: "790mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Chicken Noodle Soup with Spinach & White Beans",
    slug: "gluten-free-chicken-noodle-soup-spinach-white-beans",
    seoTitle: "Gluten-Free Chicken Noodle Soup with Spinach & White Beans - Protein-Packed",
    description: "Protein-packed and nutrient-rich — hearty yet light with fresh spinach and creamy white beans.",
    longDescription: "This gluten-free chicken noodle soup with spinach and white beans is a nutritional powerhouse that doesn't sacrifice comfort or flavor. Cannellini beans add extra protein and fiber, making the soup more filling and nutritious. Fresh spinach wilts into the hot broth, adding vibrant color and a boost of vitamins. The combination of chicken, beans, and noodles creates a complete protein-rich meal that's both hearty and surprisingly light. This soup is perfect for when you want something that nourishes your body while still providing maximum comfort. The white beans add a creamy texture without heaviness, and the spinach keeps it feeling fresh.",
    seoDescription: "Gluten-free chicken noodle soup with spinach and white beans. Protein-packed, nutrient-rich comfort soup with cannellini beans and fresh greens.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-chicken-noodle-soup-spinach-white-beans.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken breast, diced",
      "8 cups gluten-free chicken broth",
      "1 can (15 oz) cannellini beans, drained and rinsed",
      "4 cups fresh spinach",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "8 oz gluten-free noodles",
      "2 tablespoons olive oil",
      "1 teaspoon dried oregano",
      "1/2 teaspoon red pepper flakes (optional)",
      "Salt and pepper to taste",
      "Grated Parmesan for serving",
      "Lemon wedges"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes.",
      "Add garlic, oregano, and red pepper flakes. Cook for 1 minute.",
      "Add diced chicken and cook until browned, about 5-6 minutes.",
      "Pour in chicken broth and bring to a boil.",
      "Add noodles and cook according to package directions.",
      "Stir in cannellini beans and spinach. Cook for 2-3 minutes until spinach wilts.",
      "Season with salt and pepper to taste.",
      "Serve hot, topped with grated Parmesan and lemon wedges."
    ],
    tags: ["gluten-free", "chicken noodle soup", "spinach", "white beans", "protein-rich", "soups & stews", "healthy", "nutritious", "cannellini beans", "hearty"],
    nutrition: {
      calories: 320,
      protein: "30g",
      carbs: "35g",
      fat: "6g",
      fiber: "7g",
      sodium: "760mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Chicken Noodle Soup with Roasted Garlic & Thyme",
    slug: "gluten-free-chicken-noodle-soup-roasted-garlic-thyme",
    seoTitle: "Gluten-Free Chicken Noodle Soup with Roasted Garlic & Thyme - Elevated Comfort",
    description: "Roasted garlic and fresh thyme infuse the broth for an aromatic, elevated take on classic comfort soup.",
    longDescription: "This gluten-free chicken noodle soup with roasted garlic and thyme is an elevated version of the classic that's perfect for when you want something a bit more special. Whole garlic cloves are roasted until soft, sweet, and caramelized, then mashed into the broth where they add incredible depth and complexity. Fresh thyme sprigs infuse the soup with herbaceous, aromatic notes that complement the roasted garlic beautifully. The combination creates a sophisticated soup that's still wonderfully comforting. Tender chicken and gluten-free noodles make it hearty, while the aromatic elements make it feel gourmet. This is the soup to serve when you want to impress.",
    seoDescription: "Gluten-free chicken noodle soup with roasted garlic and fresh thyme. Elevated, aromatic comfort soup with sweet roasted garlic and herbs.",
    category: "Soups & Stews",
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-chicken-noodle-soup-roasted-garlic-thyme.png",
    ingredients: [
      "1.5 lbs boneless, skinless chicken breasts",
      "8 cups gluten-free chicken broth",
      "1 head garlic, cloves separated but unpeeled",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "1 onion, diced",
      "6-8 sprigs fresh thyme",
      "2 bay leaves",
      "8 oz gluten-free noodles",
      "3 tablespoons olive oil",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
      "Crusty gluten-free bread for serving"
    ],
    instructions: [
      "Preheat oven to 400°F. Toss garlic cloves with 1 tablespoon olive oil and wrap in foil. Roast for 20 minutes until soft. Squeeze out cloves and mash into a paste.",
      "Heat remaining olive oil in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes.",
      "Add roasted garlic paste and stir for 1 minute.",
      "Pour in chicken broth. Add thyme sprigs and bay leaves. Bring to a boil.",
      "Add chicken and simmer for 20 minutes until cooked through.",
      "Remove chicken, shred, and set aside.",
      "Add noodles and cook according to package directions.",
      "Return chicken to the pot. Season with salt and pepper.",
      "Remove thyme sprigs and bay leaves.",
      "Serve hot, garnished with fresh parsley."
    ],
    tags: ["gluten-free", "chicken noodle soup", "roasted garlic", "thyme", "elevated", "soups & stews", "aromatic", "herbs", "gourmet", "sophisticated"],
    nutrition: {
      calories: 290,
      protein: "26g",
      carbs: "30g",
      fat: "7g",
      fiber: "3g",
      sodium: "770mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Slow Cooker Chicken Noodle Soup",
    slug: "gluten-free-slow-cooker-chicken-noodle-soup",
    seoTitle: "Gluten-Free Slow Cooker Chicken Noodle Soup - Hands-Off Comfort",
    description: "Hands-off, all-day simmered version with tender chicken and perfect noodle texture — ultimate convenience and flavor.",
    longDescription: "This gluten-free slow cooker chicken noodle soup is the ultimate set-it-and-forget-it comfort meal. The chicken, vegetables, and broth simmer together all day, developing deep, rich flavors while you go about your day. The chicken becomes incredibly tender, practically falling apart, and the vegetables become melt-in-your-mouth soft. The key is to add the noodles during the last 30 minutes of cooking to prevent them from getting mushy. When you come home, your house will smell amazing and dinner will be ready. This is perfect for busy weekdays when you want a homemade meal with minimal effort.",
    seoDescription: "Gluten-free slow cooker chicken noodle soup with all-day simmered flavors. Hands-off convenience with tender chicken and perfect texture.",
    category: "Soups & Stews",
    prepTime: 15,
    cookTime: 360,
    totalTime: 375,
    servings: 8,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-slow-cooker-chicken-noodle-soup.png",
    ingredients: [
      "2 lbs boneless, skinless chicken breasts or thighs",
      "8 cups gluten-free chicken broth",
      "3 carrots, peeled and sliced",
      "3 celery stalks, sliced",
      "1 large onion, diced",
      "4 cloves garlic, minced",
      "2 bay leaves",
      "1 teaspoon dried thyme",
      "1 teaspoon dried parsley",
      "8 oz gluten-free noodles",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Place chicken breasts, carrots, celery, onion, garlic, bay leaves, thyme, and dried parsley in a slow cooker.",
      "Pour in chicken broth. Season with salt and pepper.",
      "Cover and cook on LOW for 6-7 hours or HIGH for 3-4 hours.",
      "Remove chicken from slow cooker and shred with two forks.",
      "Return shredded chicken to the slow cooker.",
      "Add gluten-free noodles. Cover and cook on HIGH for 20-30 minutes until noodles are tender.",
      "Remove bay leaves. Taste and adjust seasoning if needed.",
      "Serve hot, garnished with fresh parsley."
    ],
    tags: ["gluten-free", "chicken noodle soup", "slow cooker", "hands-off", "easy", "soups & stews", "set-and-forget", "convenient", "tender chicken", "all-day simmered"],
    nutrition: {
      calories: 280,
      protein: "28g",
      carbs: "28g",
      fat: "5g",
      fiber: "3g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: false
  }
];

async function addRecipes() {
  console.log("Adding 10 Gluten-Free Chicken Noodle Soup recipes...");
  
  for (const recipe of chickenSoupRecipes) {
    try {
      await db.insert(recipes).values({
        id: nanoid(),
        ...recipe,
        rating: "4.8",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`✓ Added: ${recipe.title}`);
    } catch (error) {
      console.error(`✗ Error adding ${recipe.title}:`, error);
    }
  }
  
  console.log("\n✅ All recipes added successfully!");
  process.exit(0);
}

addRecipes();
