import { db } from "../server/db";
import { recipes } from "../shared/schema";

const sausageRollWreaths = [
  {
    title: "Gluten-Free Sausage Roll Wreath with Caramelized Onions & Sage",
    slug: "gluten-free-sausage-roll-wreath-caramelized-onions-sage",
    description: "Sweet onions, savory pork sausage, and aromatic sage — a perfect holiday centerpiece with mustard dipping sauce.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Caramelized Onions & Sage is the ultimate holiday centerpiece that combines classic flavors in a stunning presentation. Golden, flaky gluten-free puff pastry encases a savory filling of quality pork sausage enriched with sweet caramelized onions that have been slowly cooked to jammy perfection, and fresh sage that adds an earthy, aromatic quality. The wreath is assembled by arranging individual sausage rolls in a circular pattern, creating a beautiful ring that's perfect for sharing. As it bakes, the pastry becomes crispy and golden, while the sausage stays juicy and the onions become even sweeter. The combination of rich meat, sweet onions, and herbaceous sage is timeless and sophisticated. Serve this impressive wreath warm from the oven with grainy mustard for dipping, and watch it disappear at holiday parties, Christmas gatherings, or New Year's Eve celebrations. It's easier to make than it looks but delivers restaurant-quality results.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 30,
    totalTime: 75,
    servings: 12,
    rating: "5.0",
    calories: 285,
    protein: "12.0",
    carbs: "18.0",
    fat: "18.0",
    fiber: "1.0",
    sugar: "3.0",
    image: "/recipe-images/sausage-roll-wreath-caramelized-onions-sage.png",
    ingredients: [
      "1 lb gluten-free puff pastry (thawed if frozen)",
      "1 lb pork sausage meat (ensure gluten-free)",
      "2 large yellow onions, thinly sliced",
      "3 tablespoons butter",
      "2 tablespoons fresh sage, chopped",
      "1 tablespoon olive oil",
      "1 teaspoon brown sugar",
      "1 egg, beaten (for egg wash)",
      "2 tablespoons sesame seeds",
      "Salt and pepper to taste",
      "Grainy mustard for serving",
      "Fresh sage leaves for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet over medium-low heat, melt butter with olive oil. Add sliced onions and cook 30-35 minutes, stirring occasionally, until deep golden brown. Add brown sugar in last 5 minutes. Season with salt and pepper. Let cool completely.",
      "Mix cooled caramelized onions with sausage meat and chopped sage until well combined.",
      "Preheat oven to 400°F. Line two large baking sheets with parchment paper.",
      "Roll out puff pastry on lightly floured surface to 1/4-inch thickness. Cut into rectangles approximately 3x5 inches (you should get about 16-20 pieces).",
      "Place 2 tablespoons of sausage-onion mixture along one long edge of each pastry rectangle, leaving 1/2 inch border.",
      "Roll pastry tightly around filling to create sausage rolls. Seal edge with beaten egg.",
      "To form wreath: Arrange sausage rolls in a circle on prepared baking sheet, slightly overlapping and placing them at an angle. The wreath should be about 10-12 inches in diameter.",
      "Brush entire wreath with beaten egg wash. Sprinkle with sesame seeds and additional sage leaves.",
      "Bake 25-30 minutes until pastry is deep golden brown and sausage is cooked through (internal temp 160°F).",
      "Let cool 10 minutes. Transfer to serving platter using two spatulas.",
      "Place bowl of grainy mustard in center of wreath. Garnish with fresh sage sprigs."
    ],
    tips: "Make sure onions are completely cool before mixing with sausage to prevent pastry from becoming soggy. If puff pastry becomes too soft while working, refrigerate for 15 minutes. Seal rolls very well to prevent leaking during baking. The wreath can be assembled up to 24 hours ahead and refrigerated — just add 5 minutes to baking time if baking from cold.",
    variations: [
      "Add chopped apple to the sausage mixture for sweetness",
      "Use chicken or turkey sausage for lighter version",
      "Top with balsamic glaze after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "holiday", "entertaining", "puff pastry", "caramelized onions", "sage", "appetizer", "party food"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Caramelized Onions & Sage - Holiday Centerpiece",
    seoDescription: "Stunning gluten-free sausage roll wreath with caramelized onions and sage. Perfect holiday party centerpiece appetizer."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Cranberry Dijon Glaze",
    slug: "gluten-free-sausage-roll-wreath-cranberry-dijon-glaze",
    description: "A festive favorite — sausage rolls brushed with tangy cranberry-Dijon glaze for color and flavor.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Cranberry Dijon Glaze is pure holiday magic on a plate, combining savory sausage with a glossy, tangy-sweet glaze that's as beautiful as it is delicious. Classic pork sausage is wrapped in flaky gluten-free puff pastry and arranged in a festive wreath shape, then baked until golden and crispy. But what makes this recipe truly special is the cranberry-Dijon glaze that's brushed over the wreath in the final minutes of baking, creating a gorgeous ruby-red sheen and adding layers of flavor. The glaze combines tart cranberry sauce with sharp Dijon mustard and a touch of honey, creating the perfect balance of sweet, tangy, and savory. The result is a show-stopping appetizer that tastes as festive as it looks. The bright red glaze makes this wreath unmistakably holiday-themed, perfect for Christmas parties, Thanksgiving gatherings, or any winter celebration where you want to serve something special.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    servings: 12,
    rating: "5.0",
    calories: 275,
    protein: "11.0",
    carbs: "22.0",
    fat: "16.0",
    fiber: "1.0",
    sugar: "8.0",
    image: "/recipe-images/sausage-roll-wreath-cranberry-dijon.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb pork sausage meat",
      "½ cup cranberry sauce (ensure gluten-free)",
      "3 tablespoons Dijon mustard",
      "2 tablespoons honey",
      "1 tablespoon apple cider vinegar",
      "1 egg, beaten",
      "2 teaspoons fresh thyme leaves",
      "Salt and pepper to taste",
      "Fresh cranberries and thyme for garnish"
    ],
    instructions: [
      "Season sausage meat with thyme, salt, and pepper. Mix well.",
      "For cranberry glaze: In small saucepan, combine cranberry sauce, Dijon mustard, honey, and vinegar. Heat over medium heat, stirring, until smooth and slightly thickened, about 5 minutes. Set aside.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll out puff pastry to 1/4-inch thickness. Cut into 3x5 inch rectangles.",
      "Place sausage filling along one edge of each rectangle. Roll tightly and seal with egg wash.",
      "Arrange sausage rolls in circular wreath pattern on baking sheet, overlapping slightly.",
      "Brush wreath with beaten egg.",
      "Bake 20 minutes until pastry is golden and puffing.",
      "Remove from oven and generously brush with cranberry-Dijon glaze.",
      "Return to oven for 5-7 more minutes until glaze is set and glossy.",
      "Cool 10 minutes. Garnish with fresh cranberries and thyme sprigs.",
      "Serve warm with extra glaze on the side for dipping."
    ],
    tips: "Don't apply glaze too early or pastry will become soggy — wait until the last 5-7 minutes of baking. The glaze can be made up to a week ahead and refrigerated. Warm it before brushing on the wreath. For extra festive appearance, add whole cranberries around the wreath before final baking.",
    variations: [
      "Use orange marmalade instead of cranberry sauce",
      "Add orange zest to the glaze",
      "Mix dried cranberries into the sausage filling"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "cranberry", "dijon", "holiday", "christmas", "entertaining", "glazed", "festive"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Cranberry Dijon Glaze - Festive Holiday Appetizer",
    seoDescription: "Festive gluten-free sausage roll wreath glazed with tangy cranberry-Dijon sauce. Beautiful holiday party centerpiece."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Cheddar & Apple",
    slug: "gluten-free-sausage-roll-wreath-cheddar-apple",
    description: "Sharp cheddar and grated apple mixed into the sausage for a sweet-savory flavor contrast.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Cheddar & Apple is a brilliant combination that proves sweet and savory belong together. The filling combines quality pork sausage with sharp cheddar cheese that melts during baking, creating pockets of gooey, tangy richness, and freshly grated apple that adds subtle sweetness and keeps the meat incredibly moist. The apple essentially melts into the sausage as it cooks, adding moisture and a gentle fruity note that complements the rich pork and sharp cheese beautifully. As the wreath bakes, the cheddar cheese melts and sometimes oozes out slightly, creating delicious crispy cheese edges on the pastry. This flavor combination is inspired by classic British pork-and-apple pairings but elevated with the addition of sharp cheddar. The result is a sausage roll wreath that's sophisticated, delicious, and perfect for fall and winter entertaining. Serve with apple chutney or honey mustard for dipping.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 28,
    totalTime: 58,
    servings: 12,
    rating: "4.9",
    calories: 295,
    protein: "13.0",
    carbs: "19.0",
    fat: "19.0",
    fiber: "1.0",
    sugar: "3.0",
    image: "/recipe-images/sausage-roll-wreath-cheddar-apple.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb pork sausage meat",
      "1 cup sharp cheddar cheese, grated",
      "1 medium apple (Granny Smith or Honeycrisp), peeled and grated",
      "1 tablespoon fresh thyme leaves",
      "½ teaspoon sage",
      "1 egg, beaten",
      "2 tablespoons pumpkin seeds or sesame seeds",
      "Salt and pepper to taste",
      "Apple chutney for serving"
    ],
    instructions: [
      "Squeeze excess moisture from grated apple using cheesecloth or paper towels.",
      "In bowl, combine sausage meat, grated apple, cheddar cheese, thyme, sage, salt, and pepper. Mix gently but thoroughly.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place about 2 tablespoons filling along one edge of each rectangle.",
      "Roll tightly, seal with egg wash.",
      "Arrange in circular wreath formation on baking sheet.",
      "Brush with egg wash and sprinkle with pumpkin seeds.",
      "Bake 25-28 minutes until golden brown and sausage is cooked through.",
      "Let rest 10 minutes before transferring to serving platter.",
      "Serve warm with apple chutney in center of wreath."
    ],
    tips: "Squeezing moisture from the grated apple is crucial to prevent soggy pastry. Use sharp cheddar for best flavor — mild cheddar won't provide enough contrast. Don't overmix the filling or sausage will become tough. The cheese may leak slightly during baking — this is normal and creates delicious crispy edges.",
    variations: [
      "Use smoked cheddar for extra depth",
      "Add chopped walnuts to the filling",
      "Try pear instead of apple"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "cheddar", "apple", "sweet savory", "holiday", "entertaining", "cheese", "fruit"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Cheddar & Apple - Sweet Savory Holiday Appetizer",
    seoDescription: "Delicious gluten-free sausage roll wreath with sharp cheddar and apple. Perfect sweet-savory holiday appetizer."
  },
  {
    title: "Gluten-Free Spicy Italian Sausage Roll Wreath with Roasted Peppers",
    slug: "gluten-free-spicy-italian-sausage-roll-wreath-roasted-peppers",
    description: "Bold and flavorful — Italian sausage, roasted peppers, and a sprinkle of Parmesan baked in flaky pastry.",
    longDescription: "This Gluten-Free Spicy Italian Sausage Roll Wreath with Roasted Peppers brings bold Italian flavors to the holiday table in spectacular fashion. Spicy Italian sausage provides the foundation, bringing fennel, garlic, and red pepper flakes for authentic Italian character. Sweet roasted red peppers add pops of color and sweetness that balance the spicy sausage beautifully, while grated Parmesan cheese adds savory umami depth. The combination is wrapped in flaky gluten-free puff pastry and formed into an impressive wreath that looks as good as it tastes. As it bakes, the sausage spices perfume the kitchen, the peppers become even sweeter, and the Parmesan creates a delicious crust. This wreath is perfect for those who love Italian flavors and want something with more kick than traditional sausage rolls. Serve with marinara sauce for dipping, and watch it disappear at holiday parties, game day gatherings, or any celebration where bold flavors are appreciated.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 28,
    totalTime: 58,
    servings: 12,
    rating: "5.0",
    calories: 290,
    protein: "13.0",
    carbs: "18.0",
    fat: "19.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/sausage-roll-wreath-spicy-italian.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb spicy Italian sausage (ensure gluten-free)",
      "½ cup roasted red peppers, chopped",
      "½ cup Parmesan cheese, grated",
      "2 cloves garlic, minced",
      "2 tablespoons fresh basil, chopped",
      "1 teaspoon fennel seeds",
      "1 egg, beaten",
      "2 tablespoons Italian seasoning",
      "Marinara sauce for serving",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Remove sausage from casings if necessary. In bowl, combine sausage, chopped roasted peppers, Parmesan, garlic, basil, and fennel seeds. Mix well.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place 2 tablespoons filling along one edge of each pastry rectangle.",
      "Roll tightly around filling, seal with egg wash.",
      "Arrange in wreath formation on baking sheet, overlapping slightly.",
      "Brush entire wreath with beaten egg.",
      "Sprinkle with Italian seasoning and extra Parmesan.",
      "Bake 25-28 minutes until golden and sausage reaches 160°F internal temperature.",
      "Let cool 10 minutes.",
      "Transfer to serving platter. Place bowl of warm marinara in center.",
      "Garnish with fresh basil leaves."
    ],
    tips: "Pat roasted peppers dry before chopping to prevent excess moisture. If you can't find spicy Italian sausage, use mild and add red pepper flakes to taste. The Parmesan on top creates a delicious crispy crust — don't skip it! This wreath is delicious warm or at room temperature.",
    variations: [
      "Add sun-dried tomatoes to the filling",
      "Use mozzarella instead of Parmesan",
      "Top with pesto after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "italian", "spicy", "roasted peppers", "parmesan", "holiday", "entertaining", "bold flavors"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Spicy Italian Sausage Roll Wreath with Roasted Peppers - Bold Holiday Appetizer",
    seoDescription: "Bold gluten-free Italian sausage roll wreath with roasted peppers and Parmesan. Spicy holiday party centerpiece."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Maple Bacon & Thyme",
    slug: "gluten-free-sausage-roll-wreath-maple-bacon-thyme",
    description: "Sweet and smoky — crumbled bacon, maple syrup glaze, and thyme for depth and aroma.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Maple Bacon & Thyme is a celebration of sweet-and-savory combinations that work perfectly together. Quality pork sausage is studded with crispy, crumbled bacon for smoky richness and textural contrast, while fresh thyme adds an earthy, herbaceous note that ties everything together. The real showstopper is the maple glaze that's brushed over the golden wreath in the final minutes of baking, creating a glossy finish and adding gentle sweetness that complements the smoky bacon and savory sausage beautifully. As it bakes, your kitchen fills with the irresistible aroma of maple, bacon, and herbs — a scent that says 'holiday breakfast' or 'special brunch' like nothing else. This wreath is perfect for Christmas morning brunch, New Year's Day gatherings, or any occasion where you want to serve something that feels indulgent and special. The combination is universally loved and always impressive.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 30,
    totalTime: 65,
    servings: 12,
    rating: "5.0",
    calories: 310,
    protein: "12.0",
    carbs: "20.0",
    fat: "20.0",
    fiber: "0.5",
    sugar: "6.0",
    image: "/recipe-images/sausage-roll-wreath-maple-bacon-thyme.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb pork sausage meat",
      "6 strips bacon, cooked crispy and crumbled",
      "3 tablespoons fresh thyme leaves, divided",
      "¼ cup pure maple syrup",
      "2 tablespoons butter, melted",
      "1 egg, beaten",
      "1 teaspoon Dijon mustard",
      "Salt and pepper to taste",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Cook bacon until crispy. Drain, cool, and crumble into small pieces.",
      "In bowl, combine sausage meat, crumbled bacon, and 2 tablespoons thyme. Season with salt and pepper. Mix gently.",
      "For maple glaze: Whisk together maple syrup, melted butter, Dijon mustard, and remaining thyme.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll out puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place filling along one edge of each rectangle. Roll tightly, seal with egg wash.",
      "Arrange in circular wreath on baking sheet.",
      "Brush with beaten egg.",
      "Bake 20 minutes until golden.",
      "Remove from oven and brush generously with maple glaze.",
      "Return to oven for 8-10 more minutes until glaze is caramelized and pastry is deep golden.",
      "Cool 10 minutes. Garnish with fresh thyme sprigs and serve warm."
    ],
    tips: "Make sure bacon is very crispy before crumbling — it needs to hold up in the moist sausage filling. Don't apply maple glaze too early or it will burn. Wait until the last 10 minutes of baking. The glaze will be sticky and shiny when done. This wreath is excellent for brunch served with scrambled eggs.",
    variations: [
      "Add a pinch of cayenne to glaze for heat",
      "Use turkey bacon for lighter version",
      "Add chopped apple to the filling"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "maple", "bacon", "thyme", "sweet savory", "holiday", "brunch", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Maple Bacon & Thyme - Sweet Savory Holiday Brunch",
    seoDescription: "Indulgent gluten-free sausage roll wreath with bacon, maple glaze, and thyme. Perfect holiday brunch centerpiece."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Spinach & Feta",
    slug: "gluten-free-sausage-roll-wreath-spinach-feta",
    description: "Greek-inspired twist — spinach, feta, and herbs wrapped with mild sausage in puff pastry.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Spinach & Feta brings Mediterranean flavors to the traditional British sausage roll format, creating something that's both familiar and excitingly different. Mild pork or chicken sausage provides the protein base, while fresh spinach adds vibrant color, nutrients, and a slightly earthy flavor. Crumbled feta cheese brings tangy, salty brightness that cuts through the richness of the meat, and a blend of Mediterranean herbs (oregano, dill, and garlic) ties everything together. The combination is wrapped in flaky gluten-free puff pastry and formed into a beautiful wreath that's as impressive to look at as it is to eat. The bright green spinach and white feta create beautiful visual interest when you cut into the wreath. This version is perfect for those who want something lighter than all-meat sausage rolls but still crave that satisfying savory pastry experience. Serve with tzatziki sauce for an authentic Greek touch.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 28,
    totalTime: 63,
    servings: 12,
    rating: "4.9",
    calories: 265,
    protein: "11.0",
    carbs: "18.0",
    fat: "17.0",
    fiber: "1.5",
    sugar: "1.0",
    image: "/recipe-images/sausage-roll-wreath-spinach-feta.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "12 oz mild sausage meat or chicken sausage",
      "10 oz frozen spinach, thawed and squeezed dry",
      "6 oz feta cheese, crumbled",
      "2 cloves garlic, minced",
      "2 tablespoons fresh dill, chopped",
      "1 teaspoon dried oregano",
      "1 egg, beaten",
      "2 tablespoons sesame seeds",
      "Pinch of nutmeg",
      "Salt and pepper to taste",
      "Tzatziki sauce for serving"
    ],
    instructions: [
      "Squeeze spinach very dry using cheesecloth or paper towels — it should be almost completely dry.",
      "In bowl, combine sausage meat, squeezed spinach, crumbled feta, garlic, dill, oregano, nutmeg, salt, and pepper. Mix gently but thoroughly.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place 2 tablespoons filling along one edge of each rectangle.",
      "Roll tightly, seal edges with egg wash.",
      "Arrange in wreath formation on baking sheet.",
      "Brush with egg wash and sprinkle with sesame seeds.",
      "Bake 25-28 minutes until golden brown and sausage is cooked through.",
      "Cool 10 minutes.",
      "Transfer to platter with bowl of tzatziki in center.",
      "Garnish with fresh dill."
    ],
    tips: "Squeezing spinach completely dry is crucial — excess moisture will make the pastry soggy and cause it to burst. Use frozen spinach rather than fresh as it's easier to squeeze dry. If using chicken sausage, season more assertively as it's milder than pork. The filling can be made a day ahead and refrigerated.",
    variations: [
      "Add sun-dried tomatoes to filling",
      "Use ricotta instead of feta for milder flavor",
      "Add pine nuts for crunch"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "spinach", "feta", "mediterranean", "greek", "holiday", "entertaining", "lighter"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Spinach & Feta - Mediterranean Holiday Appetizer",
    seoDescription: "Mediterranean-inspired gluten-free sausage roll wreath with spinach and feta. Lighter holiday party centerpiece."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Everything Bagel Seasoning",
    slug: "gluten-free-sausage-roll-wreath-everything-bagel-seasoning",
    description: "Trendy twist — topped with everything bagel seasoning and served with cream cheese dip.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Everything Bagel Seasoning is a modern, trendy take on the traditional sausage roll that celebrates one of the most popular flavor combinations of recent years. Classic pork sausage (or you can use chicken sausage for a lighter option) is wrapped in flaky gluten-free puff pastry and generously topped with everything bagel seasoning — that addictive blend of sesame seeds, poppy seeds, dried onion, dried garlic, and flaky salt. As the wreath bakes, the seeds toast and the onion and garlic bits become crispy and aromatic, creating incredible texture and flavor on top of the golden pastry. To complete the bagel-inspired theme, the wreath is served with a bowl of whipped cream cheese dip in the center, which can be plain or flavored with chives, smoked salmon, or everything bagel seasoning itself. This wreath is perfect for brunch gatherings, modern entertaining, or any occasion where you want to serve something current and Instagram-worthy while still being delicious and satisfying.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Easy",
    prepTime: 25,
    cookTime: 28,
    totalTime: 53,
    servings: 12,
    rating: "5.0",
    calories: 280,
    protein: "11.0",
    carbs: "19.0",
    fat: "18.0",
    fiber: "1.0",
    sugar: "1.0",
    image: "/recipe-images/sausage-roll-wreath-everything-bagel.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb pork or chicken sausage meat",
      "¼ cup everything bagel seasoning, plus more for topping",
      "1 egg, beaten",
      "8 oz cream cheese, softened",
      "2 tablespoons milk or cream",
      "2 tablespoons fresh chives, chopped",
      "1 teaspoon lemon juice",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Mix sausage meat with 2 tablespoons everything bagel seasoning, salt, and pepper.",
      "For cream cheese dip: Whip cream cheese with milk, chives, lemon juice, and 1 tablespoon everything bagel seasoning until smooth and fluffy. Refrigerate until serving.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place sausage filling along one edge of each rectangle. Roll tightly, seal with egg wash.",
      "Arrange in circular wreath on baking sheet.",
      "Brush generously with beaten egg.",
      "Sprinkle liberally with everything bagel seasoning, making sure to cover entire surface.",
      "Bake 25-28 minutes until deep golden brown and sausage is cooked through.",
      "Cool 10 minutes.",
      "Transfer to serving platter. Place bowl of whipped cream cheese dip in center of wreath.",
      "Serve warm or at room temperature."
    ],
    tips: "Don't be shy with the everything bagel seasoning — generous topping is key to this recipe's success. Use store-bought seasoning or make your own by combining sesame seeds, poppy seeds, dried minced onion, dried minced garlic, and flaky salt. The cream cheese dip can be made up to 3 days ahead. This wreath is delicious both warm and at room temperature.",
    variations: [
      "Add cream cheese directly into sausage filling",
      "Use smoked salmon cream cheese for dip",
      "Top with scallions after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "everything bagel", "trendy", "modern", "cream cheese", "holiday", "brunch", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Everything Bagel Seasoning - Modern Holiday Appetizer",
    seoDescription: "Trendy gluten-free sausage roll wreath with everything bagel seasoning and cream cheese dip. Modern holiday party food."
  },
  {
    title: "Gluten-Free Sausage Roll Wreath with Jalapeño & Cheddar",
    slug: "gluten-free-sausage-roll-wreath-jalapeno-cheddar",
    description: "Spicy and comforting — jalapeños and melted cheese baked into sausage filling for a kick.",
    longDescription: "This Gluten-Free Sausage Roll Wreath with Jalapeño & Cheddar is for those who like a little heat with their holiday appetizers. Classic pork sausage is kicked up with fresh jalapeño peppers that add bright, spicy flavor and beautiful green flecks throughout the filling, while sharp cheddar cheese melts during baking to create pockets of gooey, tangy richness that balance the heat perfectly. The combination is wrapped in flaky gluten-free puff pastry and formed into an impressive wreath that's golden on the outside and spicy-cheesy on the inside. As it bakes, the jalapeños mellow slightly but still provide a nice kick, and the cheddar cheese melts into the sausage and sometimes oozes out to create delicious crispy cheese edges. This wreath is perfect for game day gatherings, casual entertaining, or any occasion where you want to serve something with bold, Tex-Mex inspired flavors. Serve with chipotle mayo or ranch dressing for cooling contrast.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 28,
    totalTime: 58,
    servings: 12,
    rating: "4.9",
    calories: 295,
    protein: "12.0",
    carbs: "18.0",
    fat: "19.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/sausage-roll-wreath-jalapeno-cheddar.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb pork sausage meat",
      "1 cup sharp cheddar cheese, shredded",
      "2-3 fresh jalapeños, seeded and finely diced",
      "2 cloves garlic, minced",
      "1 teaspoon cumin",
      "1 teaspoon smoked paprika",
      "1 egg, beaten",
      "2 tablespoons fresh cilantro, chopped",
      "Salt and pepper to taste",
      "Chipotle mayo or ranch for serving"
    ],
    instructions: [
      "In bowl, combine sausage meat, diced jalapeños, cheddar cheese, garlic, cumin, paprika, cilantro, salt, and pepper. Mix well but gently.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place 2 tablespoons spicy cheese filling along one edge of each rectangle.",
      "Roll tightly around filling, seal with egg wash.",
      "Arrange in wreath formation on baking sheet, overlapping slightly.",
      "Brush entire wreath with beaten egg.",
      "Optionally, sprinkle with extra shredded cheddar on top.",
      "Bake 25-28 minutes until golden and sausage reaches 160°F.",
      "Let cool 10 minutes.",
      "Transfer to platter. Place bowl of chipotle mayo in center.",
      "Garnish with fresh jalapeño slices and cilantro."
    ],
    tips: "Remove seeds and membranes from jalapeños to control heat level — leave some seeds if you want more spice. The cheese may leak during baking — this is normal and creates delicious crispy edges. Use sharp or extra sharp cheddar for best flavor. Wear gloves when handling jalapeños to avoid skin irritation.",
    variations: [
      "Add diced green chiles for milder heat",
      "Use pepper jack cheese instead of cheddar",
      "Top with pickled jalapeños after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "jalapeño", "cheddar", "spicy", "tex-mex", "cheese", "holiday", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sausage Roll Wreath with Jalapeño & Cheddar - Spicy Holiday Appetizer",
    seoDescription: "Spicy gluten-free sausage roll wreath with jalapeños and cheddar cheese. Bold, cheesy holiday party food."
  },
  {
    title: "Gluten-Free Chicken Sausage Roll Wreath with Pesto & Sun-Dried Tomatoes",
    slug: "gluten-free-chicken-sausage-roll-wreath-pesto-sundried-tomatoes",
    description: "Light and Mediterranean — chicken sausage with basil pesto and diced sun-dried tomatoes.",
    longDescription: "This Gluten-Free Chicken Sausage Roll Wreath with Pesto & Sun-Dried Tomatoes is a lighter, brighter take on traditional sausage rolls that celebrates Mediterranean flavors. Mild chicken sausage provides lean protein that serves as a perfect canvas for the vibrant flavors of basil pesto and sun-dried tomatoes. The pesto adds herbaceous freshness and a beautiful green color, while the sun-dried tomatoes contribute intense umami sweetness and gorgeous dark red accents throughout the filling. Pine nuts (traditional in pesto) add textural interest and nutty flavor. The combination is wrapped in flaky gluten-free puff pastry and formed into an elegant wreath that looks as sophisticated as it tastes. This version is perfect for those who want something lighter than pork sausage, appreciate Mediterranean flavors, or are looking for a sausage roll that feels more summery and fresh even during holiday season. Serve with extra pesto for dipping or a simple balsamic reduction.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 25,
    totalTime: 55,
    servings: 12,
    rating: "4.9",
    calories: 260,
    protein: "12.0",
    carbs: "18.0",
    fat: "16.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/sausage-roll-wreath-chicken-pesto.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb chicken sausage meat (remove from casings)",
      "½ cup basil pesto (ensure gluten-free)",
      "⅓ cup sun-dried tomatoes packed in oil, drained and chopped",
      "¼ cup Parmesan cheese, grated",
      "2 tablespoons pine nuts, toasted",
      "1 egg, beaten",
      "2 tablespoons fresh basil leaves, for garnish",
      "Salt and pepper to taste",
      "Extra pesto for serving"
    ],
    instructions: [
      "In bowl, combine chicken sausage, pesto, chopped sun-dried tomatoes, Parmesan, and toasted pine nuts. Mix gently but thoroughly. Season with salt and pepper.",
      "Preheat oven to 375°F (slightly lower for chicken). Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place 2 tablespoons filling along one edge of each rectangle.",
      "Roll tightly, seal with egg wash.",
      "Arrange in circular wreath on baking sheet.",
      "Brush with beaten egg.",
      "Bake 23-25 minutes until golden and chicken reaches 165°F internal temperature.",
      "Cool 10 minutes.",
      "Transfer to serving platter. Place bowl of pesto in center.",
      "Garnish with fresh basil leaves and additional sun-dried tomato strips.",
      "Serve warm or at room temperature."
    ],
    tips: "Pat sun-dried tomatoes dry before chopping to remove excess oil. Use store-bought or homemade pesto — just ensure it's gluten-free. Chicken sausage is leaner than pork, so it can dry out if overcooked — watch timing carefully. The pesto keeps the filling moist. Toast pine nuts in dry skillet over medium heat for 2-3 minutes until fragrant and lightly golden.",
    variations: [
      "Add fresh mozzarella to filling",
      "Use arugula pesto instead of basil",
      "Top with balsamic glaze after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "chicken", "pesto", "sun-dried tomatoes", "mediterranean", "lighter", "holiday", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Chicken Sausage Roll Wreath with Pesto & Sun-Dried Tomatoes - Light Mediterranean Appetizer",
    seoDescription: "Light Mediterranean gluten-free chicken sausage roll wreath with pesto and sun-dried tomatoes. Elegant holiday appetizer."
  },
  {
    title: "Gluten-Free Venison Sausage Roll Wreath with Red Wine & Rosemary",
    slug: "gluten-free-venison-sausage-roll-wreath-red-wine-rosemary",
    description: "Gourmet variation — venison sausage, red wine reduction, and rosemary for a rich, elegant flavor.",
    longDescription: "This Gluten-Free Venison Sausage Roll Wreath with Red Wine & Rosemary is the ultimate gourmet version of sausage rolls, perfect for upscale entertaining or when you want to serve something truly special and memorable. Wild venison sausage provides lean, rich, gamey flavor that's more complex and sophisticated than standard pork sausage. The meat is enriched with a red wine reduction that adds deep, complex notes and helps keep the lean venison moist during cooking, while fresh rosemary contributes aromatic, piney flavor that's classic with game meats. The combination is wrapped in flaky gluten-free puff pastry and formed into an elegant wreath that looks restaurant-quality. As it bakes, the venison becomes tender and flavorful, the wine reduction caramelizes slightly, and the rosemary perfumes everything beautifully. This wreath is perfect for Christmas dinner parties, New Year's Eve celebrations, or any occasion where you want to impress with bold, sophisticated flavors. Serve with red wine jus or cranberry-port sauce.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 28,
    totalTime: 68,
    servings: 12,
    rating: "5.0",
    calories: 275,
    protein: "14.0",
    carbs: "17.0",
    fat: "16.0",
    fiber: "0.5",
    sugar: "2.0",
    image: "/recipe-images/sausage-roll-wreath-venison-wine-rosemary.png",
    ingredients: [
      "1 lb gluten-free puff pastry",
      "1 lb venison sausage meat (or ground venison mixed with pork fat)",
      "½ cup red wine",
      "3 tablespoons fresh rosemary, finely chopped",
      "2 shallots, finely minced",
      "2 cloves garlic, minced",
      "2 tablespoons butter",
      "1 tablespoon balsamic vinegar",
      "1 teaspoon juniper berries, crushed (optional)",
      "1 egg, beaten",
      "Salt and pepper to taste",
      "Fresh rosemary sprigs for garnish",
      "Red wine jus for serving"
    ],
    instructions: [
      "Make red wine reduction: In saucepan, melt butter and sauté shallots and garlic until soft, 3-4 minutes. Add red wine, balsamic vinegar, and crushed juniper berries. Simmer 10-12 minutes until reduced by half and syrupy. Let cool completely.",
      "In bowl, combine venison sausage, cooled wine reduction, chopped rosemary, salt, and pepper. Mix gently.",
      "Preheat oven to 400°F. Line baking sheets with parchment.",
      "Roll puff pastry to 1/4-inch thickness. Cut into rectangles.",
      "Place 2 tablespoons venison filling along one edge of each rectangle.",
      "Roll tightly, seal with egg wash.",
      "Arrange in elegant wreath formation on baking sheet.",
      "Brush with egg wash. Press small rosemary sprigs decoratively on top.",
      "Bake 25-28 minutes until deep golden and venison reaches 160°F.",
      "Let rest 10 minutes.",
      "Transfer to serving platter. Place bowl of red wine jus in center.",
      "Garnish with fresh rosemary branches."
    ],
    tips: "If using ground venison instead of venison sausage, add 20% pork fat to keep it moist. The wine reduction must be completely cool before mixing with meat or it will start cooking the sausage. Venison is leaner than pork, so watch baking time carefully to avoid overcooking. This wreath is elegant served at room temperature as well as warm.",
    variations: [
      "Use port wine instead of red wine",
      "Add dried cranberries to filling",
      "Top with red wine glaze after baking"
    ],
    tags: ["gluten-free", "sausage roll", "wreath", "venison", "red wine", "rosemary", "gourmet", "elegant", "game meat", "holiday"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Venison Sausage Roll Wreath with Red Wine & Rosemary - Gourmet Holiday Appetizer",
    seoDescription: "Gourmet gluten-free venison sausage roll wreath with red wine and rosemary. Elegant, sophisticated holiday centerpiece."
  }
];

async function seed() {
  try {
    await db
      .insert(recipes)
      .values(sausageRollWreaths)
      .onConflictDoNothing({ target: [recipes.slug] });
    
    console.log(`Successfully added ${sausageRollWreaths.length} gluten-free sausage roll wreath recipes to the database!`);
    console.log("All recipes have been inserted under Appetizers → Holiday & Entertaining category.");
  } catch (error) {
    console.error("Error adding recipes:", error);
    throw error;
  }
}

seed()
  .then(() => {
    console.log("Seed completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
