import { db } from '../server/db';
import { recipes } from '../shared/schema';

const bruleeBrieRecipes = [
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Fig Jam & Thyme',
    slug: 'bruleed-brie-crostini-fig-jam-thyme',
    description: 'Elegant appetizer featuring creamy brie topped with sweet fig jam and fresh thyme, finished with a crackling caramelized sugar crust. Perfect for wine pairings and sophisticated entertaining.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Fig Jam & Thyme are the epitome of elegant entertaining, combining the luxurious texture of creamy brie with the sweet earthiness of fig jam and the aromatic freshness of thyme, all topped with a crackling caramelized sugar crust that adds both visual drama and textural contrast. The crispy gluten-free crostini base provides the perfect foundation for layers of flavor—sweet fig jam spread generously, followed by a thick slice of room-temperature brie that melts slightly from the heat of the torch. When you sprinkle sugar over the cheese and caramelize it with a kitchen torch (or under the broiler), it creates a glossy, crackling crust reminiscent of crème brûlée, adding a sophisticated sweet element that balances beautifully with the savory, creamy brie. Fresh thyme leaves and flaky sea salt finish each piece, adding herbaceous notes and a touch of salinity that ties all the flavors together. These crostini are perfect for wine and cheese parties, holiday gatherings, or any occasion that calls for impressive yet approachable appetizers. The combination of textures—crisp bread, creamy cheese, crackling sugar, and fresh herbs—creates a memorable eating experience that will have your guests asking for the recipe.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 12,
    rating: '4.8',
    calories: 145,
    protein: '5.0',
    carbs: '12.0',
    fat: '8.0',
    fiber: '1.0',
    sugar: '5.0',
    image: '/recipe-images/bruleed-brie-crostini-fig-jam-thyme.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1/4 cup fig jam',
      '2 tablespoons fresh thyme leaves',
      '2 tablespoons olive oil',
      'Flaky sea salt, for garnish'
    ],
    instructions: [
      'Preheat oven to 400°F. Brush crostini slices with olive oil and arrange on baking sheet.',
      'Toast crostini in oven for 5-7 minutes until golden and crispy. Remove and let cool slightly.',
      'Spread a thin layer of fig jam on each crostini. Top with a slice of brie.',
      'Sprinkle an even layer of sugar over each brie slice (about 3/4 teaspoon per crostini).',
      'Using a kitchen torch, carefully caramelize the sugar until golden and bubbling. If no torch, broil on high for 1-2 minutes, watching closely.',
      'Immediately garnish with fresh thyme leaves and a pinch of flaky sea salt.',
      'Serve within 10 minutes while the brûléed crust is still crisp and the brie is warm and creamy.'
    ],
    tips: 'Use an even layer of sugar for uniform caramelization. Work quickly after torching as the sugar will harden into the crisp crust. Room temperature brie melts more evenly than cold cheese. These can be assembled ahead of time and brûléed just before serving for maximum convenience.',
    variations: [
      'Use honey instead of fig jam for a lighter sweetness',
      'Add crumbled walnuts for extra crunch',
      'Substitute rosemary for thyme for different aromatics',
      'Drizzle with balsamic reduction before serving'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'crostini', 'fig', 'thyme', 'elegant', 'entertaining', 'wine pairing', 'party bites'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Fig Jam & Thyme - Elegant Appetizer',
    seoDescription: 'Elegant gluten-free brûléed brie crostini with sweet fig jam and fresh thyme. Features creamy brie and crackling caramelized sugar crust - perfect for wine pairings.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Honey & Pistachios',
    slug: 'bruleed-brie-crostini-honey-pistachios',
    description: 'Sweet-salty perfection with creamy brie, honey drizzle, and crunchy pistachios beneath a glossy brûléed sugar crust. A show-stopping appetizer that balances elegant and approachable.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Honey & Pistachios deliver the perfect balance of sweet and salty in every bite, making them an instant crowd favorite at any gathering. The magic starts with crispy gluten-free crostini brushed with olive oil and toasted to golden perfection. Creamy, luxurious brie cheese is layered on top, followed by a drizzle of high-quality honey that adds natural sweetness and helps the chopped pistachios adhere. The rough-chopped pistachios provide a vibrant green color and essential crunch that contrasts beautifully with the soft, creamy cheese. When you sprinkle sugar over everything and torch it until caramelized, you create a glossy, crackling crust that shatters satisfyingly with each bite. An additional drizzle of honey after brûléeing adds extra sweetness and visual appeal, while a finishing touch of flaky sea salt is absolutely essential—it enhances the honey\'s sweetness, balances the richness of the brie, and makes the pistachios\' natural flavor pop. These crostini walk the line between sophisticated and approachable, making them perfect for both casual gatherings and formal events. They pair wonderfully with champagne, prosecco, or crisp white wines.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 12,
    cookTime: 10,
    totalTime: 22,
    servings: 12,
    rating: '4.9',
    calories: 158,
    protein: '6.0',
    carbs: '13.0',
    fat: '9.0',
    fiber: '1.0',
    sugar: '6.0',
    image: '/recipe-images/bruleed-brie-crostini-honey-pistachios.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1/4 cup honey',
      '1/3 cup shelled pistachios, roughly chopped',
      '2 tablespoons olive oil',
      'Flaky sea salt, for finishing'
    ],
    instructions: [
      'Preheat oven to 400°F. Brush crostini with olive oil and place on baking sheet.',
      'Toast until golden and crisp, about 5-7 minutes. Cool slightly.',
      'Place a brie slice on each crostini. Drizzle with a small amount of honey.',
      'Sprinkle chopped pistachios over the brie, pressing gently to adhere.',
      'Top each with an even layer of sugar (about 3/4 teaspoon).',
      'Torch the sugar until caramelized and golden, or broil on high for 1-2 minutes.',
      'Drizzle with additional honey and finish with a pinch of flaky sea salt.',
      'Serve immediately while the brûléed crust is crisp and cheese is warm.'
    ],
    tips: 'Toast pistachios first in a dry pan for deeper, nuttier flavor. Use high-quality honey for best taste—wildflower or clover honey work beautifully. Press nuts gently into the honey so they stick during torching. The salt contrast is essential and enhances all the other flavors.',
    variations: [
      'Swap pistachios for crushed almonds or hazelnuts',
      'Add a tiny pinch of red pepper flakes for heat',
      'Use truffle honey for luxury version',
      'Top with edible flowers for special occasions'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'honey', 'pistachios', 'sweet and salty', 'crostini', 'entertaining', 'party bites', 'elegant'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Honey & Pistachios - Sweet Salty Perfection',
    seoDescription: 'Sweet-salty gluten-free brûléed brie crostini with honey drizzle and crunchy pistachios. Crackling caramelized sugar makes this an elegant party appetizer.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Cranberry Compote',
    slug: 'bruleed-brie-crostini-cranberry-compote',
    description: 'Festive holiday appetizer with tart cranberry compote, creamy brie, and crackling caramelized sugar. The perfect balance of sweet and tangy for seasonal entertaining.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Cranberry Compote are the ultimate holiday party appetizer, combining the festive flavors of tart cranberries with luxurious creamy brie and a dramatic caramelized sugar crust. The homemade cranberry compote is simple to make and can be prepared days ahead—fresh or frozen cranberries are simmered with sugar and a splash of orange juice until the berries burst and the mixture thickens into a ruby-red, jammy consistency with bright, tangy flavor. This compote is spread generously on crispy gluten-free crostini, providing a tart-sweet base that cuts through the richness of the brie beautifully. A thick slice of creamy brie goes on top, and then comes the magic: an even sprinkle of granulated sugar that gets torched until it caramelizes into a glossy, crackling crust that adds sweetness and an irresistible textural contrast. Fresh rosemary sprigs add an aromatic, piney note that feels festive and seasonal. The combination of tart cranberry, creamy cheese, and sweet caramelized sugar creates a perfectly balanced bite. These crostini are stunning on a holiday appetizer spread, beautiful enough for Thanksgiving or Christmas entertaining, yet easy enough for casual gatherings.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 20,
    cookTime: 10,
    totalTime: 30,
    servings: 12,
    rating: '4.9',
    calories: 142,
    protein: '5.0',
    carbs: '15.0',
    fat: '7.0',
    fiber: '1.0',
    sugar: '8.0',
    image: '/recipe-images/bruleed-brie-crostini-cranberry-compote.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1 cup fresh or frozen cranberries',
      '1/4 cup sugar (for compote)',
      '2 tablespoons orange juice',
      '2 tablespoons olive oil',
      'Fresh rosemary sprigs, for garnish'
    ],
    instructions: [
      'Make cranberry compote: Combine cranberries, 1/4 cup sugar, and orange juice in small saucepan. Simmer 10 minutes until berries burst and mixture thickens. Cool completely.',
      'Preheat oven to 400°F. Brush crostini with olive oil and arrange on baking sheet.',
      'Toast crostini 5-7 minutes until crisp and golden. Cool slightly.',
      'Spread a spoonful of cranberry compote on each crostini. Top with brie slice.',
      'Sprinkle 3/4 teaspoon sugar evenly over each brie slice.',
      'Torch sugar until caramelized and golden, or broil on high 1-2 minutes.',
      'Garnish with small rosemary sprigs and serve immediately.',
      'Best enjoyed within 10 minutes while sugar crust is crisp.'
    ],
    tips: 'Make compote up to 3 days ahead and refrigerate in an airtight container. Orange zest adds extra brightness to the compote if you have it. Use warmed brie (room temperature) for easier melting. Store extra compote for serving with turkey, pork, or other holiday dishes.',
    variations: [
      'Add cinnamon stick to compote while cooking',
      'Mix in chopped pecans to the compote',
      'Use pomegranate seeds for different tart flavor',
      'Add splash of Grand Marnier to compote for adults'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'cranberry', 'holiday', 'festive', 'thanksgiving', 'christmas', 'entertaining', 'party bites'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Cranberry Compote - Holiday Appetizer',
    seoDescription: 'Festive gluten-free brûléed brie crostini with homemade cranberry compote. Tart, sweet, and creamy with crackling caramelized sugar - perfect holiday appetizer.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Balsamic Strawberries',
    slug: 'bruleed-brie-crostini-balsamic-strawberries',
    description: 'Romantic and elegant with fresh strawberries marinated in aged balsamic, creamy brie, and a torch-caramelized sugar crust. Perfect for spring entertaining and special occasions.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Balsamic Strawberries are a romantic, elegant appetizer that celebrates the arrival of spring with fresh, seasonal flavors and beautiful presentation. Sweet, ripe strawberries are sliced and marinated in a mixture of high-quality aged balsamic vinegar and honey, which draws out their natural juices and intensifies their sweetness while adding a sophisticated tangy depth. After marinating for at least 15 minutes, the strawberries become tender and glossy, infused with the complex flavors of the balsamic. These jewel-like berries are layered onto crispy gluten-free crostini, topped with creamy brie, and then sprinkled with sugar that gets torched into a crackling caramelized crust. The reserved balsamic marinade is drizzled over the top, adding glossy visual appeal and another layer of sweet-tart flavor. Fresh basil leaves provide an unexpected aromatic finish that pairs beautifully with both the strawberries and the brie. The result is a sophisticated appetizer that looks stunning on a platter and tastes even better than it looks. Perfect for bridal showers, garden parties, or romantic dinners, these crostini showcase how simple, quality ingredients can create something truly special.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 20,
    cookTime: 8,
    totalTime: 28,
    servings: 12,
    rating: '4.8',
    calories: 138,
    protein: '5.0',
    carbs: '13.0',
    fat: '7.0',
    fiber: '1.0',
    sugar: '6.0',
    image: '/recipe-images/bruleed-brie-crostini-balsamic-strawberries.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1 cup fresh strawberries, hulled and sliced',
      '2 tablespoons balsamic vinegar',
      '1 tablespoon honey',
      '2 tablespoons olive oil',
      'Fresh basil leaves, for garnish'
    ],
    instructions: [
      'Marinate strawberries: Toss sliced strawberries with balsamic vinegar and honey. Let sit 15 minutes.',
      'Preheat oven to 400°F. Brush crostini with olive oil and place on baking sheet.',
      'Toast crostini 5-7 minutes until golden and crisp. Cool slightly.',
      'Drain strawberries slightly (reserve balsamic for drizzling). Place 2-3 strawberry slices on each crostini.',
      'Top with brie slice, then sprinkle evenly with sugar (about 3/4 teaspoon per piece).',
      'Torch sugar until caramelized and glossy, or broil on high 1-2 minutes.',
      'Drizzle with reserved balsamic marinade and garnish with small basil leaves.',
      'Serve immediately while sugar is crisp and brie is warm.'
    ],
    tips: 'Use ripe, sweet strawberries for best flavor—taste them before buying. Quality aged balsamic vinegar makes a huge difference in this recipe. Let strawberries marinate longer (up to 1 hour) for deeper flavor infusion. Fresh basil adds essential aromatic brightness that ties everything together.',
    variations: [
      'Use raspberries or blackberries instead',
      'Add cracked black pepper for contrast',
      'Substitute fresh mint for basil',
      'Reduce balsamic to a glaze for more intensity'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'strawberries', 'balsamic', 'spring', 'elegant', 'romantic', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Balsamic Strawberries - Spring Appetizer',
    seoDescription: 'Elegant gluten-free brûléed brie crostini with balsamic strawberries and fresh basil. Romantic spring appetizer with crackling caramelized sugar crust.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Pear & Rosemary',
    slug: 'bruleed-brie-crostini-pear-rosemary',
    description: 'Sophisticated autumn appetizer featuring delicate pear slices, aromatic rosemary, and creamy brie under a glossy caramelized sugar crust. Perfectly balanced and aromatic.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Pear & Rosemary capture the essence of autumn in an elegant, aromatic appetizer that feels both rustic and refined. Ripe but firm pears are sliced paper-thin and tossed with lemon juice to prevent browning while adding a subtle citrus brightness. These delicate pear slices are layered onto crispy gluten-free crostini along with fresh rosemary needles, which release their piney, aromatic oils as they warm. Creamy brie cheese goes on top, and then the whole thing gets sprinkled with sugar and torched until caramelized into a glossy, crackling crust. The combination of sweet pear, herbaceous rosemary, rich brie, and caramelized sugar creates a beautifully balanced bite with layers of flavor and texture. An optional drizzle of honey adds extra sweetness and gloss, though the recipe is perfectly delicious without it. The aromatic quality of fresh rosemary is essential to this recipe—dried rosemary simply won\'t provide the same impact. These crostini are perfect for fall entertaining, whether at Thanksgiving, harvest dinners, or cozy wine and cheese gatherings. They pair wonderfully with crisp white wines or light-bodied reds.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 12,
    rating: '4.7',
    calories: 140,
    protein: '5.0',
    carbs: '14.0',
    fat: '7.0',
    fiber: '2.0',
    sugar: '6.0',
    image: '/recipe-images/bruleed-brie-crostini-pear-rosemary.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '2 ripe but firm pears, thinly sliced',
      '2 tablespoons fresh rosemary leaves',
      '1 tablespoon lemon juice',
      '2 tablespoons olive oil',
      'Honey, for drizzling (optional)'
    ],
    instructions: [
      'Toss pear slices with lemon juice to prevent browning.',
      'Preheat oven to 400°F. Brush crostini with olive oil and arrange on baking sheet.',
      'Toast crostini 5-7 minutes until crisp and golden. Cool slightly.',
      'Layer 2-3 thin pear slices on each crostini. Sprinkle with a few rosemary leaves.',
      'Top with brie slice, then evenly sprinkle sugar over top (about 3/4 teaspoon).',
      'Torch sugar until caramelized and golden, or broil on high 1-2 minutes, watching carefully.',
      'Garnish with additional fresh rosemary and optional honey drizzle.',
      'Serve within 10 minutes while the sugar crust is still crisp.'
    ],
    tips: 'Use Bartlett or Bosc pears for best texture and flavor. Slice pears thinly and uniformly so they cook evenly. Fresh rosemary is absolutely essential—dried won\'t work in this recipe. Lemon juice keeps pears from oxidizing and adds brightness.',
    variations: [
      'Use apple slices instead of pears',
      'Add crumbled blue cheese for stronger flavor',
      'Substitute thyme for rosemary',
      'Top with candied walnuts for extra crunch'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'pear', 'rosemary', 'autumn', 'fall', 'elegant', 'aromatic', 'party bites'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Pear & Rosemary - Fall Appetizer',
    seoDescription: 'Sophisticated gluten-free brûléed brie crostini with pear and fresh rosemary. Aromatic autumn appetizer with crackling caramelized sugar.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Salted Caramel & Almonds',
    slug: 'bruleed-brie-crostini-salted-caramel-almonds',
    description: 'Decadent dessert-style appetizer with rich salted caramel drizzle, toasted almonds, and creamy brie beneath a glossy brûléed crust. Sweet, salty, and utterly irresistible.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Salted Caramel & Almonds blur the line between appetizer and dessert in the most delicious way, creating a decadent treat that\'s perfect for ending a meal or serving as a bridge between savory and sweet courses. The foundation is crispy gluten-free crostini brushed with olive oil and toasted until golden. A drizzle of rich salted caramel sauce goes on first, providing a sweet, buttery base with just enough salt to keep things interesting. Creamy brie cheese is placed on top—its mild, buttery flavor pairs surprisingly well with caramel. Toasted sliced almonds add essential crunch and a nutty depth that complements both the caramel and cheese beautifully. Toasting the almonds first intensifies their flavor and makes them extra crispy. An even layer of sugar is sprinkled over everything, then torched until it caramelizes into a glossy, crackling crust that adds even more sweetness and that signature brûléed texture. Another drizzle of salted caramel after torching adds visual appeal and extra flavor, while flaky sea salt is the crucial finishing touch that balances all the sweetness and makes every element shine. These crostini are perfect for special occasions when you want to offer something truly indulgent and memorable.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 12,
    rating: '4.9',
    calories: 172,
    protein: '6.0',
    carbs: '15.0',
    fat: '10.0',
    fiber: '1.0',
    sugar: '8.0',
    image: '/recipe-images/bruleed-brie-crostini-salted-caramel-almonds.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1/3 cup sliced almonds, toasted',
      '1/4 cup salted caramel sauce',
      '2 tablespoons olive oil',
      'Flaky sea salt, for finishing'
    ],
    instructions: [
      'Toast almonds in dry skillet over medium heat 3-4 minutes until golden and fragrant. Set aside.',
      'Preheat oven to 400°F. Brush crostini with olive oil and place on baking sheet.',
      'Toast crostini 5-7 minutes until crisp and golden. Cool slightly.',
      'Drizzle each crostini with a small amount of salted caramel. Top with brie slice.',
      'Sprinkle toasted almonds over brie, pressing gently. Top with even layer of sugar.',
      'Torch sugar until caramelized and glossy, or broil on high 1-2 minutes.',
      'Drizzle with additional salted caramel and finish with pinch of flaky sea salt.',
      'Serve immediately while sugar crust is crisp and caramel is warm.'
    ],
    tips: 'Use quality salted caramel sauce for best flavor—homemade is wonderful but store-bought works great. Toast almonds for deeper, nuttier taste. Don\'t skip the flaky salt—it balances the sweetness perfectly. These can serve as a bridge between appetizer and dessert courses.',
    variations: [
      'Use pecans instead of almonds',
      'Add a tiny pinch of cinnamon to caramel',
      'Top with dark chocolate shavings',
      'Drizzle with chocolate sauce alongside caramel'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'salted caramel', 'almonds', 'sweet', 'dessert-style', 'decadent', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Salted Caramel & Almonds - Decadent Treat',
    seoDescription: 'Decadent gluten-free brûléed brie crostini with salted caramel and toasted almonds. Sweet, salty dessert-style appetizer with crackling caramelized sugar.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Apple Butter & Cinnamon',
    slug: 'bruleed-brie-crostini-apple-butter-cinnamon',
    description: 'Cozy fall comfort with spiced apple butter, warm cinnamon sugar, and creamy brie under a crackling caramelized crust. Perfect for autumn gatherings and fireside entertaining.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Apple Butter & Cinnamon are the ultimate cozy fall appetizer, capturing the warm, spiced flavors of autumn in every bite. The star ingredient is apple butter—a concentrated, slow-cooked apple spread with deep, caramelized apple flavor and warm spices like cinnamon and nutmeg. This gets spread generously on crispy gluten-free crostini, providing a sweet, spiced base that tastes like fall in spread form. Creamy brie cheese goes on top, its mild, buttery flavor letting the apple butter shine while adding luxurious richness. The sugar topping gets a special treatment here—it\'s mixed with ground cinnamon before sprinkling, so when it caramelizes under the torch or broiler, it creates a spiced, crackling crust with visible cinnamon specks and warm aromatic flavor. The result is an appetizer that tastes like apple pie meets cheese course, with the perfect balance of sweet, spiced, and savory flavors. These crostini are ideal for autumn gatherings, Thanksgiving appetizers, or any occasion where you want to serve something comforting and seasonal. They pair beautifully with hard cider, spiced wine, or apple cider.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Easy',
    prepTime: 12,
    cookTime: 10,
    totalTime: 22,
    servings: 12,
    rating: '4.8',
    calories: 148,
    protein: '5.0',
    carbs: '14.0',
    fat: '8.0',
    fiber: '1.0',
    sugar: '7.0',
    image: '/recipe-images/bruleed-brie-crostini-apple-butter-cinnamon.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1/4 cup apple butter',
      '1 teaspoon ground cinnamon',
      '2 tablespoons olive oil',
      'Cinnamon stick, for garnish (optional)'
    ],
    instructions: [
      'Mix sugar with cinnamon in small bowl. Set aside.',
      'Preheat oven to 400°F. Brush crostini with olive oil and arrange on baking sheet.',
      'Toast crostini 5-7 minutes until golden and crisp. Cool slightly.',
      'Spread a generous layer of apple butter on each crostini. Top with brie slice.',
      'Sprinkle cinnamon sugar evenly over each brie slice (about 3/4 teaspoon).',
      'Torch sugar until caramelized and golden, or broil on high 1-2 minutes.',
      'Serve immediately while warm. Garnish platter with cinnamon sticks if desired.',
      'Best enjoyed within 10 minutes while sugar crust is crisp.'
    ],
    tips: 'Use quality apple butter for best flavor—look for brands with minimal added sugar and warm spices. Mix cinnamon thoroughly into sugar for even distribution and flavor. Warm apple butter slightly in microwave for easier spreading. Pairs beautifully with hard cider, spiced wine, or warm apple cider.',
    variations: [
      'Use pumpkin butter instead of apple',
      'Add pinch of nutmeg to cinnamon sugar',
      'Top with candied pecans',
      'Drizzle with maple syrup before serving'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'apple butter', 'cinnamon', 'fall', 'autumn', 'cozy', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Apple Butter & Cinnamon - Cozy Fall Appetizer',
    seoDescription: 'Cozy gluten-free brûléed brie crostini with spiced apple butter and cinnamon sugar. Perfect fall appetizer with crackling caramelized crust.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Prosciutto & Honey',
    slug: 'bruleed-brie-crostini-prosciutto-honey',
    description: 'Ultimate sweet and savory combination with crispy prosciutto, honey drizzle, and creamy brie beneath a torch-caramelized sugar crust. Sophisticated and crowd-pleasing.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Prosciutto & Honey represent the pinnacle of sweet and savory balance, combining Italian-style cured meat with honey sweetness and luxurious creamy cheese. The recipe starts by crisping thin slices of prosciutto in a dry skillet until they become crispy, salty shards with concentrated porky flavor and delicate crunch. Crispy gluten-free crostini provide the base, topped with a generous slice of creamy brie that will melt slightly from the heat of the torch. A piece of the crispy prosciutto goes on top of the brie, adding salty, savory depth. Then comes the magic: an even sprinkle of sugar gets torched until it caramelizes into a glossy, crackling crust that adds sweetness and textural contrast. High-quality honey is drizzled over the top, adding floral sweetness that bridges the salty prosciutto and rich brie beautifully. Fresh thyme leaves provide aromatic herbal notes, while cracked black pepper adds sophisticated bite and visual appeal. The combination of textures—crisp bread, creamy cheese, crackling sugar, crispy meat—creates an unforgettable eating experience. These crostini are perfect for upscale entertaining and pair wonderfully with Italian wines, prosecco, or champagne.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 12,
    rating: '4.9',
    calories: 162,
    protein: '7.0',
    carbs: '13.0',
    fat: '9.0',
    fiber: '0.0',
    sugar: '6.0',
    image: '/recipe-images/bruleed-brie-crostini-prosciutto-honey.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '6 thin slices prosciutto, torn into pieces',
      '3 tablespoons honey',
      '2 tablespoons olive oil',
      'Fresh thyme leaves, for garnish',
      'Black pepper, to taste'
    ],
    instructions: [
      'Crisp prosciutto: Heat dry skillet over medium heat. Add prosciutto pieces and cook 2-3 minutes until crispy. Drain on paper towel.',
      'Preheat oven to 400°F. Brush crostini with olive oil and place on baking sheet.',
      'Toast crostini 5-7 minutes until golden and crisp. Cool slightly.',
      'Top each crostini with brie slice. Add a piece of crispy prosciutto on top.',
      'Sprinkle sugar evenly over each (about 3/4 teaspoon per piece).',
      'Torch sugar until caramelized and golden, or broil on high 1-2 minutes.',
      'Drizzle with honey, garnish with thyme leaves and cracked black pepper.',
      'Serve immediately while prosciutto is crisp and sugar crust is crackling.'
    ],
    tips: 'Crisp prosciutto adds essential texture contrast—don\'t skip this step. Use high-quality Italian prosciutto di Parma for best flavor. The balance of honey sweetness and salt is key to success. Black pepper adds sophisticated bite that elevates the whole dish.',
    variations: [
      'Use jamón serrano instead of prosciutto',
      'Add fig slices alongside prosciutto',
      'Substitute hot honey for regular honey',
      'Top with arugula for peppery bite'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'prosciutto', 'honey', 'sweet and savory', 'elegant', 'gourmet', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Prosciutto & Honey - Gourmet Appetizer',
    seoDescription: 'Sophisticated gluten-free brûléed brie crostini with crispy prosciutto and honey. Perfect sweet-savory appetizer with crackling caramelized sugar.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Blueberry Compote & Mint',
    slug: 'bruleed-brie-crostini-blueberry-compote-mint',
    description: 'Vibrant and fresh with homemade blueberry compote, bright mint, and creamy brie beneath a glossy caramelized sugar crust. Beautiful purple hues make this a stunning party appetizer.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Blueberry Compote & Mint are visually stunning with their vibrant purple-blue color and fresh, bright flavors that make them perfect for spring and summer entertaining. The homemade blueberry compote is wonderfully simple to make—fresh or frozen blueberries are simmered with sugar and a squeeze of lemon juice until the berries burst and release their juices, creating a thick, jammy mixture with concentrated berry flavor and beautiful deep purple color. The lemon juice is essential, brightening the berry flavor and preventing it from being too sweet. This gorgeous compote gets spread generously on crispy gluten-free crostini, creating a sweet, fruity base. Creamy brie cheese goes on top, its mild flavor providing a neutral backdrop that lets the blueberries shine. An even layer of sugar is sprinkled over everything, then torched until it caramelizes into a glossy, crackling crust that adds sweetness and that irresistible brûléed texture. Fresh mint leaves are the final touch—torn or left whole, they add a bright, refreshing aromatic note that cuts through the richness and adds visual appeal with their vibrant green color. These crostini are as beautiful as they are delicious, making them perfect for garden parties, bridal showers, or any occasion where you want to impress.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Medium',
    prepTime: 18,
    cookTime: 10,
    totalTime: 28,
    servings: 12,
    rating: '4.8',
    calories: 144,
    protein: '5.0',
    carbs: '15.0',
    fat: '7.0',
    fiber: '1.0',
    sugar: '7.0',
    image: '/recipe-images/bruleed-brie-crostini-blueberry-compote-mint.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1 cup fresh or frozen blueberries',
      '2 tablespoons sugar (for compote)',
      '1 tablespoon lemon juice',
      '2 tablespoons olive oil',
      'Fresh mint leaves, for garnish'
    ],
    instructions: [
      'Make blueberry compote: Combine blueberries, 2 tablespoons sugar, and lemon juice in saucepan. Simmer 8-10 minutes until berries burst and mixture thickens. Cool completely.',
      'Preheat oven to 400°F. Brush crostini with olive oil and arrange on baking sheet.',
      'Toast crostini 5-7 minutes until crisp and golden. Cool slightly.',
      'Spread a spoonful of blueberry compote on each crostini. Top with brie slice.',
      'Sprinkle sugar evenly over brie (about 3/4 teaspoon per piece).',
      'Torch sugar until caramelized and glossy, or broil on high 1-2 minutes.',
      'Garnish with fresh mint leaves torn or left whole.',
      'Serve within 10 minutes while sugar crust is crisp and cheese is warm.'
    ],
    tips: 'Make compote up to 3 days ahead and refrigerate. Fresh blueberries give best flavor and color, but frozen work great too. Lemon juice brightens the berry flavor and prevents over-sweetness. Fresh mint adds refreshing aromatic finish that\'s essential to the recipe.',
    variations: [
      'Use blackberries or mixed berries',
      'Add lavender to compote for floral notes',
      'Substitute basil for mint',
      'Top with lemon zest for extra brightness'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'blueberry', 'mint', 'fresh', 'vibrant', 'summer', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Blueberry Compote & Mint - Summer Appetizer',
    seoDescription: 'Vibrant gluten-free brûléed brie crostini with blueberry compote and fresh mint. Beautiful summer appetizer with crackling caramelized sugar.'
  },
  {
    title: 'Gluten-Free Brûléed Brie Crostini with Mango Chutney & Chili Flakes',
    slug: 'bruleed-brie-crostini-mango-chutney-chili-flakes',
    description: 'Exotic and exciting with sweet-spicy mango chutney, red chili heat, and buttery brie beneath a crackling caramelized sugar crust. A bold appetizer that brings tropical flair to any gathering.',
    longDescription: 'These Gluten-Free Brûléed Brie Crostini with Mango Chutney & Chili Flakes are an exotic, bold appetizer that brings tropical flavors and exciting heat to your entertaining spread. The star ingredient is mango chutney—a sweet, tangy, spiced condiment with Indian origins that combines ripe mango with vinegar, sugar, and warming spices. Major Grey\'s is the classic brand, but any quality mango chutney will work beautifully. This sweet-tart-spicy spread gets layered generously on crispy gluten-free crostini, providing a complex flavor base with tropical fruit sweetness and subtle spice. Creamy brie cheese goes on top, its mild, buttery flavor providing a cooling contrast to the chutney\'s complexity. Red chili flakes are sprinkled over the brie before the sugar topping—adjust the amount to your heat tolerance, but don\'t skip them entirely as they add essential warmth and visual appeal with their bright red color. The sugar gets torched until caramelized into a crackling crust, and then fresh cilantro leaves and lime wedges finish the presentation, adding bright, fresh notes that balance the rich cheese and sweet chutney. These crostini are perfect for adventurous eaters and pair wonderfully with sparkling wine, beer, or tropical cocktails.',
    category: 'Appetizers',
    subcategory: 'Entertaining & Party Bites',
    difficulty: 'Easy',
    prepTime: 12,
    cookTime: 8,
    totalTime: 20,
    servings: 12,
    rating: '4.7',
    calories: 151,
    protein: '5.0',
    carbs: '15.0',
    fat: '8.0',
    fiber: '1.0',
    sugar: '7.0',
    image: '/recipe-images/bruleed-brie-crostini-mango-chutney-chili-flakes.png',
    ingredients: [
      '12 slices gluten-free baguette or crostini',
      '8 oz brie cheese, cut into 12 slices',
      '3 tablespoons granulated sugar',
      '1/3 cup mango chutney',
      '1/2 teaspoon red chili flakes',
      '2 tablespoons olive oil',
      'Fresh cilantro leaves, for garnish',
      'Lime wedges, for serving'
    ],
    instructions: [
      'Preheat oven to 400°F. Brush crostini with olive oil and place on baking sheet.',
      'Toast crostini 5-7 minutes until golden and crisp. Cool slightly.',
      'Spread a generous layer of mango chutney on each crostini. Top with brie slice.',
      'Sprinkle a small pinch of chili flakes over brie (adjust to heat preference).',
      'Top with even layer of sugar (about 3/4 teaspoon per piece).',
      'Torch sugar until caramelized and golden, or broil on high 1-2 minutes, watching closely.',
      'Garnish with fresh cilantro leaves and additional chili flakes if desired.',
      'Serve with lime wedges on the side. Best within 10 minutes while sugar is crisp.'
    ],
    tips: 'Use quality mango chutney—Major Grey\'s is the classic choice. Adjust chili flakes to your heat tolerance—start with less if unsure. Cilantro and lime add essential fresh brightness that balances the rich, sweet flavors. These pair beautifully with sparkling wine, beer, or tropical cocktails.',
    variations: [
      'Use peach or apricot chutney instead',
      'Add diced fresh mango on top',
      'Substitute Thai basil for cilantro',
      'Top with crushed peanuts for extra crunch'
    ],
    tags: ['gluten-free', 'appetizer', 'brie', 'brûléed', 'mango chutney', 'spicy', 'exotic', 'tropical', 'bold', 'party bites', 'entertaining'],
    isNaturallyGlutenFree: false,
    status: 'published',
    seoTitle: 'Gluten-Free Brûléed Brie Crostini with Mango Chutney & Chili - Exotic Appetizer',
    seoDescription: 'Exotic gluten-free brûléed brie crostini with mango chutney and chili flakes. Bold sweet-spicy appetizer with crackling caramelized sugar.'
  }
];

async function seed() {
  try {
    console.log('Adding 10 gluten-free brûléed brie crostini recipes...');
    
    await db.insert(recipes).values(bruleeBrieRecipes).onConflictDoNothing();
    
    console.log('Successfully added brûléed brie crostini recipes!');
    process.exit(0);
  } catch (error) {
    console.error('Error adding recipes:', error);
    process.exit(1);
  }
}

seed();
