import { db } from "../server/db";
import { recipes } from "../shared/schema";

const caramelizedOnionGoatCheeseBites = [
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Thyme & Balsamic",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-thyme-balsamic",
    description: "Classic and elegant — sweet onions balanced with tangy goat cheese, thyme, and balsamic reduction drizzle.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Thyme & Balsamic are the epitome of elegant appetizers that taste as sophisticated as they look. Golden-brown caramelized onions, slowly cooked to perfection over 40 minutes until they're sweet and jammy, are paired with creamy, tangy goat cheese and fresh thyme on crispy gluten-free cracker bases. The final touch is a drizzle of rich balsamic reduction that adds depth and a glossy finish. The combination of sweet caramelized onions, tart goat cheese, herbaceous thyme, and tangy balsamic creates a perfect balance of flavors that will have your guests reaching for seconds. These bites are ideal for wine and cheese parties, holiday gatherings, or any occasion where you want to serve something that looks restaurant-quality but is surprisingly simple to make. The key is patience with the onions — low and slow caramelization develops deep, complex sweetness.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 50,
    cookTime: 12,
    totalTime: 62,
    servings: 24,
    rating: "5.0",
    calories: 78,
    protein: "2.5",
    carbs: "8.0",
    fat: "4.0",
    fiber: "0.5",
    sugar: "3.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-thyme-balsamic.png",
    ingredients: [
      "24 gluten-free crackers or rounds",
      "3 large yellow onions, thinly sliced",
      "3 tablespoons butter",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "2 tablespoons fresh thyme leaves",
      "2 tablespoons balsamic vinegar (for cooking)",
      "¼ cup balsamic reduction (for drizzling)",
      "2 teaspoons brown sugar",
      "Salt and pepper to taste",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "In a large skillet over medium-low heat, melt butter with olive oil. Add sliced onions and stir to coat.",
      "Cook onions slowly for 35-45 minutes, stirring occasionally, until deep golden brown and caramelized. Reduce heat if onions start to burn.",
      "When onions are nearly done, add balsamic vinegar, brown sugar, and half the thyme leaves. Cook 3-4 more minutes until liquid evaporates. Season with salt and pepper. Let cool.",
      "Preheat oven to 375°F if using crackers that need warming. Otherwise, keep at room temperature.",
      "Mix softened goat cheese with remaining thyme leaves and a pinch of salt until smooth and spreadable.",
      "Spread about 1 teaspoon of goat cheese mixture on each cracker or base.",
      "Top each with a generous spoonful of caramelized onions.",
      "If desired, warm bites in oven for 3-5 minutes to slightly melt the cheese.",
      "Drizzle each bite with balsamic reduction and garnish with fresh thyme sprigs.",
      "Serve immediately while warm or at room temperature."
    ],
    tips: "The key to perfect caramelized onions is patience — cook low and slow. Don't rush the process or the onions will burn instead of caramelize. Make the onions up to 3 days ahead and refrigerate. You can make your own balsamic reduction by simmering ½ cup balsamic vinegar until reduced by half.",
    variations: [
      "Use red onions instead of yellow for a slightly different flavor",
      "Add a splash of white wine when deglazing the onions",
      "Top with toasted walnuts for extra crunch"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "balsamic", "thyme", "appetizer", "finger food", "party", "elegant", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Thyme & Balsamic - Elegant Appetizer",
    seoDescription: "Elegant gluten-free caramelized onion and goat cheese bites with fresh thyme and balsamic reduction. Perfect party appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Fig Jam",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-fig-jam",
    description: "Rich and sweet — layers of fig jam under creamy cheese, finished with caramelized onions and rosemary.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Fig Jam are a luxurious combination of sweet and savory flavors that create an unforgettable taste experience. Each bite starts with a crispy gluten-free base spread with rich, jammy fig preserves that provide deep sweetness and subtle texture from the fig seeds. Creamy goat cheese adds tanginess that balances the sweet fig, while golden caramelized onions contribute their own complex sweetness and soft texture. Fresh rosemary brings an aromatic, woodsy note that ties everything together beautifully. The result is a sophisticated appetizer with layers of flavor and texture that's perfect for upscale entertaining, holiday parties, or wine tastings. The combination of fig and goat cheese is classic French bistro fare, while the caramelized onions add an extra dimension that makes these bites truly special.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 50,
    cookTime: 10,
    totalTime: 60,
    servings: 24,
    rating: "5.0",
    calories: 92,
    protein: "2.5",
    carbs: "11.0",
    fat: "4.5",
    fiber: "0.8",
    sugar: "6.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-fig-jam.png",
    ingredients: [
      "24 gluten-free crackers or crostini",
      "3 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "½ cup fig jam or preserves",
      "2 tablespoons fresh rosemary, chopped",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet over medium-low heat, melt butter with olive oil. Add onions and cook 35-45 minutes, stirring occasionally, until deep golden brown.",
      "Add balsamic vinegar to onions in the last 5 minutes of cooking. Season with salt and pepper. Let cool.",
      "Mix softened goat cheese with half the chopped rosemary until smooth.",
      "Spread a thin layer of fig jam on each cracker or crostini base.",
      "Add a dollop of rosemary goat cheese on top of the fig jam.",
      "Top each with a spoonful of caramelized onions.",
      "Preheat oven to 350°F. Place bites on baking sheet and warm for 8-10 minutes until cheese is slightly melted.",
      "Remove from oven and garnish with remaining fresh rosemary.",
      "Serve warm for best flavor and texture."
    ],
    tips: "Use high-quality fig jam for best results — look for one with visible fig pieces. The onions can be caramelized up to 3 days ahead. These bites are best served warm so the cheese is soft and creamy.",
    variations: [
      "Use apricot or cherry jam instead of fig",
      "Add crumbled walnuts on top for crunch",
      "Drizzle with honey before serving"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "fig jam", "rosemary", "appetizer", "party", "gourmet", "sweet savory", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Fig Jam - Gourmet Appetizer",
    seoDescription: "Gourmet gluten-free bites with fig jam, caramelized onions, goat cheese, and rosemary. Perfect elegant party appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Puff Pastry Cups",
    slug: "gluten-free-caramelized-onion-goat-cheese-puff-pastry-cups",
    description: "Bite-sized cups made from gluten-free puff pastry filled with caramelized onions and goat cheese.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Puff Pastry Cups are showstopping appetizers that combine flaky, buttery pastry with the classic pairing of sweet caramelized onions and tangy goat cheese. The gluten-free puff pastry is cut and shaped into individual cups, then baked until golden and crispy. Each delicate cup is filled with a mixture of creamy goat cheese and deeply caramelized onions, creating a perfect bite-sized portion. The contrast between the crispy, flaky pastry and the soft, creamy filling is absolutely delightful. These elegant bites look like they came from a fancy bakery or upscale catering company, but they're surprisingly easy to make at home. They're perfect for special occasions, holiday parties, bridal showers, or any event where you want to impress your guests with restaurant-quality hors d'oeuvres.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 20,
    totalTime: 75,
    servings: 24,
    rating: "4.9",
    calories: 105,
    protein: "3.0",
    carbs: "9.0",
    fat: "7.0",
    fiber: "0.5",
    sugar: "2.5",
    image: "/recipe-images/caramelized-onion-goat-cheese-puff-pastry.png",
    ingredients: [
      "2 sheets gluten-free puff pastry, thawed",
      "3 large yellow onions, thinly sliced",
      "3 tablespoons butter",
      "1 tablespoon olive oil",
      "6 oz goat cheese, softened",
      "2 tablespoons heavy cream",
      "2 tablespoons fresh thyme leaves",
      "1 tablespoon balsamic vinegar",
      "1 egg, beaten (for egg wash)",
      "Salt and pepper to taste",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet over medium-low heat, melt butter with oil. Add onions and cook 40-45 minutes until deep golden brown. Add balsamic vinegar in last 5 minutes. Season and let cool.",
      "Preheat oven to 400°F. Grease a 24-cup mini muffin tin.",
      "Roll out puff pastry slightly and cut into 24 squares, about 3x3 inches each.",
      "Press each pastry square into a muffin cup, allowing edges to stick up slightly. Prick bottoms with fork.",
      "Brush pastry with beaten egg wash.",
      "Bake empty cups for 12-15 minutes until golden and puffed. Remove from oven and gently press down centers if they've puffed too much.",
      "While cups bake, mix goat cheese with cream and half the thyme until smooth and spreadable.",
      "Fill each baked pastry cup with a small spoonful of goat cheese mixture, then top with caramelized onions.",
      "Return to oven for 3-5 minutes to warm filling.",
      "Garnish with remaining fresh thyme and serve warm."
    ],
    tips: "Work quickly with puff pastry and keep it cold until ready to use. If pastry gets too warm, refrigerate for 10 minutes. The pastry cups can be baked a day ahead and stored in an airtight container — just fill and warm before serving.",
    variations: [
      "Add crumbled bacon to the filling",
      "Mix in sun-dried tomatoes with the goat cheese",
      "Top with a balsamic reduction drizzle"
    ],
    tags: ["gluten-free", "puff pastry", "caramelized onion", "goat cheese", "appetizer", "party", "elegant", "finger food", "showstopper", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Puff Pastry Cups - Elegant Party Appetizer",
    seoDescription: "Showstopping gluten-free puff pastry cups filled with caramelized onions and goat cheese. Perfect elegant party appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Honey & Rosemary",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-honey-rosemary",
    description: "Drizzled with honey and sprinkled with fresh rosemary for a sweet-herbal contrast.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Honey & Rosemary are a beautiful study in flavor balance, combining sweet, savory, tangy, and herbal notes in every bite. Golden caramelized onions provide deep sweetness and umami, while tangy goat cheese adds creamy contrast. Fresh rosemary brings an aromatic, piney note that elevates the entire dish, and a drizzle of golden honey adds floral sweetness and a gorgeous glossy finish. The honey amplifies the natural sweetness of the caramelized onions while complementing the earthiness of the rosemary. These bites are visually stunning with their golden tones and herb garnishes, making them perfect for upscale entertaining, holiday cocktail parties, or wine tastings. The combination is sophisticated yet approachable, and the flavors are so well-balanced that they appeal to a wide range of palates.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 50,
    cookTime: 10,
    totalTime: 60,
    servings: 24,
    rating: "5.0",
    calories: 85,
    protein: "2.5",
    carbs: "9.5",
    fat: "4.0",
    fiber: "0.5",
    sugar: "4.5",
    image: "/recipe-images/caramelized-onion-goat-cheese-honey-rosemary.png",
    ingredients: [
      "24 gluten-free crackers or polenta rounds",
      "3 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "3 tablespoons honey, plus more for drizzling",
      "2 tablespoons fresh rosemary, finely chopped",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "In large skillet over medium-low heat, melt butter with oil. Add onions and cook 40-45 minutes, stirring occasionally, until deep golden and caramelized.",
      "Add balsamic vinegar and 1 tablespoon honey to onions. Cook 3 more minutes. Season with salt and pepper. Let cool.",
      "Mix softened goat cheese with 2 tablespoons honey and half the chopped rosemary until smooth.",
      "Spread honey-rosemary goat cheese on each cracker or polenta round.",
      "Top with a generous spoonful of caramelized onions.",
      "Preheat oven to 350°F. Place bites on baking sheet and warm for 8-10 minutes.",
      "Remove from oven and immediately drizzle each bite with additional honey.",
      "Sprinkle with remaining fresh rosemary.",
      "Garnish with small rosemary sprigs and serve warm."
    ],
    tips: "Use good quality honey — the flavor really shines through. For a more intense rosemary flavor, let the goat cheese mixture sit for 30 minutes before using. The honey will be easier to drizzle if you warm it slightly first.",
    variations: [
      "Use thyme instead of rosemary",
      "Add a pinch of red pepper flakes for subtle heat",
      "Top with toasted pine nuts"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "honey", "rosemary", "sweet savory", "appetizer", "party", "elegant", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Honey & Rosemary - Sweet Savory Appetizer",
    seoDescription: "Sweet and savory gluten-free bites with caramelized onions, goat cheese, honey, and rosemary. Perfect elegant appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Mushrooms & Thyme",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-mushroom-thyme",
    description: "Sautéed mushrooms layered with sweet onions and goat cheese on a gluten-free cracker base.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Mushrooms & Thyme are an earthy, umami-rich appetizer that celebrates the deep flavors of caramelized vegetables and herbs. Golden-brown caramelized onions are joined by sautéed mushrooms that add meaty texture and savory depth. The mushrooms are cooked until they release and then reabsorb their liquid, concentrating their flavor. Creamy, tangy goat cheese provides a luxurious base, while fresh thyme ties everything together with its woodsy, aromatic notes. These bites have a wonderfully complex flavor profile that's both rustic and refined, making them perfect for fall and winter entertaining, wine and cheese nights, or any gathering where you want to serve something substantial and satisfying. The combination of three deeply flavored components creates layers of taste in every bite.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 12,
    totalTime: 67,
    servings: 24,
    rating: "4.9",
    calories: 82,
    protein: "3.0",
    carbs: "8.0",
    fat: "4.5",
    fiber: "1.0",
    sugar: "2.5",
    image: "/recipe-images/caramelized-onion-goat-cheese-mushroom-thyme.png",
    ingredients: [
      "24 gluten-free crackers",
      "2 large yellow onions, thinly sliced",
      "8 oz cremini or button mushrooms, sliced",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil, divided",
      "8 oz goat cheese, softened",
      "3 tablespoons fresh thyme leaves, divided",
      "2 cloves garlic, minced",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet, melt 2 tablespoons butter with 1 tablespoon oil. Add onions and cook 40-45 minutes over medium-low heat until deep golden. Add balsamic vinegar in last 5 minutes. Transfer to bowl.",
      "In same skillet, add remaining butter and oil. Add mushrooms and cook over medium-high heat for 8-10 minutes, stirring occasionally, until golden and liquid has evaporated.",
      "Add garlic and half the thyme to mushrooms. Cook 1 more minute. Season with salt and pepper. Let cool.",
      "Mix goat cheese with remaining thyme leaves until smooth.",
      "Spread goat cheese mixture on each cracker.",
      "Top with caramelized onions, then add sautéed mushrooms.",
      "Preheat oven to 350°F. Warm bites on baking sheet for 5-7 minutes.",
      "Garnish with fresh thyme sprigs and serve warm."
    ],
    tips: "Don't crowd the mushrooms in the pan or they'll steam instead of brown. Cook them in batches if needed. Both the onions and mushrooms can be made 2 days ahead and refrigerated. Use a mix of mushroom varieties for more complex flavor.",
    variations: [
      "Add a splash of white wine when cooking the mushrooms",
      "Use shallots instead of regular onions",
      "Top with toasted hazelnuts or pecans"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "mushrooms", "thyme", "earthy", "umami", "appetizer", "party", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Mushrooms & Thyme - Earthy Appetizer",
    seoDescription: "Earthy gluten-free bites with caramelized onions, sautéed mushrooms, goat cheese, and thyme. Perfect umami-rich appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Prosciutto",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-prosciutto",
    description: "Wrapped in prosciutto before baking — savory, salty, and decadent.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Prosciutto are the ultimate in savory indulgence, combining sweet, tangy, and salty elements in perfect harmony. Each bite features creamy goat cheese mixed with sweet caramelized onions, all wrapped in a delicate slice of prosciutto that becomes crispy and slightly caramelized in the oven. The prosciutto adds a salty, meaty element that complements the sweetness of the onions and the tanginess of the cheese beautifully. As the bites bake, the prosciutto shrinks and crisps, creating an elegant presentation and adding textural contrast. These are sophisticated appetizers that work equally well for casual gatherings or upscale events. They're perfect for meat and cheese boards, cocktail parties, or holiday entertaining when you want to serve something special that feels luxurious and indulgent.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 15,
    totalTime: 70,
    servings: 24,
    rating: "5.0",
    calories: 95,
    protein: "5.0",
    carbs: "6.0",
    fat: "6.0",
    fiber: "0.5",
    sugar: "2.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-prosciutto.png",
    ingredients: [
      "24 gluten-free crackers or small bread rounds",
      "2 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "6 oz goat cheese, softened",
      "12 thin slices prosciutto, cut in half",
      "2 tablespoons fresh thyme leaves",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
      "Fresh thyme for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet, melt butter with oil over medium-low heat. Add onions and cook 40-45 minutes until deep golden brown. Add balsamic vinegar in last 5 minutes. Let cool.",
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Mix goat cheese with caramelized onions and thyme until well combined.",
      "Place crackers on prepared baking sheet.",
      "Top each cracker with about 1 tablespoon of the goat cheese-onion mixture, forming it into a small mound.",
      "Wrap each bite with a half slice of prosciutto, tucking the ends underneath.",
      "Bake for 12-15 minutes until prosciutto is crispy and slightly browned.",
      "Remove from oven and let cool for 3-4 minutes.",
      "Garnish with fresh thyme sprigs and serve warm."
    ],
    tips: "Use thin prosciutto slices for best results — they'll crisp up nicely without becoming too chewy. The goat cheese mixture can be made a day ahead. Don't add salt to the mixture as the prosciutto is already quite salty.",
    variations: [
      "Use serrano ham instead of prosciutto",
      "Add a small basil leaf before wrapping",
      "Drizzle with honey after baking"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "prosciutto", "appetizer", "party", "savory", "elegant", "decadent", "finger food"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Prosciutto - Decadent Appetizer",
    seoDescription: "Decadent gluten-free bites with caramelized onions, goat cheese, wrapped in crispy prosciutto. Perfect savory appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Cranberry Glaze",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-cranberry-glaze",
    description: "Holiday-ready version topped with tart cranberry sauce and thyme.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Cranberry Glaze are the perfect holiday appetizer, combining festive flavors with elegant presentation. Sweet, jammy caramelized onions pair beautifully with tangy goat cheese, while a ruby-red cranberry glaze adds tart brightness and gorgeous color. Fresh thyme ties everything together with its earthy, aromatic notes. The cranberry glaze is made by simmering fresh cranberries with sugar and orange juice until they burst and thicken, creating a jewel-toned topping that's both beautiful and delicious. These bites are ideal for Thanksgiving, Christmas, New Year's Eve, or any holiday gathering where you want to serve something that tastes amazing and looks stunning. The combination of colors — golden onions, white cheese, and ruby cranberries — makes these as visually appealing as they are delicious.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 15,
    totalTime: 70,
    servings: 24,
    rating: "5.0",
    calories: 88,
    protein: "2.5",
    carbs: "10.0",
    fat: "4.0",
    fiber: "0.8",
    sugar: "5.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-cranberry.png",
    ingredients: [
      "24 gluten-free crackers",
      "2 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "For cranberry glaze:",
      "1 cup fresh cranberries",
      "¼ cup sugar",
      "¼ cup orange juice",
      "2 tablespoons water",
      "2 tablespoons fresh thyme leaves",
      "Salt and pepper to taste",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Caramelize onions: In large skillet, melt butter with oil. Add onions and cook over medium-low heat for 40-45 minutes until deep golden brown. Season with salt and pepper. Let cool.",
      "Make cranberry glaze: In small saucepan, combine cranberries, sugar, orange juice, and water. Bring to boil, then reduce heat and simmer 10-12 minutes until cranberries burst and mixture thickens. Let cool.",
      "Mix goat cheese with half the thyme leaves until smooth.",
      "Spread goat cheese on each cracker.",
      "Top with a spoonful of caramelized onions.",
      "Preheat oven to 350°F. Warm bites on baking sheet for 5-7 minutes.",
      "Remove from oven and top each bite with a small spoonful of cranberry glaze.",
      "Garnish with remaining fresh thyme and serve."
    ],
    tips: "The cranberry glaze can be made up to 5 days ahead and refrigerated. It will thicken as it cools — add a splash of orange juice if it becomes too thick. For a smoother glaze, pulse it in a food processor after cooling.",
    variations: [
      "Add a pinch of cinnamon to the cranberry glaze",
      "Use dried cranberries rehydrated in orange juice",
      "Top with candied pecans for crunch"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "cranberry", "holiday", "thanksgiving", "christmas", "appetizer", "festive", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Cranberry Glaze - Holiday Appetizer",
    seoDescription: "Festive gluten-free bites with caramelized onions, goat cheese, and cranberry glaze. Perfect Thanksgiving and Christmas appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Walnut Crust",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-walnut-crust",
    description: "Nutty gluten-free walnut base topped with creamy cheese and caramelized onions.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Walnut Crust feature a unique homemade base made from ground walnuts, creating a nutty, earthy foundation that complements the other flavors beautifully. The walnut crust is pressed into mini muffin tins and baked until golden and crispy, providing both flavor and texture that elevates these bites beyond simple crackers. The crust's nuttiness pairs wonderfully with sweet caramelized onions and tangy goat cheese, creating a sophisticated flavor profile. These bites are perfect for those avoiding grains entirely or anyone who appreciates the rich, buttery flavor of walnuts. They're ideal for upscale entertaining, wine and cheese parties, or holiday gatherings where you want to serve something truly special and memorable. The walnut crust also adds visual interest and a rustic, artisanal quality.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 60,
    cookTime: 25,
    totalTime: 85,
    servings: 24,
    rating: "4.9",
    calories: 95,
    protein: "3.5",
    carbs: "6.0",
    fat: "7.0",
    fiber: "1.0",
    sugar: "2.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-walnut-crust.png",
    ingredients: [
      "For walnut crust:",
      "2 cups walnuts",
      "2 tablespoons butter, melted",
      "1 egg",
      "½ teaspoon salt",
      "For topping:",
      "2 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "6 oz goat cheese, softened",
      "2 tablespoons fresh thyme leaves",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 24-cup mini muffin tin.",
      "Make walnut crust: In food processor, pulse walnuts until finely ground but not paste. Add melted butter, egg, and salt. Pulse until mixture holds together when pressed.",
      "Press about 1 tablespoon of walnut mixture into each muffin cup, pressing up the sides slightly to form cups.",
      "Bake walnut crusts for 12-15 minutes until golden and set. Let cool in pan for 10 minutes, then carefully remove to wire rack.",
      "While crusts bake, caramelize onions: In large skillet, melt butter with oil. Add onions and cook over medium-low heat for 40-45 minutes until deep golden. Add balsamic vinegar in last 5 minutes.",
      "Mix goat cheese with thyme until smooth.",
      "Place a small spoonful of goat cheese in each walnut cup.",
      "Top with caramelized onions.",
      "Return to oven for 3-5 minutes to warm through. Serve warm or at room temperature."
    ],
    tips: "Make sure walnuts are finely ground but stop before they become walnut butter. The walnut crusts can be made a day ahead and stored in an airtight container. Reheat briefly before filling.",
    variations: [
      "Use pecans instead of walnuts",
      "Add grated Parmesan to the walnut mixture",
      "Top with a drizzle of honey"
    ],
    tags: ["gluten-free", "grain-free", "walnut crust", "caramelized onion", "goat cheese", "appetizer", "party", "nutty", "low-carb", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Walnut Crust - Grain-Free Appetizer",
    seoDescription: "Grain-free gluten-free bites with walnut crust, caramelized onions, and goat cheese. Perfect nutty low-carb appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Hot Honey Drizzle",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-hot-honey-drizzle",
    description: "Sweet and spicy twist — finished with a drizzle of hot honey and chili flakes.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Hot Honey Drizzle are for those who love the exciting interplay of sweet, savory, and spicy flavors. Golden caramelized onions provide deep sweetness, tangy goat cheese adds creamy contrast, and a drizzle of hot honey brings the heat. The hot honey — made by infusing regular honey with red pepper flakes — adds layers of flavor with its initial sweetness followed by a pleasant warming sensation. A final sprinkle of chili flakes adds visual appeal and an extra kick for spice lovers. These bites are conversation-starters that will have your guests reaching for more. They're perfect for adventurous eaters, cocktail parties, or any gathering where you want to serve something unexpected and memorable. The combination of flavors is bold yet balanced, with each element complementing the others.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 10,
    totalTime: 65,
    servings: 24,
    rating: "4.9",
    calories: 86,
    protein: "2.5",
    carbs: "9.0",
    fat: "4.5",
    fiber: "0.5",
    sugar: "4.5",
    image: "/recipe-images/caramelized-onion-goat-cheese-hot-honey.png",
    ingredients: [
      "24 gluten-free crackers",
      "2 large yellow onions, thinly sliced",
      "2 tablespoons butter",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "For hot honey:",
      "⅓ cup honey",
      "1-2 teaspoons red pepper flakes",
      "1 tablespoon balsamic vinegar",
      "Red chili flakes for garnish",
      "Fresh thyme for garnish",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Make hot honey: In small saucepan, warm honey over low heat. Add red pepper flakes and let steep for 10-15 minutes. Strain if desired for milder heat, or leave flakes in for more spice. Set aside.",
      "Caramelize onions: In large skillet, melt butter with oil. Add onions and cook over medium-low heat for 40-45 minutes until deep golden brown. Add balsamic vinegar in last 5 minutes. Season with salt and pepper. Let cool.",
      "Spread goat cheese on each cracker.",
      "Top each with a generous spoonful of caramelized onions.",
      "Preheat oven to 350°F. Warm bites on baking sheet for 5-7 minutes.",
      "Remove from oven and immediately drizzle each bite with hot honey.",
      "Sprinkle with a pinch of red chili flakes.",
      "Garnish with fresh thyme and serve warm."
    ],
    tips: "Adjust the heat level by using more or less red pepper flakes in the honey. Start with less and taste before adding more. The hot honey can be made up to 2 weeks ahead and stored at room temperature. Warm it slightly before drizzling for easier handling.",
    variations: [
      "Use jalapeño-infused honey instead",
      "Add a squeeze of lime juice before serving",
      "Top with toasted pepitas for crunch"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "hot honey", "spicy", "sweet heat", "appetizer", "party", "bold flavors", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Hot Honey - Sweet Spicy Appetizer",
    seoDescription: "Bold gluten-free bites with caramelized onions, goat cheese, and hot honey drizzle. Perfect sweet and spicy party appetizer."
  },
  {
    title: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Pear & Sage",
    slug: "gluten-free-caramelized-onion-goat-cheese-bites-pear-sage",
    description: "Sliced pear, goat cheese, and onions over crisp base — earthy and aromatic.",
    longDescription: "These Gluten-Free Caramelized Onion & Goat Cheese Bites with Pear & Sage are an elegant autumn appetizer that celebrates the classic pairing of pear and cheese with a sophisticated twist. Thin slices of ripe, sweet pear add a fresh, fruity note that balances beautifully with tangy goat cheese and sweet caramelized onions. Fresh sage leaves are crisped in butter until aromatic and delicate, adding an earthy, slightly peppery flavor that ties the other ingredients together perfectly. The combination is both rustic and refined, making these bites suitable for upscale dinner parties, fall gatherings, or holiday entertaining. The visual presentation is stunning with the pale pear slices contrasting against the golden onions and white cheese. These bites capture the essence of autumn in every bite — fresh fruit, warming herbs, and comforting caramelized vegetables.",
    category: "Appetizers",
    subcategory: "Party & Finger Foods",
    difficulty: "Medium",
    prepTime: 55,
    cookTime: 12,
    totalTime: 67,
    servings: 24,
    rating: "5.0",
    calories: 80,
    protein: "2.5",
    carbs: "9.0",
    fat: "4.0",
    fiber: "1.0",
    sugar: "4.0",
    image: "/recipe-images/caramelized-onion-goat-cheese-pear-sage.png",
    ingredients: [
      "24 gluten-free crackers or crostini",
      "2 large yellow onions, thinly sliced",
      "3 tablespoons butter, divided",
      "1 tablespoon olive oil",
      "8 oz goat cheese, softened",
      "2 ripe pears, thinly sliced",
      "20-24 fresh sage leaves",
      "1 tablespoon balsamic vinegar",
      "1 tablespoon lemon juice",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Caramelize onions: In large skillet, melt 2 tablespoons butter with oil. Add onions and cook over medium-low heat for 40-45 minutes until deep golden. Add balsamic vinegar in last 5 minutes. Season and let cool.",
      "In small skillet, melt remaining 1 tablespoon butter. Add sage leaves and fry for 30-60 seconds until crispy. Remove to paper towels.",
      "Toss sliced pears with lemon juice to prevent browning.",
      "Spread goat cheese on each cracker or crostini.",
      "Top with caramelized onions.",
      "Add a thin slice of pear to each bite.",
      "Preheat oven to 350°F. Warm bites on baking sheet for 5-7 minutes.",
      "Remove from oven and top each with a crispy sage leaf.",
      "Serve immediately while warm."
    ],
    tips: "Choose pears that are ripe but still firm — they should slice easily without falling apart. Bosc or Anjou pears work particularly well. The sage leaves crisp up quickly, so watch them carefully. Use them immediately or they'll soften.",
    variations: [
      "Use apple slices instead of pear",
      "Add a drizzle of honey before serving",
      "Sprinkle with toasted walnuts"
    ],
    tags: ["gluten-free", "caramelized onion", "goat cheese", "pear", "sage", "autumn", "fall", "appetizer", "elegant", "vegetarian"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion & Goat Cheese Bites with Pear & Sage - Autumn Appetizer",
    seoDescription: "Elegant autumn gluten-free bites with caramelized onions, goat cheese, pear, and crispy sage. Perfect fall appetizer."
  }
];

async function seed() {
  console.log("Adding 10 gluten-free caramelized onion & goat cheese bite recipes...");
  
  try {
    const result = await db
      .insert(recipes)
      .values(caramelizedOnionGoatCheeseBites)
      .onConflictDoNothing({ target: [recipes.slug] });
    
    console.log(`Successfully added ${caramelizedOnionGoatCheeseBites.length} caramelized onion & goat cheese bite recipes to the database!`);
    console.log("All recipes have been inserted under Appetizers → Party & Finger Foods category.");
  } catch (error) {
    console.error("Error adding recipes:", error);
    throw error;
  }
}

seed()
  .then(() => {
    console.log("Seed completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
