import { db } from "../server/db";
import { recipes } from "../shared/schema";

const gougereRecipes = [
  {
    title: "Gluten-Free Gougères with Smoked Salmon & Chive Cream",
    slug: "gluten-free-gougeres-smoked-salmon-chive-cream",
    description: "Delicate cheese puffs filled with whipped cream cheese, lemon zest, and chives — topped with ribbons of smoked salmon.",
    longDescription: "These Gluten-Free Gougères with Smoked Salmon & Chive Cream are the ultimate elegant appetizer. Classic French gougères - light, airy cheese puffs made from pâte à choux - are reimagined with gluten-free flour that performs beautifully. The puffs bake up golden and crispy on the outside while remaining delightfully hollow inside. Each one is filled with a luxurious whipped cream cheese mixture brightened with lemon zest and fresh chives, then topped with silky ribbons of smoked salmon. The combination of textures and flavors is extraordinary - crispy pastry, creamy filling, and delicate salmon. Perfect for cocktail parties, brunch, or any celebration where you want to impress. These are French elegance made gluten-free.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    servings: 24,
    rating: "5.0",
    calories: 95,
    protein: "4.5",
    carbs: "6.0",
    fat: "6.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-gougeres-smoked-salmon-chive-cream.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons unsalted butter, cubed",
      "1 teaspoon salt",
      "1 cup gluten-free all-purpose flour blend",
      "4 large eggs",
      "1 cup shredded Gruyère cheese",
      "8 oz cream cheese, softened",
      "3 tablespoons fresh chives, minced",
      "1 tablespoon lemon zest",
      "8 oz smoked salmon, cut into ribbons",
      "Fresh chives and lemon wedges for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line two baking sheets with parchment paper.",
      "In medium saucepan, bring water, butter, and salt to rolling boil over high heat.",
      "Remove from heat and add all the gluten-free flour at once. Stir vigorously with wooden spoon until mixture forms a ball.",
      "Return pan to medium heat and cook, stirring constantly, for 1-2 minutes to dry out the dough slightly.",
      "Transfer dough to bowl of stand mixer (or large bowl). Let cool 5 minutes.",
      "Add eggs one at a time, beating well after each addition until dough is smooth and glossy.",
      "Stir in Gruyère cheese until evenly distributed.",
      "Using two spoons or piping bag, drop tablespoon-sized mounds onto prepared baking sheets, spacing 2 inches apart.",
      "Bake 25-30 minutes until puffed, golden brown, and crispy. Do not open oven door during first 20 minutes or gougères will collapse.",
      "Remove from oven and cool completely on wire rack.",
      "Make filling: Beat cream cheese with chives and lemon zest until smooth and fluffy.",
      "Split cooled gougères in half or cut small opening in side. Pipe or spoon chive cream cheese inside.",
      "Top each with a ribbon of smoked salmon and garnish with chives.",
      "Serve immediately or refrigerate up to 2 hours before serving."
    ],
    tips: "Don't open oven door during first 20 minutes of baking. Gougères should be completely hollow inside - if they're doughy, they need more baking time. Can bake gougères ahead and store airtight, then crisp in 350°F oven for 5 minutes before filling.",
    variations: [
      "Use different cheese: Gruyère, Comté, or aged cheddar",
      "Add Dijon mustard to the cream cheese filling",
      "Top with caviar for ultimate luxury"
    ],
    tags: ["gluten-free", "gougères", "smoked salmon", "french", "appetizer", "elegant", "party", "brunch", "cheese puffs", "choux pastry"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Gougères with Smoked Salmon & Chive Cream - French Elegance",
    seoDescription: "Elegant gluten-free cheese puffs filled with chive cream cheese and topped with smoked salmon. Perfect appetizer, French-inspired."
  },
  {
    title: "Gluten-Free Gougères with Smoked Salmon & Lemon Dill Mousse",
    slug: "gluten-free-gougeres-smoked-salmon-lemon-dill-mousse",
    description: "A light mousse made with cream cheese, dill, and lemon folded into airy gougères — elegant and refreshing.",
    longDescription: "These Gluten-Free Gougères with Smoked Salmon & Lemon Dill Mousse bring bright, fresh flavors to classic French cheese puffs. The mousse is incredibly light and fluffy - cream cheese whipped with fresh dill, lemon juice, and zest until airy and cloud-like. This delicate filling complements the crispy gougères perfectly without weighing them down. Folded smoked salmon adds elegance and a pop of color. The combination of crispy pastry, lemony mousse, herbaceous dill, and silky salmon is simply divine. These are sophisticated enough for the fanciest occasions but approachable enough to make for yourself. A true celebration of texture and flavor.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    servings: 24,
    rating: "4.9",
    calories: 92,
    protein: "4.0",
    carbs: "6.0",
    fat: "6.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-gougeres-smoked-salmon-lemon-dill-mousse.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup grated Comté or Gruyère cheese",
      "8 oz cream cheese, softened",
      "1/4 cup sour cream",
      "3 tablespoons fresh dill, minced",
      "2 tablespoons lemon juice",
      "1 tablespoon lemon zest",
      "8 oz smoked salmon",
      "Fresh dill sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Bring water, butter, and salt to boil in saucepan.",
      "Add flour all at once, stirring vigorously until dough forms ball and pulls away from sides.",
      "Cook dough over medium heat for 1-2 minutes, stirring constantly.",
      "Transfer to mixer bowl and cool 5 minutes.",
      "Beat in eggs one at a time until dough is smooth and glossy.",
      "Fold in grated cheese.",
      "Pipe or spoon mounds onto baking sheets, 2 inches apart.",
      "Bake 25-30 minutes until puffed, golden, and crispy. Don't open oven for first 20 minutes.",
      "Cool completely on wire rack.",
      "Make mousse: Beat cream cheese with sour cream until very smooth.",
      "Fold in dill, lemon juice, and lemon zest. Whip until light and fluffy.",
      "Split gougères and fill with lemon dill mousse.",
      "Top each with folded smoked salmon and garnish with fresh dill.",
      "Serve immediately."
    ],
    tips: "Mousse should be light and airy - don't overmix. Fold ingredients gently to maintain volume. Gougères are best filled just before serving to maintain crispness.",
    variations: [
      "Add capers to the mousse",
      "Use mascarpone instead of cream cheese",
      "Include finely chopped cucumber"
    ],
    tags: ["gluten-free", "gougères", "smoked salmon", "lemon", "dill", "mousse", "french", "elegant", "appetizer", "party"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Gougères with Smoked Salmon & Lemon Dill Mousse - Refreshing Elegance",
    seoDescription: "Light gluten-free cheese puffs with airy lemon dill mousse and smoked salmon. Sophisticated French appetizer."
  },
  {
    title: "Gluten-Free Everything-Seasoned Gougères with Smoked Salmon",
    slug: "gluten-free-everything-seasoned-gougeres-smoked-salmon",
    description: "Topped with everything bagel seasoning and filled with crème fraîche, red onion, and salmon — brunch perfection.",
    longDescription: "These Gluten-Free Everything-Seasoned Gougères with Smoked Salmon bring bagel shop flavors to French pastry. Each golden puff is topped with everything bagel seasoning (sesame seeds, poppy seeds, dried onion, garlic, and salt) before baking, creating a crunchy, aromatic crust. Inside, they're filled with tangy crème fraîche, thinly sliced red onion, and premium smoked salmon. The combination is pure brunch perfection - all the flavors of a classic bagel with lox but in an elegant, gluten-free cheese puff. These are conversation starters that disappear quickly at any gathering.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    servings: 24,
    rating: "5.0",
    calories: 98,
    protein: "4.5",
    carbs: "7.0",
    fat: "6.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-everything-seasoned-gougeres-smoked-salmon.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup shredded white cheddar",
      "3 tablespoons everything bagel seasoning",
      "1 cup crème fraîche",
      "1/4 red onion, very thinly sliced",
      "8 oz smoked salmon",
      "2 tablespoons capers (optional)",
      "Fresh dill for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux dough: Boil water, butter, and salt together.",
      "Add flour all at once and stir until dough forms smooth ball.",
      "Cook 1-2 minutes over medium heat to dry dough slightly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in shredded cheddar.",
      "Pipe or spoon mounds onto baking sheets.",
      "Sprinkle generously with everything bagel seasoning.",
      "Bake 25-30 minutes until puffed and golden. Don't open oven early.",
      "Cool completely.",
      "Split gougères or cut small opening.",
      "Fill with dollop of crème fraîche.",
      "Top with red onion slices, smoked salmon, and capers if using.",
      "Garnish with fresh dill and serve."
    ],
    tips: "Press everything seasoning gently into dough before baking so it adheres. Slice red onion paper-thin for best texture. These are best assembled just before serving.",
    variations: [
      "Add cream cheese to the filling",
      "Include thinly sliced cucumber",
      "Use homemade everything seasoning"
    ],
    tags: ["gluten-free", "gougères", "everything bagel", "smoked salmon", "brunch", "appetizer", "party", "french-american", "cheese puffs"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Everything-Seasoned Gougères with Smoked Salmon - Brunch Perfection",
    seoDescription: "Unique gluten-free cheese puffs with everything bagel seasoning, crème fraîche, and smoked salmon. Perfect brunch appetizer."
  },
  {
    title: "Gluten-Free Mini Gougères with Smoked Salmon & Capers",
    slug: "gluten-free-mini-gougeres-smoked-salmon-capers",
    description: "Bite-sized puffs piped with caper cream and smoked salmon — cocktail-ready.",
    longDescription: "These Gluten-Free Mini Gougères with Smoked Salmon & Capers are the perfect one-bite appetizer for cocktail parties. Petite cheese puffs - about the size of a quarter - are baked until golden and crispy, then piped with a tangy caper cream cheese filling and topped with small pieces of smoked salmon and briny capers. The small size makes them ideal for passing at parties or serving with drinks. Each bite delivers crispy pastry, creamy filling, silky salmon, and a pop of briny caper flavor. These are elegant, impressive, and surprisingly easy to eat while mingling. Make ahead and fill just before guests arrive.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 25,
    totalTime: 55,
    servings: 48,
    rating: "4.9",
    calories: 48,
    protein: "2.0",
    carbs: "3.0",
    fat: "3.0",
    fiber: "0.0",
    sugar: "0.5",
    image: "/recipe-images/gluten-free-mini-gougeres-smoked-salmon-capers.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup grated Parmesan cheese",
      "8 oz cream cheese, softened",
      "2 tablespoons capers, minced",
      "1 tablespoon caper brine",
      "1 tablespoon lemon juice",
      "6 oz smoked salmon, cut into small pieces",
      "Whole capers for garnish",
      "Fresh chives for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Boil water, butter, and salt in saucepan.",
      "Add flour all at once, stirring until dough forms ball.",
      "Cook over medium heat 1-2 minutes, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in Parmesan cheese.",
      "Using small piping tip or two small spoons, pipe or drop mini mounds (about 1 teaspoon each) onto baking sheets, 1 inch apart.",
      "Bake 20-25 minutes until puffed and golden brown.",
      "Cool completely on wire rack.",
      "Make caper cream: Beat cream cheese with minced capers, caper brine, and lemon juice until smooth.",
      "Using small piping tip, pipe caper cream into or onto each mini gougère.",
      "Top each with small piece of smoked salmon and a caper.",
      "Garnish with minced chives and serve."
    ],
    tips: "Mini gougères bake faster than regular size - watch carefully to prevent burning. Use a piping bag for uniform size and easy filling. Can be made ahead and crisped in oven before filling.",
    variations: [
      "Add fresh dill to the cream",
      "Use whipped goat cheese instead",
      "Top with caviar for luxury version"
    ],
    tags: ["gluten-free", "gougères", "mini", "bite-sized", "smoked salmon", "capers", "cocktail party", "appetizer", "elegant", "french"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Mini Gougères with Smoked Salmon & Capers - Cocktail Perfect",
    seoDescription: "Bite-sized gluten-free cheese puffs with caper cream and smoked salmon. Perfect cocktail party appetizer."
  },
  {
    title: "Gluten-Free Gougères with Smoked Salmon & Horseradish Cream",
    slug: "gluten-free-gougeres-smoked-salmon-horseradish-cream",
    description: "Bold and tangy — crème fraîche and horseradish filling with smoked salmon curls.",
    longDescription: "These Gluten-Free Gougères with Smoked Salmon & Horseradish Cream are for those who love bold flavors. The filling combines tangy crème fraîche with prepared horseradish, creating a spicy, creamy mixture that cuts through the richness of the cheese puffs. Fresh dill adds herbaceous notes while lemon brightens everything. Delicate smoked salmon curls provide visual elegance and silky texture. The contrast between the spicy horseradish cream and mild salmon is absolutely delicious. These sophisticated appetizers are perfect for guests who appreciate assertive flavors. They're memorable, impressive, and surprisingly addictive.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    servings: 24,
    rating: "4.8",
    calories: 94,
    protein: "4.0",
    carbs: "6.0",
    fat: "6.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-gougeres-smoked-salmon-horseradish-cream.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup shredded Gruyère",
      "1 cup crème fraîche",
      "3 tablespoons prepared horseradish, drained",
      "2 tablespoons fresh dill, minced",
      "1 tablespoon lemon juice",
      "8 oz smoked salmon",
      "Fresh dill sprigs and lemon zest for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux pastry: Bring water, butter, and salt to boil.",
      "Add flour all at once and stir vigorously until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in Gruyère cheese.",
      "Pipe or spoon mounds onto baking sheets, spacing 2 inches apart.",
      "Bake 25-30 minutes until puffed, golden, and crispy.",
      "Cool completely on wire rack.",
      "Make horseradish cream: Mix crème fraîche with drained horseradish, dill, and lemon juice. Taste and adjust horseradish to preference.",
      "Split cooled gougères or cut opening in side.",
      "Pipe or spoon horseradish cream inside each puff.",
      "Top with curled ribbons of smoked salmon.",
      "Garnish with fresh dill and lemon zest. Serve immediately."
    ],
    tips: "Drain horseradish well before mixing or cream will be watery. Adjust horseradish amount to taste - start with less if unsure. The filling is bold so a little goes a long way.",
    variations: [
      "Use sour cream instead of crème fraîche",
      "Add cream cheese for milder flavor",
      "Include finely minced chives"
    ],
    tags: ["gluten-free", "gougères", "smoked salmon", "horseradish", "bold", "spicy", "appetizer", "french", "party", "elegant"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Gougères with Smoked Salmon & Horseradish Cream - Bold & Tangy",
    seoDescription: "Bold gluten-free cheese puffs with spicy horseradish cream and smoked salmon. Sophisticated appetizer with kick."
  },
  {
    title: "Gluten-Free Gougères with Smoked Salmon & Goat Cheese Mousse",
    slug: "gluten-free-gougeres-smoked-salmon-goat-cheese-mousse",
    description: "Whipped goat cheese and lemon filling — savory and tangy, paired with delicate salmon.",
    longDescription: "These Gluten-Free Gougères with Smoked Salmon & Goat Cheese Mousse are elegance personified. The filling is a cloud-like mousse made from tangy goat cheese whipped with cream cheese, fresh lemon, and herbs until incredibly light and airy. This sophisticated filling pairs beautifully with the crispy cheese puffs and delicate smoked salmon. The goat cheese provides distinctive tang while the lemon adds brightness. Fresh herbs and a hint of garlic round out the flavors. These are refined, memorable, and absolutely delicious. Perfect for wine tastings, cocktail parties, or any time you want to serve something truly special.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    servings: 24,
    rating: "5.0",
    calories: 96,
    protein: "4.5",
    carbs: "6.0",
    fat: "6.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-gougeres-smoked-salmon-goat-cheese-mousse.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup shredded Gruyère",
      "6 oz goat cheese, softened",
      "4 oz cream cheese, softened",
      "2 tablespoons heavy cream",
      "2 tablespoons lemon juice",
      "1 tablespoon lemon zest",
      "2 tablespoons fresh chives, minced",
      "1 clove garlic, minced",
      "8 oz smoked salmon",
      "Fresh herbs and lemon zest for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux dough: Boil water, butter, and salt.",
      "Add flour all at once, stirring until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in Gruyère.",
      "Pipe or spoon onto baking sheets.",
      "Bake 25-30 minutes until puffed and golden.",
      "Cool completely.",
      "Make mousse: Beat goat cheese and cream cheese until very smooth.",
      "Add heavy cream and beat until fluffy.",
      "Fold in lemon juice, lemon zest, chives, and garlic. Whip until light and airy like mousse.",
      "Split gougères and pipe mousse inside generously.",
      "Top each with folded smoked salmon.",
      "Garnish with fresh herbs and lemon zest. Serve immediately."
    ],
    tips: "Let cheeses come to room temperature for smoothest mousse. Whip until very light and fluffy - this takes a few minutes. The mousse should hold soft peaks.",
    variations: [
      "Add fresh dill or tarragon",
      "Include finely minced shallots",
      "Use herbed goat cheese"
    ],
    tags: ["gluten-free", "gougères", "smoked salmon", "goat cheese", "mousse", "elegant", "french", "appetizer", "sophisticated", "tangy"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Gougères with Smoked Salmon & Goat Cheese Mousse - Sophisticated",
    seoDescription: "Elegant gluten-free cheese puffs with light goat cheese mousse and smoked salmon. Refined French appetizer."
  },
  {
    title: "Gluten-Free Parmesan Gougères with Smoked Salmon & Dill Butter",
    slug: "gluten-free-parmesan-gougeres-smoked-salmon-dill-butter",
    description: "Parmesan choux pastry brushed with dill butter and topped with salmon for extra richness.",
    longDescription: "These Gluten-Free Parmesan Gougères with Smoked Salmon & Dill Butter are luxuriously rich and flavorful. The choux pastry is loaded with freshly grated Parmesan, which creates an incredible savory base. After baking, the puffs are brushed with melted butter infused with fresh dill, adding aromatic richness. Ribbons of smoked salmon are draped over each puff, and a final sprinkle of Parmesan adds visual appeal. The combination of nutty Parmesan, fragrant dill butter, and silky salmon is absolutely divine. These are indulgent, memorable, and perfect for special occasions when you want to pull out all the stops.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 30,
    totalTime: 55,
    servings: 24,
    rating: "4.9",
    calories: 102,
    protein: "5.0",
    carbs: "6.0",
    fat: "7.0",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-parmesan-gougeres-smoked-salmon-dill-butter.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1.5 cups freshly grated Parmesan cheese, divided",
      "4 tablespoons butter for dill butter",
      "3 tablespoons fresh dill, minced",
      "8 oz smoked salmon",
      "Fresh dill sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux pastry: Boil water, 6 tablespoons butter, and salt.",
      "Add flour all at once, stirring until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in 1 cup Parmesan cheese.",
      "Pipe or spoon mounds onto baking sheets.",
      "Sprinkle tops with remaining Parmesan.",
      "Bake 25-30 minutes until puffed, golden, and crispy.",
      "While gougères bake, make dill butter: Melt 4 tablespoons butter and stir in minced dill. Set aside.",
      "As soon as gougères come out of oven, brush generously with dill butter.",
      "Let cool slightly.",
      "Top each gougère with ribbon of smoked salmon.",
      "Garnish with fresh dill sprigs and serve warm or at room temperature."
    ],
    tips: "Use freshly grated Parmesan for best flavor - pre-grated doesn't melt as well. Brush with dill butter while gougères are still warm so it soaks in. Can be assembled a few hours ahead and refrigerated.",
    variations: [
      "Add lemon zest to dill butter",
      "Use Gruyère instead of Parmesan",
      "Include minced garlic in butter"
    ],
    tags: ["gluten-free", "gougères", "parmesan", "smoked salmon", "dill butter", "rich", "elegant", "french", "appetizer", "special occasion"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Parmesan Gougères with Smoked Salmon & Dill Butter - Luxurious",
    seoDescription: "Rich gluten-free Parmesan cheese puffs with dill butter and smoked salmon. Luxurious French appetizer."
  },
  {
    title: "Gluten-Free Cheddar Gougères with Smoked Salmon & Pickled Shallots",
    slug: "gluten-free-cheddar-gougeres-smoked-salmon-pickled-shallots",
    description: "A sharper cheese variation topped with thinly sliced salmon and tangy pickled shallots.",
    longDescription: "These Gluten-Free Cheddar Gougères with Smoked Salmon & Pickled Shallots bring bold, assertive flavors to the traditional French appetizer. Sharp white cheddar gives the puffs a more pronounced cheese flavor than traditional Gruyère. Thinly sliced smoked salmon provides elegance while quick-pickled shallots add a bright, tangy punch that cuts through the richness. The pickled shallots are easy to make - just shallots, vinegar, and a touch of sugar - but they add incredible flavor and beautiful pink color. These are modern, bold, and absolutely delicious. Perfect for guests who appreciate big flavors.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 30,
    totalTime: 65,
    servings: 24,
    rating: "4.8",
    calories: 94,
    protein: "4.5",
    carbs: "7.0",
    fat: "6.0",
    fiber: "0.5",
    sugar: "1.5",
    image: "/recipe-images/gluten-free-cheddar-gougeres-smoked-salmon-pickled-shallots.png",
    ingredients: [
      "2 shallots, thinly sliced",
      "1/2 cup white wine vinegar",
      "1 tablespoon sugar",
      "1/2 teaspoon salt",
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1.5 cups shredded sharp white cheddar",
      "8 oz smoked salmon, thinly sliced",
      "Fresh chives for garnish"
    ],
    instructions: [
      "Make pickled shallots: Combine vinegar, sugar, and 1/2 teaspoon salt in small saucepan. Bring to boil.",
      "Add sliced shallots, remove from heat, and let sit 20-30 minutes. Drain before using.",
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux pastry: Boil water, butter, and 1 teaspoon salt.",
      "Add flour all at once, stirring until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth.",
      "Fold in sharp cheddar cheese.",
      "Pipe or spoon mounds onto baking sheets.",
      "Bake 25-30 minutes until puffed and golden.",
      "Cool completely.",
      "Top each gougère with folded smoked salmon slice.",
      "Add a few drained pickled shallots to each.",
      "Garnish with fresh chives and serve."
    ],
    tips: "Pickled shallots can be made days ahead and stored in refrigerator. Sharp cheddar provides more flavor than mild - use good quality aged cheddar. The contrast of sharp cheese, rich salmon, and tangy shallots is key.",
    variations: [
      "Use aged Gouda instead of cheddar",
      "Add cream cheese filling",
      "Include capers with shallots"
    ],
    tags: ["gluten-free", "gougères", "cheddar", "smoked salmon", "pickled shallots", "bold", "modern", "appetizer", "french", "tangy"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cheddar Gougères with Smoked Salmon & Pickled Shallots - Bold Flavors",
    seoDescription: "Bold gluten-free cheddar cheese puffs with smoked salmon and tangy pickled shallots. Modern French appetizer."
  },
  {
    title: "Gluten-Free Gruyère Gougères with Smoked Salmon & Caviar Cream",
    slug: "gluten-free-gruyere-gougeres-smoked-salmon-caviar-cream",
    description: "Luxurious version featuring crème fraîche, chives, and salmon, finished with a touch of caviar.",
    longDescription: "These Gluten-Free Gruyère Gougères with Smoked Salmon & Caviar Cream are the ultimate luxury appetizer. Classic Gruyère cheese puffs are filled with crème fraîche mixed with fresh chives, then topped with premium smoked salmon and finished with a small dollop of caviar. The caviar adds briny pops of flavor and incredible visual elegance. This is special occasion food at its finest - perfect for New Year's Eve, anniversaries, or any time you want to celebrate in style. While the caviar is certainly a splurge, a little goes a long way. These are unforgettable, impressive, and absolutely delicious.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    servings: 24,
    rating: "5.0",
    calories: 108,
    protein: "5.0",
    carbs: "6.0",
    fat: "7.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-gruyere-gougeres-smoked-salmon-caviar-cream.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1.5 cups shredded Gruyère cheese",
      "1 cup crème fraîche",
      "3 tablespoons fresh chives, minced",
      "1 tablespoon lemon juice",
      "8 oz premium smoked salmon",
      "2 oz caviar (your choice of quality)",
      "Fresh chives and lemon zest for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux pastry: Bring water, butter, and salt to boil.",
      "Add flour all at once, stirring vigorously until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in Gruyère cheese.",
      "Pipe or spoon elegant mounds onto baking sheets.",
      "Bake 25-30 minutes until puffed, golden, and crispy.",
      "Cool completely on wire rack.",
      "Mix crème fraîche with chives and lemon juice.",
      "Split gougères or cut small opening.",
      "Pipe or spoon chive crème fraîche inside each puff.",
      "Top with folded piece of smoked salmon.",
      "Add small dollop (about 1/4 teaspoon) of caviar to each.",
      "Garnish with chives and lemon zest. Serve immediately with champagne."
    ],
    tips: "Use best quality ingredients you can afford - this is a luxury appetizer. Handle caviar gently with non-metal spoon. Assemble just before serving to maintain crispness. Perfect with champagne or sparkling wine.",
    variations: [
      "Use different types of caviar",
      "Add cream cheese to filling",
      "Include fresh dill with chives"
    ],
    tags: ["gluten-free", "gougères", "gruyère", "smoked salmon", "caviar", "luxury", "elegant", "special occasion", "french", "champagne"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Gruyère Gougères with Smoked Salmon & Caviar - Ultimate Luxury",
    seoDescription: "Luxurious gluten-free Gruyère cheese puffs with smoked salmon and caviar. Perfect for celebrations, elegant French appetizer."
  },
  {
    title: "Gluten-Free Blini-Style Gougères with Smoked Salmon & Crème Fraîche",
    slug: "gluten-free-blini-style-gougeres-smoked-salmon-creme-fraiche",
    description: "Inspired by classic blinis — airy gougères topped with crème fraîche, dill, and salmon rosettes.",
    longDescription: "These Gluten-Free Blini-Style Gougères with Smoked Salmon & Crème Fraîche blend French and Russian culinary traditions. The gougères replace traditional buckwheat blinis while maintaining all the classic toppings - tangy crème fraîche, fresh dill, and beautifully formed salmon rosettes. The crispy, airy cheese puffs provide wonderful textural contrast to the creamy toppings. Each one is topped generously with crème fraîche, then garnished with a salmon rosette (made by rolling thin slices into flower shapes) and fresh dill. These are stunning to look at and absolutely delicious to eat. Perfect for brunch, cocktail parties, or any elegant gathering.",
    category: "Appetizers",
    subcategory: "Savory Pastries",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 30,
    totalTime: 65,
    servings: 24,
    rating: "4.9",
    calories: 96,
    protein: "4.0",
    carbs: "6.0",
    fat: "6.5",
    fiber: "0.5",
    sugar: "1.0",
    image: "/recipe-images/gluten-free-blini-style-gougeres-smoked-salmon-creme-fraiche.png",
    ingredients: [
      "1 cup water",
      "6 tablespoons butter",
      "1 teaspoon salt",
      "1 cup gluten-free flour blend",
      "4 eggs",
      "1 cup shredded Gruyère",
      "1.5 cups crème fraîche",
      "2 tablespoons lemon juice",
      "8 oz smoked salmon, thinly sliced",
      "Large bunch fresh dill",
      "Lemon zest for garnish",
      "Black pepper"
    ],
    instructions: [
      "Preheat oven to 425°F. Line baking sheets with parchment.",
      "Make choux pastry: Boil water, butter, and salt.",
      "Add flour all at once, stirring until dough forms ball.",
      "Cook 1-2 minutes over medium heat, stirring constantly.",
      "Transfer to bowl and cool 5 minutes.",
      "Beat in eggs one at a time until smooth and glossy.",
      "Fold in Gruyère.",
      "Pipe or spoon slightly flattened mounds onto baking sheets (blini-style shape).",
      "Bake 25-30 minutes until puffed and golden.",
      "Cool completely.",
      "Mix crème fraîche with lemon juice.",
      "Make salmon rosettes: Roll thin salmon slices into rose shapes.",
      "Top each gougère with generous dollop of lemon crème fraîche.",
      "Place salmon rosette on top of cream.",
      "Garnish with fresh dill sprig, lemon zest, and cracked black pepper.",
      "Serve immediately."
    ],
    tips: "Pipe gougères slightly flatter for blini shape. To make salmon rosettes, roll thin slices tightly then arrange petals. The presentation is key - arrange beautifully for maximum impact.",
    variations: [
      "Add sour cream to crème fraîche",
      "Include capers as garnish",
      "Top with red onion slivers"
    ],
    tags: ["gluten-free", "gougères", "blini-style", "smoked salmon", "crème fraîche", "french-russian", "elegant", "brunch", "appetizer", "beautiful"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Blini-Style Gougères with Smoked Salmon & Crème Fraîche - French-Russian Fusion",
    seoDescription: "Beautiful gluten-free cheese puffs topped like Russian blinis with crème fraîche and salmon rosettes. Elegant fusion appetizer."
  }
];

async function addGougereRecipes() {
  console.log("Adding 10 Gougères with Smoked Salmon recipes to database...");
  
  try {
    for (const recipe of gougereRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Gougères recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addGougereRecipes();
