import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const potatoCakeRecipes = [
  {
    title: "Gluten-Free Chocolate Potato Cake",
    slug: "gluten-free-chocolate-potato-cake",
    seoTitle: "Gluten-Free Chocolate Potato Cake - Rich & Moist Dessert",
    description: "Deeply moist and fudgy chocolate cake enriched with mashed potatoes and cocoa — topped with dark chocolate ganache.",
    longDescription: "This gluten-free chocolate potato cake is a revelation in baking — incredibly moist, rich, and deeply chocolatey, with the secret ingredient being smooth mashed potatoes. The potatoes add exceptional moisture and tenderness to the crumb without any potato flavor, creating a cake that stays fresh for days. Dark cocoa powder delivers intense chocolate flavor, while the addition of espresso powder enhances the chocolate notes. The cake is crowned with a glossy dark chocolate ganache that sets into a silky coating. This recipe has roots in European baking traditions where potatoes were used to extend flour and create ultra-tender cakes. Perfect for birthdays, special occasions, or any time you crave serious chocolate indulgence. The texture is somewhere between a fudge brownie and a classic chocolate cake — deeply satisfying and irresistibly decadent.",
    seoDescription: "Gluten-free chocolate potato cake with dark chocolate ganache. Ultra-moist, fudgy, and rich dessert made with mashed potatoes.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 25,
    cookTime: 45,
    totalTime: 70,
    servings: 12,
    difficulty: "Medium",
    rating: "4.8",
    image: "/recipe-images/gluten-free-chocolate-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled (about 2 medium potatoes)",
      "1½ cups gluten-free all-purpose flour blend",
      "¾ cup Dutch-process cocoa powder",
      "1½ teaspoons baking powder (gluten-free)",
      "1 teaspoon baking soda",
      "½ teaspoon salt",
      "1 teaspoon instant espresso powder",
      "1¾ cups granulated sugar",
      "3 large eggs, room temperature",
      "¾ cup vegetable oil or melted coconut oil",
      "1 cup buttermilk (or dairy-free alternative)",
      "2 teaspoons vanilla extract",
      "For ganache: 8 oz dark chocolate chips, ¾ cup heavy cream"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease and line two 9-inch round cake pans with parchment paper.",
      "Boil potatoes until tender, mash until completely smooth, and let cool to room temperature.",
      "In a large bowl, whisk together gluten-free flour, cocoa powder, baking powder, baking soda, salt, and espresso powder.",
      "In another bowl, beat sugar and eggs until light and fluffy, about 3 minutes.",
      "Beat in cooled mashed potatoes, oil, buttermilk, and vanilla until smooth.",
      "Gently fold dry ingredients into wet ingredients until just combined — do not overmix.",
      "Divide batter evenly between prepared pans.",
      "Bake for 35-45 minutes until a toothpick inserted in center comes out with just a few moist crumbs.",
      "Cool in pans for 15 minutes, then turn out onto wire racks to cool completely.",
      "For ganache: heat cream until just simmering, pour over chocolate chips, let sit 2 minutes, then stir until smooth.",
      "Let ganache cool to spreadable consistency, about 20 minutes.",
      "Place one cake layer on serving plate, spread with some ganache, top with second layer.",
      "Pour remaining ganache over top, letting it drip down the sides. Smooth with offset spatula.",
      "Garnish with chocolate shavings if desired. Refrigerate 30 minutes to set ganache before serving."
    ],
    tags: ["gluten-free", "chocolate cake", "potato cake", "dessert", "birthday cake", "ganache", "moist cake", "fudgy", "special occasion", "European baking"],
    nutrition: {
      calories: 420,
      protein: "6g",
      carbs: "52g",
      fat: "22g",
      fiber: "4g",
      sodium: "280mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Vanilla Bean Potato Cake",
    slug: "gluten-free-vanilla-bean-potato-cake",
    seoTitle: "Gluten-Free Vanilla Bean Potato Cake - Light & Buttery",
    description: "Light, buttery sponge with mashed potato for softness — finished with vanilla bean glaze and powdered sugar.",
    longDescription: "This gluten-free vanilla bean potato cake is pure elegance in its simplicity — a tender, buttery sponge cake made exceptionally soft with the addition of smooth mashed potatoes. Real vanilla bean paste creates beautiful vanilla specks throughout the cake while delivering authentic vanilla flavor that extract alone can't match. The potatoes work magic in this recipe, creating a crumb that's simultaneously light and moist, staying fresh for days without drying out. The cake is finished with a glossy vanilla bean glaze made from powdered sugar, milk, and more vanilla bean paste, then dusted with a snowy coating of powdered sugar. This is the perfect afternoon tea cake or elegant dessert for any occasion. Serve it with fresh berries, a dollop of whipped cream, or simply on its own with hot coffee or tea. The simplicity of the flavors allows the beautiful vanilla and tender texture to shine.",
    seoDescription: "Gluten-free vanilla bean potato cake with vanilla glaze. Light, buttery, and incredibly moist tea cake with real vanilla bean.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 20,
    cookTime: 40,
    totalTime: 60,
    servings: 10,
    difficulty: "Easy",
    rating: "4.9",
    image: "/recipe-images/gluten-free-vanilla-bean-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled and smooth",
      "2 cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon baking soda",
      "½ teaspoon salt",
      "¾ cup unsalted butter, softened",
      "1½ cups granulated sugar",
      "3 large eggs, room temperature",
      "2 tablespoons vanilla bean paste (or 1 tablespoon vanilla extract)",
      "¾ cup whole milk (or dairy-free milk)",
      "For glaze: 1½ cups powdered sugar, 3-4 tablespoons milk, 1 teaspoon vanilla bean paste",
      "Extra powdered sugar for dusting"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 10-inch bundt pan or tube pan thoroughly and dust with gluten-free flour.",
      "Prepare smooth mashed potatoes and cool to room temperature.",
      "In a medium bowl, whisk together gluten-free flour, baking powder, baking soda, and salt.",
      "In a large bowl, cream butter and sugar together until light and fluffy, about 4 minutes.",
      "Beat in eggs one at a time, mixing well after each addition.",
      "Mix in cooled mashed potatoes and vanilla bean paste until smooth.",
      "Alternately add dry ingredients and milk to the butter mixture, beginning and ending with dry ingredients. Mix until just combined.",
      "Pour batter into prepared pan and smooth the top.",
      "Bake for 40-50 minutes until golden and a toothpick inserted near center comes out clean.",
      "Cool in pan for 15 minutes, then invert onto wire rack to cool completely.",
      "For glaze: whisk together powdered sugar, milk, and vanilla bean paste until smooth and pourable.",
      "Drizzle glaze over cooled cake, letting it drip down the sides.",
      "Once glaze sets (about 20 minutes), dust with additional powdered sugar.",
      "Garnish with fresh vanilla pods if desired. Slice and serve with tea or coffee."
    ],
    tags: ["gluten-free", "vanilla cake", "potato cake", "dessert", "tea cake", "bundt cake", "vanilla bean", "elegant", "afternoon tea", "simple"],
    nutrition: {
      calories: 385,
      protein: "5g",
      carbs: "58g",
      fat: "16g",
      fiber: "2g",
      sodium: "240mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Strawberry Potato Cake with Cream Cheese Frosting",
    slug: "gluten-free-strawberry-potato-cake-cream-cheese",
    seoTitle: "Gluten-Free Strawberry Potato Cake - Fresh & Fruity Dessert",
    description: "Sweet and fruity — fresh strawberries folded into a potato-based batter, layered with tangy cream cheese frosting.",
    longDescription: "This gluten-free strawberry potato cake with cream cheese frosting is a celebration of fresh fruit and tender cake. Diced fresh strawberries are gently folded into a moist potato-enriched batter, creating pockets of sweet-tart fruit throughout. The mashed potatoes keep the cake incredibly soft and help retain moisture even as the strawberries release their juices during baking. The result is a cake with a beautiful light pink tint and bursts of strawberry flavor in every bite. Layers of tangy cream cheese frosting provide the perfect counterpoint to the sweet cake, while more fresh strawberry slices adorn the top for a stunning presentation. This is an ideal spring or summer dessert, perfect for birthdays, brunches, or any celebration. The combination of potato-enriched cake and strawberries creates a uniquely tender crumb that's hard to achieve with traditional cake recipes.",
    seoDescription: "Gluten-free strawberry potato cake with cream cheese frosting. Fresh strawberries in moist layers with tangy frosting.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 30,
    cookTime: 35,
    totalTime: 65,
    servings: 12,
    difficulty: "Medium",
    rating: "4.9",
    image: "/recipe-images/gluten-free-strawberry-potato-cake-cream-cheese.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2¼ cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon baking soda",
      "½ teaspoon salt",
      "¾ cup unsalted butter, softened",
      "1½ cups granulated sugar",
      "3 large eggs",
      "1 teaspoon vanilla extract",
      "½ cup buttermilk",
      "1½ cups fresh strawberries, diced small",
      "For frosting: 12 oz cream cheese softened, ½ cup butter softened, 4 cups powdered sugar, 1 teaspoon vanilla",
      "Fresh strawberries and mint for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease and line two 9-inch round cake pans with parchment paper.",
      "Prepare smooth mashed potatoes and cool completely.",
      "In a bowl, whisk together gluten-free flour, baking powder, baking soda, and salt.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 4 minutes.",
      "Beat in eggs one at a time, then mix in cooled mashed potatoes and vanilla.",
      "Alternately add dry ingredients and buttermilk, beginning and ending with dry ingredients.",
      "Gently fold in diced strawberries — do not overmix.",
      "Divide batter evenly between prepared pans.",
      "Bake for 30-35 minutes until toothpick inserted in center comes out clean (some strawberry moisture is okay).",
      "Cool in pans for 15 minutes, then turn out onto wire racks to cool completely.",
      "For frosting: beat cream cheese and butter until smooth. Gradually add powdered sugar and vanilla, beating until light and fluffy.",
      "Place one cake layer on serving plate, spread with generous layer of frosting.",
      "Top with second cake layer. Frost top and sides with remaining frosting.",
      "Decorate with fresh strawberry slices and mint leaves. Refrigerate until ready to serve.",
      "Best served slightly chilled. Store covered in refrigerator up to 4 days."
    ],
    tags: ["gluten-free", "strawberry cake", "potato cake", "cream cheese frosting", "layer cake", "spring dessert", "fresh fruit", "birthday cake", "summer", "celebration"],
    nutrition: {
      calories: 485,
      protein: "6g",
      carbs: "68g",
      fat: "23g",
      fiber: "2g",
      sodium: "310mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Blackberry & Lemon Potato Cake",
    slug: "gluten-free-blackberry-lemon-potato-cake",
    seoTitle: "Gluten-Free Blackberry Lemon Potato Cake - Summer Dessert",
    description: "Zesty lemon and tart blackberries baked into a soft crumb — perfect for summer desserts or brunch.",
    longDescription: "This gluten-free blackberry and lemon potato cake is a bright, refreshing dessert that captures the essence of summer. Fresh lemon zest and juice provide vibrant citrus flavor throughout the tender potato-enriched cake, while plump blackberries dot the batter, creating pockets of tart-sweet fruit that burst with flavor. The mashed potatoes ensure the cake stays incredibly moist even as it bakes with the fruit. A light lemon glaze drizzled over the top adds extra citrus punch and a beautiful glossy finish. The combination of lemon and blackberry is a classic pairing — the citrus brightens the berries while the berries add depth and complexity to the lemon. This cake is perfect for brunch gatherings, afternoon tea, or as a not-too-sweet dessert after a summer meal. The beautiful purple berries against the golden-yellow cake make for a stunning presentation.",
    seoDescription: "Gluten-free blackberry lemon potato cake. Fresh berries and citrus in a moist summer dessert perfect for brunch.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    difficulty: "Easy",
    rating: "4.7",
    image: "/recipe-images/gluten-free-blackberry-lemon-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2 cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon salt",
      "¾ cup unsalted butter, softened",
      "1½ cups granulated sugar",
      "3 large eggs",
      "Zest of 2 lemons",
      "¼ cup fresh lemon juice",
      "½ cup whole milk",
      "1½ cups fresh blackberries",
      "For glaze: 1 cup powdered sugar, 2-3 tablespoons lemon juice, 1 teaspoon lemon zest"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13-inch baking pan and line with parchment paper.",
      "Prepare smooth mashed potatoes and cool to room temperature.",
      "In a medium bowl, whisk together gluten-free flour, baking powder, and salt.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 4 minutes.",
      "Beat in eggs one at a time, then mix in cooled mashed potatoes.",
      "Add lemon zest and lemon juice, mixing until combined.",
      "Alternately add dry ingredients and milk, beginning and ending with dry ingredients.",
      "Gently fold in blackberries — be careful not to break them up too much.",
      "Pour batter into prepared pan and smooth the top.",
      "Bake for 40-45 minutes until golden and a toothpick inserted in center comes out clean.",
      "Cool in pan on wire rack for 15 minutes.",
      "For glaze: whisk together powdered sugar, lemon juice, and lemon zest until smooth.",
      "Drizzle glaze over warm cake. Let cool completely before cutting.",
      "Garnish with fresh blackberries and lemon zest. Serve at room temperature.",
      "Store covered at room temperature up to 3 days or refrigerated up to 5 days."
    ],
    tags: ["gluten-free", "blackberry cake", "lemon cake", "potato cake", "summer dessert", "brunch", "fruit cake", "citrus", "fresh berries", "tea cake"],
    nutrition: {
      calories: 395,
      protein: "5g",
      carbs: "61g",
      fat: "16g",
      fiber: "3g",
      sodium: "220mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Raspberry & White Chocolate Potato Cake",
    slug: "gluten-free-raspberry-white-chocolate-potato-cake",
    seoTitle: "Gluten-Free Raspberry White Chocolate Potato Cake - Indulgent Dessert",
    description: "Creamy, sweet, and slightly tart — raspberry swirls and white chocolate chunks create an indulgent texture.",
    longDescription: "This gluten-free raspberry and white chocolate potato cake is pure indulgence — tender cake studded with white chocolate chunks and ribboned with fresh raspberry swirls. The mashed potatoes create an incredibly soft, moist crumb that stays fresh for days, while the white chocolate adds creamy sweetness and the raspberries provide bright, tart balance. As the cake bakes, the white chocolate melts slightly, creating pockets of creamy richness, while the raspberries maintain their shape and deliver bursts of fruit flavor. A white chocolate drizzle on top adds elegance and extra sweetness. This cake is perfect for special occasions, Valentine's Day, or any time you want to impress with both flavor and presentation. The pink raspberry swirls against the white chocolate chunks make for a beautiful cross-section when sliced. It's a sophisticated dessert that feels luxurious while being naturally gluten-free.",
    seoDescription: "Gluten-free raspberry white chocolate potato cake. Indulgent dessert with fruit swirls and creamy chocolate chunks.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 12,
    difficulty: "Medium",
    rating: "4.8",
    image: "/recipe-images/gluten-free-raspberry-white-chocolate-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2¼ cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon baking soda",
      "½ teaspoon salt",
      "¾ cup unsalted butter, softened",
      "1¾ cups granulated sugar",
      "4 large eggs",
      "1 teaspoon vanilla extract",
      "¾ cup sour cream",
      "1 cup white chocolate chips or chunks",
      "1½ cups fresh raspberries",
      "For drizzle: ½ cup white chocolate chips, 2 tablespoons cream"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 10-inch bundt pan very well and dust with gluten-free flour.",
      "Prepare smooth mashed potatoes and cool completely.",
      "In a bowl, whisk together gluten-free flour, baking powder, baking soda, and salt.",
      "In a large bowl, cream butter and sugar until very light and fluffy, about 5 minutes.",
      "Beat in eggs one at a time, mixing well after each addition.",
      "Mix in cooled mashed potatoes and vanilla until smooth.",
      "Alternately add dry ingredients and sour cream, beginning and ending with dry ingredients.",
      "Fold in white chocolate chips.",
      "Pour half the batter into prepared bundt pan.",
      "Scatter half the raspberries over batter, gently pressing them in slightly.",
      "Pour remaining batter over raspberries, then top with remaining raspberries.",
      "Use a knife to gently swirl the raspberries through the batter — don't overmix.",
      "Bake for 50-60 minutes until golden and a toothpick inserted comes out clean (some chocolate is okay).",
      "Cool in pan for 20 minutes, then carefully invert onto wire rack to cool completely.",
      "For drizzle: melt white chocolate chips with cream, stirring until smooth. Drizzle over cooled cake.",
      "Garnish with fresh raspberries. Let drizzle set before serving, about 30 minutes."
    ],
    tags: ["gluten-free", "raspberry cake", "white chocolate", "potato cake", "bundt cake", "special occasion", "indulgent", "elegant", "dessert", "fruit"],
    nutrition: {
      calories: 445,
      protein: "6g",
      carbs: "59g",
      fat: "22g",
      fiber: "2g",
      sodium: "270mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Currant & Rhubarb Potato Cake with Streusel Topping",
    slug: "gluten-free-currant-rhubarb-potato-cake-streusel",
    seoTitle: "Gluten-Free Currant Rhubarb Potato Cake - Rustic Dessert",
    description: "Rustic tea cake featuring tangy rhubarb and currants, topped with a crunchy cinnamon oat streusel.",
    longDescription: "This gluten-free currant and rhubarb potato cake with streusel topping is a rustic, comforting dessert that celebrates traditional flavors with a modern twist. Tart rhubarb pieces and sweet dried currants are studded throughout the moist potato-enriched cake, creating a beautiful balance of sweet and tangy flavors. The mashed potatoes keep the cake tender even with the acidic rhubarb. A generous layer of crunchy cinnamon-oat streusel topping adds textural contrast and extra sweetness. This cake has roots in farmhouse and cottage baking traditions where potatoes were commonly used in cakes and breads. It's perfect for afternoon tea, spring brunch, or as a not-too-sweet dessert. The combination of rhubarb and currants is classic in European baking, and the streusel topping makes every slice feel special. Serve it warm with a scoop of vanilla ice cream or a dollop of whipped cream for the ultimate comfort dessert.",
    seoDescription: "Gluten-free currant rhubarb potato cake with streusel topping. Rustic tea cake with tart fruit and crunchy topping.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 25,
    cookTime: 55,
    totalTime: 80,
    servings: 12,
    difficulty: "Medium",
    rating: "4.7",
    image: "/recipe-images/gluten-free-currant-rhubarb-potato-cake-streusel.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2 cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon baking soda",
      "½ teaspoon salt",
      "1 teaspoon cinnamon",
      "¾ cup unsalted butter, softened",
      "1¼ cups granulated sugar",
      "3 large eggs",
      "1 teaspoon vanilla extract",
      "½ cup buttermilk",
      "1½ cups fresh rhubarb, diced",
      "½ cup dried currants",
      "For streusel: ¾ cup gluten-free oats, ½ cup gluten-free flour, ½ cup brown sugar, 1 teaspoon cinnamon, 6 tablespoons cold butter"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13-inch baking pan and line with parchment paper.",
      "Prepare smooth mashed potatoes and cool to room temperature.",
      "Make streusel: combine oats, flour, brown sugar, and cinnamon. Cut in cold butter until crumbly. Set aside.",
      "In a medium bowl, whisk together gluten-free flour, baking powder, baking soda, salt, and cinnamon.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 4 minutes.",
      "Beat in eggs one at a time, then mix in cooled mashed potatoes and vanilla.",
      "Alternately add dry ingredients and buttermilk, beginning and ending with dry ingredients.",
      "Fold in diced rhubarb and dried currants gently.",
      "Pour batter into prepared pan and smooth the top.",
      "Sprinkle streusel topping evenly over the batter.",
      "Bake for 50-55 minutes until a toothpick inserted in center comes out clean and streusel is golden.",
      "Cool in pan on wire rack for at least 20 minutes.",
      "Serve warm or at room temperature. Delicious with vanilla ice cream or whipped cream.",
      "Store covered at room temperature up to 3 days."
    ],
    tags: ["gluten-free", "rhubarb cake", "currant", "potato cake", "streusel topping", "rustic", "tea cake", "spring dessert", "farmhouse baking", "comfort food"],
    nutrition: {
      calories: 410,
      protein: "5g",
      carbs: "60g",
      fat: "18g",
      fiber: "3g",
      sodium: "260mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Rum & Amaretto Potato Cake",
    slug: "gluten-free-rum-amaretto-potato-cake",
    seoTitle: "Gluten-Free Rum Amaretto Potato Cake - Sophisticated Dessert",
    description: "Decadent, aromatic cake soaked in rum syrup and finished with amaretto glaze — rich and sophisticated.",
    longDescription: "This gluten-free rum and amaretto potato cake is a sophisticated, adult dessert that showcases the beautiful pairing of dark rum and almond-flavored amaretto liqueur. The potato-enriched cake itself is tender and buttery, providing the perfect canvas for the rum syrup that's brushed on while the cake is still warm. The syrup soaks into every crumb, creating incredible moisture and depth of flavor. An amaretto glaze is then drizzled over the top, adding another layer of almond complexity and a beautiful glossy finish. Crushed amaretti cookies garnish the top for textural contrast and visual appeal. This cake is inspired by Italian rum cakes and captures the essence of elegant European desserts. It's perfect for dinner parties, special celebrations, or any time you want to serve something truly special. The combination of potato-moistness with the aromatic liqueurs creates an unforgettable flavor experience.",
    seoDescription: "Gluten-free rum amaretto potato cake. Sophisticated dessert soaked in rum syrup with amaretto glaze.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 30,
    cookTime: 45,
    totalTime: 75,
    servings: 12,
    difficulty: "Medium",
    rating: "4.8",
    image: "/recipe-images/gluten-free-rum-amaretto-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2¼ cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon salt",
      "¾ teaspoon almond extract",
      "1 cup unsalted butter, softened",
      "1¾ cups granulated sugar",
      "4 large eggs",
      "1 teaspoon vanilla extract",
      "½ cup whole milk",
      "For rum syrup: ½ cup water, ½ cup sugar, ⅓ cup dark rum",
      "For amaretto glaze: 1½ cups powdered sugar, 3 tablespoons amaretto liqueur, 1-2 tablespoons milk",
      "Crushed amaretti cookies for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 10-inch bundt pan very thoroughly and dust with gluten-free flour.",
      "Prepare smooth mashed potatoes and cool completely.",
      "In a medium bowl, whisk together gluten-free flour, baking powder, and salt.",
      "In a large bowl, cream butter and sugar until very light and fluffy, about 5 minutes.",
      "Beat in eggs one at a time, mixing well after each addition.",
      "Mix in cooled mashed potatoes, vanilla extract, and almond extract until smooth.",
      "Alternately add dry ingredients and milk, beginning and ending with dry ingredients.",
      "Pour batter into prepared bundt pan and smooth the top.",
      "Bake for 40-45 minutes until golden and a toothpick inserted comes out clean.",
      "While cake bakes, make rum syrup: combine water and sugar in saucepan, bring to boil, remove from heat, stir in rum.",
      "When cake comes out of oven, immediately poke holes all over with a skewer.",
      "Slowly brush warm rum syrup all over the cake, letting it soak in. Use all the syrup.",
      "Cool cake in pan for 30 minutes, then invert onto serving plate.",
      "For glaze: whisk together powdered sugar, amaretto, and milk until smooth and pourable.",
      "Drizzle amaretto glaze over cooled cake. Garnish with crushed amaretti cookies.",
      "Let glaze set for 30 minutes before serving. Best served the same day."
    ],
    tags: ["gluten-free", "rum cake", "amaretto", "potato cake", "sophisticated", "adult dessert", "Italian-inspired", "special occasion", "bundt cake", "liqueur"],
    nutrition: {
      calories: 465,
      protein: "5g",
      carbs: "64g",
      fat: "18g",
      fiber: "1g",
      sodium: "190mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Carrot & Potato Spice Cake",
    slug: "gluten-free-carrot-potato-spice-cake",
    seoTitle: "Gluten-Free Carrot Potato Spice Cake - Moist & Flavorful",
    description: "Warmly spiced with cinnamon, nutmeg, and ginger — carrots and potatoes create incredible moisture and flavor depth.",
    longDescription: "This gluten-free carrot and potato spice cake is a marriage of two vegetable-based cake traditions, creating something truly special. Finely grated carrots and smooth mashed potatoes work together to produce a cake that's incredibly moist, tender, and packed with flavor. Warming spices — cinnamon, nutmeg, ginger, and a hint of cardamom — create an aromatic cake that fills your kitchen with the most wonderful fragrance as it bakes. The combination of carrots and potatoes means this cake stays fresh and moist for up to a week. Traditional cream cheese frosting with a hint of vanilla provides the perfect tangy-sweet complement. Chopped walnuts can be folded into the batter or sprinkled on top for extra crunch. This cake is perfect for fall and winter celebrations, holidays, or any time you crave the comforting flavors of spice cake. It's a sophisticated twist on classic carrot cake.",
    seoDescription: "Gluten-free carrot potato spice cake with cream cheese frosting. Ultra-moist with warming spices and vegetables.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 14,
    difficulty: "Medium",
    rating: "4.9",
    image: "/recipe-images/gluten-free-carrot-potato-spice-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2 cups finely grated carrots (about 3 medium carrots)",
      "2½ cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "1 teaspoon baking soda",
      "1 teaspoon salt",
      "2 teaspoons cinnamon",
      "1 teaspoon ground ginger",
      "½ teaspoon nutmeg",
      "¼ teaspoon cardamom",
      "1 cup vegetable oil",
      "1¾ cups brown sugar, packed",
      "4 large eggs",
      "2 teaspoons vanilla extract",
      "1 cup chopped walnuts (optional)",
      "For frosting: 12 oz cream cheese softened, ½ cup butter softened, 4 cups powdered sugar, 2 teaspoons vanilla"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease two 9-inch round cake pans and line with parchment paper.",
      "Prepare smooth mashed potatoes and cool completely. Finely grate carrots.",
      "In a large bowl, whisk together gluten-free flour, baking powder, baking soda, salt, and all spices.",
      "In another large bowl, whisk together oil and brown sugar until smooth.",
      "Beat in eggs one at a time, then mix in vanilla extract.",
      "Stir in cooled mashed potatoes and grated carrots until well combined.",
      "Gently fold dry ingredients into wet ingredients until just combined.",
      "Fold in chopped walnuts if using.",
      "Divide batter evenly between prepared pans.",
      "Bake for 45-50 minutes until a toothpick inserted in center comes out clean.",
      "Cool in pans for 15 minutes, then turn out onto wire racks to cool completely.",
      "For frosting: beat cream cheese and butter until smooth and fluffy.",
      "Gradually add powdered sugar and vanilla, beating until light and creamy.",
      "Place one cake layer on serving plate, spread with generous layer of frosting.",
      "Top with second layer, then frost top and sides with remaining frosting.",
      "Garnish with chopped walnuts if desired. Refrigerate until ready to serve.",
      "Store covered in refrigerator up to 5 days. Best served at room temperature."
    ],
    tags: ["gluten-free", "carrot cake", "potato cake", "spice cake", "cream cheese frosting", "fall dessert", "moist cake", "holiday", "celebration", "vegetable cake"],
    nutrition: {
      calories: 510,
      protein: "6g",
      carbs: "70g",
      fat: "25g",
      fiber: "3g",
      sodium: "380mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Coconut & Pineapple Potato Cake",
    slug: "gluten-free-coconut-pineapple-potato-cake",
    seoTitle: "Gluten-Free Coconut Pineapple Potato Cake - Tropical Dessert",
    description: "Tropical twist — mashed potatoes add fluffiness to this island-inspired dessert topped with toasted coconut.",
    longDescription: "This gluten-free coconut and pineapple potato cake brings tropical paradise to your dessert table. Sweet crushed pineapple and shredded coconut are folded into a fluffy potato-enriched batter, creating a cake that's incredibly moist and bursting with island flavors. The mashed potatoes work beautifully with the pineapple juice, creating a cake that stays tender and fresh for days. Toasted coconut flakes scattered on top add textural contrast and nutty flavor. This cake has the spirit of a piña colada in cake form — sweet pineapple, creamy coconut, and a hint of rum extract for that tropical vibe. It's perfect for summer gatherings, luau parties, or any time you want to escape to the tropics. The bright, cheerful flavors make everyone smile. Serve it as-is, with a simple cream cheese frosting, or topped with whipped cream and more fresh pineapple for an extra special presentation.",
    seoDescription: "Gluten-free coconut pineapple potato cake. Tropical dessert with moist cake, fruit, and toasted coconut topping.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 25,
    cookTime: 45,
    totalTime: 70,
    servings: 12,
    difficulty: "Easy",
    rating: "4.8",
    image: "/recipe-images/gluten-free-coconut-pineapple-potato-cake.png",
    ingredients: [
      "1 cup mashed potatoes, cooled",
      "2¼ cups gluten-free all-purpose flour blend",
      "2 teaspoons baking powder (gluten-free)",
      "½ teaspoon baking soda",
      "½ teaspoon salt",
      "¾ cup unsalted butter, softened",
      "1½ cups granulated sugar",
      "3 large eggs",
      "1 teaspoon vanilla extract",
      "½ teaspoon rum extract (or coconut extract)",
      "1 cup crushed pineapple with juice",
      "1 cup sweetened shredded coconut",
      "½ cup coconut milk",
      "1 cup toasted coconut flakes for topping",
      "Fresh pineapple wedges for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13-inch baking pan and line with parchment paper.",
      "Toast 1 cup coconut flakes in a dry skillet over medium heat until golden, stirring constantly. Set aside for topping.",
      "Prepare smooth mashed potatoes and cool to room temperature.",
      "In a medium bowl, whisk together gluten-free flour, baking powder, baking soda, and salt.",
      "In a large bowl, cream butter and sugar until light and fluffy, about 4 minutes.",
      "Beat in eggs one at a time, then mix in cooled mashed potatoes, vanilla extract, and rum extract.",
      "Stir in crushed pineapple with its juice.",
      "Alternately add dry ingredients and coconut milk, beginning and ending with dry ingredients.",
      "Fold in 1 cup shredded coconut.",
      "Pour batter into prepared pan and smooth the top.",
      "Bake for 40-45 minutes until golden and a toothpick inserted in center comes out clean.",
      "While cake is still warm, sprinkle toasted coconut flakes evenly over the top.",
      "Cool completely in pan on wire rack.",
      "Garnish with fresh pineapple wedges before serving.",
      "Store covered at room temperature up to 3 days. Can also serve with whipped cream or coconut cream."
    ],
    tags: ["gluten-free", "coconut cake", "pineapple cake", "potato cake", "tropical dessert", "summer", "island-inspired", "piña colada", "fruity", "party"],
    nutrition: {
      calories: 425,
      protein: "5g",
      carbs: "56g",
      fat: "21g",
      fiber: "2g",
      sodium: "250mg"
    },
    isNaturallyGlutenFree: false
  },
  {
    title: "Gluten-Free Chocolate Raspberry Potato Layer Cake",
    slug: "gluten-free-chocolate-raspberry-potato-layer-cake",
    seoTitle: "Gluten-Free Chocolate Raspberry Layer Cake - Elegant Showstopper",
    description: "Elegant showstopper — alternating layers of chocolate potato cake and raspberry cream filling.",
    longDescription: "This gluten-free chocolate raspberry potato layer cake is an absolute showstopper — three elegant layers of deeply chocolatey potato cake alternating with luscious raspberry cream filling, all covered in rich chocolate ganache. The potato-enriched chocolate layers are incredibly moist and tender with a fine crumb that holds up beautifully in this multi-layer construction. The raspberry cream filling is made with fresh raspberries folded into sweetened whipped cream with a hint of cream cheese for stability and tangy balance. Dark chocolate ganache coats the outside, creating a glossy, professional finish, while fresh raspberries cascade down the side for dramatic presentation. This is the cake you make for birthdays, anniversaries, or any celebration that deserves something extraordinary. The combination of chocolate and raspberry is timeless and elegant, and the addition of mashed potatoes ensures the cake stays incredibly moist for days. It looks like it came from a high-end bakery, but it's surprisingly achievable at home.",
    seoDescription: "Gluten-free chocolate raspberry potato layer cake. Elegant showstopper with three layers, cream filling, and ganache.",
    category: "Desserts",
    subcategory: "Gluten-Free Potato Cake",
    prepTime: 45,
    cookTime: 35,
    totalTime: 80,
    servings: 14,
    difficulty: "Hard",
    rating: "4.9",
    image: "/recipe-images/gluten-free-chocolate-raspberry-potato-layer-cake.png",
    ingredients: [
      "1½ cups mashed potatoes, cooled",
      "2 cups gluten-free all-purpose flour blend",
      "1 cup Dutch-process cocoa powder",
      "2 teaspoons baking powder (gluten-free)",
      "1½ teaspoons baking soda",
      "1 teaspoon salt",
      "2 cups granulated sugar",
      "4 large eggs",
      "1 cup vegetable oil",
      "1½ cups buttermilk",
      "2 teaspoons vanilla extract",
      "For filling: 2 cups heavy cream, ½ cup powdered sugar, 4 oz cream cheese softened, 1½ cups fresh raspberries",
      "For ganache: 12 oz dark chocolate, 1 cup heavy cream",
      "Fresh raspberries and cocoa powder for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease and line three 8-inch round cake pans with parchment paper.",
      "Prepare smooth mashed potatoes and cool completely.",
      "In a large bowl, whisk together gluten-free flour, cocoa powder, baking powder, baking soda, and salt.",
      "In another large bowl, whisk together sugar and eggs until light, about 2 minutes.",
      "Beat in cooled mashed potatoes, oil, buttermilk, and vanilla until smooth.",
      "Gently fold dry ingredients into wet ingredients until just combined.",
      "Divide batter evenly among three prepared pans.",
      "Bake for 30-35 minutes until toothpick inserted in center comes out with just a few moist crumbs.",
      "Cool in pans for 15 minutes, then turn out onto wire racks to cool completely.",
      "For filling: beat cream cheese until smooth. In separate bowl, whip heavy cream with powdered sugar to stiff peaks.",
      "Fold whipped cream into cream cheese gently. Carefully fold in 1 cup raspberries (reserve ½ cup for garnish).",
      "For ganache: heat cream until just simmering, pour over chocolate, let sit 2 minutes, then stir until smooth. Cool to spreadable consistency.",
      "To assemble: place one cake layer on serving plate, spread with half the raspberry cream.",
      "Top with second cake layer, spread with remaining raspberry cream.",
      "Top with third cake layer. Cover entire cake with chocolate ganache, smoothing with offset spatula.",
      "Arrange fresh raspberries on top and cascading down one side. Dust with cocoa powder.",
      "Refrigerate at least 1 hour before serving to set ganache. Store refrigerated up to 4 days."
    ],
    tags: ["gluten-free", "chocolate cake", "raspberry", "potato cake", "layer cake", "showstopper", "celebration", "birthday", "elegant", "special occasion"],
    nutrition: {
      calories: 560,
      protein: "7g",
      carbs: "65g",
      fat: "32g",
      fiber: "5g",
      sodium: "420mg"
    },
    isNaturallyGlutenFree: false
  }
];

async function addPotatoCakeRecipes() {
  try {
    console.log("🍰 Adding 10 Gluten-Free Potato Cake recipes to database...\n");

    for (const recipe of potatoCakeRecipes) {
      const recipeData = {
        id: nanoid(),
        ...recipe,
        status: "published" as const,
        createdAt: new Date(),
        updatedAt: new Date()
      };

      await db.insert(recipes).values(recipeData);
      console.log(`✅ Added: ${recipe.title}`);
    }

    console.log("\n🎉 Successfully added all 10 Gluten-Free Potato Cake recipes!");
    console.log("📊 Total recipes added: 10");
    console.log("🔍 Category: Desserts > Gluten-Free Potato Cake");
    
    process.exit(0);
  } catch (error) {
    console.error("❌ Error adding recipes:", error);
    process.exit(1);
  }
}

addPotatoCakeRecipes();
