import { db } from "../server/db";
import { recipes } from "../shared/schema";

const naughtyKnots = [
  {
    title: "Gluten-Free Naughty Knots with Garlic Butter & Parmesan",
    slug: "naughty-knots-garlic-butter-parmesan",
    description: "The classic — golden, soft knots brushed with garlicky butter and sprinkled with Parmesan and parsley.",
    longDescription: "These Gluten-Free Naughty Knots with Garlic Butter & Parmesan are the ultimate crowd-pleaser that brings the irresistible flavor of traditional garlic knots to your gluten-free table. Soft, pillowy gluten-free dough is rolled into strips, tied into beautiful knots, and baked until golden brown and perfectly crispy on the edges while remaining tender inside. As soon as they emerge from the oven, each knot is generously brushed with melted garlic butter infused with fresh minced garlic and a hint of Italian seasoning, then showered with grated Parmesan cheese and fresh parsley. The combination of buttery richness, aromatic garlic, salty cheese, and bright herbs creates an addictive flavor that makes these knots impossible to resist. They're perfect for serving alongside pasta, soups, or salads, or simply as a party appetizer that will disappear in minutes. The knot shape isn't just beautiful—it creates more surface area for that delicious garlic butter to cling to, ensuring maximum flavor in every bite.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 12,
    rating: "5.0",
    calories: 165,
    protein: "5.0",
    carbs: "22.0",
    fat: "7.0",
    fiber: "2.0",
    sugar: "2.0",
    image: "/recipe-images/naughty-knots-garlic-butter-parmesan.png",
    ingredients: [
      "1 lb gluten-free pizza dough (store-bought or homemade)",
      "4 tablespoons butter, melted",
      "4 cloves garlic, minced",
      "1/2 cup grated Parmesan cheese",
      "2 tablespoons fresh parsley, chopped",
      "1 teaspoon Italian seasoning",
      "1/2 teaspoon salt",
      "Olive oil for brushing"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper.",
      "Divide gluten-free dough into 12 equal pieces.",
      "Roll each piece into a rope about 6-8 inches long.",
      "Gently tie each rope into a simple knot, tucking ends underneath.",
      "Place knots on prepared baking sheet, spacing them 2 inches apart.",
      "Brush tops lightly with olive oil.",
      "Bake for 16-18 minutes until golden brown.",
      "While baking, mix melted butter with minced garlic and Italian seasoning.",
      "Remove knots from oven and immediately brush generously with garlic butter.",
      "Sprinkle with Parmesan cheese and fresh parsley.",
      "Serve warm."
    ],
    tips: "Don't pull the dough too tight when tying knots or they may break. If dough is sticky, lightly oil your hands. For extra garlic flavor, add roasted garlic to the butter. These are best served fresh but can be reheated at 350°F for 5 minutes.",
    variations: [
      "Add red pepper flakes for spicy garlic knots",
      "Use asiago cheese instead of Parmesan",
      "Mix in fresh basil with the parsley"
    ],
    tags: ["gluten-free", "naughty knots", "garlic knots", "appetizer", "bread", "party food", "garlic butter", "parmesan", "italian", "snack"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Garlic Butter Parmesan Naughty Knots - Classic Recipe",
    seoDescription: "Classic gluten-free garlic knots brushed with garlic butter and Parmesan. Perfect appetizer or side dish."
  },
  {
    title: "Gluten-Free Naughty Knots with Truffle Oil & Herbs",
    slug: "naughty-knots-truffle-oil-herbs",
    description: "Elevated and aromatic — infused with truffle oil, fresh rosemary, and sea salt.",
    longDescription: "These Gluten-Free Naughty Knots with Truffle Oil & Herbs are an elegant twist on classic garlic knots, perfect for upscale dinner parties and sophisticated entertaining. Soft gluten-free dough is shaped into beautiful knots and baked until golden, then drizzled with luxurious truffle oil that infuses each bite with earthy, aromatic flavor. Fresh rosemary needles are pressed into the dough before baking, releasing their piney fragrance as they crisp up in the oven. A finishing sprinkle of flaky sea salt enhances all the flavors and adds a delightful crunch. The combination of truffle and rosemary creates a gourmet experience that elevates these simple bread knots into something truly special. They pair wonderfully with Italian wines, creamy risottos, or elegant cheese boards. Despite their fancy flavor profile, these knots are surprisingly easy to make—the secret is using high-quality truffle oil and fresh herbs. They're sure to impress guests and make any meal feel like a special occasion.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 12,
    rating: "5.0",
    calories: 155,
    protein: "4.0",
    carbs: "23.0",
    fat: "6.0",
    fiber: "2.0",
    sugar: "1.0",
    image: "/recipe-images/naughty-knots-truffle-oil-herbs.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "3 tablespoons truffle oil",
      "2 tablespoons fresh rosemary, finely chopped",
      "1 tablespoon olive oil",
      "1 teaspoon flaky sea salt",
      "1/2 teaspoon black pepper",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line baking sheet with parchment.",
      "Divide dough into 12 equal portions.",
      "Roll each portion into a 7-inch rope.",
      "Tie into knots, tucking ends under.",
      "Brush knots with olive oil and press chopped rosemary into surface.",
      "Arrange on baking sheet with space between each.",
      "Bake for 16-18 minutes until golden.",
      "Remove from oven and immediately drizzle with truffle oil.",
      "Sprinkle with flaky sea salt and black pepper.",
      "Garnish with fresh rosemary sprigs.",
      "Serve warm for best truffle aroma."
    ],
    tips: "Use white truffle oil for more delicate flavor or black truffle oil for stronger taste. Fresh rosemary is essential—dried won't provide the same impact. Store in airtight container and reheat gently to preserve truffle flavor.",
    variations: [
      "Add grated Pecorino Romano cheese",
      "Mix in fresh thyme with rosemary",
      "Drizzle with truffle honey for sweet-savory twist"
    ],
    tags: ["gluten-free", "naughty knots", "truffle", "rosemary", "gourmet", "elegant", "appetizer", "bread", "herbs", "sophisticated"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Truffle Oil Herb Naughty Knots - Gourmet Recipe",
    seoDescription: "Elegant gluten-free bread knots with truffle oil and fresh rosemary. Sophisticated appetizer for entertaining."
  },
  {
    title: "Gluten-Free Cheddar & Jalapeño Naughty Knots",
    slug: "naughty-knots-cheddar-jalapeno",
    description: "Bold and cheesy — shredded cheddar and diced jalapeños baked inside and brushed with garlic butter.",
    longDescription: "These Gluten-Free Cheddar & Jalapeño Naughty Knots pack a flavorful punch with sharp cheddar cheese and spicy jalapeños baked right into the dough. Soft gluten-free dough is mixed with shredded sharp cheddar and diced fresh jalapeños before being shaped into beautiful knots. As they bake, the cheese melts into pockets of gooey goodness while the jalapeños soften and release their heat throughout the knot. After baking, each knot is brushed with garlic butter for an extra layer of savory flavor. The result is a spicy, cheesy, buttery bite that's perfect for game day, parties, or any time you want something with bold flavor. The heat level is customizable—use fewer jalapeños for mild spice or keep the seeds in for extra kick. These knots are fantastic on their own but also pair wonderfully with ranch dressing, sour cream, or a cold beer. They're addictive little bundles of cheesy, spicy deliciousness that will have everyone coming back for more.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 20,
    totalTime: 50,
    servings: 12,
    rating: "5.0",
    calories: 190,
    protein: "7.0",
    carbs: "21.0",
    fat: "9.0",
    fiber: "2.0",
    sugar: "2.0",
    image: "/recipe-images/naughty-knots-cheddar-jalapeno.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "1 cup sharp cheddar cheese, shredded",
      "2-3 jalapeños, seeded and diced",
      "3 tablespoons butter, melted",
      "2 cloves garlic, minced",
      "1/4 teaspoon cayenne pepper (optional)",
      "Salt to taste"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheet with parchment.",
      "Knead shredded cheddar and diced jalapeños into the dough until evenly distributed.",
      "Divide dough into 12 equal pieces.",
      "Roll each piece into a rope, being careful not to tear dough around cheese.",
      "Tie each rope into a knot.",
      "Place knots on prepared baking sheet.",
      "Bake for 18-20 minutes until golden and cheese is melted.",
      "Mix melted butter with minced garlic and cayenne if using.",
      "Brush hot knots with garlic butter.",
      "Sprinkle with additional cheddar if desired.",
      "Serve warm for maximum cheese pull."
    ],
    tips: "Remove jalapeño seeds for milder heat. Use extra-sharp cheddar for more intense flavor. If dough becomes sticky from cheese, lightly flour your hands. Best served immediately while cheese is melty.",
    variations: [
      "Add cooked bacon bits to the dough",
      "Use pepper jack cheese for extra spice",
      "Top with pickled jalapeño slices after baking"
    ],
    tags: ["gluten-free", "naughty knots", "cheddar", "jalapeño", "spicy", "cheesy", "appetizer", "party food", "game day", "bread"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cheddar Jalapeño Naughty Knots - Spicy Cheesy Recipe",
    seoDescription: "Bold gluten-free bread knots with cheddar cheese and jalapeños. Perfect spicy party appetizer."
  },
  {
    title: "Gluten-Free Cinnamon Sugar Naughty Knots",
    slug: "naughty-knots-cinnamon-sugar",
    description: "Sweet twist — rolled in cinnamon sugar and finished with vanilla glaze for dessert-style knots.",
    longDescription: "These Gluten-Free Cinnamon Sugar Naughty Knots transform savory bread knots into a delightful sweet treat that's perfect for breakfast, brunch, or dessert. Soft gluten-free dough is shaped into beautiful knots, brushed with melted butter, and generously coated in a cinnamon-sugar mixture before baking. As they bake, the sugar caramelizes slightly, creating a sweet, crispy exterior while the inside stays soft and tender. Once cooled slightly, the knots are drizzled with a simple vanilla glaze made from powdered sugar, vanilla extract, and milk, adding an extra layer of sweetness and visual appeal. The combination of warm cinnamon, sweet sugar, and vanilla creates a flavor reminiscent of cinnamon rolls but in a fun, pull-apart format. These are fantastic for holiday brunches, kids' parties, or coffee gatherings. They're like portable cinnamon rolls that don't require any fussing with yeast rising times. Serve them warm for the best experience—the aroma alone will have everyone gathering around the table.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    servings: 12,
    rating: "5.0",
    calories: 175,
    protein: "3.0",
    carbs: "28.0",
    fat: "6.0",
    fiber: "1.0",
    sugar: "12.0",
    image: "/recipe-images/naughty-knots-cinnamon-sugar.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "4 tablespoons butter, melted",
      "1/2 cup granulated sugar",
      "2 teaspoons cinnamon",
      "1 cup powdered sugar",
      "2 tablespoons milk",
      "1/2 teaspoon vanilla extract"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheet with parchment.",
      "Mix granulated sugar and cinnamon in a shallow bowl.",
      "Divide dough into 12 pieces and roll into ropes.",
      "Tie each rope into a knot.",
      "Brush each knot generously with melted butter.",
      "Roll knots in cinnamon-sugar mixture to coat completely.",
      "Place on baking sheet with space between each.",
      "Bake for 13-15 minutes until golden.",
      "While baking, whisk together powdered sugar, milk, and vanilla to make glaze.",
      "Let knots cool for 5 minutes.",
      "Drizzle with vanilla glaze.",
      "Serve warm or at room temperature."
    ],
    tips: "Make sure knots are well-coated with butter so cinnamon sugar adheres. Adjust glaze consistency by adding more milk or powdered sugar. For extra indulgence, add cream cheese to the glaze. These are best enjoyed fresh.",
    variations: [
      "Add cardamom to cinnamon sugar for chai flavor",
      "Drizzle with caramel instead of vanilla glaze",
      "Mix in orange zest with the cinnamon sugar"
    ],
    tags: ["gluten-free", "naughty knots", "cinnamon sugar", "sweet", "dessert", "breakfast", "brunch", "vanilla glaze", "pastry", "treat"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cinnamon Sugar Naughty Knots - Sweet Treat Recipe",
    seoDescription: "Sweet gluten-free cinnamon sugar knots with vanilla glaze. Perfect for breakfast or dessert."
  },
  {
    title: "Gluten-Free Naughty Knots with Browned Butter & Sage",
    slug: "naughty-knots-browned-butter-sage",
    description: "Rich, nutty browned butter and crispy sage leaves turn these into elegant dinner companions.",
    longDescription: "These Gluten-Free Naughty Knots with Browned Butter & Sage are sophisticated dinner rolls that showcase the magic of browned butter. The process of browning butter transforms ordinary melted butter into something extraordinary—it develops a rich, nutty aroma and complex flavor that elevates everything it touches. Fresh sage leaves are crisped in the browned butter, becoming fragrant and adding their earthy, slightly peppery notes to the mix. Soft gluten-free dough knots are baked until golden, then immediately brushed with this aromatic browned butter sage mixture. The result is a bread that's worthy of fine dining but easy enough for home cooks to master. The nutty butter soaks into the warm bread while the crispy sage leaves provide textural contrast. These knots are perfect alongside roasted meats, fall soups, or Thanksgiving dinner. They bring an upscale restaurant quality to your table with surprisingly simple techniques. The key is watching the butter carefully as it browns—it can go from perfect to burned quickly.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 12,
    rating: "5.0",
    calories: 160,
    protein: "4.0",
    carbs: "22.0",
    fat: "7.0",
    fiber: "2.0",
    sugar: "1.0",
    image: "/recipe-images/naughty-knots-browned-butter-sage.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "6 tablespoons butter",
      "15-20 fresh sage leaves",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "Olive oil for brushing"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line baking sheet with parchment.",
      "Divide dough into 12 pieces and shape into knots.",
      "Brush lightly with olive oil and place on baking sheet.",
      "Bake for 16-18 minutes until golden.",
      "While knots bake, melt butter in light-colored skillet over medium heat.",
      "Add sage leaves and cook, swirling pan, until butter turns golden brown and smells nutty (3-4 minutes).",
      "Remove from heat immediately.",
      "Remove knots from oven and brush generously with browned butter.",
      "Top each knot with a crispy sage leaf.",
      "Season with salt and pepper.",
      "Serve immediately while warm."
    ],
    tips: "Watch butter carefully—it goes from browned to burned quickly. Use a light-colored pan so you can see the butter color changing. Sage leaves will crisp up as the butter browns. These are best served fresh for maximum flavor and aroma.",
    variations: [
      "Add garlic cloves to brown with the butter",
      "Mix in fresh thyme with the sage",
      "Finish with grated Parmesan cheese"
    ],
    tags: ["gluten-free", "naughty knots", "browned butter", "sage", "gourmet", "elegant", "bread", "dinner rolls", "thanksgiving", "sophisticated"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Browned Butter Sage Naughty Knots - Gourmet Recipe",
    seoDescription: "Elegant gluten-free bread knots with nutty browned butter and crispy sage. Perfect dinner rolls."
  },
  {
    title: "Gluten-Free Naughty Knots with Mozzarella & Marinara Dip",
    slug: "naughty-knots-mozzarella-marinara",
    description: "Pull-apart cheesy knots served with a side of warm marinara — perfect for parties.",
    longDescription: "These Gluten-Free Naughty Knots with Mozzarella & Marinara Dip are the ultimate party appetizer that combines the best of pizza flavors in a fun, shareable format. Soft gluten-free dough is stuffed with gooey mozzarella cheese, shaped into knots, and baked until golden brown with the cheese melted and stretchy inside. Each knot is brushed with garlic herb butter and sprinkled with Italian seasoning for authentic pizza flavor. The real magic happens when you serve these hot from the oven with a bowl of warm marinara sauce in the center for dipping. As you pull a knot apart, the melted mozzarella stretches into long, Instagram-worthy cheese pulls that make these irresistible. They're like deconstructed pizza in the most fun format possible. Perfect for game day, movie nights, or any gathering where you want crowd-pleasing finger food. Kids and adults alike go crazy for these cheesy, dippable knots. Serve them hot and watch them disappear in minutes as everyone fights over the cheesiest ones.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 20,
    totalTime: 50,
    servings: 12,
    rating: "5.0",
    calories: 195,
    protein: "8.0",
    carbs: "23.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "3.0",
    image: "/recipe-images/naughty-knots-mozzarella-marinara.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "8 oz mozzarella cheese, cut into small cubes",
      "3 tablespoons butter, melted",
      "2 cloves garlic, minced",
      "1 teaspoon Italian seasoning",
      "1 1/2 cups marinara sauce, warmed",
      "Fresh basil for garnish",
      "Grated Parmesan for topping"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheet with parchment.",
      "Divide dough into 12 equal pieces.",
      "Flatten each piece slightly and place a cube of mozzarella in center.",
      "Wrap dough around cheese and roll into a rope.",
      "Tie into a knot, ensuring cheese is sealed inside.",
      "Place knots on baking sheet.",
      "Mix melted butter with minced garlic and Italian seasoning.",
      "Brush knots with garlic butter mixture.",
      "Bake for 18-20 minutes until golden and cheese is melted.",
      "Warm marinara sauce.",
      "Brush knots with remaining garlic butter.",
      "Serve hot with warm marinara in center bowl for dipping.",
      "Garnish with fresh basil and Parmesan."
    ],
    tips: "Seal cheese completely inside dough to prevent leaking. If cheese escapes during baking, it will still taste great. Use fresh mozzarella for best cheese pull. These must be served hot for maximum cheese stretchiness.",
    variations: [
      "Add pepperoni pieces with the mozzarella",
      "Mix in Italian sausage crumbles",
      "Use pesto instead of marinara for dipping"
    ],
    tags: ["gluten-free", "naughty knots", "mozzarella", "marinara", "cheesy", "pizza flavored", "party food", "appetizer", "dipping", "game day"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Mozzarella Marinara Naughty Knots - Party Appetizer",
    seoDescription: "Cheesy gluten-free bread knots with mozzarella and marinara dip. Perfect party appetizer."
  },
  {
    title: "Gluten-Free Naughty Knots with Hot Honey & Red Pepper Flakes",
    slug: "naughty-knots-hot-honey",
    description: "Sweet heat — brushed with hot honey and topped with chili flakes for a spicy-sweet glaze.",
    longDescription: "These Gluten-Free Naughty Knots with Hot Honey & Red Pepper Flakes deliver an addictive combination of sweet, spicy, and savory that will have you reaching for more. Soft gluten-free dough knots are baked until golden and crispy, then brushed with melted butter before being drizzled generously with hot honey—a mixture of pure honey infused with red pepper flakes and cayenne that provides the perfect balance of sweet and heat. An extra sprinkle of red pepper flakes on top adds visual appeal and allows heat lovers to get an extra kick in certain bites. The contrast between the slightly sweet bread, the hot honey glaze, and the spicy pepper flakes creates a complex flavor profile that's both sophisticated and crave-worthy. These knots are fantastic as an appetizer with cocktails, as a side to spicy dishes, or even as a unique addition to a brunch spread. The heat level is customizable—start with less cayenne and add more to taste. They pair wonderfully with cold beer, sparkling wine, or iced tea.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 12,
    rating: "5.0",
    calories: 170,
    protein: "4.0",
    carbs: "25.0",
    fat: "6.0",
    fiber: "2.0",
    sugar: "8.0",
    image: "/recipe-images/naughty-knots-hot-honey.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "1/3 cup honey",
      "1 teaspoon red pepper flakes, plus more for topping",
      "1/4 teaspoon cayenne pepper",
      "3 tablespoons butter, melted",
      "1/4 teaspoon salt",
      "Fresh thyme for garnish (optional)"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line baking sheet with parchment.",
      "Make hot honey: Heat honey in small saucepan with 1 teaspoon red pepper flakes and cayenne. Simmer 2 minutes, then remove from heat and let steep.",
      "Divide dough into 12 pieces and shape into knots.",
      "Place on baking sheet and bake for 16-18 minutes until golden.",
      "Remove from oven and brush with melted butter.",
      "Drizzle generously with hot honey.",
      "Sprinkle with additional red pepper flakes.",
      "Garnish with fresh thyme if desired.",
      "Serve warm for best flavor."
    ],
    tips: "Adjust heat by varying amount of cayenne and red pepper flakes. Hot honey can be made ahead and stored for up to a month. For milder version, use less cayenne. Serve these warm for the best contrast between hot and sweet.",
    variations: [
      "Add a squeeze of lime juice for brightness",
      "Mix in fresh jalapeño slices",
      "Brush with chili oil before hot honey for extra heat"
    ],
    tags: ["gluten-free", "naughty knots", "hot honey", "spicy", "sweet", "appetizer", "bread", "red pepper flakes", "heat", "bold"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Hot Honey Naughty Knots - Spicy Sweet Recipe",
    seoDescription: "Gluten-free bread knots with hot honey and red pepper flakes. Sweet and spicy appetizer."
  },
  {
    title: "Gluten-Free Naughty Knots with Everything Bagel Seasoning",
    slug: "naughty-knots-everything-bagel",
    description: "Savory and trendy — coated with everything seasoning and brushed with olive oil.",
    longDescription: "These Gluten-Free Naughty Knots with Everything Bagel Seasoning bring the iconic flavor of New York bagels to a fun, pull-apart bread format. Soft gluten-free dough is shaped into beautiful knots, brushed with olive oil, and generously coated with everything bagel seasoning—a savory blend of sesame seeds, poppy seeds, dried garlic, dried onion, and flaky salt. As they bake, the seeds toast and the garlic and onion become fragrant, creating an irresistible aroma. The olive oil helps the seasonings adhere and adds richness while keeping the knots tender. These are perfect for brunch spreads, served alongside cream cheese or lox, or as a savory snack any time of day. They have all the satisfying flavor of an everything bagel without the need for boiling or lengthy preparation. Kids and adults love the fun shape and familiar seasoning blend. Serve them warm from the oven or at room temperature—they're delicious either way and make great lunch box additions or after-school snacks.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 12,
    rating: "5.0",
    calories: 155,
    protein: "5.0",
    carbs: "23.0",
    fat: "5.0",
    fiber: "2.0",
    sugar: "1.0",
    image: "/recipe-images/naughty-knots-everything-bagel.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "3 tablespoons olive oil",
      "3 tablespoons everything bagel seasoning",
      "1 egg white, beaten (optional for extra shine)",
      "Cream cheese for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line baking sheet with parchment.",
      "Divide dough into 12 equal pieces.",
      "Roll each piece into a rope about 7 inches long.",
      "Tie into knots and place on baking sheet.",
      "Brush each knot generously with olive oil (or egg white for shinier finish).",
      "Sprinkle liberally with everything bagel seasoning, pressing gently to adhere.",
      "Bake for 16-18 minutes until golden brown.",
      "Remove from oven and brush with a bit more olive oil if desired.",
      "Serve warm or at room temperature.",
      "Optional: serve with cream cheese for spreading."
    ],
    tips: "Press seasoning gently into dough so it sticks during baking. Use store-bought everything seasoning or make your own blend. For shinier knots, use egg white instead of olive oil before adding seasoning. These keep well for 2-3 days in an airtight container.",
    variations: [
      "Make your own everything seasoning with custom ratios",
      "Add dried dill to the seasoning blend",
      "Serve with flavored cream cheese (chive, veggie, lox)"
    ],
    tags: ["gluten-free", "naughty knots", "everything bagel", "savory", "bread", "appetizer", "brunch", "snack", "sesame", "trendy"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Everything Bagel Naughty Knots - Savory Recipe",
    seoDescription: "Gluten-free bread knots with everything bagel seasoning. Perfect savory snack or brunch item."
  },
  {
    title: "Gluten-Free Naughty Knots with Pesto & Parmesan",
    slug: "naughty-knots-pesto-parmesan",
    description: "Italian-inspired — swirled with basil pesto, baked golden, and topped with extra cheese.",
    longDescription: "These Gluten-Free Naughty Knots with Pesto & Parmesan are bursting with fresh Italian flavors from vibrant basil pesto and salty Parmesan cheese. Gluten-free dough is rolled out, generously spread with homemade or store-bought basil pesto, then rolled up and cut into portions that are shaped into beautiful knots. As they bake, the pesto swirls throughout the bread, infusing every bite with the flavors of fresh basil, garlic, pine nuts, and Parmesan. After baking, the knots are brushed with olive oil and topped with additional grated Parmesan and fresh basil for maximum impact. The green swirls of pesto make these visually stunning, while the aroma as they bake is absolutely intoxicating. They're perfect alongside Italian dinners, served with soup or salad, or as a standalone appetizer. The pesto keeps the knots moist and flavorful, and the Parmesan adds a salty, umami punch. These are sophisticated enough for dinner parties but simple enough for weeknight meals.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 12,
    rating: "5.0",
    calories: 180,
    protein: "6.0",
    carbs: "22.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "2.0",
    image: "/recipe-images/naughty-knots-pesto-parmesan.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "1/2 cup basil pesto",
      "1/2 cup grated Parmesan cheese, divided",
      "2 tablespoons olive oil",
      "Fresh basil leaves for garnish",
      "Pine nuts for garnish (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheet with parchment.",
      "Roll dough into rectangle about 1/4 inch thick.",
      "Spread pesto evenly over dough, leaving 1/2 inch border.",
      "Sprinkle with 1/4 cup Parmesan.",
      "Roll up tightly from long side.",
      "Cut into 12 equal pieces.",
      "Gently stretch each piece and tie into a loose knot.",
      "Place on baking sheet.",
      "Bake for 16-18 minutes until golden.",
      "Brush with olive oil.",
      "Top with remaining Parmesan, fresh basil, and pine nuts if using.",
      "Serve warm."
    ],
    tips: "Use high-quality pesto for best flavor—homemade is ideal. Don't overfill or knots may unravel. If dough is too sticky, dust lightly with gluten-free flour. These are best served warm but also delicious at room temperature.",
    variations: [
      "Use sun-dried tomato pesto instead of basil",
      "Add mozzarella with the Parmesan for extra cheese",
      "Mix in chopped olives with the pesto"
    ],
    tags: ["gluten-free", "naughty knots", "pesto", "parmesan", "italian", "basil", "bread", "appetizer", "savory", "herbs"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pesto Parmesan Naughty Knots - Italian Recipe",
    seoDescription: "Italian-inspired gluten-free bread knots with basil pesto and Parmesan. Delicious appetizer."
  },
  {
    title: "Gluten-Free Naughty Knots with Maple Butter & Sea Salt",
    slug: "naughty-knots-maple-butter",
    description: "Sweet-savory perfection — coated in maple butter glaze and lightly salted for balance.",
    longDescription: "These Gluten-Free Naughty Knots with Maple Butter & Sea Salt strike the perfect balance between sweet and savory, making them irresistible at any time of day. Soft gluten-free dough is shaped into knots and baked until golden, then brushed liberally with maple butter—a heavenly mixture of real butter and pure maple syrup that creates a glossy, sweet glaze. A sprinkle of flaky sea salt on top provides the perfect counterpoint to the sweetness, enhancing all the flavors and adding textural interest. The combination is reminiscent of salted caramel but with the warm, earthy sweetness of maple. These knots are perfect for brunch alongside bacon and eggs, as a unique side to roasted meats, or even as a sweet treat with afternoon coffee. The maple butter soaks into the warm bread, making each bite rich and flavorful. They're especially popular during fall and winter when maple flavors feel particularly cozy and appropriate. Kids love the sweet glaze while adults appreciate the sophisticated sweet-salty balance.",
    category: "Appetizers",
    subcategory: "Breads & Holiday Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 12,
    rating: "5.0",
    calories: 185,
    protein: "4.0",
    carbs: "26.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "7.0",
    image: "/recipe-images/naughty-knots-maple-butter.png",
    ingredients: [
      "1 lb gluten-free pizza dough",
      "5 tablespoons butter, melted",
      "3 tablespoons pure maple syrup",
      "1 teaspoon flaky sea salt",
      "1/4 teaspoon cinnamon (optional)"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line baking sheet with parchment.",
      "Divide dough into 12 equal pieces.",
      "Roll each piece into a rope and tie into a knot.",
      "Place knots on prepared baking sheet.",
      "Bake for 16-18 minutes until golden brown.",
      "While baking, mix melted butter with maple syrup and cinnamon if using.",
      "Remove knots from oven and immediately brush generously with maple butter.",
      "Sprinkle with flaky sea salt.",
      "Let sit for 2-3 minutes to allow maple butter to soak in.",
      "Serve warm for best flavor."
    ],
    tips: "Use pure maple syrup, not pancake syrup, for authentic flavor. Flaky sea salt works best—table salt will be too intense. Brush maple butter on while knots are hot so it soaks in. These are best enjoyed fresh but can be reheated.",
    variations: [
      "Add a pinch of cayenne for sweet-spicy-salty combo",
      "Mix in vanilla extract with the maple butter",
      "Top with chopped pecans or walnuts"
    ],
    tags: ["gluten-free", "naughty knots", "maple", "sweet and savory", "butter", "sea salt", "bread", "brunch", "breakfast", "fall"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Maple Butter Naughty Knots - Sweet Savory Recipe",
    seoDescription: "Gluten-free bread knots with maple butter and sea salt. Perfect sweet-savory treat."
  }
];

async function seed() {
  console.log("Adding 10 gluten-free naughty knot recipes...");

  await db.insert(recipes).values(naughtyKnots).onConflictDoNothing();

  console.log("Successfully added naughty knot recipes!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Error seeding naughty knots:", error);
  process.exit(1);
});
