import { db } from "../server/db";
import { recipes } from "../shared/schema";

const sweetPotatoCrescentBites = [
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Brown Sugar & Pecans",
    slug: "gluten-free-sweet-potato-crescent-bites-brown-sugar-pecans",
    description: "Classic holiday favorite — mashed sweet potato with brown sugar, butter, and toasted pecans wrapped in flaky gluten-free crescent dough.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Brown Sugar & Pecans are a delightful twist on the classic holiday sweet potato casserole. Each bite features velvety mashed sweet potato mixed with rich brown sugar and butter, all wrapped in tender, flaky gluten-free crescent dough. The toasted pecans add a wonderful nutty crunch and depth of flavor that perfectly complements the sweet potato filling. As they bake, the dough becomes golden and crispy while the filling stays creamy and comforting. These bites are perfect for Thanksgiving gatherings, holiday parties, or any time you want to serve an impressive yet easy appetizer. The combination of sweet, nutty, and buttery flavors makes them irresistible to guests of all ages.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "5.0",
    calories: 145,
    protein: "2.5",
    carbs: "18.0",
    fat: "7.5",
    fiber: "2.0",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-brown-sugar-pecans.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato (about 1 large sweet potato)",
      "3 tablespoons brown sugar",
      "2 tablespoons butter, melted",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon nutmeg",
      "1/2 cup pecans, toasted and chopped",
      "1/4 teaspoon salt",
      "1 egg, beaten (for egg wash)",
      "2 tablespoons turbinado sugar for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, mix mashed sweet potato, brown sugar, melted butter, cinnamon, nutmeg, and salt until well combined.",
      "Fold in chopped toasted pecans.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato mixture at the wide end of each triangle.",
      "Roll up each triangle starting from the wide end, enclosing the filling.",
      "Place on prepared baking sheet, seam side down.",
      "Brush each crescent with beaten egg and sprinkle with turbinado sugar.",
      "Bake for 16-18 minutes until golden brown and flaky.",
      "Let cool 5 minutes before serving."
    ],
    tips: "Keep crescent dough chilled until ready to use for easier handling. Toast pecans in a dry skillet for 3-4 minutes to enhance their flavor. These can be assembled up to 24 hours ahead and refrigerated before baking.",
    variations: [
      "Add a drizzle of maple syrup after baking",
      "Use walnuts instead of pecans",
      "Include a pinch of ground ginger for extra warmth"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "appetizer", "holiday", "thanksgiving", "pecans", "brown sugar", "party food", "fall"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Brown Sugar & Pecans - Holiday Appetizer",
    seoDescription: "Delicious gluten-free sweet potato crescent bites with brown sugar and toasted pecans. Perfect holiday appetizer for Thanksgiving and festive gatherings."
  },
  {
    title: "Gluten-Free Savory Sweet Potato Crescent Bites with Goat Cheese & Sage",
    slug: "gluten-free-savory-sweet-potato-crescent-bites-goat-cheese-sage",
    description: "Elegant and aromatic — sweet potato mash paired with tangy goat cheese and crispy sage wrapped in flaky dough.",
    longDescription: "These Gluten-Free Savory Sweet Potato Crescent Bites with Goat Cheese & Sage are an elegant appetizer that balances sweet and savory flavors beautifully. The creamy sweet potato filling is enhanced with tangy goat cheese that adds richness and a pleasant tanginess. Fresh sage leaves are crisped in butter and mixed into the filling, providing an aromatic, earthy flavor that complements the sweetness of the potato. Each bite is wrapped in tender gluten-free crescent dough and baked until golden and flaky. These sophisticated bites are perfect for wine tastings, cocktail parties, or as an elegant starter for holiday dinners. The combination of flavors is refined yet comforting, making them a memorable addition to any gathering.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 16,
    rating: "4.9",
    calories: 138,
    protein: "3.5",
    carbs: "16.0",
    fat: "7.0",
    fiber: "1.8",
    sugar: "3.5",
    image: "/recipe-images/gluten-free-savory-sweet-potato-crescent-bites-goat-cheese-sage.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "4 oz goat cheese, softened",
      "12 fresh sage leaves",
      "2 tablespoons butter",
      "1/4 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/8 teaspoon garlic powder",
      "1 egg, beaten (for egg wash)",
      "Flaky sea salt for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a small skillet, melt butter over medium heat. Add sage leaves and cook 2-3 minutes until crispy. Remove and chop finely.",
      "In a bowl, combine mashed sweet potato, softened goat cheese, chopped crispy sage, salt, pepper, and garlic powder. Mix until smooth.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato-goat cheese mixture at the wide end of each triangle.",
      "Roll up from wide end, sealing edges well.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and sprinkle with flaky sea salt.",
      "Bake 16-18 minutes until golden and crispy.",
      "Serve warm, garnished with additional fresh sage if desired."
    ],
    tips: "Make sure goat cheese is at room temperature for easier mixing. Don't skip crisping the sage - it adds incredible flavor. These pair beautifully with white wine or sparkling cider.",
    variations: [
      "Add caramelized onions to the filling",
      "Use feta cheese instead of goat cheese",
      "Include a pinch of thyme with the sage"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "savory", "goat cheese", "sage", "appetizer", "elegant", "party food", "holiday"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Savory Sweet Potato Crescent Bites with Goat Cheese & Sage - Elegant Appetizer",
    seoDescription: "Sophisticated gluten-free sweet potato bites with tangy goat cheese and crispy sage. Perfect elegant appetizer for holiday entertaining."
  },
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Cinnamon Honey Drizzle",
    slug: "gluten-free-sweet-potato-crescent-bites-cinnamon-honey-drizzle",
    description: "Dessert-inspired — lightly sweetened potato filling topped with a warm honey-cinnamon glaze.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Cinnamon Honey Drizzle are a delightful dessert-style appetizer that straddles the line between sweet treat and sophisticated bite. The sweet potato filling is lightly sweetened and spiced with warm cinnamon, then wrapped in flaky gluten-free crescent dough. After baking until golden, each bite is drizzled with a warm honey-cinnamon glaze that adds a beautiful shine and extra layer of sweetness. The combination is reminiscent of a sweet potato pie but in a convenient, hand-held form. These are perfect for brunches, afternoon tea, or as a sweet ending to a holiday appetizer spread. The honey glaze caramelizes slightly on top, creating an irresistible glossy finish.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "5.0",
    calories: 152,
    protein: "2.0",
    carbs: "22.0",
    fat: "6.5",
    fiber: "1.5",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-cinnamon-honey-drizzle.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "2 tablespoons maple syrup",
      "1 teaspoon cinnamon, divided",
      "1/4 teaspoon vanilla extract",
      "1/8 teaspoon nutmeg",
      "Pinch of salt",
      "1 egg, beaten (for egg wash)",
      "For the glaze: 3 tablespoons honey",
      "1/2 teaspoon cinnamon",
      "1 tablespoon butter"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, mix mashed sweet potato, maple syrup, 1/2 teaspoon cinnamon, vanilla extract, nutmeg, and salt until smooth.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato mixture at the wide end of each triangle.",
      "Roll up from the wide end, tucking edges to seal.",
      "Place on prepared baking sheet, seam side down.",
      "Brush each crescent with beaten egg.",
      "Bake 16-18 minutes until golden brown.",
      "While baking, make the glaze: In a small saucepan, warm honey, butter, and remaining 1/2 teaspoon cinnamon over low heat until combined.",
      "Drizzle warm honey-cinnamon glaze over baked crescents.",
      "Serve warm or at room temperature."
    ],
    tips: "Don't overbake - they should be golden but still soft. The honey glaze is best applied while crescents are still warm so it adheres well. Can be made ahead and reheated in oven to restore flakiness.",
    variations: [
      "Add a cream cheese drizzle on top",
      "Sprinkle with toasted coconut",
      "Use agave nectar instead of honey for a different flavor"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "dessert", "cinnamon", "honey", "sweet", "brunch", "party food", "holiday"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Cinnamon Honey Drizzle - Sweet Appetizer",
    seoDescription: "Sweet gluten-free sweet potato crescent bites with warm honey-cinnamon glaze. Perfect dessert-style appetizer for brunch and parties."
  },
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Cranberry Brie Filling",
    slug: "gluten-free-sweet-potato-crescent-bites-cranberry-brie",
    description: "Tart cranberries and melty brie balance the sweetness — a perfect Thanksgiving appetizer.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Cranberry Brie Filling are the ultimate Thanksgiving appetizer, combining all the flavors of the holiday in one delicious bite. Creamy sweet potato filling is paired with tangy cranberry sauce and rich, melty brie cheese, all wrapped in flaky gluten-free crescent dough. The sweetness of the potato is perfectly balanced by the tart cranberries, while the brie adds luxurious creaminess that ties everything together. As they bake, the brie melts into the filling and the cranberries become jammy and delicious. These festive bites are stunning on a holiday table and disappear quickly at any gathering. The combination is sophisticated yet comforting, making them ideal for both casual and elegant occasions.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "5.0",
    calories: 155,
    protein: "4.0",
    carbs: "17.0",
    fat: "8.0",
    fiber: "1.8",
    sugar: "6.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-cranberry-brie.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "6 oz brie cheese, cut into small cubes",
      "1/2 cup cranberry sauce (whole berry style)",
      "1 tablespoon maple syrup",
      "1/4 teaspoon salt",
      "1/8 teaspoon black pepper",
      "1 egg, beaten (for egg wash)",
      "Fresh rosemary sprigs for garnish",
      "Coarse sea salt for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, mix mashed sweet potato with maple syrup, salt, and pepper.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1 tablespoon of sweet potato mixture at the wide end of each triangle.",
      "Top sweet potato with a few cubes of brie and 1 teaspoon of cranberry sauce.",
      "Carefully roll up from the wide end, sealing edges well to prevent leaking.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and sprinkle with coarse sea salt.",
      "Bake 16-18 minutes until golden brown and cheese is melted.",
      "Let cool 5 minutes before serving. Garnish with fresh rosemary sprigs."
    ],
    tips: "Use whole berry cranberry sauce for better texture. Don't overfill - the brie will melt and expand. These can be assembled ahead and frozen, then baked directly from frozen (add 3-4 minutes to baking time).",
    variations: [
      "Use dried cranberries rehydrated in orange juice",
      "Add chopped pecans to the filling",
      "Substitute camembert for brie"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "cranberry", "brie", "thanksgiving", "holiday", "appetizer", "festive", "party food"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Cranberry Brie - Thanksgiving Appetizer",
    seoDescription: "Festive gluten-free sweet potato bites with cranberry sauce and melted brie. Perfect Thanksgiving and holiday party appetizer."
  },
  {
    title: "Gluten-Free Maple Bacon Sweet Potato Crescent Bites",
    slug: "gluten-free-maple-bacon-sweet-potato-crescent-bites",
    description: "Sweet and smoky — mashed sweet potato with maple syrup and crispy bacon crumbles.",
    longDescription: "These Gluten-Free Maple Bacon Sweet Potato Crescent Bites are the ultimate sweet and savory combination that everyone will love. Creamy mashed sweet potato is mixed with pure maple syrup for natural sweetness, then studded with crispy bacon crumbles that add smoky, salty flavor. All of this is wrapped in tender, flaky gluten-free crescent dough and baked until golden. The contrast between the sweet maple-enhanced potato and the savory bacon is absolutely addictive. These bites are perfect for brunch gatherings, game day parties, or holiday appetizer spreads. They're hearty enough to be satisfying but still elegant enough for special occasions. The maple and bacon combination is a crowd-pleaser that appeals to all ages.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 16,
    rating: "5.0",
    calories: 162,
    protein: "4.5",
    carbs: "17.0",
    fat: "9.0",
    fiber: "1.5",
    sugar: "7.0",
    image: "/recipe-images/gluten-free-maple-bacon-sweet-potato-crescent-bites.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "6 strips bacon, cooked crispy and crumbled",
      "3 tablespoons pure maple syrup",
      "1/4 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/8 teaspoon smoked paprika",
      "1 egg, beaten (for egg wash)",
      "2 tablespoons chives, chopped (for garnish)",
      "Extra maple syrup for drizzling (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Cook bacon until very crispy, drain on paper towels, and crumble into small pieces. Set aside.",
      "In a bowl, combine mashed sweet potato, maple syrup, salt, pepper, and smoked paprika. Mix well.",
      "Fold in crumbled bacon, reserving some for topping.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato-bacon mixture at the wide end of each triangle.",
      "Roll up from the wide end, sealing edges.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and top with reserved bacon crumbles.",
      "Bake 16-18 minutes until golden brown and crispy.",
      "Drizzle with additional maple syrup if desired and garnish with chopped chives."
    ],
    tips: "Make sure bacon is very crispy so it stays crunchy in the filling. Turkey bacon can be substituted for a lighter option. These reheat beautifully in the oven or air fryer.",
    variations: [
      "Add a touch of bourbon to the filling",
      "Use pancetta instead of bacon",
      "Include caramelized shallots for extra depth"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "bacon", "maple", "sweet-savory", "brunch", "appetizer", "party food", "crowd-pleaser"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Maple Bacon Sweet Potato Crescent Bites - Sweet & Savory Appetizer",
    seoDescription: "Irresistible gluten-free sweet potato bites with maple syrup and crispy bacon. Perfect sweet-savory appetizer for brunch and parties."
  },
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Marshmallow & Pecan Crunch",
    slug: "gluten-free-sweet-potato-crescent-bites-marshmallow-pecan-crunch",
    description: "A nod to classic casserole — sweet potato puree topped with mini marshmallows and pecans inside golden pastry.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Marshmallow & Pecan Crunch are a delightful tribute to the beloved sweet potato casserole. Each bite features creamy sweet potato filling studded with mini marshmallows and crunchy toasted pecans, all wrapped in flaky gluten-free crescent dough. As they bake, the marshmallows become gooey and slightly caramelized while the pecans add a wonderful nutty crunch. The result is a nostalgic flavor combination that brings back memories of holiday dinners but in a convenient, hand-held form. These are perfect for Thanksgiving, Christmas gatherings, or any time you want to serve something fun and festive. Kids and adults alike will love the sweet, gooey, crunchy texture combination.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "4.9",
    calories: 168,
    protein: "2.5",
    carbs: "23.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "11.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-marshmallow-pecan-crunch.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "2 tablespoons brown sugar",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon vanilla extract",
      "Pinch of salt",
      "1 cup mini marshmallows",
      "1/2 cup pecans, toasted and chopped",
      "1 egg, beaten (for egg wash)",
      "2 tablespoons turbinado sugar for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Toast pecans in a dry skillet over medium heat for 3-4 minutes. Chop and set aside.",
      "In a bowl, mix mashed sweet potato, brown sugar, cinnamon, vanilla, and salt until smooth.",
      "Gently fold in mini marshmallows and chopped pecans.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato mixture at the wide end of each triangle.",
      "Roll up from the wide end, being careful not to squeeze out filling.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and sprinkle with turbinado sugar.",
      "Bake 16-18 minutes until golden brown. Some marshmallow may peek through - this is perfect!",
      "Let cool 5 minutes before serving to allow marshmallows to set slightly."
    ],
    tips: "Don't overfill - the marshmallows will expand as they heat. If any marshmallow leaks out during baking, it will caramelize beautifully. These are best served warm while marshmallows are still gooey.",
    variations: [
      "Add a drizzle of caramel sauce after baking",
      "Use walnuts instead of pecans",
      "Include a pinch of cardamom for exotic warmth"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "marshmallow", "pecans", "dessert", "holiday", "thanksgiving", "nostalgic", "sweet"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Marshmallow & Pecan - Holiday Dessert Appetizer",
    seoDescription: "Fun gluten-free sweet potato bites with mini marshmallows and pecans. Sweet holiday appetizer inspired by classic casserole."
  },
  {
    title: "Gluten-Free Spiced Sweet Potato Crescent Bites with Ginger & Orange Zest",
    slug: "gluten-free-spiced-sweet-potato-crescent-bites-ginger-orange",
    description: "Warm spices and citrusy notes for a bright, aromatic twist.",
    longDescription: "These Gluten-Free Spiced Sweet Potato Crescent Bites with Ginger & Orange Zest are a bright and aromatic take on the traditional sweet potato bite. The sweet potato filling is enhanced with warm spices including fresh ginger, cinnamon, and a hint of cardamom, then brightened with fresh orange zest that adds vibrant citrus notes. The combination creates a complex, layered flavor profile that's both comforting and refreshing. Each bite is wrapped in tender gluten-free crescent dough and baked until golden and flaky. These sophisticated bites are perfect for holiday entertaining when you want something a bit different from the traditional flavors. The ginger adds warmth and slight spiciness while the orange provides brightness that cuts through the richness.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 25,
    cookTime: 18,
    totalTime: 43,
    servings: 16,
    rating: "4.9",
    calories: 142,
    protein: "2.0",
    carbs: "19.0",
    fat: "6.5",
    fiber: "1.8",
    sugar: "8.0",
    image: "/recipe-images/gluten-free-spiced-sweet-potato-crescent-bites-ginger-orange.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "2 tablespoons honey",
      "1 tablespoon fresh ginger, grated",
      "Zest of 1 orange",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon cardamom",
      "1/8 teaspoon nutmeg",
      "Pinch of salt",
      "1 egg, beaten (for egg wash)",
      "Orange zest for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, combine mashed sweet potato, honey, grated ginger, orange zest, cinnamon, cardamom, nutmeg, and salt. Mix until well combined.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of spiced sweet potato mixture at the wide end of each triangle.",
      "Roll up from the wide end, tucking edges to seal.",
      "Place on prepared baking sheet, seam side down.",
      "Brush each crescent with beaten egg.",
      "Sprinkle additional orange zest on top.",
      "Bake 16-18 minutes until golden brown and aromatic.",
      "Serve warm. These pair beautifully with spiced chai or hot cider."
    ],
    tips: "Use fresh ginger for the best flavor - grate it finely so it distributes evenly. The orange zest adds brightness - don't skip it! These can be made ahead and reheated in a 350°F oven for 5-7 minutes.",
    variations: [
      "Add a touch of crystallized ginger for extra punch",
      "Include lemon zest along with orange for more citrus",
      "Drizzle with orange glaze after baking"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "ginger", "orange", "spiced", "aromatic", "holiday", "appetizer", "citrus"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Spiced Sweet Potato Crescent Bites with Ginger & Orange - Aromatic Holiday Appetizer",
    seoDescription: "Aromatic gluten-free sweet potato bites with fresh ginger and orange zest. Bright, spiced holiday appetizer with complex flavors."
  },
  {
    title: "Gluten-Free Savory Sweet Potato Crescent Bites with Caramelized Onion & Feta",
    slug: "gluten-free-savory-sweet-potato-crescent-bites-caramelized-onion-feta",
    description: "A flavorful combination of sweet potato mash, caramelized onions, and creamy feta.",
    longDescription: "These Gluten-Free Savory Sweet Potato Crescent Bites with Caramelized Onion & Feta are a sophisticated appetizer that showcases the beautiful interplay between sweet and savory flavors. Sweet potatoes are mashed and combined with deeply caramelized onions that add rich, complex sweetness, and tangy feta cheese that provides a salty, creamy counterpoint. All of this is wrapped in flaky gluten-free crescent dough and baked until golden. The caramelized onions take time but are absolutely worth it, providing layers of flavor that elevate these bites to gourmet status. These are perfect for wine tastings, cocktail parties, or as an elegant starter for dinner parties. The combination is refined and memorable, guaranteed to impress your guests.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Medium",
    prepTime: 35,
    cookTime: 18,
    totalTime: 53,
    servings: 16,
    rating: "5.0",
    calories: 148,
    protein: "3.5",
    carbs: "18.0",
    fat: "7.5",
    fiber: "1.8",
    sugar: "5.0",
    image: "/recipe-images/gluten-free-savory-sweet-potato-crescent-bites-caramelized-onion-feta.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "2 large yellow onions, thinly sliced",
      "4 oz feta cheese, crumbled",
      "3 tablespoons olive oil, divided",
      "1 teaspoon fresh thyme leaves",
      "1/4 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1 tablespoon balsamic vinegar",
      "1 egg, beaten (for egg wash)",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Make caramelized onions: Heat 2 tablespoons olive oil in large skillet over medium heat. Add sliced onions and cook 25-30 minutes, stirring occasionally, until deep golden and caramelized. Add balsamic vinegar in last 2 minutes. Season with salt and pepper. Set aside to cool.",
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, mix mashed sweet potato with fresh thyme, remaining salt and pepper.",
      "Fold in cooled caramelized onions and crumbled feta cheese.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato mixture at the wide end of each triangle.",
      "Roll up from the wide end, sealing edges well.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and drizzle with remaining olive oil.",
      "Bake 16-18 minutes until golden brown and crispy.",
      "Garnish with fresh thyme sprigs and serve warm."
    ],
    tips: "Be patient when caramelizing onions - low and slow is the key to deep flavor. Can caramelize onions up to 3 days ahead. The feta adds saltiness, so go light on additional salt in the filling.",
    variations: [
      "Add toasted pine nuts to the filling",
      "Use goat cheese instead of feta",
      "Include sun-dried tomatoes for Mediterranean flair"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "savory", "caramelized onions", "feta", "sophisticated", "appetizer", "party food", "gourmet"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Savory Sweet Potato Crescent Bites with Caramelized Onion & Feta - Gourmet Appetizer",
    seoDescription: "Sophisticated gluten-free sweet potato bites with caramelized onions and feta cheese. Elegant savory appetizer for special occasions."
  },
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Apple Butter & Walnuts",
    slug: "gluten-free-sweet-potato-crescent-bites-apple-butter-walnuts",
    description: "Cozy fall fusion — apple butter, sweet potato, and chopped walnuts wrapped in flaky pastry.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Apple Butter & Walnuts are the essence of fall in a single bite. Creamy sweet potato is blended with rich, spiced apple butter that adds depth and complexity, then studded with toasted walnuts for crunch and earthy flavor. The combination is wrapped in tender gluten-free crescent dough and baked until golden and flaky. The apple butter brings warm spices like cinnamon and cloves that complement the natural sweetness of the potato perfectly. These bites are ideal for autumn gatherings, Thanksgiving appetizer spreads, or cozy weekend brunches. The flavors are comforting and nostalgic, evoking memories of harvest season and family gatherings. Serve warm with hot apple cider for the ultimate fall experience.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "4.9",
    calories: 156,
    protein: "2.5",
    carbs: "20.0",
    fat: "7.5",
    fiber: "2.0",
    sugar: "9.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-apple-butter-walnuts.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "1/3 cup apple butter",
      "1/2 cup walnuts, toasted and chopped",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon nutmeg",
      "Pinch of cloves",
      "Pinch of salt",
      "1 egg, beaten (for egg wash)",
      "Coarse sugar for topping"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "Toast walnuts in a dry skillet over medium heat for 3-4 minutes until fragrant. Chop and set aside.",
      "In a bowl, combine mashed sweet potato, apple butter, cinnamon, nutmeg, cloves, and salt. Mix until smooth.",
      "Fold in chopped toasted walnuts, reserving some for topping.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato-apple butter mixture at the wide end of each triangle.",
      "Roll up from the wide end, sealing edges.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg and sprinkle with coarse sugar and reserved walnuts.",
      "Bake 16-18 minutes until golden brown and aromatic.",
      "Serve warm. These pair perfectly with hot apple cider or spiced tea."
    ],
    tips: "Use good quality apple butter for best flavor - the spices should be pronounced. Toast walnuts to enhance their flavor and add crunch. These freeze beautifully - bake from frozen, adding 3-4 minutes to baking time.",
    variations: [
      "Use pecans instead of walnuts",
      "Add dried cranberries to the filling",
      "Include a touch of bourbon in the filling for adult gatherings"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "apple butter", "walnuts", "fall", "autumn", "cozy", "appetizer", "thanksgiving"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Apple Butter & Walnuts - Cozy Fall Appetizer",
    seoDescription: "Comforting gluten-free sweet potato bites with apple butter and toasted walnuts. Perfect cozy fall and Thanksgiving appetizer."
  },
  {
    title: "Gluten-Free Sweet Potato Crescent Bites with Rum Glaze & Cinnamon Sugar",
    slug: "gluten-free-sweet-potato-crescent-bites-rum-glaze-cinnamon-sugar",
    description: "A dessert-style bite — sweet potato mash baked in dough, brushed with rum glaze, and dusted with cinnamon sugar.",
    longDescription: "These Gluten-Free Sweet Potato Crescent Bites with Rum Glaze & Cinnamon Sugar are an indulgent dessert-style appetizer perfect for adult gatherings. Creamy sweet potato filling is lightly spiced and wrapped in flaky gluten-free crescent dough, then baked until golden. After baking, each bite is brushed with a warm rum glaze that adds sophisticated flavor and beautiful shine, then dusted with cinnamon sugar for extra sweetness and sparkle. The rum glaze provides a subtle warmth and complexity that elevates these from simple sweet bites to elegant dessert appetizers. These are perfect for holiday cocktail parties, New Year's celebrations, or any occasion when you want to serve something special. The combination of flavors is rich, warming, and utterly delicious.",
    category: "Appetizers",
    subcategory: "Holiday & Party Bites",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 18,
    totalTime: 38,
    servings: 16,
    rating: "5.0",
    calories: 165,
    protein: "2.0",
    carbs: "24.0",
    fat: "6.5",
    fiber: "1.5",
    sugar: "13.0",
    image: "/recipe-images/gluten-free-sweet-potato-crescent-bites-rum-glaze-cinnamon-sugar.png",
    ingredients: [
      "1 package (8 oz) gluten-free crescent dough",
      "1 cup mashed sweet potato",
      "2 tablespoons brown sugar",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon vanilla extract",
      "Pinch of salt",
      "1 egg, beaten (for egg wash)",
      "For the rum glaze: 3 tablespoons butter",
      "2 tablespoons dark rum",
      "1/4 cup powdered sugar",
      "For topping: 2 tablespoons granulated sugar",
      "1 teaspoon cinnamon"
    ],
    instructions: [
      "Preheat oven to 375°F. Line baking sheet with parchment paper.",
      "In a bowl, mix mashed sweet potato, brown sugar, 1/2 teaspoon cinnamon, vanilla, and salt until smooth.",
      "Unroll gluten-free crescent dough and separate into triangles.",
      "Place about 1½ tablespoons of sweet potato mixture at the wide end of each triangle.",
      "Roll up from the wide end, sealing edges well.",
      "Place on prepared baking sheet, seam side down.",
      "Brush with beaten egg.",
      "Bake 16-18 minutes until golden brown.",
      "While baking, make rum glaze: Melt butter in small saucepan, add rum and cook for 1 minute. Remove from heat and whisk in powdered sugar until smooth.",
      "Mix cinnamon and granulated sugar for topping.",
      "Brush warm baked crescents with rum glaze, then immediately dust with cinnamon sugar.",
      "Serve warm or at room temperature."
    ],
    tips: "For non-alcoholic version, use rum extract and increase butter slightly. The rum glaze should be applied while crescents are still warm so it absorbs well. These are best served fresh but can be reheated in oven.",
    variations: [
      "Use bourbon instead of rum for different flavor",
      "Add a cream cheese glaze on top",
      "Include chopped pecans in the filling"
    ],
    tags: ["gluten-free", "sweet potato", "crescent bites", "rum glaze", "cinnamon sugar", "dessert", "indulgent", "holiday", "party food", "sweet"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sweet Potato Crescent Bites with Rum Glaze & Cinnamon Sugar - Dessert Appetizer",
    seoDescription: "Indulgent gluten-free sweet potato bites with rum glaze and cinnamon sugar. Elegant dessert-style appetizer for holiday parties."
  }
];

async function addRecipes() {
  try {
    console.log("Adding 10 gluten-free sweet potato crescent bite recipes...");
    await db.insert(recipes).values(sweetPotatoCrescentBites);
    console.log("Successfully added all 10 recipes!");
    process.exit(0);
  } catch (error) {
    console.error("Error adding recipes:", error);
    process.exit(1);
  }
}

addRecipes();
