import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const pastelonRecipes = [
  {
    title: "Gluten-Free Classic Puerto Rican Pastelón",
    slug: "gluten-free-classic-puerto-rican-pastelon",
    seoTitle: "Gluten-Free Classic Puerto Rican Pastelón - Traditional Recipe",
    description: "Traditional layered sweet plantains, beef picadillo with sofrito, and mozzarella — perfectly balanced Puerto Rican comfort food.",
    longDescription: "This gluten-free classic Puerto Rican pastelón is the ultimate comfort food, featuring layers of golden fried sweet plantains alternating with savory beef picadillo seasoned with authentic sofrito. The sweet plantains are caramelized to perfection, providing a beautiful contrast to the richly spiced meat filling. Topped with melted mozzarella cheese and baked until bubbly, this dish is a staple at Puerto Rican celebrations and family gatherings. The name 'pastelón' comes from its resemblance to a cake or large pastry. Each slice reveals beautiful layers of sweet and savory goodness. This is traditionally served at holidays and special occasions, bringing families together over its irresistible combination of flavors. Serve it sliced like lasagna with a side of rice and beans for the complete Puerto Rican experience.",
    seoDescription: "Authentic gluten-free Puerto Rican pastelón with sweet plantains, beef picadillo, and cheese. Traditional Caribbean comfort food recipe.",
    category: "International",
    prepTime: 30,
    cookTime: 45,
    totalTime: 75,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-classic-puerto-rican-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains (yellow with black spots)",
      "Vegetable oil for frying",
      "1.5 lbs ground beef",
      "1 cup sofrito (homemade or store-bought gluten-free)",
      "1 can (8 oz) tomato sauce",
      "1/4 cup green olives, sliced",
      "2 tablespoons capers",
      "1 tablespoon sazón seasoning (gluten-free)",
      "1 teaspoon ground cumin",
      "2 cups shredded mozzarella cheese",
      "3 eggs, beaten",
      "Salt and pepper to taste",
      "Fresh cilantro for garnish"
    ],
    instructions: [
      "Peel plantains and slice lengthwise into 1/4-inch thick strips.",
      "Heat 1/2 inch of oil in a large skillet over medium-high heat. Fry plantain slices until golden on both sides, about 3-4 minutes per side. Drain on paper towels.",
      "In another skillet, brown ground beef over medium-high heat. Drain excess fat.",
      "Add sofrito, tomato sauce, olives, capers, sazón, cumin, salt, and pepper to the beef. Simmer for 10-12 minutes until thickened.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the fried plantains on the bottom of the dish, overlapping slightly.",
      "Spread all of the beef picadillo over the plantains.",
      "Layer remaining plantains on top of the meat.",
      "Pour beaten eggs over the top layer, allowing them to seep through.",
      "Sprinkle mozzarella cheese evenly over the top.",
      "Bake for 35-40 minutes until cheese is melted and golden.",
      "Let rest for 10 minutes before slicing. Garnish with fresh cilantro and serve."
    ],
    tags: ["gluten-free", "pastelón", "Puerto Rican", "sweet plantains", "beef", "picadillo", "Caribbean", "Latin", "casserole", "traditional"],
    nutrition: {
      calories: 485,
      protein: "28g",
      carbs: "48g",
      fat: "20g",
      fiber: "4g",
      sodium: "680mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Sweet Plantain & Beef Pastelón with Olives & Raisins",
    slug: "gluten-free-sweet-plantain-beef-pastelon",
    seoTitle: "Gluten-Free Sweet Plantain Beef Pastelón - Sweet & Savory Classic",
    description: "Authentic combination of sweet fried plantains, spiced beef, briny olives, and sweet raisins — the ultimate sweet-salty flavor.",
    longDescription: "This gluten-free sweet plantain and beef pastelón with olives and raisins represents the perfect balance of sweet and savory that defines Puerto Rican cuisine. The addition of raisins adds bursts of natural sweetness that complement the caramelized plantains, while briny green olives provide a salty counterpoint. This classic combination is deeply traditional, reflecting the Spanish influence on Caribbean cooking. The beef picadillo is enriched with sofrito, creating layers of complex flavor. Each bite offers a different experience — sometimes you get the sweetness of plantain and raisin, other times the savory richness of spiced beef and olives. This is comfort food at its finest, perfect for Sunday dinners and holiday celebrations.",
    seoDescription: "Gluten-free sweet plantain and beef pastelón with olives and raisins. Traditional sweet-savory Puerto Rican comfort food.",
    category: "International",
    prepTime: 30,
    cookTime: 45,
    totalTime: 75,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-sweet-plantain-beef-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "1.5 lbs ground beef",
      "1 cup sofrito",
      "1 can (8 oz) tomato sauce",
      "1/2 cup green olives with pimientos, sliced",
      "1/2 cup golden raisins",
      "3 tablespoons capers",
      "2 teaspoons sazón seasoning (gluten-free)",
      "1 teaspoon dried oregano",
      "2 cups shredded mozzarella",
      "3 eggs, beaten",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Peel and slice plantains lengthwise. Fry in hot oil until golden and caramelized, about 3-4 minutes per side. Drain well.",
      "Brown ground beef in a large skillet. Drain excess fat.",
      "Add sofrito and cook for 2 minutes until fragrant.",
      "Stir in tomato sauce, olives, raisins, capers, sazón, oregano, salt, and pepper.",
      "Simmer for 12-15 minutes until mixture thickens and raisins plump.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Arrange half the plantains in the bottom of the dish.",
      "Spread beef picadillo evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top, letting them seep through the layers.",
      "Sprinkle with mozzarella cheese.",
      "Bake for 35-40 minutes until golden and bubbly.",
      "Cool for 10 minutes, slice, and serve with rice and beans."
    ],
    tags: ["gluten-free", "pastelón", "sweet plantains", "beef", "olives", "raisins", "Puerto Rican", "Caribbean", "sweet-savory", "traditional"],
    nutrition: {
      calories: 510,
      protein: "27g",
      carbs: "52g",
      fat: "21g",
      fiber: "4g",
      sodium: "720mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Chicken Sofrito Pastelón",
    slug: "gluten-free-chicken-sofrito-pastelon",
    seoTitle: "Gluten-Free Chicken Sofrito Pastelón - Lighter Caribbean Recipe",
    description: "Lighter twist using shredded chicken, homemade sofrito, and roasted peppers layered with sweet plantains.",
    longDescription: "This gluten-free chicken sofrito pastelón offers a lighter take on the traditional recipe while maintaining all the authentic Caribbean flavors. Instead of ground beef, tender shredded chicken is simmered in a rich homemade sofrito sauce with roasted red peppers for added sweetness and color. The result is a dish that's just as satisfying but slightly lighter in texture and flavor. The sofrito — a aromatic blend of peppers, onions, garlic, and cilantro — infuses the chicken with incredible depth. Roasted peppers add natural sweetness that complements the caramelized plantains beautifully. This version is perfect for those who prefer poultry or want a slightly less heavy option that's still packed with traditional flavor.",
    seoDescription: "Gluten-free chicken sofrito pastelón with roasted peppers and sweet plantains. Lighter Caribbean comfort food recipe.",
    category: "International",
    prepTime: 35,
    cookTime: 45,
    totalTime: 80,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-chicken-sofrito-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "2 lbs boneless chicken breasts or thighs",
      "1.5 cups homemade sofrito",
      "1 cup roasted red peppers, sliced",
      "1 can (8 oz) tomato sauce",
      "1/4 cup green olives, sliced",
      "2 teaspoons sazón (gluten-free)",
      "1 teaspoon ground cumin",
      "2 cups shredded white cheddar or mozzarella",
      "3 eggs, beaten",
      "Fresh cilantro",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Cook chicken in boiling water for 20 minutes until tender. Shred with two forks.",
      "Peel and slice plantains lengthwise. Fry until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, heat sofrito over medium heat for 2 minutes.",
      "Add shredded chicken, roasted peppers, tomato sauce, olives, sazón, cumin, salt, and pepper.",
      "Simmer for 10-12 minutes until mixture thickens and flavors meld.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the fried plantains on the bottom.",
      "Spread chicken mixture evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top layer.",
      "Sprinkle with cheese.",
      "Bake for 35-40 minutes until golden and bubbly.",
      "Garnish with fresh cilantro and serve."
    ],
    tags: ["gluten-free", "pastelón", "chicken", "sofrito", "sweet plantains", "Puerto Rican", "Caribbean", "lighter", "roasted peppers", "Latin"],
    nutrition: {
      calories: 465,
      protein: "32g",
      carbs: "46g",
      fat: "17g",
      fiber: "4g",
      sodium: "640mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Vegetarian Pastelón with Lentils & Sweet Plantains",
    slug: "gluten-free-vegetarian-lentil-pastelon",
    seoTitle: "Gluten-Free Vegetarian Lentil Pastelón - Plant-Based Caribbean",
    description: "Hearty vegetarian version made with lentil picadillo, onions, and melted cheese — wholesome and flavorful.",
    longDescription: "This gluten-free vegetarian pastelón with lentils proves that plant-based versions can be just as hearty and satisfying as the original. Instead of ground meat, protein-rich brown or green lentils are seasoned with traditional sofrito and spices to create a picadillo that's remarkably similar in texture and flavor to the beef version. The lentils absorb all the aromatic flavors while providing excellent nutrition and fiber. Layered between sweet caramelized plantains and topped with melted cheese, this version is perfect for vegetarian diners or anyone looking to incorporate more plant-based meals. It's wholesome, satisfying, and packed with the authentic Puerto Rican flavors you crave.",
    seoDescription: "Gluten-free vegetarian pastelón with lentils and sweet plantains. Hearty plant-based Caribbean comfort food recipe.",
    category: "International",
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-vegetarian-lentil-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "2 cups cooked brown or green lentils (about 1 cup dry)",
      "1 cup sofrito",
      "1 large onion, diced",
      "1 can (8 oz) tomato sauce",
      "1/4 cup green olives, chopped",
      "2 tablespoons capers",
      "2 teaspoons sazón (gluten-free)",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "2 cups shredded cheese (mozzarella or cheddar)",
      "3 eggs, beaten",
      "Salt and pepper to taste"
    ],
    instructions: [
      "If using dry lentils, cook according to package directions until tender. Drain well.",
      "Peel and slice plantains lengthwise. Fry in hot oil until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, sauté diced onion in 2 tablespoons oil until softened, about 5 minutes.",
      "Add sofrito and cook for 2 minutes until fragrant.",
      "Stir in cooked lentils, tomato sauce, olives, capers, sazón, cumin, paprika, salt, and pepper.",
      "Simmer for 10-12 minutes until mixture thickens. Mash lightly with a fork if desired for better texture.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread lentil mixture evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top.",
      "Sprinkle with cheese.",
      "Bake for 35-40 minutes until golden and set.",
      "Cool for 10 minutes before slicing and serving."
    ],
    tags: ["gluten-free", "pastelón", "vegetarian", "lentils", "sweet plantains", "Puerto Rican", "Caribbean", "plant-based", "wholesome", "Latin"],
    nutrition: {
      calories: 445,
      protein: "18g",
      carbs: "54g",
      fat: "17g",
      fiber: "8g",
      sodium: "620mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Turkey Pastelón with Roasted Garlic & Herbs",
    slug: "gluten-free-turkey-herb-pastelon",
    seoTitle: "Gluten-Free Turkey Herb Pastelón - Lean & Aromatic Recipe",
    description: "Lean and aromatic, featuring ground turkey and herb-infused sofrito for a lighter, fresh version.",
    longDescription: "This gluten-free turkey pastelón with roasted garlic and herbs is a lighter, more health-conscious version that doesn't sacrifice any flavor. Lean ground turkey is seasoned with an herb-infused sofrito featuring roasted garlic, fresh cilantro, oregano, and thyme. The roasted garlic adds a mellow sweetness and depth that complements the turkey's mild flavor perfectly. Fresh herbs brighten the dish and add aromatic complexity. This version is lower in fat than the traditional beef version but still delivers all the comforting, satisfying qualities you expect from pastelón. It's perfect for those watching their diet but still wanting to enjoy this beloved Caribbean classic.",
    seoDescription: "Gluten-free turkey pastelón with roasted garlic and fresh herbs. Lean, aromatic Caribbean comfort food recipe.",
    category: "International",
    prepTime: 35,
    cookTime: 45,
    totalTime: 80,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-turkey-herb-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "1.5 lbs lean ground turkey",
      "1 whole head garlic, roasted",
      "1 cup sofrito",
      "1 can (8 oz) tomato sauce",
      "2 tablespoons fresh cilantro, chopped",
      "1 tablespoon fresh oregano, chopped",
      "1 tablespoon fresh thyme leaves",
      "1/4 cup green olives, sliced",
      "2 teaspoons sazón (gluten-free)",
      "2 cups shredded mozzarella",
      "3 eggs, beaten",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Roast garlic: Cut top off head of garlic, drizzle with oil, wrap in foil, and roast at 400°F for 30-35 minutes until soft. Squeeze out cloves and mash.",
      "Peel and slice plantains lengthwise. Fry until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, cook ground turkey over medium-high heat until browned, breaking it up as it cooks.",
      "Add roasted garlic, sofrito, tomato sauce, fresh herbs, olives, sazón, salt, and pepper.",
      "Simmer for 10-12 minutes until mixture thickens and flavors meld.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the fried plantains on the bottom.",
      "Spread turkey mixture evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top layer.",
      "Sprinkle with mozzarella cheese.",
      "Bake for 35-40 minutes until cheese is golden and bubbly.",
      "Let rest for 10 minutes, garnish with fresh herbs, and serve."
    ],
    tags: ["gluten-free", "pastelón", "turkey", "roasted garlic", "herbs", "sweet plantains", "Puerto Rican", "Caribbean", "lean", "healthy"],
    nutrition: {
      calories: 435,
      protein: "28g",
      carbs: "47g",
      fat: "15g",
      fiber: "4g",
      sodium: "590mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free BBQ Picadillo Pastelón with Cheese Crust",
    slug: "gluten-free-bbq-picadillo-pastelon",
    seoTitle: "Gluten-Free BBQ Pastelón - Smoky Sweet Caribbean Fusion",
    description: "Smoky barbecue twist on classic picadillo layered with plantains and cheddar crust — sweet, spicy, and bold.",
    longDescription: "This gluten-free BBQ picadillo pastelón with cheese crust takes the traditional recipe in a bold new direction with smoky barbecue flavors. The beef picadillo is enhanced with gluten-free BBQ sauce, smoked paprika, and caramelized onions for deep, complex flavor. The sweetness of the barbecue sauce complements the caramelized plantains beautifully, while a sharp cheddar cheese crust on top adds a savory, slightly tangy finish. This fusion version bridges Caribbean and American BBQ traditions, creating something familiar yet exciting. It's perfect for those who love bold, smoky flavors and want to try something different from the traditional pastelón.",
    seoDescription: "Gluten-free BBQ picadillo pastelón with cheese crust. Smoky, sweet Caribbean-American fusion comfort food recipe.",
    category: "International",
    prepTime: 30,
    cookTime: 45,
    totalTime: 75,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-bbq-picadillo-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "1.5 lbs ground beef",
      "1 large onion, diced",
      "1 cup sofrito",
      "1/2 cup gluten-free BBQ sauce",
      "1 can (8 oz) tomato sauce",
      "2 teaspoons smoked paprika",
      "1 teaspoon chipotle powder",
      "1 teaspoon ground cumin",
      "2 cups shredded sharp cheddar cheese",
      "3 eggs, beaten",
      "Salt and pepper to taste",
      "Fresh cilantro for garnish"
    ],
    instructions: [
      "Peel and slice plantains lengthwise. Fry until golden and caramelized, 3-4 minutes per side. Drain.",
      "In a large skillet, cook diced onion in 1 tablespoon oil until caramelized, about 8-10 minutes.",
      "Add ground beef and brown, breaking it up as it cooks. Drain excess fat.",
      "Stir in sofrito, BBQ sauce, tomato sauce, smoked paprika, chipotle powder, cumin, salt, and pepper.",
      "Simmer for 12-15 minutes until thick and smoky-sweet.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread BBQ picadillo evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top.",
      "Generously sprinkle sharp cheddar cheese on top for a crispy crust.",
      "Bake for 35-40 minutes until cheese is golden and crispy.",
      "Cool for 10 minutes, garnish with cilantro, and serve."
    ],
    tags: ["gluten-free", "pastelón", "BBQ", "beef", "sweet plantains", "fusion", "Caribbean", "smoky", "cheese crust", "bold flavors"],
    nutrition: {
      calories: 520,
      protein: "29g",
      carbs: "50g",
      fat: "23g",
      fiber: "4g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Plantain & Shrimp Pastelón with Coconut Cream Sauce",
    slug: "gluten-free-plantain-shrimp-pastelon",
    seoTitle: "Gluten-Free Shrimp Pastelón - Caribbean Seafood Fusion",
    description: "Caribbean fusion version — sautéed shrimp in coconut sofrito with sweet plantains and mozzarella.",
    longDescription: "This gluten-free plantain and shrimp pastelón with coconut cream sauce is an elegant Caribbean fusion that showcases the region's incredible seafood. Succulent shrimp are sautéed in a coconut-infused sofrito sauce that's creamy, aromatic, and slightly sweet. The coconut cream adds tropical richness that pairs beautifully with the caramelized plantains. This is a lighter, more refined version of pastelón that feels special enough for entertaining. The shrimp cook quickly and provide delicate protein that doesn't overpower the other flavors. Finished with melted mozzarella and fresh cilantro, this coastal-inspired version brings ocean breezes to your table.",
    seoDescription: "Gluten-free shrimp pastelón with coconut cream and sweet plantains. Elegant Caribbean seafood fusion recipe.",
    category: "International",
    prepTime: 30,
    cookTime: 35,
    totalTime: 65,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-plantain-shrimp-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "1.5 lbs large shrimp, peeled and deveined",
      "1 cup sofrito",
      "1 cup coconut cream",
      "1 red bell pepper, diced",
      "1/2 cup white wine (optional, or use broth)",
      "2 cloves garlic, minced",
      "1 teaspoon paprika",
      "1/2 teaspoon red pepper flakes",
      "2 cups shredded mozzarella",
      "3 eggs, beaten",
      "Fresh cilantro and lime wedges",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Peel and slice plantains lengthwise. Fry until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, heat 2 tablespoons oil over medium heat. Sauté bell pepper for 3 minutes.",
      "Add garlic and sofrito. Cook for 2 minutes until fragrant.",
      "Add shrimp and cook for 2-3 minutes until pink.",
      "Pour in coconut cream and white wine (if using). Add paprika, red pepper flakes, salt, and pepper.",
      "Simmer for 5-6 minutes until sauce thickens slightly. Remove from heat.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread shrimp and coconut sauce evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top.",
      "Sprinkle with mozzarella cheese.",
      "Bake for 30-35 minutes until golden and bubbly.",
      "Garnish with fresh cilantro and serve with lime wedges."
    ],
    tags: ["gluten-free", "pastelón", "shrimp", "coconut", "seafood", "sweet plantains", "Caribbean", "fusion", "tropical", "elegant"],
    nutrition: {
      calories: 490,
      protein: "26g",
      carbs: "48g",
      fat: "21g",
      fiber: "4g",
      sodium: "620mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Black Bean & Sweet Corn Pastelón",
    slug: "gluten-free-black-bean-corn-pastelon",
    seoTitle: "Gluten-Free Black Bean Corn Pastelón - Southwest Caribbean Fusion",
    description: "Southwest-inspired vegetarian take with spiced black beans, corn, cilantro, and pepper jack cheese.",
    longDescription: "This gluten-free black bean and sweet corn pastelón represents a creative fusion between Southwest and Caribbean cuisines. Protein-rich black beans seasoned with cumin, chili powder, and cilantro create a hearty vegetarian filling, while sweet corn adds pops of freshness and natural sweetness. Pepper jack cheese brings a spicy kick that complements the sweet plantains beautifully. This colorful, vibrant version is packed with fiber and plant-based protein, making it both nutritious and satisfying. The combination of textures and flavors creates something entirely new while respecting the layered structure of traditional pastelón. It's perfect for vegetarians and anyone looking for a bold, flavorful meatless meal.",
    seoDescription: "Gluten-free black bean and corn pastelón with pepper jack. Southwest-Caribbean vegetarian fusion comfort food.",
    category: "International",
    prepTime: 30,
    cookTime: 40,
    totalTime: 70,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-black-bean-corn-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "2 cans (15 oz each) black beans, drained and rinsed",
      "2 cups sweet corn (fresh or frozen)",
      "1 cup sofrito",
      "1 red bell pepper, diced",
      "1 can (8 oz) tomato sauce",
      "2 teaspoons ground cumin",
      "1 teaspoon chili powder",
      "1/2 cup fresh cilantro, chopped",
      "2 cups shredded pepper jack cheese",
      "3 eggs, beaten",
      "Salt and pepper to taste",
      "Lime wedges for serving"
    ],
    instructions: [
      "Peel and slice plantains lengthwise. Fry until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, heat 2 tablespoons oil. Sauté bell pepper for 4 minutes until softened.",
      "Add sofrito and cook for 2 minutes until fragrant.",
      "Stir in black beans, corn, tomato sauce, cumin, chili powder, salt, and pepper.",
      "Simmer for 8-10 minutes, mashing some of the beans for better texture.",
      "Remove from heat and stir in half the cilantro.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread black bean and corn mixture evenly over plantains.",
      "Top with remaining plantain slices.",
      "Pour beaten eggs over the top.",
      "Sprinkle with pepper jack cheese.",
      "Bake for 35-40 minutes until cheese is melted and golden.",
      "Garnish with remaining cilantro and serve with lime wedges."
    ],
    tags: ["gluten-free", "pastelón", "black beans", "corn", "vegetarian", "Southwest", "Caribbean fusion", "sweet plantains", "spicy", "colorful"],
    nutrition: {
      calories: 455,
      protein: "19g",
      carbs: "56g",
      fat: "17g",
      fiber: "9g",
      sodium: "640mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Chorizo & Sweet Potato Pastelón",
    slug: "gluten-free-chorizo-sweet-potato-pastelon",
    seoTitle: "Gluten-Free Chorizo Sweet Potato Pastelón - Spicy & Sweet",
    description: "Sweet and spicy — chorizo filling with mashed sweet potato and caramelized onions for deep flavor.",
    longDescription: "This gluten-free chorizo and sweet potato pastelón is a bold, flavor-packed variation that combines spicy Mexican chorizo with sweet potatoes for incredible depth. The chorizo provides smoky, spicy richness, while mashed sweet potatoes add natural sweetness and create an interesting textural contrast to the plantain layers. Caramelized onions bring additional sweetness and complexity. This version layers sweet on sweet (plantains and sweet potatoes) balanced by the spicy, savory chorizo — creating a dish that's deeply satisfying and uniquely delicious. The combination of orange sweet potatoes and golden plantains makes this visually stunning as well.",
    seoDescription: "Gluten-free chorizo and sweet potato pastelón with caramelized onions. Spicy-sweet Caribbean fusion comfort food.",
    category: "International",
    prepTime: 35,
    cookTime: 50,
    totalTime: 85,
    servings: 8,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-chorizo-sweet-potato-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying",
      "1 lb Mexican chorizo (gluten-free)",
      "2 large sweet potatoes, peeled and cubed",
      "2 large onions, thinly sliced",
      "1 cup sofrito",
      "1/2 cup chicken or vegetable broth",
      "2 teaspoons smoked paprika",
      "1 teaspoon ground cumin",
      "2 cups shredded Monterey Jack cheese",
      "3 eggs, beaten",
      "2 tablespoons butter",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Boil sweet potato cubes until tender, about 12-15 minutes. Drain and mash with butter, salt, and pepper. Set aside.",
      "Peel and slice plantains lengthwise. Fry until golden, 3-4 minutes per side. Drain.",
      "In a large skillet, cook sliced onions over medium-low heat for 15 minutes until deeply caramelized. Remove and set aside.",
      "In the same skillet, cook chorizo over medium heat, breaking it up, until cooked through.",
      "Add sofrito, broth, paprika, and cumin. Simmer for 5-6 minutes. Stir in caramelized onions.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread half the mashed sweet potato over plantains.",
      "Spread chorizo mixture over sweet potato layer.",
      "Top with remaining sweet potato, then remaining plantain slices.",
      "Pour beaten eggs over the top.",
      "Sprinkle with Monterey Jack cheese.",
      "Bake for 40-45 minutes until golden and bubbling.",
      "Cool for 10 minutes before serving."
    ],
    tags: ["gluten-free", "pastelón", "chorizo", "sweet potato", "spicy", "sweet plantains", "Caribbean", "Mexican fusion", "bold flavors", "caramelized onions"],
    nutrition: {
      calories: 540,
      protein: "22g",
      carbs: "54g",
      fat: "27g",
      fiber: "6g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Breakfast Pastelón with Eggs & Cheese",
    slug: "gluten-free-breakfast-pastelon",
    seoTitle: "Gluten-Free Breakfast Pastelón - Morning Caribbean Brunch",
    description: "Morning twist — layers of baked plantains, scrambled eggs, and cheese, topped with avocado crema.",
    longDescription: "This gluten-free breakfast pastelón with eggs and cheese reimagines the classic dish as the ultimate brunch creation. Instead of picadillo, fluffy scrambled eggs provide protein and a light, creamy texture. The eggs are seasoned simply to let the sweet plantains shine. Melted cheddar cheese adds richness, while a cool, tangy avocado crema on top provides freshness and contrast. This version can be assembled ahead and baked in the morning, making it perfect for weekend brunch or holiday breakfast gatherings. The combination of sweet plantains and savory eggs is surprisingly delicious — familiar yet new. Serve with fresh fruit and coffee for a complete Caribbean-inspired brunch.",
    seoDescription: "Gluten-free breakfast pastelón with eggs, cheese, and avocado crema. Caribbean-inspired brunch casserole recipe.",
    category: "Breakfast",
    prepTime: 25,
    cookTime: 35,
    totalTime: 60,
    servings: 8,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-breakfast-pastelon.png",
    ingredients: [
      "6 ripe sweet plantains",
      "Vegetable oil for frying or baking spray",
      "10 large eggs",
      "1/4 cup milk or cream",
      "2 cups shredded cheddar cheese",
      "2 tablespoons butter",
      "Salt and pepper to taste",
      "For avocado crema:",
      "2 ripe avocados",
      "1/2 cup sour cream or Greek yogurt",
      "Juice of 1 lime",
      "2 tablespoons fresh cilantro",
      "Salt to taste",
      "Fresh salsa for serving (optional)"
    ],
    instructions: [
      "Peel plantains and slice lengthwise. You can either fry them in oil or bake at 400°F for 20 minutes, flipping once, until golden.",
      "Whisk together 7 eggs, milk, salt, and pepper.",
      "Melt butter in a large skillet and scramble the egg mixture until just set but still soft. Remove from heat.",
      "Preheat oven to 350°F. Grease a 9x13-inch baking dish.",
      "Layer half the plantains on the bottom.",
      "Spread scrambled eggs evenly over plantains.",
      "Sprinkle with half the cheese.",
      "Top with remaining plantain slices.",
      "Beat remaining 3 eggs and pour over the top layer.",
      "Sprinkle with remaining cheese.",
      "Bake for 30-35 minutes until cheese is golden and eggs are set.",
      "While baking, make avocado crema: blend avocados, sour cream, lime juice, cilantro, and salt until smooth.",
      "Cool pastelón for 5 minutes, slice, and serve topped with avocado crema and salsa."
    ],
    tags: ["gluten-free", "pastelón", "breakfast", "brunch", "eggs", "sweet plantains", "avocado", "Caribbean", "morning", "make-ahead"],
    nutrition: {
      calories: 465,
      protein: "17g",
      carbs: "42g",
      fat: "26g",
      fiber: "5g",
      sodium: "440mg"
    },
    isNaturallyGlutenFree: true
  }
];

async function addRecipes() {
  console.log("Adding 10 Gluten-Free Pastelón recipes...");
  
  for (const recipe of pastelonRecipes) {
    try {
      await db.insert(recipes).values({
        id: nanoid(),
        ...recipe,
        rating: "4.8",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`✓ Added: ${recipe.title}`);
    } catch (error) {
      console.error(`✗ Error adding ${recipe.title}:`, error);
    }
  }
  
  console.log("\n✅ All pastelón recipes added successfully!");
  process.exit(0);
}

addRecipes();
