import { db } from "../server/db";
import { recipes } from "../shared/schema";

const pineappleStuffingRecipes = [
  {
    title: "Gluten-Free Classic Pineapple Stuffing",
    slug: "gluten-free-classic-pineapple-stuffing",
    description: "Traditional sweet stuffing made with gluten-free bread, crushed pineapple, eggs, and butter — caramelized and golden with a perfect balance of sweet and savory.",
    longDescription: "This Gluten-Free Classic Pineapple Stuffing is a beloved holiday tradition that brings a sweet, tropical twist to your table. Made with cubed gluten-free bread soaked in a mixture of crushed pineapple, eggs, melted butter, and just a touch of sugar, this casserole bakes up golden and caramelized on top while staying moist and custardy inside. The pineapple adds natural sweetness and a delightful texture that complements ham, turkey, or pork perfectly. This versatile dish works equally well as a side for Easter brunch, Thanksgiving dinner, or Christmas gatherings. The recipe is simple enough for beginners but impressive enough to become a family favorite that gets requested year after year.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 45,
    totalTime: 60,
    servings: 10,
    rating: "4.8",
    calories: 220,
    protein: "5.0",
    carbs: "35.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "18.0",
    image: "/recipe-images/gluten-free-classic-pineapple-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread, cut into 1-inch cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "3/4 cup granulated sugar",
      "4 large eggs, beaten",
      "1/2 cup unsalted butter, melted",
      "1/4 cup milk",
      "1 teaspoon vanilla extract",
      "1/2 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Spread bread cubes on baking sheet and toast in oven for 10 minutes until slightly dry. Transfer to large bowl.",
      "In separate bowl, mix crushed pineapple with juice, sugar, beaten eggs, melted butter, milk, vanilla, and salt.",
      "Pour pineapple mixture over bread cubes and stir gently until bread is evenly coated.",
      "Let stand 10 minutes for bread to absorb liquid.",
      "Transfer mixture to prepared baking dish and spread evenly.",
      "Bake 40-45 minutes until top is golden brown and edges are caramelized.",
      "Let cool 10 minutes before serving. Serve warm as a side dish."
    ],
    tips: "Use day-old bread for best texture. Can be assembled a day ahead and refrigerated, then baked before serving. Add 10 minutes to bake time if starting from cold.",
    variations: [
      "Add 1/2 cup chopped pecans for crunch",
      "Mix in 1/2 cup shredded coconut",
      "Top with additional sugar before baking for extra caramelization"
    ],
    tags: ["gluten-free", "pineapple stuffing", "holiday", "side dish", "sweet", "casserole", "make-ahead", "easter"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Classic Pineapple Stuffing - Sweet Holiday Side Dish",
    seoDescription: "Traditional pineapple stuffing made gluten-free with crushed pineapple, eggs, and butter. Golden caramelized top, moist interior - perfect for holidays."
  },
  {
    title: "Gluten-Free Pineapple Stuffing with Brown Sugar Crust",
    slug: "gluten-free-pineapple-stuffing-brown-sugar-crust",
    description: "Buttery baked casserole topped with brown sugar and cinnamon for a dessert-style twist — crispy caramelized top with soft, sweet center.",
    longDescription: "This Gluten-Free Pineapple Stuffing with Brown Sugar Crust elevates the classic recipe with a decadent caramelized topping that's reminiscent of crème brûlée. The base is made with tender gluten-free bread cubes soaked in a sweet pineapple custard, while the top is generously sprinkled with brown sugar and cinnamon that caramelizes into a crispy, candy-like crust during baking. Each bite offers the perfect contrast between the crunchy, sweet top layer and the soft, custardy interior. This version is sweet enough to serve as a dessert but pairs beautifully with savory holiday ham or roasted pork. It's a showstopper that will have guests asking for the recipe.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 50,
    totalTime: 65,
    servings: 12,
    rating: "4.9",
    calories: 245,
    protein: "4.5",
    carbs: "40.0",
    fat: "9.0",
    fiber: "1.5",
    sugar: "24.0",
    image: "/recipe-images/gluten-free-pineapple-stuffing-brown-sugar.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "3/4 cup granulated sugar",
      "4 eggs, beaten",
      "1/2 cup butter, melted",
      "1/2 teaspoon vanilla extract",
      "For topping: 1/2 cup brown sugar",
      "1 teaspoon cinnamon",
      "2 tablespoons butter, melted"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes until slightly dry. Transfer to large bowl.",
      "Mix crushed pineapple, granulated sugar, eggs, melted butter, and vanilla in bowl.",
      "Pour over bread cubes and stir until evenly moistened. Let stand 10 minutes.",
      "Transfer to prepared baking dish and spread evenly.",
      "In small bowl, combine brown sugar and cinnamon. Sprinkle evenly over top.",
      "Drizzle 2 tablespoons melted butter over brown sugar topping.",
      "Bake 45-50 minutes until top is deeply caramelized and crispy.",
      "Let cool 15 minutes before serving to allow crust to set."
    ],
    tips: "Watch carefully during last 10 minutes to prevent burning. The brown sugar will bubble and caramelize. For extra crispy top, broil for 1-2 minutes at the end.",
    variations: [
      "Add chopped macadamia nuts to topping",
      "Use maple sugar instead of brown sugar",
      "Sprinkle with flaky sea salt before serving"
    ],
    tags: ["gluten-free", "pineapple stuffing", "brown sugar", "holiday", "dessert", "sweet", "caramelized", "brunch"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pineapple Stuffing with Brown Sugar Crust - Dessert Side",
    seoDescription: "Sweet pineapple stuffing with caramelized brown sugar cinnamon topping. Crispy crust, soft center - a decadent gluten-free holiday dish."
  },
  {
    title: "Gluten-Free Savory Pineapple & Herb Stuffing",
    slug: "gluten-free-savory-pineapple-herb-stuffing",
    description: "Combines pineapple with sage, thyme, and caramelized onions — perfect as a ham or pork side dish with a sophisticated sweet-savory balance.",
    longDescription: "This Gluten-Free Savory Pineapple & Herb Stuffing is a sophisticated take on the classic that brings together sweet pineapple with aromatic herbs and caramelized onions. Unlike traditional sweet versions, this recipe balances the fruit's natural sweetness with fresh sage, thyme, and deeply caramelized onions that add depth and complexity. It's the perfect accompaniment to roasted ham, pork tenderloin, or turkey, adding a gourmet touch to your holiday table. The herbs infuse the bread with savory aromatics while the pineapple keeps everything moist and adds little bursts of sweetness throughout. This is an excellent choice for those who want the unique flavor of pineapple stuffing but prefer a more savory profile.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 45,
    totalTime: 70,
    servings: 10,
    rating: "4.7",
    calories: 195,
    protein: "6.0",
    carbs: "28.0",
    fat: "7.0",
    fiber: "2.5",
    sugar: "12.0",
    image: "/recipe-images/gluten-free-savory-pineapple-herb-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, drained (reserve 1/2 cup juice)",
      "3 tablespoons butter",
      "2 large onions, thinly sliced",
      "3 eggs, beaten",
      "1/2 cup gluten-free chicken broth",
      "2 tablespoons fresh sage, chopped",
      "1 tablespoon fresh thyme",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "In large skillet, melt butter over medium heat. Add sliced onions and cook 15-20 minutes, stirring occasionally, until deeply caramelized.",
      "Add sage and thyme to onions and cook 1 minute more. Remove from heat.",
      "In bowl, whisk together eggs, reserved pineapple juice, and chicken broth.",
      "Add drained pineapple, caramelized onions with herbs, salt, and pepper to bread cubes. Toss to combine.",
      "Pour egg mixture over bread and stir gently until evenly moistened.",
      "Transfer to prepared baking dish.",
      "Bake 40-45 minutes until top is golden brown.",
      "Let rest 10 minutes before serving."
    ],
    tips: "Don't rush the caramelized onions - they need time to develop deep flavor. Can be made a day ahead and reheated. Draining the pineapple prevents the stuffing from being too wet.",
    variations: [
      "Add crumbled gluten-free sausage",
      "Mix in dried cranberries",
      "Use rosemary instead of thyme"
    ],
    tags: ["gluten-free", "pineapple stuffing", "savory", "herbs", "holiday", "side dish", "onions", "thanksgiving"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Savory Pineapple & Herb Stuffing - Gourmet Holiday Side",
    seoDescription: "Sophisticated pineapple stuffing with caramelized onions, sage, and thyme. Sweet-savory balance perfect for ham or turkey. Gluten-free."
  },
  {
    title: "Gluten-Free Pineapple Stuffing with Ham & Sage",
    slug: "gluten-free-pineapple-stuffing-ham-sage",
    description: "Sweet-salty balance featuring diced ham, herbs, and crushed pineapple — ideal for holiday brunch or Easter dinner with classic flavor.",
    longDescription: "This Gluten-Free Pineapple Stuffing with Ham & Sage is the ultimate sweet and savory combination that's perfect for Easter brunch or any holiday meal. Tender cubes of gluten-free bread are mixed with diced ham, sweet crushed pineapple, and fragrant fresh sage, then baked until golden. The ham adds a salty, smoky element that perfectly balances the sweetness of the pineapple, while the sage provides an earthy, aromatic note. This hearty casserole is substantial enough to serve as a main dish for brunch or a satisfying side dish alongside roasted meats. It's also an excellent way to use up leftover holiday ham, transforming it into something completely new and delicious.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.8",
    calories: 235,
    protein: "11.0",
    carbs: "32.0",
    fat: "8.0",
    fiber: "2.0",
    sugar: "16.0",
    image: "/recipe-images/gluten-free-pineapple-stuffing-ham-sage.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "2 cups cooked ham, diced",
      "1 can (20 oz) crushed pineapple, undrained",
      "3/4 cup sugar",
      "4 eggs, beaten",
      "1/2 cup butter, melted",
      "3 tablespoons fresh sage, chopped",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes until lightly dried.",
      "In large bowl, combine toasted bread cubes and diced ham.",
      "In separate bowl, mix crushed pineapple with juice, sugar, beaten eggs, melted butter, chopped sage, salt, and pepper.",
      "Pour pineapple mixture over bread and ham. Stir gently to combine.",
      "Let stand 10 minutes for bread to absorb liquid.",
      "Transfer to prepared baking dish and spread evenly.",
      "Bake 40-45 minutes until top is golden and edges are slightly crispy.",
      "Let cool 10 minutes before serving."
    ],
    tips: "Use quality deli ham or leftover holiday ham cut into 1/2-inch cubes. Fresh sage is essential for best flavor - dried sage won't give the same aromatic quality.",
    variations: [
      "Add diced bell peppers for color",
      "Use Canadian bacon instead of ham",
      "Mix in shredded Swiss cheese"
    ],
    tags: ["gluten-free", "pineapple stuffing", "ham", "sage", "holiday", "brunch", "easter", "savory-sweet"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pineapple Stuffing with Ham & Sage - Easter Brunch Recipe",
    seoDescription: "Sweet and savory pineapple stuffing loaded with diced ham and fresh sage. Perfect gluten-free side for Easter or holiday brunch."
  },
  {
    title: "Gluten-Free Tropical Pineapple Stuffing with Coconut",
    slug: "gluten-free-tropical-pineapple-stuffing-coconut",
    description: "Pineapple mixed with shredded coconut, almond flour, and vanilla — inspired by island flavors with a sweet, tropical twist.",
    longDescription: "This Gluten-Free Tropical Pineapple Stuffing with Coconut transports your taste buds to a tropical paradise with its combination of sweet pineapple and toasted coconut. The addition of almond flour creates a tender, cake-like texture while vanilla extract enhances the tropical sweetness. Shredded coconut is mixed throughout and sprinkled on top, where it toasts to golden perfection during baking. This version is lighter and sweeter than traditional pineapple stuffing, making it perfect for summer gatherings, luaus, or anyone who loves tropical flavors. It's also naturally dairy-free when made with coconut oil, making it suitable for guests with various dietary restrictions. Serve it as a unique dessert or sweet side dish that will have everyone asking for seconds.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 45,
    totalTime: 60,
    servings: 10,
    rating: "4.7",
    calories: 255,
    protein: "5.0",
    carbs: "38.0",
    fat: "11.0",
    fiber: "3.0",
    sugar: "20.0",
    image: "/recipe-images/gluten-free-tropical-pineapple-stuffing.png",
    ingredients: [
      "7 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "1 cup shredded coconut, divided",
      "1/2 cup almond flour",
      "3/4 cup sugar",
      "4 eggs, beaten",
      "1/2 cup coconut oil, melted",
      "1 teaspoon vanilla extract",
      "1/4 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "Add 3/4 cup shredded coconut and almond flour to bread cubes.",
      "In separate bowl, mix crushed pineapple with juice, sugar, eggs, melted coconut oil, vanilla, and salt.",
      "Pour pineapple mixture over bread mixture and stir until evenly combined.",
      "Let stand 10 minutes for bread to absorb liquid.",
      "Transfer to prepared baking dish. Sprinkle remaining 1/4 cup coconut on top.",
      "Bake 40-45 minutes until top is golden and coconut is toasted.",
      "Cool 10 minutes before serving."
    ],
    tips: "Use unsweetened shredded coconut for less sweetness, or sweetened for a dessert-like dish. Watch the coconut topping during last 10 minutes to prevent burning.",
    variations: [
      "Add diced mango for extra tropical flavor",
      "Mix in macadamia nuts",
      "Drizzle with coconut cream before serving"
    ],
    tags: ["gluten-free", "pineapple stuffing", "coconut", "tropical", "sweet", "dairy-free", "island-inspired", "dessert"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Tropical Pineapple Stuffing with Coconut - Island Recipe",
    seoDescription: "Tropical pineapple stuffing with toasted coconut and almond flour. Sweet, dairy-free, and gluten-free with island-inspired flavors."
  },
  {
    title: "Gluten-Free Pineapple Rum Glazed Stuffing",
    slug: "gluten-free-pineapple-rum-glazed-stuffing",
    description: "A boozy, festive version with spiced rum glaze baked over the top — warm, aromatic, and indulgent for adult holiday gatherings.",
    longDescription: "This Gluten-Free Pineapple Rum Glazed Stuffing is an elegant, grown-up version of the classic that's perfect for festive holiday celebrations. The traditional sweet pineapple base is elevated with a luscious rum glaze infused with warm spices like cinnamon and nutmeg. As it bakes, the glaze caramelizes into a glossy, aromatic coating that's absolutely irresistible. The rum adds depth and complexity without being overwhelming, and most of the alcohol cooks off during baking, leaving behind rich flavor. This sophisticated casserole is ideal for New Year's Eve, Christmas dinner, or any adult gathering where you want to serve something special. Pair it with glazed ham or roasted pork for a truly memorable meal.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 50,
    totalTime: 70,
    servings: 10,
    rating: "4.9",
    calories: 265,
    protein: "5.0",
    carbs: "42.0",
    fat: "9.0",
    fiber: "1.5",
    sugar: "26.0",
    image: "/recipe-images/gluten-free-pineapple-rum-glazed-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "3/4 cup sugar",
      "4 eggs, beaten",
      "1/2 cup butter, melted",
      "For glaze: 1/2 cup brown sugar",
      "1/4 cup spiced rum",
      "2 tablespoons butter",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon nutmeg"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "Mix crushed pineapple, sugar, eggs, and melted butter. Pour over bread and stir. Let stand 10 minutes.",
      "Transfer to prepared baking dish.",
      "For glaze: In small saucepan, combine brown sugar, rum, butter, cinnamon, and nutmeg. Heat over medium, stirring until sugar dissolves and mixture is smooth.",
      "Pour half the glaze over stuffing.",
      "Bake 30 minutes. Pour remaining glaze over top.",
      "Continue baking 15-20 minutes until deeply golden and caramelized.",
      "Let cool 15 minutes to allow glaze to set before serving."
    ],
    tips: "Use a good quality spiced rum for best flavor. The glaze will be thin when hot but thickens as it cools. Can substitute rum extract plus 1/4 cup pineapple juice for non-alcoholic version.",
    variations: [
      "Use dark rum for richer flavor",
      "Add orange zest to the glaze",
      "Top with chopped candied pecans"
    ],
    tags: ["gluten-free", "pineapple stuffing", "rum", "glazed", "holiday", "festive", "adult", "special occasion"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pineapple Rum Glazed Stuffing - Festive Holiday Recipe",
    seoDescription: "Elegant pineapple stuffing with spiced rum glaze. Caramelized, aromatic, and perfect for adult holiday gatherings. Gluten-free indulgence."
  },
  {
    title: "Gluten-Free Vegan Pineapple Stuffing",
    slug: "gluten-free-vegan-pineapple-stuffing",
    description: "Made with flax eggs, coconut oil, and maple syrup — soft, moist, and completely plant-based without sacrificing flavor or texture.",
    longDescription: "This Gluten-Free Vegan Pineapple Stuffing proves that you don't need eggs or dairy to create a delicious, satisfying casserole. Flax eggs provide binding while coconut oil adds richness, and pure maple syrup brings natural sweetness that complements the pineapple perfectly. The result is a tender, moist stuffing with all the classic flavors but made entirely from plant-based ingredients. This recipe is perfect for vegan guests, those with egg or dairy allergies, or anyone looking to enjoy a lighter version of this holiday favorite. It's proof that dietary restrictions don't mean you have to miss out on traditional holiday comfort foods. Even non-vegans will love this naturally sweet, wholesome casserole.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.6",
    calories: 215,
    protein: "3.5",
    carbs: "37.0",
    fat: "7.0",
    fiber: "3.0",
    sugar: "19.0",
    image: "/recipe-images/gluten-free-vegan-pineapple-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "3 flax eggs (3 tablespoons ground flaxseed + 9 tablespoons water)",
      "1/2 cup coconut oil, melted",
      "1/2 cup maple syrup",
      "1/4 cup unsweetened almond milk",
      "1 teaspoon vanilla extract",
      "1/4 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish with coconut oil.",
      "Make flax eggs: Mix ground flaxseed with water and let sit 10 minutes until thick and gel-like.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "In separate bowl, whisk together flax eggs, crushed pineapple with juice, melted coconut oil, maple syrup, almond milk, vanilla, and salt.",
      "Pour mixture over bread cubes and stir gently until bread is evenly moistened.",
      "Let stand 10 minutes for bread to absorb liquid.",
      "Transfer to prepared baking dish.",
      "Bake 40-45 minutes until top is golden brown.",
      "Cool 10 minutes before serving."
    ],
    tips: "Make sure flax eggs gel properly - they should be thick and viscous. Use refined coconut oil if you don't want coconut flavor. Can be made ahead and reheated.",
    variations: [
      "Add chopped walnuts for crunch",
      "Mix in raisins or dried cranberries",
      "Use agave nectar instead of maple syrup"
    ],
    tags: ["gluten-free", "vegan", "pineapple stuffing", "plant-based", "dairy-free", "egg-free", "holiday", "healthy"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Vegan Pineapple Stuffing - Plant-Based Holiday Side",
    seoDescription: "Delicious vegan pineapple stuffing made with flax eggs and maple syrup. Moist, sweet, gluten-free, and completely plant-based."
  },
  {
    title: "Gluten-Free Pineapple Upside-Down Stuffing Cups",
    slug: "gluten-free-pineapple-upside-down-stuffing-cups",
    description: "Individual servings baked in muffin tins with caramelized pineapple rounds — perfect for parties, portion control, and elegant presentation.",
    longDescription: "These Gluten-Free Pineapple Upside-Down Stuffing Cups are a creative, party-perfect take on traditional pineapple stuffing. Each individual portion is baked in a muffin tin with a caramelized pineapple ring and cherry on the bottom, just like the classic upside-down cake. When inverted, the golden, caramelized pineapple becomes a beautiful crown on top of each cup. These portions are not only adorable and Instagram-worthy, but they're also practical - everyone gets their own serving, there's no scooping or serving mess, and they're easy to grab for buffet-style gatherings. They freeze beautifully too, making them ideal for make-ahead entertaining. Guests of all ages love these fun, individual treats that combine nostalgia with convenience.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    servings: 12,
    rating: "4.8",
    calories: 195,
    protein: "4.0",
    carbs: "32.0",
    fat: "7.0",
    fiber: "1.5",
    sugar: "20.0",
    image: "/recipe-images/gluten-free-pineapple-upside-down-cups.png",
    ingredients: [
      "6 cups gluten-free bread cubes",
      "1 can (20 oz) pineapple rings, juice reserved",
      "12 maraschino cherries",
      "1/2 cup brown sugar",
      "1/4 cup butter, melted",
      "3 eggs, beaten",
      "1/2 cup pineapple juice",
      "1/2 cup granulated sugar",
      "1/4 cup butter, melted (additional)",
      "1/2 teaspoon vanilla"
    ],
    instructions: [
      "Preheat oven to 350°F. Generously grease a 12-cup muffin tin.",
      "Place 1 teaspoon brown sugar in bottom of each muffin cup.",
      "Drizzle a little melted butter over brown sugar in each cup.",
      "Cut pineapple rings to fit muffin cups and place one in each. Put cherry in center of each ring.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "In separate bowl, whisk together eggs, pineapple juice, granulated sugar, 1/4 cup melted butter, and vanilla.",
      "Pour over bread cubes and mix until moistened.",
      "Spoon bread mixture into muffin cups over pineapple, filling to top.",
      "Bake 25-30 minutes until golden and set.",
      "Cool 5 minutes, then run knife around edges and invert onto serving platter."
    ],
    tips: "Grease muffin tin very well to ensure cups release cleanly. Invert while still warm for best results. If pineapple sticks, use a small spatula to help release.",
    variations: [
      "Use fresh pineapple instead of canned",
      "Add crushed pecans to brown sugar layer",
      "Drizzle with caramel sauce before serving"
    ],
    tags: ["gluten-free", "pineapple stuffing", "individual portions", "party food", "upside-down", "elegant", "make-ahead", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pineapple Upside-Down Stuffing Cups - Party-Perfect Recipe",
    seoDescription: "Individual pineapple stuffing cups with caramelized pineapple tops. Perfect gluten-free appetizer or side for parties and entertaining."
  },
  {
    title: "Gluten-Free Cinnamon-Pecan Pineapple Stuffing",
    slug: "gluten-free-cinnamon-pecan-pineapple-stuffing",
    description: "Sweet variation loaded with toasted pecans and warm cinnamon — excellent as a dessert or breakfast side with comforting spice.",
    longDescription: "This Gluten-Free Cinnamon-Pecan Pineapple Stuffing is a warm, comforting variation that's perfect for cool mornings or cozy holiday gatherings. The classic sweet pineapple base is enhanced with aromatic cinnamon and studded with toasted pecans that add wonderful crunch and nutty flavor. As it bakes, your kitchen fills with the irresistible aroma of cinnamon and caramelizing sugar. This version is sweet enough to serve as a dessert but works equally well as a special breakfast or brunch dish. The pecans can be mixed throughout or sprinkled on top for extra crunch. It's reminiscent of a coffee cake but with the unique texture and flavor that only pineapple stuffing can provide. Serve it warm with a dollop of whipped cream or vanilla ice cream for an unforgettable treat.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.8",
    calories: 270,
    protein: "5.0",
    carbs: "39.0",
    fat: "12.0",
    fiber: "2.5",
    sugar: "22.0",
    image: "/recipe-images/gluten-free-cinnamon-pecan-pineapple-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, undrained",
      "1 cup pecans, chopped and toasted",
      "3/4 cup sugar",
      "4 eggs, beaten",
      "1/2 cup butter, melted",
      "2 teaspoons cinnamon",
      "1/2 teaspoon vanilla extract",
      "1/4 teaspoon nutmeg"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast pecans in dry skillet over medium heat for 3-5 minutes until fragrant. Set aside.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "Add 3/4 cup toasted pecans to bread (reserve 1/4 cup for topping).",
      "In separate bowl, mix crushed pineapple with juice, sugar, eggs, melted butter, cinnamon, vanilla, and nutmeg.",
      "Pour over bread and pecans. Stir until evenly combined.",
      "Let stand 10 minutes.",
      "Transfer to prepared baking dish. Sprinkle remaining pecans on top.",
      "Bake 40-45 minutes until golden brown and set.",
      "Cool 10 minutes before serving. Serve warm."
    ],
    tips: "Toast pecans before adding for deeper flavor. Can be served as breakfast with maple syrup drizzled on top. Stores well and tastes great reheated.",
    variations: [
      "Add diced apples to the mixture",
      "Use walnuts instead of pecans",
      "Drizzle with cream cheese glaze"
    ],
    tags: ["gluten-free", "pineapple stuffing", "pecans", "cinnamon", "sweet", "dessert", "breakfast", "brunch"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cinnamon-Pecan Pineapple Stuffing - Sweet Breakfast Side",
    seoDescription: "Sweet pineapple stuffing with toasted pecans and warm cinnamon. Perfect gluten-free dessert or breakfast casserole for holidays."
  },
  {
    title: "Gluten-Free Pineapple Cheese Stuffing",
    slug: "gluten-free-pineapple-cheese-stuffing",
    description: "Sweet and savory fusion using cream cheese and cheddar for a rich, tangy twist on the classic casserole — unexpectedly delicious.",
    longDescription: "This Gluten-Free Pineapple Cheese Stuffing is an unexpected but absolutely delicious combination that will surprise and delight your guests. The addition of cream cheese creates an incredibly rich, creamy texture, while sharp cheddar adds a savory, tangy element that perfectly balances the sweet pineapple. The result is a unique sweet-and-savory dish that's hard to categorize - it works as a side dish with ham or turkey, a brunch casserole, or even a unique dessert. The cheese melts throughout, creating pockets of creamy richness, while the top gets golden and slightly crispy. This recipe is perfect for adventurous eaters and anyone who loves the combination of sweet and savory flavors. It's become a surprise favorite at many holiday tables and always generates conversation.",
    category: "Holiday",
    subcategory: "Pineapple Stuffing",
    difficulty: "Easy",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 10,
    rating: "4.7",
    calories: 285,
    protein: "8.0",
    carbs: "36.0",
    fat: "13.0",
    fiber: "1.5",
    sugar: "19.0",
    image: "/recipe-images/gluten-free-pineapple-cheese-stuffing.png",
    ingredients: [
      "8 cups gluten-free bread cubes",
      "1 can (20 oz) crushed pineapple, drained",
      "8 oz cream cheese, softened and cubed",
      "1 cup sharp cheddar cheese, shredded",
      "3/4 cup sugar",
      "4 eggs, beaten",
      "1/2 cup butter, melted",
      "1/2 teaspoon salt"
    ],
    instructions: [
      "Preheat oven to 350°F. Grease a 9x13 inch baking dish.",
      "Toast bread cubes in oven for 10 minutes. Transfer to large bowl.",
      "Add cubed cream cheese and 3/4 cup shredded cheddar to bread cubes.",
      "In separate bowl, mix drained pineapple, sugar, beaten eggs, melted butter, and salt.",
      "Pour pineapple mixture over bread and cheese. Stir gently - cream cheese will remain in chunks.",
      "Let stand 10 minutes for bread to absorb liquid.",
      "Transfer to prepared baking dish.",
      "Sprinkle remaining 1/4 cup cheddar on top.",
      "Bake 40-45 minutes until golden brown and cheese is melted.",
      "Cool 10 minutes to allow cheese to set slightly before serving."
    ],
    tips: "Don't overmix - the cream cheese chunks will melt during baking to create creamy pockets. Use full-fat cream cheese for best texture. Great with spiral-cut ham.",
    variations: [
      "Add diced jalapeños for heat",
      "Use Gruyere instead of cheddar",
      "Mix in crumbled bacon"
    ],
    tags: ["gluten-free", "pineapple stuffing", "cheese", "cream cheese", "sweet-savory", "unique", "holiday", "brunch"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pineapple Cheese Stuffing - Sweet & Savory Holiday Side",
    seoDescription: "Unique pineapple stuffing with cream cheese and cheddar. Rich, creamy, sweet-savory fusion that's perfect for holidays. Gluten-free."
  }
];

async function addPineappleStuffingRecipes() {
  console.log("Adding 10 Pineapple Stuffing recipes to database...");
  
  try {
    for (const recipe of pineappleStuffingRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`✓ Added: ${recipe.title}`);
    }
    
    console.log("\n✅ All 10 Pineapple Stuffing recipes added successfully!");
    console.log("Remember to move images to client/public/recipe-images/!");
  } catch (error) {
    console.error("Error adding recipes:", error);
  }
  
  process.exit(0);
}

addPineappleStuffingRecipes();
