import { db } from "../server/db";
import { recipes } from "../shared/schema";
import { nanoid } from "nanoid";

const cauliflowerZitiRecipes = [
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Ricotta & Marinara",
    slug: "gluten-free-cauliflower-ziti-ricotta-marinara",
    seoTitle: "Gluten-Free Cauliflower Baked Ziti - Classic Italian Comfort Food",
    description: "Classic version — roasted cauliflower layered with marinara, ricotta, mozzarella, and Parmesan — rich and satisfying low-carb dinner.",
    longDescription: "This gluten-free cauliflower baked ziti with ricotta and marinara is the perfect low-carb alternative to traditional pasta ziti, delivering all the comfort and satisfaction without the gluten or carbs. Cauliflower florets are roasted until golden and slightly caramelized, then layered with rich marinara sauce, creamy ricotta cheese, and topped with bubbling mozzarella and Parmesan. The roasted cauliflower mimics the texture of al dente pasta while adding extra nutrients and fiber. This classic version honors traditional Italian flavors while making the dish lighter and more vegetable-forward. It's perfect for those following gluten-free or low-carb diets who don't want to sacrifice the comforting, cheesy satisfaction of baked ziti. Serve it with a simple green salad and garlic bread for the complete Italian experience.",
    seoDescription: "Gluten-free cauliflower baked ziti with ricotta and marinara. Classic low-carb Italian comfort food with roasted cauliflower and cheese.",
    category: "Dinner",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-cauliflower-ziti-ricotta-marinara.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "3 cups marinara sauce (gluten-free)",
      "15 oz ricotta cheese",
      "2 cups shredded mozzarella cheese",
      "1/2 cup grated Parmesan cheese",
      "2 cloves garlic, minced",
      "1 teaspoon Italian seasoning",
      "1/2 teaspoon red pepper flakes (optional)",
      "Salt and pepper to taste",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Line a baking sheet with parchment paper.",
      "Toss cauliflower florets with olive oil, salt, and pepper. Spread on baking sheet.",
      "Roast cauliflower for 25-30 minutes until golden and tender, stirring halfway through.",
      "Reduce oven temperature to 375°F.",
      "In a bowl, mix ricotta with half the Parmesan, garlic, Italian seasoning, salt, and pepper.",
      "In a 9x13-inch baking dish, spread 1 cup marinara sauce on the bottom.",
      "Layer half the roasted cauliflower over the sauce.",
      "Dollop half the ricotta mixture over cauliflower, then spread 1 cup marinara.",
      "Sprinkle with 1 cup mozzarella.",
      "Repeat layers with remaining cauliflower, ricotta, and marinara.",
      "Top with remaining mozzarella and Parmesan cheese.",
      "Cover with foil and bake for 25 minutes.",
      "Remove foil and bake 10-15 minutes more until cheese is golden and bubbly.",
      "Let rest 10 minutes. Garnish with fresh basil and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "Italian", "low-carb", "ricotta", "marinara", "vegetarian", "comfort food", "dinner"],
    nutrition: {
      calories: 320,
      protein: "19g",
      carbs: "22g",
      fat: "18g",
      fiber: "6g",
      sodium: "780mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Spinach & Mozzarella",
    slug: "gluten-free-cauliflower-ziti-spinach-mozzarella",
    seoTitle: "Gluten-Free Cauliflower Ziti with Spinach - Healthy Italian Dinner",
    description: "Creamy spinach folded into marinara sauce with roasted cauliflower and melty mozzarella topping — nutritious and delicious.",
    longDescription: "This gluten-free cauliflower baked ziti with spinach and mozzarella combines the heartiness of roasted cauliflower with the nutritional powerhouse of fresh spinach, all bound together in rich marinara and topped with melted mozzarella. The spinach wilts into the sauce, adding vibrant color, iron, and vitamins while complementing the cauliflower's mild flavor. This version is particularly nutrient-dense, packing in vegetables while maintaining the comfort food appeal of traditional baked ziti. The combination of cauliflower and spinach creates interesting textures and makes this dish feel extra wholesome. It's perfect for sneaking more greens into your family's diet without sacrificing flavor or satisfaction.",
    seoDescription: "Gluten-free cauliflower baked ziti with spinach and mozzarella. Healthy low-carb Italian dinner packed with vegetables.",
    category: "Dinner",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-cauliflower-ziti-spinach-mozzarella.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "4 cups fresh spinach",
      "3 cups marinara sauce (gluten-free)",
      "15 oz ricotta cheese",
      "2.5 cups shredded mozzarella cheese",
      "1/2 cup grated Parmesan",
      "3 cloves garlic, minced",
      "1 teaspoon Italian seasoning",
      "1/4 teaspoon nutmeg",
      "Salt and pepper to taste",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with 2 tablespoons olive oil, salt, and pepper. Roast on a baking sheet for 25-30 minutes until golden.",
      "Reduce oven to 375°F.",
      "In a large skillet, heat remaining olive oil. Add garlic and cook for 1 minute.",
      "Add spinach and cook until wilted, about 2-3 minutes.",
      "Stir in marinara sauce and Italian seasoning. Simmer for 5 minutes.",
      "In a bowl, mix ricotta with Parmesan, nutmeg, salt, and pepper.",
      "In a 9x13-inch baking dish, spread one-third of the spinach-marinara sauce.",
      "Layer half the roasted cauliflower, then dollop half the ricotta mixture.",
      "Sprinkle with 1 cup mozzarella.",
      "Repeat layers: sauce, cauliflower, ricotta, and another cup of mozzarella.",
      "Top with remaining sauce and mozzarella.",
      "Cover with foil and bake for 25 minutes.",
      "Uncover and bake 10-15 minutes until golden and bubbly.",
      "Rest 10 minutes, garnish with basil, and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "spinach", "Italian", "low-carb", "vegetarian", "healthy", "dinner", "nutritious"],
    nutrition: {
      calories: 335,
      protein: "20g",
      carbs: "23g",
      fat: "19g",
      fiber: "7g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Sausage & Peppers",
    slug: "gluten-free-cauliflower-ziti-sausage-peppers",
    seoTitle: "Gluten-Free Cauliflower Ziti with Sausage - Hearty Italian Dinner",
    description: "Spicy Italian sausage, sautéed bell peppers, and roasted cauliflower baked in zesty tomato sauce — hearty and flavorful.",
    longDescription: "This gluten-free cauliflower baked ziti with sausage and peppers is a hearty, protein-packed version that satisfies even the biggest appetites. Spicy Italian sausage is browned until crispy, then combined with colorful sautéed bell peppers for a classic Italian flavor combination. The roasted cauliflower provides substance while the sausage delivers bold, savory flavor. This dish is perfect for meat lovers who want to enjoy Italian comfort food while incorporating more vegetables. The peppers add natural sweetness and color, while the sausage fat enriches the tomato sauce. It's a complete meal in one dish — protein, vegetables, and plenty of melted cheese all baked together until golden and irresistible.",
    seoDescription: "Gluten-free cauliflower baked ziti with Italian sausage and peppers. Hearty low-carb dinner with bold Italian flavors.",
    category: "Dinner",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-sausage-peppers.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "1 lb Italian sausage (gluten-free), casings removed",
      "2 bell peppers (red and yellow), sliced",
      "1 onion, diced",
      "3 cups marinara sauce (gluten-free)",
      "2 cups shredded mozzarella",
      "1/2 cup grated Parmesan",
      "3 cloves garlic, minced",
      "1 teaspoon Italian seasoning",
      "1/2 teaspoon red pepper flakes",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with 2 tablespoons olive oil, salt, and pepper. Roast for 25-30 minutes until golden.",
      "In a large skillet, heat remaining olive oil. Cook sausage, breaking it up, until browned, about 6-8 minutes. Remove and set aside.",
      "In the same skillet, sauté onion and bell peppers for 5-6 minutes until softened.",
      "Add garlic and cook for 1 minute.",
      "Return sausage to skillet. Add marinara sauce, Italian seasoning, and red pepper flakes. Simmer for 5 minutes.",
      "Reduce oven to 375°F.",
      "In a 9x13-inch baking dish, combine roasted cauliflower with sausage-pepper mixture.",
      "Toss everything together well.",
      "Sprinkle with mozzarella and Parmesan cheese.",
      "Cover with foil and bake for 20 minutes.",
      "Uncover and bake 10-15 minutes until cheese is golden and bubbly.",
      "Let rest 10 minutes. Garnish with fresh parsley and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "Italian sausage", "peppers", "Italian", "low-carb", "hearty", "dinner", "protein-rich"],
    nutrition: {
      calories: 420,
      protein: "26g",
      carbs: "24g",
      fat: "26g",
      fiber: "6g",
      sodium: "920mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti Alfredo",
    slug: "gluten-free-cauliflower-ziti-alfredo",
    seoTitle: "Gluten-Free Cauliflower Ziti Alfredo - Creamy Low-Carb Dinner",
    description: "White sauce variation with creamy Alfredo, garlic, and a mix of cheeses — indulgent and low-carb comfort food.",
    longDescription: "This gluten-free cauliflower baked ziti Alfredo is an indulgent, creamy white sauce version that rivals any traditional pasta dish. Rich Alfredo sauce made with butter, cream, garlic, and Parmesan coats tender roasted cauliflower florets, then everything is topped with a blend of melted cheeses. This is pure comfort food — rich, creamy, and satisfying — but with the added benefits of cauliflower's nutrients and fiber. The Alfredo sauce clings beautifully to the cauliflower's nooks and crannies, just like it would to pasta. Perfect for special occasions or when you want to treat yourself to something truly decadent while staying gluten-free and low-carb. Serve with a crisp green salad to balance the richness.",
    seoDescription: "Gluten-free cauliflower baked ziti Alfredo. Creamy, indulgent low-carb Italian dinner with white sauce and cheese.",
    category: "Dinner",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-alfredo.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "2 tablespoons olive oil",
      "4 tablespoons butter",
      "4 cloves garlic, minced",
      "2 cups heavy cream",
      "1.5 cups grated Parmesan cheese",
      "1.5 cups shredded mozzarella cheese",
      "1/2 cup shredded fontina or provolone",
      "1/4 teaspoon nutmeg",
      "Salt and white pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with olive oil, salt, and pepper. Roast for 25-30 minutes until golden and tender.",
      "Reduce oven to 375°F.",
      "In a large saucepan, melt butter over medium heat. Add garlic and cook for 1-2 minutes until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer.",
      "Reduce heat to low and stir in 1 cup Parmesan cheese. Cook, stirring, until cheese melts and sauce thickens, about 5-6 minutes.",
      "Season with nutmeg, salt, and white pepper.",
      "In a 9x13-inch baking dish, combine roasted cauliflower with Alfredo sauce. Toss well to coat.",
      "Top with mozzarella, fontina, and remaining Parmesan cheese.",
      "Cover with foil and bake for 20 minutes.",
      "Remove foil and bake 10-15 minutes more until cheese is golden and bubbling.",
      "Let rest 10 minutes. Garnish with fresh parsley and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "Alfredo", "Italian", "low-carb", "creamy", "indulgent", "dinner", "white sauce"],
    nutrition: {
      calories: 485,
      protein: "21g",
      carbs: "16g",
      fat: "40g",
      fiber: "5g",
      sodium: "680mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Pesto & Chicken",
    slug: "gluten-free-cauliflower-ziti-pesto-chicken",
    seoTitle: "Gluten-Free Cauliflower Ziti with Pesto - High-Protein Dinner",
    description: "Fresh basil pesto with roasted chicken and mozzarella — aromatic and high-protein Italian dinner.",
    longDescription: "This gluten-free cauliflower baked ziti with pesto and chicken is a vibrant, aromatic dish that showcases the bright flavors of fresh basil pesto. Tender roasted chicken breast is combined with golden cauliflower, all tossed in fragrant basil pesto made with garlic, pine nuts, Parmesan, and olive oil. The result is a dish that's both lighter and more flavorful than traditional red sauce versions. The pesto coats every piece of cauliflower and chicken, delivering intense herbal flavor in every bite. This high-protein version is perfect for those looking for a satisfying, nutritious meal that feels special. The combination of green pesto and golden cauliflower makes this visually stunning as well as delicious.",
    seoDescription: "Gluten-free cauliflower baked ziti with pesto and chicken. Aromatic, high-protein low-carb Italian dinner with fresh basil.",
    category: "Dinner",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-pesto-chicken.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "1.5 lbs boneless chicken breasts",
      "1 cup basil pesto (store-bought or homemade gluten-free)",
      "1/2 cup heavy cream",
      "2 cups shredded mozzarella cheese",
      "1/2 cup grated Parmesan cheese",
      "1/4 cup pine nuts",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
      "Fresh basil leaves for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with 2 tablespoons olive oil, salt, and pepper. Roast for 25-30 minutes until golden.",
      "Season chicken with salt and pepper. Heat remaining olive oil in a skillet and cook chicken for 6-7 minutes per side until cooked through. Let rest, then dice into bite-sized pieces.",
      "Reduce oven to 375°F.",
      "In a large bowl, whisk together pesto and heavy cream until well combined.",
      "Add roasted cauliflower, diced chicken, and half the mozzarella and Parmesan to the pesto mixture. Toss well to coat.",
      "Transfer to a 9x13-inch baking dish.",
      "Top with remaining mozzarella and Parmesan. Scatter pine nuts over the top.",
      "Cover with foil and bake for 20 minutes.",
      "Remove foil and bake 10-12 minutes more until cheese is golden and pine nuts are toasted.",
      "Let rest 10 minutes. Garnish with fresh basil and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "pesto", "chicken", "Italian", "low-carb", "high-protein", "dinner", "aromatic"],
    nutrition: {
      calories: 445,
      protein: "36g",
      carbs: "14g",
      fat: "29g",
      fiber: "5g",
      sodium: "620mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Eggplant & Tomato",
    slug: "gluten-free-cauliflower-ziti-eggplant-tomato",
    seoTitle: "Gluten-Free Cauliflower Ziti with Eggplant - Mediterranean Dinner",
    description: "Vegetarian Mediterranean version — roasted eggplant, cherry tomatoes, and creamy ricotta blend — wholesome and flavorful.",
    longDescription: "This gluten-free cauliflower baked ziti with eggplant and tomato is a Mediterranean-inspired vegetarian masterpiece that celebrates the flavors of summer. Roasted eggplant adds a meaty texture and subtle smokiness, while cherry tomatoes burst with sweetness. Combined with roasted cauliflower, creamy ricotta, and melted mozzarella, this dish is both wholesome and deeply satisfying. The eggplant and cauliflower roast together, developing rich, caramelized flavors that complement the bright tomatoes and fresh basil. This is perfect for vegetarians or anyone looking to eat more plant-based meals without sacrificing comfort or flavor. The variety of vegetables makes this particularly nutrient-dense and colorful.",
    seoDescription: "Gluten-free cauliflower baked ziti with eggplant and cherry tomatoes. Mediterranean vegetarian low-carb dinner.",
    category: "Dinner",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-eggplant-tomato.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "1 large eggplant, cubed",
      "4 tablespoons olive oil",
      "2 cups cherry tomatoes, halved",
      "2.5 cups marinara sauce (gluten-free)",
      "15 oz ricotta cheese",
      "2 cups shredded mozzarella",
      "1/2 cup grated Parmesan",
      "3 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "Fresh basil leaves",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Preheat oven to 425°F. Line two baking sheets with parchment paper.",
      "Toss cauliflower with 2 tablespoons olive oil, salt, and pepper. Spread on one baking sheet.",
      "Toss eggplant cubes with remaining olive oil, salt, and pepper. Spread on the second baking sheet.",
      "Roast both for 25-30 minutes until golden and tender, stirring halfway through.",
      "Reduce oven to 375°F.",
      "In a bowl, mix ricotta with half the Parmesan, oregano, salt, and pepper.",
      "In a 9x13-inch baking dish, spread 1 cup marinara sauce.",
      "Layer half the roasted cauliflower and eggplant, then scatter half the cherry tomatoes.",
      "Dollop half the ricotta mixture over vegetables, then spread 1 cup marinara.",
      "Sprinkle with 1 cup mozzarella.",
      "Repeat layers with remaining vegetables, tomatoes, ricotta, and marinara.",
      "Top with remaining mozzarella and Parmesan. Scatter fresh basil leaves.",
      "Cover with foil and bake for 25 minutes.",
      "Uncover and bake 12-15 minutes until golden. Rest 10 minutes and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "eggplant", "vegetarian", "Mediterranean", "Italian", "low-carb", "dinner", "wholesome"],
    nutrition: {
      calories: 350,
      protein: "19g",
      carbs: "26g",
      fat: "20g",
      fiber: "8g",
      sodium: "760mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Meatballs & Marinara",
    slug: "gluten-free-cauliflower-ziti-meatballs",
    seoTitle: "Gluten-Free Cauliflower Ziti with Meatballs - Hearty Italian Dinner",
    description: "Mini gluten-free meatballs baked with roasted cauliflower, mozzarella, and extra sauce for comfort-food perfection.",
    longDescription: "This gluten-free cauliflower baked ziti with meatballs and marinara is the ultimate comfort food, combining tender mini meatballs with roasted cauliflower in rich marinara sauce, all topped with bubbling mozzarella. The meatballs are made with gluten-free breadcrumbs and baked until perfectly browned, then nestled among the cauliflower florets. This dish delivers all the satisfaction of spaghetti and meatballs but in a low-carb, gluten-free format. The extra sauce keeps everything moist and flavorful, while the cheese brings everything together. Kids and adults alike love this version — it's hearty, filling, and packed with protein. Perfect for Sunday dinner or whenever you need serious comfort food.",
    seoDescription: "Gluten-free cauliflower baked ziti with meatballs and marinara. Hearty low-carb Italian comfort food with mini meatballs.",
    category: "Dinner",
    prepTime: 30,
    cookTime: 55,
    totalTime: 85,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-meatballs.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "For meatballs:",
      "1 lb ground beef",
      "1/4 cup gluten-free breadcrumbs",
      "1 egg",
      "1/4 cup grated Parmesan",
      "2 cloves garlic, minced",
      "1 teaspoon Italian seasoning",
      "Salt and pepper",
      "For assembly:",
      "3.5 cups marinara sauce (gluten-free)",
      "2.5 cups shredded mozzarella",
      "1/2 cup grated Parmesan",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with 2 tablespoons olive oil, salt, and pepper. Roast for 25-30 minutes until golden.",
      "While cauliflower roasts, make meatballs: Mix ground beef, breadcrumbs, egg, Parmesan, garlic, Italian seasoning, salt, and pepper.",
      "Form into 20-24 mini meatballs (about 1 inch each).",
      "Heat remaining olive oil in a large skillet. Brown meatballs on all sides, about 8-10 minutes. They don't need to be fully cooked through.",
      "Reduce oven to 375°F.",
      "In a 9x13-inch baking dish, spread 1 cup marinara sauce.",
      "Add roasted cauliflower and meatballs, distributing evenly.",
      "Pour remaining marinara sauce over everything, making sure meatballs are covered.",
      "Sprinkle with mozzarella and Parmesan cheese.",
      "Cover with foil and bake for 30 minutes.",
      "Remove foil and bake 12-15 minutes until cheese is golden and meatballs are cooked through.",
      "Let rest 10 minutes. Garnish with fresh basil and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "meatballs", "Italian", "low-carb", "comfort food", "dinner", "hearty", "marinara"],
    nutrition: {
      calories: 465,
      protein: "32g",
      carbs: "24g",
      fat: "27g",
      fiber: "6g",
      sodium: "880mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Four Cheeses",
    slug: "gluten-free-cauliflower-ziti-four-cheese",
    seoTitle: "Gluten-Free Four Cheese Cauliflower Ziti - Ultra Cheesy Dinner",
    description: "A cheese lover's dream — ricotta, mozzarella, fontina, and Parmesan with roasted garlic — indulgent and creamy.",
    longDescription: "This gluten-free cauliflower baked ziti with four cheeses is an ultra-indulgent dish for serious cheese lovers. Roasted cauliflower is enveloped in a blend of four distinct cheeses: creamy ricotta, melty mozzarella, nutty fontina, and sharp Parmesan. Roasted garlic adds sweet, mellow depth that complements all the cheeses beautifully. The combination creates layers of flavor and texture — creamy, stretchy, sharp, and nutty all at once. This is pure decadence while still being gluten-free and lower in carbs than traditional pasta. Perfect for special occasions or when you want to treat yourself to something truly luxurious. Serve with a crisp salad to balance the richness of all that glorious cheese.",
    seoDescription: "Gluten-free four cheese cauliflower baked ziti. Ultra cheesy low-carb Italian dinner with ricotta, mozzarella, fontina, and Parmesan.",
    category: "Dinner",
    prepTime: 25,
    cookTime: 50,
    totalTime: 75,
    servings: 6,
    difficulty: "Medium",
    image: "/recipe-images/gluten-free-cauliflower-ziti-four-cheese.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "1 head garlic, roasted",
      "15 oz ricotta cheese",
      "1.5 cups shredded mozzarella cheese",
      "1 cup shredded fontina cheese",
      "1 cup grated Parmesan cheese",
      "1 cup marinara sauce (gluten-free)",
      "1/2 cup heavy cream",
      "1 teaspoon Italian seasoning",
      "1/4 teaspoon nutmeg",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Roast garlic: Cut top off head of garlic, drizzle with oil, wrap in foil, and roast at 400°F for 35-40 minutes until soft. Squeeze out cloves and mash.",
      "Preheat oven to 425°F. Toss cauliflower with olive oil, salt, and pepper. Roast for 25-30 minutes until golden.",
      "Reduce oven to 375°F.",
      "In a large bowl, combine ricotta, half the mozzarella, half the fontina, half the Parmesan, roasted garlic, Italian seasoning, nutmeg, salt, and pepper. Mix well.",
      "In another bowl, mix marinara sauce with heavy cream.",
      "In a 9x13-inch baking dish, spread half the marinara-cream sauce.",
      "Add roasted cauliflower and toss to coat.",
      "Dollop ricotta-cheese mixture over cauliflower.",
      "Pour remaining sauce over the top.",
      "Sprinkle with remaining mozzarella, fontina, and Parmesan.",
      "Cover with foil and bake for 25 minutes.",
      "Remove foil and bake 15-18 minutes until cheese is golden and bubbling.",
      "Let rest 10 minutes. Garnish with parsley and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "four cheese", "Italian", "low-carb", "indulgent", "dinner", "ultra cheesy", "roasted garlic"],
    nutrition: {
      calories: 495,
      protein: "27g",
      carbs: "20g",
      fat: "36g",
      fiber: "5g",
      sodium: "820mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Cauliflower Baked Ziti with Spicy Arrabbiata Sauce",
    slug: "gluten-free-cauliflower-ziti-arrabbiata",
    seoTitle: "Gluten-Free Spicy Cauliflower Ziti - Arrabbiata Style Dinner",
    description: "A fiery twist — roasted cauliflower baked in spicy tomato sauce with crushed red pepper and provolone — bold and flavorful.",
    longDescription: "This gluten-free cauliflower baked ziti with spicy arrabbiata sauce is for those who love heat with their Italian food. The classic arrabbiata sauce — made with tomatoes, garlic, and lots of crushed red pepper — coats tender roasted cauliflower, creating a dish that's both fiery and satisfying. Provolone cheese adds a slightly sharp, smoky flavor that complements the spicy sauce perfectly. The heat level can be adjusted to your preference, making this as mild or as volcanic as you like. This bold version is perfect for spice lovers who want their comfort food with a kick. The cauliflower holds up beautifully to the intense flavors, absorbing the spicy sauce while maintaining its texture.",
    seoDescription: "Gluten-free spicy cauliflower baked ziti with arrabbiata sauce. Bold, fiery low-carb Italian dinner with crushed red pepper.",
    category: "Dinner",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-cauliflower-ziti-arrabbiata.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "3 tablespoons olive oil",
      "3 cups crushed tomatoes",
      "6 cloves garlic, minced",
      "1-2 tablespoons crushed red pepper flakes (adjust to taste)",
      "1 teaspoon dried oregano",
      "2 cups shredded provolone cheese",
      "1/2 cup grated Parmesan",
      "1/4 cup fresh parsley, chopped",
      "Salt to taste",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with 2 tablespoons olive oil and salt. Roast for 25-30 minutes until golden and tender.",
      "While cauliflower roasts, make arrabbiata sauce: Heat remaining olive oil in a large saucepan over medium heat.",
      "Add garlic and cook for 1-2 minutes until fragrant but not browned.",
      "Add crushed tomatoes, red pepper flakes, oregano, and salt.",
      "Simmer for 12-15 minutes, stirring occasionally, until sauce thickens.",
      "Stir in fresh parsley.",
      "Reduce oven to 375°F.",
      "In a 9x13-inch baking dish, combine roasted cauliflower with arrabbiata sauce. Toss well.",
      "Top with provolone and Parmesan cheese.",
      "Cover with foil and bake for 20 minutes.",
      "Remove foil and bake 10-12 minutes more until cheese is melted and bubbly.",
      "Let rest 10 minutes. Garnish with fresh basil and serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "arrabbiata", "spicy", "Italian", "low-carb", "dinner", "bold flavors", "fiery"],
    nutrition: {
      calories: 305,
      protein: "17g",
      carbs: "20g",
      fat: "18g",
      fiber: "6g",
      sodium: "720mg"
    },
    isNaturallyGlutenFree: true
  },
  {
    title: "Gluten-Free Creamy Cauliflower Baked Ziti with Sun-Dried Tomatoes & Basil",
    slug: "gluten-free-cauliflower-ziti-sun-dried-tomato",
    seoTitle: "Gluten-Free Cauliflower Ziti with Sun-Dried Tomatoes - Creamy Dinner",
    description: "Light, tangy, and flavorful — baked with cream sauce, sun-dried tomatoes, and fresh basil — elegant Italian dinner.",
    longDescription: "This gluten-free creamy cauliflower baked ziti with sun-dried tomatoes and basil is an elegant, sophisticated take on the classic. Sun-dried tomatoes provide intense, concentrated tomato flavor and a slight tanginess that brightens the rich cream sauce. Fresh basil adds aromatic freshness, while the cream sauce brings everything together in luxurious harmony. This version feels lighter than traditional red sauce but is still incredibly satisfying. The sun-dried tomatoes and basil make it perfect for spring and summer, though it's delicious year-round. This is the kind of dish you serve when you want to impress guests while keeping things gluten-free and relatively light. The combination of flavors is both familiar and exciting.",
    seoDescription: "Gluten-free creamy cauliflower baked ziti with sun-dried tomatoes and basil. Elegant, tangy low-carb Italian dinner.",
    category: "Dinner",
    prepTime: 20,
    cookTime: 45,
    totalTime: 65,
    servings: 6,
    difficulty: "Easy",
    image: "/recipe-images/gluten-free-cauliflower-ziti-sun-dried-tomato.png",
    ingredients: [
      "1 large head cauliflower, cut into florets",
      "2 tablespoons olive oil",
      "1 cup sun-dried tomatoes in oil, drained and chopped",
      "1.5 cups heavy cream",
      "1/2 cup chicken or vegetable broth",
      "3 cloves garlic, minced",
      "2 cups shredded mozzarella cheese",
      "3/4 cup grated Parmesan cheese",
      "1/2 cup fresh basil leaves, torn",
      "1 teaspoon Italian seasoning",
      "Salt and pepper to taste",
      "Fresh basil and Parmesan shavings for garnish"
    ],
    instructions: [
      "Preheat oven to 425°F. Toss cauliflower with olive oil, salt, and pepper. Roast for 25-30 minutes until golden and tender.",
      "Reduce oven to 375°F.",
      "In a large saucepan, combine heavy cream and broth. Bring to a gentle simmer over medium heat.",
      "Add garlic and cook for 1-2 minutes.",
      "Stir in half the Parmesan cheese and Italian seasoning. Cook until cheese melts and sauce thickens slightly, about 5 minutes.",
      "Add sun-dried tomatoes and half the fresh basil. Simmer for 2 minutes. Season with salt and pepper.",
      "In a 9x13-inch baking dish, combine roasted cauliflower with the cream sauce. Toss well to coat.",
      "Top with mozzarella and remaining Parmesan.",
      "Cover with foil and bake for 20 minutes.",
      "Remove foil and bake 12-15 minutes until cheese is golden and bubbly.",
      "Let rest 10 minutes. Garnish with remaining fresh basil and Parmesan shavings. Serve."
    ],
    tags: ["gluten-free", "cauliflower", "baked ziti", "sun-dried tomatoes", "basil", "creamy", "Italian", "low-carb", "dinner", "elegant"],
    nutrition: {
      calories: 425,
      protein: "18g",
      carbs: "18g",
      fat: "34g",
      fiber: "5g",
      sodium: "660mg"
    },
    isNaturallyGlutenFree: true
  }
];

async function addRecipes() {
  console.log("Adding 10 Gluten-Free Cauliflower Baked Ziti recipes...");
  
  for (const recipe of cauliflowerZitiRecipes) {
    try {
      await db.insert(recipes).values({
        id: nanoid(),
        ...recipe,
        rating: "4.8",
        createdAt: new Date(),
        updatedAt: new Date()
      });
      console.log(`✓ Added: ${recipe.title}`);
    } catch (error) {
      console.error(`✗ Error adding ${recipe.title}:`, error);
    }
  }
  
  console.log("\n✅ All cauliflower baked ziti recipes added successfully!");
  process.exit(0);
}

addRecipes();
