import { db } from "../server/db";
import { recipes } from "../shared/schema";

const bakedBrieWreaths = [
  {
    title: "Gluten-Free Honey-Glazed Baked Brie Wreath with Fresh Thyme",
    slug: "baked-brie-wreath-honey-thyme",
    description: "Classic honey-drizzled brie surrounded by herb-seasoned gluten-free dough balls baked to golden perfection.",
    longDescription: "This Gluten-Free Honey-Glazed Baked Brie Wreath with Fresh Thyme is the ultimate elegant holiday centerpiece that combines creamy melted brie with aromatic herbs in a stunning presentation. Golden gluten-free dough balls, brushed with garlic herb butter and studded with fresh thyme leaves, are arranged in a perfect circle around a wheel of luxurious brie cheese. As the wreath bakes, the dough becomes beautifully golden and pillowy while the brie softens and melts, creating an irresistible warm center perfect for dipping the pull-apart bread portions. The honey glaze drizzled over the top adds a touch of sweetness that perfectly balances the savory garlic and earthy thyme. This recipe is surprisingly easy to make despite its impressive appearance, making it perfect for holiday parties, Christmas gatherings, or any special occasion where you want to wow your guests. The combination of warm, gooey cheese with herb-infused bread and sweet honey creates an addictive flavor that disappears quickly.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 8,
    rating: "5.0",
    calories: 285,
    protein: "11.0",
    carbs: "28.0",
    fat: "14.0",
    fiber: "2.0",
    sugar: "8.0",
    image: "/recipe-images/baked-brie-wreath-honey-thyme.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough or pastry dough",
      "3 tablespoons honey",
      "2 tablespoons fresh thyme leaves",
      "1 egg, beaten (for egg wash)",
      "2 tablespoons butter, melted",
      "1 teaspoon garlic powder",
      "1/4 teaspoon sea salt",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line a large baking sheet with parchment paper.",
      "Place the brie wheel in the center of the prepared baking sheet.",
      "Divide the gluten-free dough into 16-20 equal pieces and roll each into a ball.",
      "Mix melted butter with garlic powder and salt. Brush each dough ball with the butter mixture and sprinkle with fresh thyme.",
      "Arrange the dough balls in a circle around the brie, touching each other to form a wreath shape.",
      "Brush the dough balls with beaten egg wash.",
      "Bake for 20-25 minutes until the dough is golden brown and the brie is soft and melted.",
      "Remove from oven and immediately drizzle with honey.",
      "Garnish with fresh thyme sprigs.",
      "Serve warm with crackers, fruit, or vegetables for dipping."
    ],
    tips: "Use room temperature brie for best melting results. Make sure dough balls are touching each other to create a continuous wreath. Don't overbake - the cheese should be melted but not runny. Can be assembled up to 4 hours ahead and refrigerated before baking.",
    variations: [
      "Use maple syrup instead of honey for a different flavor profile",
      "Add crushed walnuts on top before baking",
      "Substitute rosemary for thyme"
    ],
    tags: ["gluten-free", "baked brie", "wreath", "holiday", "appetizer", "cheese", "honey", "thyme", "party food", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Honey-Glazed Baked Brie Wreath - Holiday Appetizer",
    seoDescription: "Classic honey-drizzled brie wreath surrounded by herb-seasoned gluten-free dough. Perfect holiday centerpiece appetizer."
  },
  {
    title: "Gluten-Free Cranberry Pecan Baked Brie Wreath",
    slug: "baked-brie-wreath-cranberry-pecan",
    description: "A festive favorite topped with cranberry sauce, chopped pecans, and rosemary sprigs.",
    longDescription: "This Gluten-Free Cranberry Pecan Baked Brie Wreath is pure holiday magic that combines sweet and savory flavors in a stunning presentation. Golden gluten-free pastry dough balls form a beautiful wreath around a wheel of creamy brie cheese that melts to perfection as it bakes. The real showstopper is the topping: vibrant cranberry sauce sweetened with brown sugar and warmed with cinnamon, scattered with crunchy toasted pecans, and finished with fresh rosemary sprigs. The contrast between the warm, gooey cheese, the sweet-tart cranberry sauce, and the nutty pecans creates an irresistible flavor combination that captures the essence of holiday entertaining. The red cranberries and green rosemary make this wreath visually festive, perfect for Thanksgiving, Christmas, or any winter celebration. It's the kind of appetizer that looks like you spent hours in the kitchen but is surprisingly simple to prepare. Serve it warm with crackers or apple slices for a crowd-pleasing appetizer that disappears in minutes.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    servings: 10,
    rating: "5.0",
    calories: 310,
    protein: "10.0",
    carbs: "32.0",
    fat: "16.0",
    fiber: "2.0",
    sugar: "12.0",
    image: "/recipe-images/baked-brie-wreath-cranberry-pecan.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free puff pastry or pizza dough",
      "1/2 cup cranberry sauce (homemade or canned)",
      "1/2 cup pecans, chopped",
      "2 tablespoons brown sugar",
      "1 egg, beaten",
      "2 tablespoons butter, melted",
      "Fresh rosemary sprigs",
      "1/4 teaspoon cinnamon"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper.",
      "Place brie wheel in center of baking sheet.",
      "In a small bowl, mix cranberry sauce with brown sugar and cinnamon.",
      "Divide dough into 18-20 equal portions and shape into balls.",
      "Brush each ball with melted butter.",
      "Arrange dough balls in a circle around the brie to form a wreath.",
      "Brush dough with egg wash.",
      "Bake for 22-25 minutes until golden brown.",
      "Remove from oven and immediately top brie with cranberry mixture.",
      "Sprinkle with chopped pecans and garnish with fresh rosemary.",
      "Serve warm with crackers or apple slices."
    ],
    tips: "Toast pecans lightly before using for enhanced flavor. Use fresh cranberry sauce for the best flavor. If cranberry sauce is too tart, add extra brown sugar. Garnish with fresh cranberries for extra color.",
    variations: [
      "Add orange zest to cranberry sauce",
      "Use walnuts instead of pecans",
      "Mix in dried cranberries with the chopped pecans"
    ],
    tags: ["gluten-free", "baked brie", "cranberry", "pecan", "holiday", "thanksgiving", "christmas", "appetizer", "festive", "wreath"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Cranberry Pecan Baked Brie Wreath - Festive Appetizer",
    seoDescription: "Gorgeous brie wreath topped with cranberry sauce and pecans. Perfect gluten-free holiday appetizer."
  },
  {
    title: "Gluten-Free Garlic Herb Baked Brie Wreath with Olive Oil Drizzle",
    slug: "baked-brie-wreath-garlic-herb",
    description: "Savory garlic butter-brushed dough with melted brie and an aromatic olive oil-herb finish.",
    longDescription: "This Gluten-Free Garlic Herb Baked Brie Wreath with Olive Oil Drizzle is a sophisticated appetizer that elevates simple ingredients into something truly special. Fresh garlic is sautéed in butter with a medley of fresh herbs—parsley, thyme, and rosemary—creating an aromatic mixture that coats each gluten-free dough ball. These herb-studded balls are arranged in a wreath around a wheel of creamy brie, then baked until the bread is golden and the cheese is melted and oozing. After baking, the entire wreath is drizzled with high-quality extra virgin olive oil, which adds richness and brings all the flavors together. The combination of pungent garlic, earthy herbs, creamy cheese, and fruity olive oil creates a Mediterranean-inspired flavor profile that's both elegant and comforting. This wreath is perfect for wine-pairing dinners, cocktail parties, or any occasion where you want to serve something that tastes gourmet but requires minimal effort. The fresh herbs make all the difference—don't substitute dried.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 8,
    rating: "5.0",
    calories: 295,
    protein: "11.0",
    carbs: "26.0",
    fat: "17.0",
    fiber: "2.0",
    sugar: "3.0",
    image: "/recipe-images/baked-brie-wreath-garlic-herb.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough",
      "4 cloves garlic, minced",
      "3 tablespoons butter, melted",
      "2 tablespoons fresh parsley, chopped",
      "1 tablespoon fresh thyme leaves",
      "1 tablespoon fresh rosemary, minced",
      "1 egg, beaten",
      "2 tablespoons extra virgin olive oil",
      "1/4 teaspoon sea salt",
      "1/4 teaspoon black pepper"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper.",
      "Mix melted butter with minced garlic, parsley, thyme, and rosemary.",
      "Place brie in center of baking sheet.",
      "Divide dough into 16-18 equal pieces and roll into balls.",
      "Brush each dough ball generously with garlic-herb butter.",
      "Arrange balls in a circle around brie, creating a wreath shape.",
      "Brush with egg wash and sprinkle with salt and pepper.",
      "Bake for 23-25 minutes until golden and fragrant.",
      "Drizzle the brie with olive oil.",
      "Garnish with additional fresh herbs.",
      "Serve immediately while warm and melty."
    ],
    tips: "Use fresh herbs for the best flavor - dried herbs won't have the same impact. Don't skimp on the garlic - it's the star of this recipe. Finish with flaky sea salt for extra elegance. Serve with crusty gluten-free bread for dipping.",
    variations: [
      "Add sun-dried tomatoes to the garlic butter",
      "Mix in grated Parmesan with the herbs",
      "Use basil instead of parsley"
    ],
    tags: ["gluten-free", "baked brie", "garlic", "herbs", "savory", "mediterranean", "appetizer", "olive oil", "wreath", "entertaining"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Garlic Herb Baked Brie Wreath - Savory Appetizer",
    seoDescription: "Savory garlic herb brie wreath with olive oil drizzle. Elegant gluten-free appetizer for entertaining."
  },
  {
    title: "Gluten-Free Fig & Walnut Baked Brie Wreath with Rosemary",
    slug: "baked-brie-wreath-fig-walnut",
    description: "Sweet and earthy fig preserves and walnuts over baked brie, wrapped in soft gluten-free pastry.",
    longDescription: "This Gluten-Free Fig & Walnut Baked Brie Wreath with Rosemary is the epitome of elegant entertaining, combining sophisticated flavors in a beautiful presentation. Creamy brie is surrounded by soft gluten-free pastry dough balls brushed with rosemary butter, then baked until golden. The magic happens when you top the melted brie with luscious fig preserves enhanced with balsamic vinegar for depth, then scatter crunchy walnuts and drizzle with honey. The combination is sublime: the sweetness of figs and honey, the earthiness of walnuts and rosemary, and the tangy richness of brie all come together in perfect harmony. The balsamic vinegar adds a sophisticated note that elevates this from simple to gourmet. This wreath is ideal for wine and cheese parties, upscale holiday gatherings, or whenever you want to impress guests with minimal effort. Fresh figs can be used when in season for an even more luxurious touch.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    servings: 10,
    rating: "5.0",
    calories: 320,
    protein: "10.0",
    carbs: "35.0",
    fat: "16.0",
    fiber: "3.0",
    sugar: "15.0",
    image: "/recipe-images/baked-brie-wreath-fig-walnut.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pastry dough",
      "1/2 cup fig preserves or jam",
      "1/2 cup walnuts, roughly chopped",
      "2 tablespoons fresh rosemary, chopped",
      "2 tablespoons honey",
      "1 egg, beaten",
      "2 tablespoons butter, melted",
      "1 tablespoon balsamic vinegar",
      "Fresh rosemary sprigs for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C) and line a baking sheet with parchment.",
      "Place brie wheel in the center of the sheet.",
      "Mix fig preserves with balsamic vinegar and 1 tablespoon honey.",
      "Divide dough into 18 equal pieces and shape into balls.",
      "Mix melted butter with chopped rosemary and brush onto each dough ball.",
      "Arrange balls around brie in a wreath formation.",
      "Brush dough with egg wash.",
      "Bake for 24-26 minutes until golden brown.",
      "Spoon fig mixture over the brie immediately after removing from oven.",
      "Top with chopped walnuts and drizzle with remaining honey.",
      "Garnish with fresh rosemary sprigs and serve warm."
    ],
    tips: "Toast walnuts lightly for deeper flavor. Use high-quality fig preserves for best results. Fresh figs can be used when in season - slice and arrange on top. Balsamic vinegar adds depth to the sweet figs.",
    variations: [
      "Substitute pecans for walnuts",
      "Use apricot preserves instead of fig",
      "Add a sprinkle of goat cheese crumbles"
    ],
    tags: ["gluten-free", "baked brie", "fig", "walnut", "rosemary", "elegant", "holiday", "appetizer", "sweet and savory", "wreath"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Fig Walnut Baked Brie Wreath - Elegant Appetizer",
    seoDescription: "Elegant brie wreath with fig preserves and walnuts. Sophisticated gluten-free holiday appetizer."
  },
  {
    title: "Gluten-Free Maple Bacon Baked Brie Wreath",
    slug: "baked-brie-wreath-maple-bacon",
    description: "Irresistible crispy bacon crumbles, maple syrup glaze, and thyme over gooey brie.",
    longDescription: "This Gluten-Free Maple Bacon Baked Brie Wreath is the ultimate crowd-pleaser that combines three irresistible ingredients: bacon, maple, and cheese. Crispy bacon is cooked until perfectly crunchy, then crumbled and scattered over a wheel of melted brie that's surrounded by golden gluten-free dough balls. But what makes this wreath truly addictive is the pure maple syrup drizzled generously over everything, creating a sweet-savory-smoky combination that's impossible to resist. Fresh thyme adds an earthy note that balances the richness. The dough balls are brushed with a maple-butter mixture before baking, infusing them with sweet flavor that complements the bacon beautifully. This wreath is perfect for brunches, game day parties, or holiday gatherings where you want something hearty and indulgent. The combination of textures—crispy bacon, gooey cheese, and pillowy bread—makes this impossible to stop eating. Use thick-cut bacon and pure maple syrup for the best results.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 25,
    totalTime: 55,
    servings: 8,
    rating: "5.0",
    calories: 340,
    protein: "14.0",
    carbs: "30.0",
    fat: "19.0",
    fiber: "2.0",
    sugar: "9.0",
    image: "/recipe-images/baked-brie-wreath-maple-bacon.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough",
      "6 strips bacon, cooked crispy and crumbled",
      "1/4 cup pure maple syrup",
      "1 tablespoon fresh thyme leaves",
      "1 egg, beaten",
      "2 tablespoons butter, melted",
      "1/4 teaspoon black pepper",
      "Fresh thyme sprigs for garnish"
    ],
    instructions: [
      "Cook bacon until crispy, then crumble and set aside.",
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper.",
      "Place brie wheel in center of sheet.",
      "Divide dough into 16-18 equal pieces and roll into balls.",
      "Brush each ball with melted butter and a small amount of maple syrup.",
      "Arrange dough balls in a circle around brie to form wreath.",
      "Brush with egg wash and sprinkle with black pepper.",
      "Bake for 23-25 minutes until golden brown.",
      "Remove from oven and immediately top brie with crumbled bacon.",
      "Drizzle generously with remaining maple syrup.",
      "Garnish with fresh thyme leaves and serve warm."
    ],
    tips: "Use thick-cut bacon for best texture. Cook bacon extra crispy so it stays crunchy on the warm brie. Use pure maple syrup, not pancake syrup. Reserve some bacon for sprinkling on top after baking.",
    variations: [
      "Add caramelized onions with the bacon",
      "Use turkey bacon for a lighter option",
      "Drizzle with bourbon-maple glaze for extra depth"
    ],
    tags: ["gluten-free", "baked brie", "maple", "bacon", "sweet and savory", "appetizer", "party food", "wreath", "crowd-pleaser", "indulgent"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Maple Bacon Baked Brie Wreath - Crowd-Pleaser",
    seoDescription: "Irresistible maple bacon brie wreath. Gluten-free appetizer combining bacon, maple, and melted cheese."
  },
  {
    title: "Gluten-Free Pomegranate Pistachio Baked Brie Wreath",
    slug: "baked-brie-wreath-pomegranate-pistachio",
    description: "Bright and colorful with jewel-toned pomegranate seeds, crushed pistachios, and honey drizzle.",
    longDescription: "This Gluten-Free Pomegranate Pistachio Baked Brie Wreath is a stunning centerpiece that's as beautiful as it is delicious. Golden gluten-free pastry dough balls, subtly spiced with cinnamon, form a perfect wreath around creamy brie. After baking, the melted cheese is topped with vibrant ruby-red pomegranate arils that sparkle like jewels, crunchy green pistachios that add color and texture, and a generous drizzle of honey that ties everything together. Fresh mint adds a bright, refreshing note that lifts the rich cheese. This wreath is especially gorgeous for Christmas entertaining—the red and green colors are naturally festive. The combination of sweet honey, tart pomegranate, nutty pistachios, and creamy brie creates a flavor profile that's both exotic and comforting. It's the kind of appetizer that makes everyone reach for their phones to take pictures before diving in.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    servings: 10,
    rating: "5.0",
    calories: 305,
    protein: "11.0",
    carbs: "32.0",
    fat: "15.0",
    fiber: "2.0",
    sugar: "13.0",
    image: "/recipe-images/baked-brie-wreath-pomegranate-pistachio.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pastry dough",
      "1/2 cup pomegranate arils (seeds)",
      "1/2 cup pistachios, shelled and roughly chopped",
      "3 tablespoons honey",
      "1 egg, beaten",
      "2 tablespoons butter, melted",
      "1 tablespoon fresh mint, chopped",
      "1/4 teaspoon cinnamon",
      "Fresh mint leaves for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C) and line a baking sheet with parchment.",
      "Place brie in center of baking sheet.",
      "Divide dough into 18-20 equal pieces and shape into balls.",
      "Brush each ball with melted butter mixed with cinnamon.",
      "Arrange dough balls in a circle around brie.",
      "Brush with egg wash.",
      "Bake for 24-26 minutes until golden.",
      "Remove from oven and immediately drizzle brie with 2 tablespoons honey.",
      "Top with pomegranate arils and chopped pistachios.",
      "Drizzle with remaining honey and sprinkle with fresh mint.",
      "Garnish with mint leaves and serve warm."
    ],
    tips: "Use fresh pomegranate arils for best flavor and appearance. Toast pistachios lightly before chopping. Add pomegranate and pistachios just before serving to maintain texture. This dish is especially beautiful for Christmas entertaining.",
    variations: [
      "Add orange zest for citrus notes",
      "Use almonds instead of pistachios",
      "Mix in dried cranberries with the pomegranate"
    ],
    tags: ["gluten-free", "baked brie", "pomegranate", "pistachio", "colorful", "festive", "elegant", "christmas", "appetizer", "wreath"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Pomegranate Pistachio Brie Wreath - Festive Appetizer",
    seoDescription: "Stunning pomegranate pistachio brie wreath. Colorful gluten-free holiday appetizer perfect for Christmas."
  },
  {
    title: "Gluten-Free Caramelized Onion & Brie Wreath with Balsamic Glaze",
    slug: "baked-brie-wreath-caramelized-onion",
    description: "Rich and savory caramelized onions baked atop brie with a tangy balsamic reduction.",
    longDescription: "This Gluten-Free Caramelized Onion & Brie Wreath with Balsamic Glaze is a sophisticated appetizer that delivers deep, complex flavors worthy of fine dining. Yellow onions are slowly caramelized with butter, olive oil, and brown sugar for 25-30 minutes until they're deeply golden, sweet, and jammy. These onions are then mixed with balsamic vinegar and cooked until reduced, creating a rich, tangy-sweet topping that's absolutely divine on melted brie. The cheese is surrounded by gluten-free dough balls brushed with olive oil and thyme, which bake up golden and aromatic. The combination of sweet caramelized onions, creamy brie, and tangy balsamic is classic French bistro fare that never goes out of style. Don't rush the onions—slow caramelization is the key to developing deep, sweet flavor. This wreath pairs beautifully with full-bodied red wines and is perfect for upscale dinner parties.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 40,
    cookTime: 25,
    totalTime: 65,
    servings: 8,
    rating: "5.0",
    calories: 315,
    protein: "11.0",
    carbs: "34.0",
    fat: "15.0",
    fiber: "2.0",
    sugar: "10.0",
    image: "/recipe-images/baked-brie-wreath-caramelized-onion.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough",
      "2 large yellow onions, thinly sliced",
      "3 tablespoons butter",
      "1 tablespoon olive oil",
      "2 tablespoons brown sugar",
      "1/4 cup balsamic vinegar",
      "1 egg, beaten",
      "1 tablespoon fresh thyme leaves",
      "1/4 teaspoon salt",
      "1/4 teaspoon black pepper"
    ],
    instructions: [
      "Heat butter and olive oil in a large skillet over medium heat. Add sliced onions, salt, and brown sugar.",
      "Cook onions, stirring occasionally, for 25-30 minutes until deeply caramelized and golden brown.",
      "Add balsamic vinegar and cook for 3-4 minutes until reduced. Set aside.",
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment.",
      "Place brie in center of sheet.",
      "Divide dough into 16-18 pieces and roll into balls.",
      "Brush balls with olive oil and sprinkle with thyme.",
      "Arrange in a circle around brie.",
      "Brush with egg wash and bake for 23-25 minutes until golden.",
      "Top brie with caramelized onions.",
      "Drizzle with additional balsamic glaze if desired and serve warm."
    ],
    tips: "Don't rush the onions - slow caramelization is key to deep flavor. Stir onions regularly to prevent burning. Can caramelize onions up to 3 days ahead. Add a splash of red wine to the onions for extra depth.",
    variations: [
      "Mix in sautéed mushrooms with the onions",
      "Add crumbled blue cheese on top",
      "Use red onions for a slightly different flavor"
    ],
    tags: ["gluten-free", "baked brie", "caramelized onion", "balsamic", "savory", "sophisticated", "appetizer", "gourmet", "wreath", "french"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Caramelized Onion Brie Wreath - Gourmet Appetizer",
    seoDescription: "Sophisticated caramelized onion brie wreath with balsamic glaze. Gluten-free gourmet appetizer."
  },
  {
    title: "Gluten-Free Apple & Cinnamon Baked Brie Wreath",
    slug: "baked-brie-wreath-apple-cinnamon",
    description: "Sweet sautéed apples and cinnamon sugar baked with brie for a dessert-style appetizer.",
    longDescription: "This Gluten-Free Apple & Cinnamon Baked Brie Wreath is a sweet and cozy appetizer that blurs the line between savory and dessert. Tart Granny Smith apples are sautéed in butter with brown sugar, cinnamon, and nutmeg until tender and caramelized, creating a filling that tastes like apple pie. This warm spiced mixture tops a wheel of melted brie that's surrounded by gluten-free pastry dough balls dusted with cinnamon sugar. The combination is reminiscent of apple pie and cheese—a classic pairing that works beautifully here. Walnuts add crunch, while a honey drizzle brings everything together with golden sweetness. This wreath is perfect for fall and winter gatherings, Thanksgiving appetizer spreads, or holiday brunches. It pairs wonderfully with apple cider and dessert wines. The sweet cinnamon aroma as it bakes will have everyone gathering in the kitchen.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 25,
    cookTime: 25,
    totalTime: 50,
    servings: 10,
    rating: "5.0",
    calories: 295,
    protein: "9.0",
    carbs: "38.0",
    fat: "13.0",
    fiber: "2.0",
    sugar: "18.0",
    image: "/recipe-images/baked-brie-wreath-apple-cinnamon.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pastry dough",
      "2 medium apples, peeled and diced",
      "3 tablespoons butter",
      "1/4 cup brown sugar",
      "1 1/2 teaspoons cinnamon",
      "1/4 teaspoon nutmeg",
      "1 egg, beaten",
      "2 tablespoons granulated sugar",
      "1/4 cup chopped walnuts (optional)",
      "2 tablespoons honey"
    ],
    instructions: [
      "Melt butter in a skillet over medium heat. Add diced apples, brown sugar, 1 teaspoon cinnamon, and nutmeg.",
      "Sauté apples for 8-10 minutes until tender and caramelized. Set aside.",
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment.",
      "Place brie in center of sheet.",
      "Mix granulated sugar with remaining 1/2 teaspoon cinnamon.",
      "Divide dough into 18-20 pieces and roll into balls.",
      "Arrange balls around brie in wreath formation.",
      "Brush with egg wash and sprinkle with cinnamon sugar.",
      "Bake for 24-26 minutes until golden.",
      "Top brie with sautéed apples and walnuts if using.",
      "Drizzle with honey and serve warm."
    ],
    tips: "Use tart apples like Granny Smith for best flavor balance. Cook apples until just tender - they'll continue softening on the warm brie. Serve with apple slices and gluten-free crackers. This pairs wonderfully with a cheese board.",
    variations: [
      "Add dried cranberries to the apple mixture",
      "Use pears instead of apples",
      "Drizzle with caramel sauce instead of honey"
    ],
    tags: ["gluten-free", "baked brie", "apple", "cinnamon", "sweet", "fall", "dessert-style", "appetizer", "wreath", "thanksgiving"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Apple Cinnamon Baked Brie Wreath - Fall Appetizer",
    seoDescription: "Sweet apple cinnamon brie wreath. Gluten-free dessert-style appetizer perfect for fall and holidays."
  },
  {
    title: "Gluten-Free Sun-Dried Tomato & Basil Baked Brie Wreath",
    slug: "baked-brie-wreath-sun-dried-tomato",
    description: "Mediterranean-inspired with sun-dried tomatoes, fresh basil leaves, and olive oil drizzle.",
    longDescription: "This Gluten-Free Sun-Dried Tomato & Basil Baked Brie Wreath brings Mediterranean sunshine to your table with vibrant flavors of Italy. Gluten-free pizza dough balls are brushed with a fragrant mixture of olive oil, fresh basil, and garlic, then arranged around a wheel of creamy brie and baked until golden. The real star is the topping: intensely flavored sun-dried tomatoes packed in oil, which provide concentrated tomato sweetness and umami depth. Fresh basil leaves add brightness and herbaceous notes, while a drizzle of high-quality extra virgin olive oil brings richness. A sprinkle of Parmesan and red pepper flakes adds complexity and a touch of heat. This wreath is perfect for summer entertaining, Italian-themed dinners, or whenever you want to transport your guests to the Mediterranean. Serve with gluten-free focaccia or breadsticks for the ultimate Italian appetizer experience.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 8,
    rating: "5.0",
    calories: 300,
    protein: "12.0",
    carbs: "27.0",
    fat: "17.0",
    fiber: "2.0",
    sugar: "4.0",
    image: "/recipe-images/baked-brie-wreath-sun-dried-tomato.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough",
      "1/2 cup sun-dried tomatoes in oil, drained and chopped",
      "1/4 cup fresh basil leaves, chopped",
      "3 tablespoons extra virgin olive oil",
      "2 cloves garlic, minced",
      "1 egg, beaten",
      "2 tablespoons grated Parmesan cheese",
      "1/4 teaspoon red pepper flakes",
      "1/4 teaspoon sea salt",
      "Fresh basil leaves for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C) and line a baking sheet with parchment.",
      "Mix 2 tablespoons olive oil with minced garlic and chopped basil.",
      "Place brie in center of baking sheet.",
      "Divide dough into 16-18 equal pieces and roll into balls.",
      "Brush each ball with the basil-garlic oil.",
      "Arrange balls in a circle around brie.",
      "Brush with egg wash and sprinkle with Parmesan.",
      "Bake for 23-25 minutes until golden brown.",
      "Remove from oven and top brie with chopped sun-dried tomatoes.",
      "Drizzle with remaining olive oil and sprinkle with red pepper flakes.",
      "Garnish with fresh basil leaves and serve warm."
    ],
    tips: "Use sun-dried tomatoes packed in oil for best flavor. Fresh basil is essential - don't substitute dried. Add a splash of balsamic vinegar for extra tang. Serve with gluten-free focaccia or breadsticks.",
    variations: [
      "Add kalamata olives with the tomatoes",
      "Mix in artichoke hearts",
      "Top with fresh mozzarella pearls"
    ],
    tags: ["gluten-free", "baked brie", "sun-dried tomato", "basil", "mediterranean", "italian", "appetizer", "olive oil", "wreath", "summer"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Sun-Dried Tomato Basil Brie Wreath - Mediterranean",
    seoDescription: "Mediterranean sun-dried tomato basil brie wreath. Gluten-free Italian-inspired appetizer."
  },
  {
    title: "Gluten-Free Spicy Hot Honey Baked Brie Wreath with Jalapeños",
    slug: "baked-brie-wreath-spicy-hot-honey",
    description: "Bold and exciting with hot honey drizzle, fresh jalapeño slices, and chili flakes.",
    longDescription: "This Gluten-Free Spicy Hot Honey Baked Brie Wreath with Jalapeños is for adventurous eaters who love bold flavors and sweet heat. Golden gluten-free dough balls surround a wheel of creamy brie, creating a classic wreath shape. But the magic happens after baking, when the melted cheese is drizzled generously with homemade hot honey—a mixture of pure honey infused with red pepper flakes and cayenne that provides the perfect balance of sweet and spicy. Fresh jalapeño slices add bright green color and fresh chile heat, while cilantro brings herbaceous freshness. A squeeze of lime at serving time cuts through the richness and adds brightness. This wreath is perfect for game day parties, taco nights, or any gathering where you want to serve something unexpected and exciting. Adjust the heat level to your preference—add more cayenne for fire or use fewer jalapeños for milder heat.",
    category: "Appetizers",
    subcategory: "Holiday & Entertaining",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 8,
    rating: "5.0",
    calories: 285,
    protein: "10.0",
    carbs: "32.0",
    fat: "13.0",
    fiber: "2.0",
    sugar: "12.0",
    image: "/recipe-images/baked-brie-wreath-spicy-hot-honey.png",
    ingredients: [
      "1 wheel (8 oz) brie cheese",
      "1 lb gluten-free pizza dough",
      "1/4 cup honey",
      "1-2 jalapeños, thinly sliced",
      "1 teaspoon red pepper flakes",
      "1/4 teaspoon cayenne pepper",
      "1 egg, beaten",
      "2 tablespoons butter, melted",
      "1 tablespoon fresh cilantro, chopped",
      "1/4 teaspoon sea salt",
      "Lime wedges for serving"
    ],
    instructions: [
      "Mix honey with red pepper flakes and cayenne to make hot honey. Let steep while preparing wreath.",
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment.",
      "Place brie in center of sheet.",
      "Divide dough into 16-18 equal pieces and roll into balls.",
      "Brush each ball with melted butter.",
      "Arrange balls around brie in a wreath.",
      "Brush with egg wash and sprinkle with sea salt.",
      "Bake for 23-25 minutes until golden.",
      "Remove from oven and immediately drizzle brie generously with hot honey.",
      "Top with fresh jalapeño slices.",
      "Garnish with cilantro and serve with lime wedges."
    ],
    tips: "Adjust heat level by varying amount of cayenne and jalapeños. Remove jalapeño seeds for milder heat. Make hot honey ahead and let flavors develop. Serve with cooling cucumber slices or sour cream.",
    variations: [
      "Use serrano peppers for extra heat",
      "Add crispy fried onions on top",
      "Mix in diced pineapple for sweet-heat-tropical combo"
    ],
    tags: ["gluten-free", "baked brie", "spicy", "hot honey", "jalapeño", "bold", "party food", "appetizer", "wreath", "heat"],
    isNaturallyGlutenFree: false,
    status: "published",
    seoTitle: "Gluten-Free Spicy Hot Honey Brie Wreath - Bold Appetizer",
    seoDescription: "Bold spicy hot honey brie wreath with jalapeños. Gluten-free appetizer with sweet heat."
  }
];

async function seed() {
  console.log("Adding 10 gluten-free baked brie wreath recipes...");

  await db.insert(recipes).values(bakedBrieWreaths).onConflictDoNothing();

  console.log("Successfully added baked brie wreath recipes!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Error seeding baked brie wreaths:", error);
  process.exit(1);
});
